
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF SHAR
//__________________________________________________________________________________
//__________________________________________________________________________________


//____________________________SHAR___________________________________________________

ADD_KIT ~D5_AC_SHAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_SHAR      0 0 0 0 1 1 0 1~
~D5_AC_SHAR      0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_SHAR        0  1  1  0  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_SHAR        0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/330_shar/d5asha.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33001
SAY @33002
SAY @33003
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33004)
		STR_VAR
			kit_name = D5_AC_SHAR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END
//____________________________________________________________________________________

//DARKCLOAK ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/330_shar/d5asha.2da~ ~override~
COPY_EXISTING ~spwi220.spl~ ~override/d5shasl.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi201.spl~ ~override/d5shabr.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi518.spl~ ~override/d5shaph.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi815.spl~ ~override/d5shabl.spl~
	LPM spell_to_innate
//____________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~d5asha~
	race 			= ~all~
	s_Life 			= ~minor~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~major~
	s_Protection 	= ~minor~
	s_War 			= ~x~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	 = ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~focus~
	s_Magic 		= ~major~
END
//__________________________________________________________________________________


//____________________________CLERIC/MAGE_____________________________________________

ADD_KIT ~D5_CM_SHAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CM_SHAR      0 0 0 0 1 1 0 1~
~D5_CM_SHAR      0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CM_SHAR        0  1  1  0  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CM_SHAR        0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/330_shar/d52sha.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CM_E  K_CM_H  K_CM_HE  K_CM_G  K_CM_D  K_CM_HL  K_CM_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 14~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33001
SAY @33002
SAY @33003
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33004)
		STR_VAR
			kit_name = D5_CM_SHAR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END
//____________________________________________________________________________________

COPY ~faiths_and_powers/kits/acolytes/330_shar/d5asha.2da~ ~override/d52sha.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d52sha.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_CM_SHAR~ 
		kit_clab = ~d52sha~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 
//____________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_mage	= 1
  STR_VAR
    clab_name 		= ~d52sha~
	race 			= ~all~
	s_Life 			= ~minor~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~major~
	s_Protection 	= ~minor~
	s_War 			= ~x~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~focus~
	s_Magic 		= ~major~
END
//__________________________________________________________________________________

