
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF MORADIN
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________

ADD_KIT ~B_CHAMP_MOR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_MOR            2 2 2 2 2 2 2 2~
~B_CHAMP_MOR            2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_MOR        1  1  0  0  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_MOR        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/807_Moradin/b_ch07.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_D~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80701 //lower
SAY @80702 //Mixed
SAY @80703 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80703)
		STR_VAR
			kit_name = B_CHAMP_MOR
			clsrcreq = ~0 0 0 1 0 0 0~
	END
END
//____________________________________________________________________________________


//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_ch07.2da~ ~override~
//+2ac/save vs magic
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_mor01.spl~ ~override~
//hammer
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_mor02.spl~ ~override~
        SAY NAME1 @80704
        SAY NAME2 @80704
        SAY UNIDENTIFIED_DESC @80705
	SAY DESC @80705
   LPF ALTER_EFFECT INT_VAR match_opcode = 111 STR_VAR resource = EVAL ~B_mor02~ END
//actual hammer
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_mor02.itm~ ~override~
        SAY NAME1 @80704
        SAY NAME2 @80704
        SAY UNIDENTIFIED_DESC @80705
	SAY DESC @80705
//COPY ~faiths_and_powers/kits/champions/807_Moradin/b_ch101a.spl~ ~override~
//3rd spell
//COPY ~faiths_and_powers/kits/champions/807_Moradin/b_ch101b.spl~ ~override~

//protection from evil
//COPY ~faiths_and_powers/kits/champions/807_Moradin/b_tyr01.spl~ ~override~

//____________________________________________________________________________________


//___________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS 1 rows
	READ_2DA_ENTRY (%rows% - 1) 5 1 clab
BUT_ONLY
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric 		= 0
	c_acolyte 		= 0
	c_fighter_cleric = 0
	c_cleric_mage	= 0
	c_cleric_thief 	= 0
	c_ranger_cleric	= 0
	c_f_m_c			= 0
        c_champion 		= 1
  STR_VAR
    clab_name = EVAL ~%clab%~
	race 			= ~dwarf~
	s_Life 			= ~paladin~
	s_Death 		= ~x~
	s_Benediction 	        = ~paladin~
	s_Destruction 	        = ~x~
	s_Protection 	        = ~paladin~
	s_War 			= ~paladin~
	s_Knowledge 	        = ~x~
	s_Deception 	        = ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~paladin~
	s_Affliction 	        = ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~paladin~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~paladin~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
END
//__________________________________________________________________________________

