
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							BARBARIAN RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________
//
ADD_KIT ~D5RBARB~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5RBARB       2 2 2 2 2 2 2 2~
~D5RBARB       2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 0 2 2 0 2 2 2 0 2 2 0 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5RBARB           1  1  0  1  1  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5RBARB           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rbarb.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_R_H   K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x40000000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @95401
SAY @95402
SAY @95403
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@95403)
		STR_VAR
			kit_name = D5RBARB
			clswpbon = ~1 0 2~
	END
END
//___________________________________________________________________________________


//BARBARIAN RANGER ABILITY FILES_____________________________________________________
//
COPY ~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rbarb.2da~ ~override~
COPY ~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rbaab.spl~ ~override~
COPY ~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rback.spl~ ~override~
//___________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
    c_scout 		= 1
  STR_VAR
    clab_name 		= ~d5_rbarb~
	race 			= ~all~
	s_Life 			= ~x~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~ranger~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
END
//__________________________________________________________________________________


//FIX BARB USABILITY__________________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
		READ_BYTE 0x1f "use"
		READ_BYTE 0x29 "kit"
		PATCH_IF ((("%kit%" BAND 0b01000000) = 0b01000000) AND 
				(("%use%" BAND 0b00001000) = 0b00001000)) THEN BEGIN
			WRITE_BYTE 0x29 ("%kit%" BAND 0b10111111) 
		END
	END
BUT_ONLY_IF_IT_CHANGES
//____________________________________________________________________________________

