//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ZEALOTS
//__________________________________________________________________________________
//__________________________________________________________________________________
//

//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							BASE KIT_1
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN //2.x version

ADD_KIT ~B_ZEALOT_1~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_ZEALOT_1           2 2 2 2 2 2 2 2~
~B_ZEALOT_1           2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1       13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_ZEALOT_1            1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_ZEALOT_1            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/zealots/b_zealot.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_H   K_P_D   K_P_G   K_P_E   K_P_HE   K_P_HL   K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x04000000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80008 //lower
SAY @80009 //Mixed
SAY @80010 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80010)
		STR_VAR
			kit_name = B_ZEALOT_1
	END
END
//____________________________________________________________________________________
END


//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/zealots/b_zealot.2da~ ~override~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN //pre 2.x version
ADD_KIT ~B_ZEALOT_1~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_ZEALOT_1           2 2 2 2 2 2 2 2~
~B_ZEALOT_1           2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1       13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_1       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_ZEALOT_1         1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_ZEALOT_1            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/zealots/b_zealot.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_H   K_P_D   K_P_G   K_P_E   K_P_HE   K_P_HL   K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x04000000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80008 //lower
SAY @80009 //Mixed
SAY @80014 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80014)
		STR_VAR
			kit_name = B_ZEALOT_1
	END
END
//____________________________________________________________________________________
END

//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							BASE KIT_2
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________


ADD_KIT ~B_ZEALOT_2~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_ZEALOT_2           2 2 2 2 2 2 2 2~
~B_ZEALOT_2           2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_2       13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_2       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_2        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_ZEALOT_2       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_ZEALOT_2         1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_ZEALOT_2         0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/zealots/b_ze00.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~ ~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00008000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80008 //lower
SAY @80009 //Mixed
SAY @80010 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80010)
		STR_VAR
			kit_name = B_ZEALOT_2
	END
END
//____________________________________________________________________________________


//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/zealots/b_ze00.2da~ ~override~
//sneaky sneaky
COPY ~faiths_and_powers/kits/zealots/b_sneak.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk02.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk03.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk04.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk05.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk06.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk07.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk08.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk09.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk10.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk11.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk12.spl~ ~override~
COPY ~faiths_and_powers/kits/zealots/b_snk13.spl~ ~override~
//nO FALL

ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_ZEALOT_2 0~
  BUT_ONLY_IF_IT_CHANGES
END

//zealot script
  COMPILE ~faiths_and_powers/kits/zealots/b_zealot.baf~ 
//zealot cre
COPY ~faiths_and_powers/kits/zealots/b_zealot.cre~ ~override~
//zealot eff
COPY ~faiths_and_powers/kits/zealots/b_zealot.eff~ ~override~
//zealot spl
COPY ~faiths_and_powers/kits/zealots/b_zealot.spl~ ~override~


//any race can have their rangers
COPY_EXISTING ~clsrcreq.2da~ ~override~ //
//ranger
    SET_2DA_ENTRY 42 2 8 1
    SET_2DA_ENTRY 42 3 8 1
    SET_2DA_ENTRY 42 4 8 1
    SET_2DA_ENTRY 42 5 8 1
    SET_2DA_ENTRY 42 6 8 1
    SET_2DA_ENTRY 42 7 8 1
BUT_ONLY_IF_IT_CHANGES
COPY_EXISTING ~clsrcreq.2da~ ~override~ //
	LPM remove_blank_lines
	APPEND_FILE ~faiths_and_powers/kits/zealots/race_zealots.txt~
BUT_ONLY_IF_IT_CHANGES
