
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					    	BEAST MYSTIC
//__________________________________________________________________________________
//__________________________________________________________________________________


ADD_KIT ~D5_OC_BEAST~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_OC_BEAST     0 0 0 1 1 1 0 1~
~D5_OC_BEAST     0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   12  9   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                    LG LN LE NG TN NE CG CN CE
~D5_OC_BEAST          0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                    FT CL MA TH DR RA
~D5_OC_BEAST          1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/occultists/762_animist/d5obst.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x20000000 11~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @76201
SAY @76202
SAY @76203
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@76204)
		STR_VAR
			kit_name = D5_OC_BEAST
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________


// ABILITY FILES_____________________________________________________________
//
COPY ~faiths_and_powers/kits/occultists/762_animist/d5obst.2da~ ~override~
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_clbe.spl~ ~override~
	SAY NAME1 @76211
	SAY UNIDENTIFIED_DESC @76211
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_clbe.itm~ ~override~
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_clno.spl~ ~override~
	SAY NAME1 @76212
	SAY UNIDENTIFIED_DESC @76212
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_wwmy.spl~ ~override~
	SAY NAME1 @76213
	SAY UNIDENTIFIED_DESC @76213
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_wwnf.spl~ ~override~
	SAY NAME1 @76214
	SAY UNIDENTIFIED_DESC @76214
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_wwcl1.itm~ ~override~
	SAY NAME1 @76215
	SAY UNIDENTIFIED_DESC @76215
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_wwcl2.itm~ ~override~
	SAY NAME1 @76215
	SAY UNIDENTIFIED_DESC @76215
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_ww01.cre~ ~override~
	SAY NAME1 @76216
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_ww02.cre~ ~override~
	SAY NAME1 @76217
COPY ~faiths_and_powers/kits/occultists/762_animist/d5_ww03.cre~ ~override~
	SAY NAME1 @76218
COPY ~faiths_and_powers/kits/misc/d5_cllv1.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_cstbo.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_disp1.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_disp2.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_disp3.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_disp4.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_disp5.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_disp6.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5_disp7.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
//______________________________________________________________________________

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_druids.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_D_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_D_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 17) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END
//___________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_occultist 	= 1
  STR_VAR
    clab_name 		= ~d5obst~
	race 			= ~all~
	s_Life 			= ~minor~
	s_Death 		= ~minor~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~major~
	s_Dread 		= ~minor~
	s_Vigor 		= ~major~
	s_Affliction 	= ~major~
	s_Animal 		= ~focus~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~minor~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~minor~
	s_Magic 		= ~x~
END
//__________________________________________________________________________________

