
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC KITS
//__________________________________________________________________________________
//__________________________________________________________________________________


//__________________________________________________________________________________

ADD_KIT ~B_PRIEST_BESHABA~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_BESHABA     1 1 1 1 1 1 1 1~
~B_PRIEST_BESHABA     1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_PRIEST_BESHABA         0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_PRIEST_BESHABA           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/332_beshaba/b_abes.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33201
SAY @33202
SAY @33203
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33203)
		STR_VAR
			kit_name = B_PRIEST_BESHABA
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END
//____________________________________________________________________________________


//MOANDER ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/332_beshaba/b_abes.2da~ ~override~

COPY ~faiths_and_powers/kits/acolytes/332_beshaba/b_bes01.spl~ ~override~

COPY ~faiths_and_powers/kits/acolytes/332_beshaba/b_bes02.spl~ ~override~
//bes03
COPY ~faiths_and_powers/spheres/spells/dread/b_c501b.bam~ ~override~ // Misfire
COPY ~faiths_and_powers/spheres/spells/dread/b_c501c.bam~ ~override~ // Misfire
//spl etc
COPY ~faiths_and_powers/spheres/spells/dread/b_c501.eff~ ~override~ // Misfire
  SAY 0x1c @50901     //Misfire

COPY ~faiths_and_powers/spheres/spells/dread/b_c501.spl~ ~override/b_bes03.spl~ // Misfire
        SAY NAME1 @50901
        SAY NAME2 @50901
        SAY UNIDENTIFIED_DESC @50902
	SAY DESC @50902
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  WRITE_BYTE 0x9C 4//Location
  WRITE_BYTE 0xC4 4//Location  +28
  WRITE_BYTE 0xEC 4//Location  +28
  WRITE_BYTE 0x114 4//Location  +28
  WRITE_BYTE 0x13C 4//Location  +28
  WRITE_BYTE 0x164 4//Location  +28
  WRITE_BYTE 0x18C 4//Location  +28
  WRITE_BYTE 0x1B4 4//Location  +28
  WRITE_BYTE 0x1DC 4//Location  +28
  WRITE_BYTE 0x204 4//Location  +28
  WRITE_BYTE 0x22C 4//Location  +28
  WRITE_BYTE 0x254 4//Location  +28
             LPF ALTER_EFFECT
              INT_VAR match_opcode = 321
              STR_VAR resource = EVAL ~b_bes03~
             END
COPY ~faiths_and_powers/kits/acolytes/332_beshaba/b_bes04.spl~ ~override~
        SAY NAME1 @33206
        SAY NAME2 @33206
        SAY UNIDENTIFIED_DESC @33207
	SAY DESC @33207

COPY ~faiths_and_powers/spheres/spells/dread/b_c501.eff~ ~override/b_bes04.eff~ // Misfire
  SAY 0x1c @33206     //Misfortune

//____________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_abes~
	race 			= ~all~
	s_Life 			= ~x~
	s_Death 		= ~major~
	s_Benediction 	= ~x~
	s_Destruction   = ~major~
	s_Protection    = ~x~
	s_War 			= ~minor~
	s_Knowledge     = ~x~
	s_Deception     = ~minor~
	s_Thought 		= ~x~
	s_Dread 		= ~major~
	s_Vigor 		= ~x~
	s_Affliction    = ~major~
	s_Animal 		= ~minor~
	s_Plant 		= ~focus~
	s_Earth 		= ~major~
	s_Water 		= ~minor~
	s_Air 			= ~minor~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~major~
	s_Magic 		= ~minor~
END
//__________________________________________________________________________________

