
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC KITS
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________TALOS___________________________________________________

ADD_KIT ~B_CLERIC_TALOS~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TALOS       1 1 1 1 1 1 1 1~
~B_CLERIC_TALOS       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_TALOS           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_TALOS           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/224_talos/b_ctal.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22401
SAY @22402
SAY @22403
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22403)
		STR_VAR
			kit_name = B_CLERIC_TALOS
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

//TALOS ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/224_talos/b_ctal.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal01.spl~     ~override~  //  Electricity resist
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal10.spl~     ~override~  //  Lightning Bolt
	SAY UNIDENTIFIED_DESC @22406  //
	SAY IDENTIFIED_DESC @22406  //
//____________________________________________________________________________________

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 19) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END
//___________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric 		= 1
  STR_VAR
    clab_name 		= ~b_ctal~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~minor~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~major~
	s_Fire 			= ~major~
	s_Light 		= ~minor~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
END
//__________________________________________________________________________________


//___________________________TALOS___________________________________________________

ADD_KIT ~B_FC_TALOS~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_FC_TALOS           1 1 1 1 1 1 1 1~
~B_FC_TALOS           1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                     LG LN LE NG TN NE CG CN CE
~B_FC_TALOS            0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                     FT CL MA TH DR RA
~B_FC_TALOS            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/224_talos/b_2tal.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FC_E  K_FC_H  K_FC_HE  K_FC_G  K_FC_D  K_FC_HL  K_FC_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 8~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22401
SAY @22402
SAY @22403
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22403)
		STR_VAR
			kit_name = B_FC_TALOS
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

COPY ~faiths_and_powers/kits/clerics/224_talos/b_ctal.2da~ ~override/b_2tal.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2tal.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_FC_TALOS~ 
		kit_clab = ~b_2tal~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 
//____________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_fighter_cleric = 1
  STR_VAR
    clab_name 		= ~b_2tal~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~minor~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~major~
	s_Fire 			= ~major~
	s_Light 		= ~minor~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
END
//__________________________________________________________________________________
