
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							BATTLEGUARD OF TEMPUS
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________

ADD_KIT ~B_CLERIC_TEMPUS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TEMPUS    1 1 1 1 1 1 1 1~
~B_CLERIC_TEMPUS    1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_TEMPUS    1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_TEMPUS    1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21001 //lower
SAY @21002 //Mixed
SAY @21003 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21003)
		STR_VAR
			kit_name = B_CLERIC_TEMPUS
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

//TEMPUS ABILITY FILES______________________________________________________________
// Incite Rage
ACTION_IF FILE_EXISTS_IN_GAME ~spcl321.spl~ BEGIN
COPY_EXISTING ~spcl321.spl~ ~override/B_TEM03.spl~ // Incite Rage
	SAY NAME1 @21004
	SAY NAME2 @21004
	SAY UNIDENTIFIED_DESC @21006  //
	SAY IDENTIFIED_DESC @21006  //
  WRITE_BYTE 0x7e 1//Target 1 cre
END

COPY ~faiths_and_powers/kits/clerics/210_tempus/b_tem05.spl~ ~override~    //+1 damage


COPY ~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~ ~override~




//REPLACE VANILLA KIT_________________________________________________________________
//should do this for IWD
ACTION_IF FILE_EXISTS_IN_GAME ~d5_menu.d5~ BEGIN
	COPY_EXISTING ~kitlist.2da~ ~override~
		COUNT_2DA_ROWS ~7~ "kit_row"
	OUTER_SET kit_row -= 2
	COPY_EXISTING ~K_C_D.2da~ ~override~
			~K_C_E.2da~ ~override~
			~K_C_G.2da~ ~override~
			~K_C_H.2da~ ~override~
			~K_C_HE.2da~ ~override~
			~K_C_HL.2da~ ~override~
			~K_C_HO.2da~ ~override~
		REPLACE_TEXTUALLY ~21~ ~%kit_row%~
	BUT_ONLY
END
//___________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric 		= 1
  STR_VAR
    clab_name 		= ~b_ctem~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~major~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~major~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~minor~
	s_Water 		= ~x~
	s_Air 			= ~minor~
	s_Fire 			= ~x~
	s_Light 		= ~minor~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
END
//__________________________________________________________________________________


//FIGHTER/CLERIC______________________________________________________________________

COPY ~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~ ~override/b_2tem.2da~

ADD_KIT ~B_FC_TEMPUS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_FC_TEMPUS    	1 1 1 1 1 1 1 1~
~B_FC_TEMPUS    	1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	9   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	9   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	9   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_FC_TEMPUS    	0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_FC_TEMPUS    	0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~override/b_2tem.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FC_E  K_FC_H  K_FC_HE  K_FC_G  K_FC_D  K_FC_HL  K_FC_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 8~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21001 //lower
SAY @21002 //Mixed
SAY @21003 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21003)
		STR_VAR
			kit_name = B_FC_TEMPUS
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2tem.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_FC_TEMPUS~ 
		kit_clab = ~b_2tem~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 
//____________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_fighter_cleric = 1
  STR_VAR
    clab_name 		= ~b_2tem~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~major~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~major~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~minor~
	s_Water 		= ~x~
	s_Air 			= ~minor~
	s_Fire 			= ~x~
	s_Light 		= ~minor~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
END
//__________________________________________________________________________________
