
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							UR-Priest
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_ur_priest BEGIN

ADD_KIT ~B_CLERIC_UR_PRIEST~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_UR_PRIEST     1 1 1 1 1 1 1 1~
~B_CLERIC_UR_PRIEST     1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_UR_PRIEST  0  1  1  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_UR_PRIEST  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/200_Ur_Priest/b_clur.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20001 //lower
SAY @20002 //Mixed
SAY @20003 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20003)
		STR_VAR
			kit_name = B_CLERIC_UR_PRIEST
			clswpbon = ~0 0 3~
	END
END

//Ur-Priest ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_clur.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01.spl~     ~override~  // sap the spirit
        SAY NAME1 @20004
        SAY NAME2 @20004
        SAY UNIDENTIFIED_DESC @20005
	SAY DESC @20005

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01a.spl~     ~override~  // sap the spirit
    LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR resource = ~b_ur01a~ END //+1 casting level notifier

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01a.eff~     ~override~  // +1 casting level notifier
  SAY 0x1c @20006    //+1 casting level notifier

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01b.spl~     ~override~  // sap the spirit

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur02.spl~     ~override~  // save penalty

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo101.spl~     ~override~  // Infravision Orison
//  SAY NAME1 @98504 //Infravision
//  SAY UNIDENTIFIED_DESC @98505   //Infravision

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo102.spl~     ~override~  // Fire bolt Orison
//  SAY NAME1 @98506 //Fire bolt
//  SAY UNIDENTIFIED_DESC @98507   //Fire bolt desc

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla02.spl~     ~override~  // Boon of Lathander
//  SAY UNIDENTIFIED_DESC @98534//

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla03.spl~     ~override~  // Hold Undead
//  SAY NAME1 @20107
//  SAY UNIDENTIFIED_DESC @20104//

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 0) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM ur_priest_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_clur~
	class 			= ~cleric~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF LATHANDER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_lathander BEGIN

ADD_KIT ~B_CLERIC_LATHANDER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_LATHANDER     1 1 1 1 1 1 1 1~
~B_CLERIC_LATHANDER     1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_LATHANDER  1  1  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_LATHANDER  1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/201_lathander/b_clat.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20101 //lower
SAY @20102 //Mixed
SAY @20103 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20103)
		STR_VAR
			kit_name = B_CLERIC_LATHANDER
			clswpbon = ~0 0 3~
	END
END

//LATHANDER ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/201_lathander/b_clat.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/201_lathander/b_turn.spl~     ~override~  // Turn Undead +4 Levels
//  SAY NAME1 @#####
//  SAY UNIDENTIFIED_DESC @#####
//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo101.spl~     ~override~  // Infravision Orison
//  SAY NAME1 @98504 //Infravision
//  SAY UNIDENTIFIED_DESC @98505   //Infravision

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo102.spl~     ~override~  // Fire bolt Orison
//  SAY NAME1 @98506 //Fire bolt
//  SAY UNIDENTIFIED_DESC @98507   //Fire bolt desc

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla02.spl~     ~override~  // Boon of Lathander
//  SAY UNIDENTIFIED_DESC @98534//

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla03.spl~     ~override~  // Hold Undead
//  SAY NAME1 @20107
//  SAY UNIDENTIFIED_DESC @20104//

COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla04.spl~     ~override~  // False Dawn
  SAY NAME1 @20108
  SAY UNIDENTIFIED_DESC @20105

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 21) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_lathander_spheres

  LAF ~DEFINE_FNP_KIT_INFO~
   INT_VAR
	u_leather_armor 	= 1		// for armor, enter '1' or 0' to indicate usability
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1 	// for weapons, enter 1 to 5 for the allowed proficiency level
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
   STR_VAR
    clab_name 		= ~b_clat~
	class 			= ~cleric~
  END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF TORM
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_torm BEGIN

ADD_KIT ~B_CLERIC_TORM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TORM      1 1 1 1 1 1 1 1~
~B_CLERIC_TORM      1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_TORM      1  1  0  1  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_TORM  1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/202_torm/b_ctor.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20201 //lower
SAY @20202 //Mixed
SAY @20203 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20103)
		STR_VAR
			kit_name = B_CLERIC_TORM
			clswpbon = ~0 0 3~
	END
END

//TORM ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/202_torm/b_ctor.2da~ ~override~
COPY_EXISTING ~SPPR102.spl~ ~override/b_tor01.spl~ // dispel magic
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~b_tor01~
  END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_torm_spheres
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 1
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ctor~
	class 			= ~cleric~
 END

//multiclass__________________________________________________________________________

ADD_KIT ~B_FC_TORM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_FC_TORM   	    1 1 1 1 1 1 1 1~
~B_FC_TORM   	    2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TORM   	    0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TORM   	    0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TORM   	    0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TORM   	    0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_FC_TORM   	    1  1  0  1  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_FC_TORM   	    1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/202_torm/b_2tor.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FC_E  K_FC_H  K_FC_HE  K_FC_G  K_FC_D  K_FC_HL  K_FC_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 8~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20201 //lower
SAY @20202 //Mixed
SAY @20203 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20103)
		STR_VAR
			kit_name = B_FC_TORM
			clswpbon = ~1 0 3~
	END
END

COPY ~faiths_and_powers/kits/clerics/202_torm/b_ctor.2da~ ~override/b_2tor.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2tor.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_FC_TORM~ 
		kit_clab = ~b_2tor~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM fighter_cleric_torm_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 2
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 2
	u_short_swords		= 2
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 0
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~b_2tor~
	class 			= ~fighter_cleric~
 END

END
//____________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF TYMORA
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_tymora BEGIN

ADD_KIT ~D5_CL_TYMORA~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CL_TYMORA    0 0 0 0 1 1 0 1~
~D5_CL_TYMORA    0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   12  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CL_TYMORA      0  0  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CL_TYMORA      1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/205_tymora/d5ctym.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20501
SAY @20502
SAY @20503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20504)
		STR_VAR
			kit_name = D5_CL_TYMORA
			clswpbon = ~0 0 3~
	END
END

//TYMORA ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5ctym.2da~ ~override~
COPY ~faiths_and_powers/kits/misc/d5luckp.spl~ ~override~
	SAY NAME1 @20511
	SAY UNIDENTIFIED_DESC @20511
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5_tym1.spl~ ~override~
	SAY NAME1 @20513
	SAY UNIDENTIFIED_DESC @20514
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5_tym1a.spl~ ~override~
	SAY NAME1 @20513
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5_tym1b.spl~ ~override~
	SAY NAME1 @20513

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_tymora_spheres
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d5ctym~
	class 			= ~cleric~
 END

//multiclass_________________________________________________________________________

ADD_KIT ~D5_CT_TYMORA~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CT_TYMORA    0 0 0 0 1 1 0 1~
~D5_CT_TYMORA    0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_TYMORA      0   0   0   0   12  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_TYMORA      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_TYMORA      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_TYMORA      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CT_TYMORA      0  0  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CT_TYMORA      0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/205_tymora/d52tym.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CT_E  K_CT_H  K_CT_HE  K_CT_G  K_CT_D  K_CT_HL  K_CT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20501
SAY @20502
SAY @20503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20504)
		STR_VAR
			kit_name = D5_CT_TYMORA
			clswpbon = ~0 0 3~
	END
END

COPY ~faiths_and_powers/kits/clerics/205_tymora/d5ctym.2da~ ~override/d52tym.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d52tym.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_CT_TYMORA~ 
		kit_clab = ~d52tym~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_thief_tymora_spheres 

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d52tym~
	class 			= ~cleric_thief~
 END

END
//__________________________________________________________________________________


//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF HELM
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_helm BEGIN

ADD_KIT ~B_CLERIC_HELM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                         T   S           F   Q             S S
//10                 L S                     W   C           L   U             W I
//9                  A M             B L S   O   I   W       A   A             O N
//8                  R A             A O H   H   M   A       I   R C   S       R G
//7                  G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                  E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_HELM       1 1 1 1 1 1 1 1~
~B_CLERIC_HELM       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           12   0   0   0  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                       LG LN LE NG TN NE CG CN CE
~B_CLERIC_HELM           1  1  0  0  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                       FT CL MA TH DR RA
~B_CLERIC_HELM           1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/208_helm/b_chel.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20801
SAY @20802
SAY @20803

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20803)
		STR_VAR
			kit_name = B_CLERIC_HELM
			clswpbon = ~0 0 3~
	END
END

//WATCHER ABILITY FILES____________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/clerics/208_helm/b_chel.2da~ ~override~

//COPY ~faiths_and_powers/kits/clerics/208_helm/b_hsp01.spl~     ~override~  // Seeking Sword
//  SAY NAME1 @98518
//  SAY UNIDENTIFIED_DESC @98519
COPY ~faiths_and_powers/kits/clerics/208_helm/SW1HSEEK.itm~     ~override~  // Seeking Sword
//For the champions, but that's fine
COPY ~faiths_and_powers/kits/clerics/208_helm/b_hab01.spl~     ~override~  // AC/Save Bonus/wp longsword

COPY ~faiths_and_powers/kits/clerics/208_helm/b_hsp02.spl~     ~override~  // Helm's Eye
  SAY NAME1 @20806
  SAY UNIDENTIFIED_DESC @20807

//COPY ~faiths_and_powers/kits/clerics/208_helm/b_hsp03.spl~     ~override~  // Farsight
//  SAY NAME1 @98522
//  SAY UNIDENTIFIED_DESC @98523

//COPY ~faiths_and_powers/kits/clerics/208_helm/b_hab02.spl~     ~override~  // Glyph of warding
//  SAY NAME1 @98532
//  SAY UNIDENTIFIED_DESC @98533

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 20) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_helm_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 1
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_chel~
	class 			= ~cleric~
 END

END
//__________________________________________________________________________________


//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF KELEMVOR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_kelemvor BEGIN

ADD_KIT ~B_CLERIC_KELEMVOR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                         T   S           F   Q             S S
//10                 L S                     W   C           L   U             W I
//9                  A M             B L S   O   I   W       A   A             O N
//8                  R A             A O H   H   M   A       I   R C   S       R G
//7                  G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                  E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_KELEMVOR       1 1 1 1 1 1 1 1~
~B_CLERIC_KELEMVOR       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR           12   0   0   0  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                       LG LN LE NG TN NE CG CN CE
~B_CLERIC_KELEMVOR        1  1  0  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                       FT CL MA TH DR RA
~B_CLERIC_KELEMVOR           1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/209_kelemvor/b_ckel.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20901
SAY @20902
SAY @20903

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20903)
		STR_VAR
			kit_name = B_CLERIC_KELEMVOR
			clswpbon = ~0 0 3~
	END
END

//KIT ABILITY FILES___________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/209_kelemvor/b_ckel.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/201_lathander/b_turn.spl~     ~override~  // Turn Undead +4 Levels
COPY ~faiths_and_powers/kits/acolytes/314_ilmater/b_ilm02.spl~ ~override~  // +4 vs death
//CHECK COMPATIBILITY WITH IWDEE AND SR
COPY_EXISTING ~SPPR409.spl~ ~override/b_kel01.spl~ // Works?
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 169
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 267
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 101
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 328
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 282
      timing = 9
      resist_dispel = 0
  END
//CHECK COMPATIBILITY WITH IWDEE AND SR
COPY_EXISTING ~SPPR413.spl~ ~override/b_kel02.spl~ // Works?
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 267
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 169
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 101
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 282
      timing = 9
      resist_dispel = 0
  END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_kelemvor_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ckel~
	class 			= ~cleric~
 END

 /////////////////////////////////////////Cleric/Mage of Kelemvor
COPY ~faiths_and_powers/kits/clerics/209_kelemvor/b_ckel.2da~ ~override/b_cmkel.2da~

 ADD_KIT ~B_CM_KELEMVOR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                         T   S           F   Q             S S
//10                 L S                     W   C           L   U             W I
//9                  A M             B L S   O   I   W       A   A             O N
//8                  R A             A O H   H   M   A       I   R C   S       R G
//7                  G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                  E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CM_KELEMVOR       1 1 1 1 1 1 1 1~
~B_CM_KELEMVOR       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_KELEMVOR           12   0   0   0  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_KELEMVOR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_KELEMVOR           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_KELEMVOR           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                       LG LN LE NG TN NE CG CN CE
~B_CM_KELEMVOR        1  1  0  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                       FT CL MA TH DR RA
~B_CM_KELEMVOR           1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~override/b_cmkel.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CM_E  K_CM_H  K_CM_HE  K_CM_G  K_CM_D  K_CM_HL  K_CM_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 14~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20901
SAY @20902
SAY @20903

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20903)
		STR_VAR
			kit_name = B_CM_KELEMVOR
			clswpbon = ~0 0 3~
	END
END

//KIT ABILITY FILES___________________________________________________________________
//
//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_cmkel.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CM_KELEMVOR~
		kit_clab = ~b_cmkel~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 


//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_mage_kelemvor_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_cmkel~
	class 			= ~cleric_mage~
 END

/////////////////////////////////Fighter/cleric of Kelemvor
COPY ~faiths_and_powers/kits/clerics/209_kelemvor/b_ckel.2da~ ~override/b_cfkel.2da~

ADD_KIT ~B_CF_KELEMVOR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CF_KELEMVOR   	    1 1 1 1 1 1 1 1~
~B_CF_KELEMVOR   	    2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CF_KELEMVOR   	    0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CF_KELEMVOR   	    0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CF_KELEMVOR   	    0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CF_KELEMVOR   	    0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CF_KELEMVOR      1  1  0  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CF_KELEMVOR   	    1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~override/b_cfkel.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FC_E  K_FC_H  K_FC_HE  K_FC_G  K_FC_D  K_FC_HL  K_FC_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 8~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20901
SAY @20902
SAY @20903

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20903)
		STR_VAR
			kit_name = B_CF_KELEMVOR
			clswpbon = ~1 0 3~
	END
END

COPY ~faiths_and_powers/kits/clerics/202_torm/b_ctor.2da~ ~override/b_2tor.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_ckel.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CF_KELEMVOR~
		kit_clab = ~b_cfkel~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM fighter_cleric_kelemvor_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 2
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 2
	u_short_swords		= 2
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 0
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~b_cfkel~
	class 			= ~fighter_cleric~
 END

END
//__________________________________________________________________________________


//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							BATTLEGUARD OF TEMPUS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_tempus BEGIN

ADD_KIT ~B_CLERIC_TEMPUS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TEMPUS    1 1 1 1 1 1 1 1~
~B_CLERIC_TEMPUS    1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_TEMPUS    1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_TEMPUS    1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21001 //lower
SAY @21002 //Mixed
SAY @21003 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21003)
		STR_VAR
			kit_name = B_CLERIC_TEMPUS
			clswpbon = ~0 0 3~
	END
END

//TEMPUS ABILITY FILES______________________________________________________________
// Incite Rage
ACTION_IF FILE_EXISTS_IN_GAME ~spcl321.spl~ BEGIN
COPY_EXISTING ~spcl321.spl~ ~override/B_TEM03.spl~ // Incite Rage
	SAY NAME1 @21004
	SAY NAME2 @21004
	SAY UNIDENTIFIED_DESC @21006  //
	SAY IDENTIFIED_DESC @21006  //
  WRITE_BYTE 0x7e 1//Target 1 cre
END

COPY ~faiths_and_powers/kits/clerics/210_tempus/b_tem05.spl~ ~override~    //+1 damage

COPY ~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~ ~override~

//REPLACE VANILLA KIT_________________________________________________________________
//... should do this for IWD
ACTION_IF FILE_EXISTS_IN_GAME ~d5_menu.d5~ BEGIN
	COPY_EXISTING ~kitlist.2da~ ~override~
		COUNT_2DA_ROWS ~7~ "kit_row"
	OUTER_SET kit_row -= 2
	COPY_EXISTING ~K_C_D.2da~ ~override~
			~K_C_E.2da~ ~override~
			~K_C_G.2da~ ~override~
			~K_C_H.2da~ ~override~
			~K_C_HE.2da~ ~override~
			~K_C_HL.2da~ ~override~
			~K_C_HO.2da~ ~override~
		REPLACE_TEXTUALLY ~21~ ~%kit_row%~
	BUT_ONLY
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_tempus_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 1
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 1
	u_katanas 			= 1
	u_bastard_swords 	= 1
	u_2hand_swords 		= 1
	u_halberds 			= 1
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ctem~
	class 			= ~cleric~
 END

//FIGHTER/CLERIC______________________________________________________________________

COPY ~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~ ~override/b_2tem.2da~

ADD_KIT ~B_FC_TEMPUS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_FC_TEMPUS    	1 1 1 1 1 1 1 1~
~B_FC_TEMPUS    	1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	9   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	9   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_FC_TEMPUS    	9   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_FC_TEMPUS    	1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_FC_TEMPUS    	0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~override/b_2tem.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FC_E  K_FC_H  K_FC_HE  K_FC_G  K_FC_D  K_FC_HL  K_FC_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 8~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21001 //lower
SAY @21002 //Mixed
SAY @21003 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21003)
		STR_VAR
			kit_name = B_FC_TEMPUS
			clswpbon = ~0 0 3~
	END
END

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2tem.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_FC_TEMPUS~ 
		kit_clab = ~b_2tem~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM fighter_cleric_tempus_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 2
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 2
	u_daggers 			= 2
	u_short_swords		= 2
	u_long_swords		= 2
	u_scimitars 		= 2
	u_katanas 			= 2
	u_bastard_swords 	= 2
	u_2hand_swords 		= 2
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 0
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~b_2tem~
	class 			= ~fighter_cleric~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF LEIRA
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_leira BEGIN

ADD_KIT ~D5_CL_LEIRA~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CL_LEIRA   0 0 0 0 1 1 0 1~
~D5_CL_LEIRA   0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CL_LEIRA       0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CL_LEIRA       0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/212_leira/d5clei.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21201
SAY @21202
SAY @21203

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21204)
		STR_VAR
			kit_name = D5_CL_LEIRA
			clswpbon = ~0 0 3~
	END
END

//MISTWALKER ABILITY FILES____________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/clerics/212_leira/d5clei.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/kits/clerics/212_leira/d5_lei1.spl~ ~override~
	SAY NAME1 @21211
	SAY UNIDENTIFIED_DESC @21212

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_leira_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d5clei~
	class 			= ~cleric~
 END

//CLERIC/THIEF______________________________________________________________________

ADD_KIT ~D5_CT_LEIRA~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CT_LEIRA     0 0 0 0 1 1 0 1~
~D5_CT_LEIRA     0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_LEIRA         0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_LEIRA         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_LEIRA         0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_LEIRA         0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CT_LEIRA         0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CT_LEIRA         0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/212_leira/d52lei.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CT_E  K_CT_H  K_CT_HE  K_CT_G  K_CT_D  K_CT_HL  K_CT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21201
SAY @21202
SAY @21203

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21204)
		STR_VAR
			kit_name = D5_CT_LEIRA
			clswpbon = ~0 0 3~
	END
END

COPY_EXISTING ~faiths_and_powers/kits/clerics/212_leira/d5clei.2da~ ~override/d52lei.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d52lei.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_CT_LEIRA~ 
		kit_clab = ~d52lei~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_thief_leira_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d52lei~
	class 			= ~cleric_thief~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF BARAVAR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_baravar BEGIN

ADD_KIT ~B_CLERIC_BARAVAR~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_BARAVAR   0 0 0 0 1 1 0 1~
~B_CLERIC_BARAVAR   0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_CLERIC_BARAVAR       0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_CLERIC_BARAVAR       0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/213_baravar/b_bara.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_G~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21301
SAY @21302
SAY @21303

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21303)
		STR_VAR
			kit_name = B_CLERIC_BARAVAR
			clswpbon = ~0 0 3~
	END
END

//KIT ABILITY FILES__________________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/clerics/213_baravar/b_bara.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/kits/clerics/212_leira/d5_lei1.spl~ ~override/b_bar01~ //it's the same ability with a different name, so...
	SAY NAME1 @21311
	SAY UNIDENTIFIED_DESC @21312

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_baravar_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_bara~
	class 			= ~cleric~
 END

//CLERIC/THIEF______________________________________________________________________

ADD_KIT ~B_CT_BARAVAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CT_BARAVAR     0 0 0 0 1 1 0 1~
~B_CT_BARAVAR     0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_BARAVAR         0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_BARAVAR         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_BARAVAR         0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_BARAVAR         0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_CT_BARAVAR         0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_CT_BARAVAR         0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/213_baravar/b_bart.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CT_G~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21301
SAY @21302
SAY @21303

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21303)
		STR_VAR
			kit_name = B_CT_BARAVAR
			clswpbon = ~0 0 3~
	END
END

COPY_EXISTING ~faiths_and_powers/kits/clerics/213_baravar/b_bart.2da~ ~override~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_bart.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CT_BARAVAR~
		kit_clab = ~b_bart~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_thief_baravar_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_bart~
	class 			= ~cleric_thief~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF LOVIATAR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_loviatar BEGIN

ADD_KIT ~B_CLERIC_LOVIATAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_LOVIATAR      0 0 0 0 1 1 0 1~
~B_CLERIC_LOVIATAR      1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   11  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_LOVIATAR  0  1  1  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_LOVIATAR  1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21901 //lower
SAY @21902 //Mixed
SAY @21903 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21903)
		STR_VAR
			kit_name = B_CLERIC_LOVIATAR
			clswpbon = ~0 0 3~
	END
END

//LOVIATAR ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.spl~     ~override~  // Pain Touch
	SAY NAME1 @21911
	SAY NAME2 @21911
	SAY UNIDENTIFIED_DESC @21912  //
	SAY IDENTIFIED_DESC @21912  //
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.itm~     ~override~  // Pain Touch
  SAY NAME1 @21911
  SAY NAME2 @21911
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov02.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov03.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov04.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov05.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov06.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov02.spl~     ~override~  // Pain Touch
  SAY NAME1 @6
  SAY NAME2 @6
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov03.spl~     ~override~  // Loviatar's Caress
	SAY NAME1 @21914
	SAY NAME2 @21914
	SAY UNIDENTIFIED_DESC @21915  //
	SAY IDENTIFIED_DESC @21915  //
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov04.spl~     ~override~  // Suppress Pain Touch
  SAY NAME1 @21916
  SAY NAME2 @21916

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_loviatar_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_clov~
	class 			= ~cleric~
 END

//CLERIC/THIEF________________________________________________________________________

ADD_KIT ~B_CT_LOVIATAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CT_LOVIATAR      0 0 0 0 1 1 0 1~
~B_CT_LOVIATAR      1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   11  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CT_LOVIATAR      0  1  1  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CT_LOVIATAR      1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/219_loviatar/b_2lov.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CT_E  K_CT_H  K_CT_HE  K_CT_G  K_CT_D  K_CT_HL  K_CT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21901 //lower
SAY @21902 //Mixed
SAY @21903 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21903)
		STR_VAR
			kit_name = B_CT_LOVIATAR
			clswpbon = ~0 0 3~
	END
END

COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~ ~override/b_2lov.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2lov.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CT_LOVIATAR~ 
		kit_clab = ~b_2lov~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_thief_loviatar_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_2lov~
	class 			= ~cleric_thief~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF TALOS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_talos BEGIN

ADD_KIT ~B_CLERIC_TALOS~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TALOS       1 1 1 1 1 1 1 1~
~B_CLERIC_TALOS       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_TALOS           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_TALOS           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/224_talos/b_ctal.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22401
SAY @22402
SAY @22403

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22403)
		STR_VAR
			kit_name = B_CLERIC_TALOS
			clswpbon = ~0 0 3~
	END
END

//TALOS ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/224_talos/b_ctal.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal01.spl~     ~override~  //  Electricity resist
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal10.spl~     ~override~  //  Lightning Bolt
	SAY UNIDENTIFIED_DESC @22406  //
	SAY IDENTIFIED_DESC @22406  //

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 19) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_talos_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ctal~
	class 			= ~cleric~
 END

//fighter/cleric_____________________________________________________________________

ADD_KIT ~B_FC_TALOS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_FC_TALOS           1 1 1 1 1 1 1 1~
~B_FC_TALOS           1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                    STR DEX CON INT WIS CHR
~B_FC_TALOS           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                     LG LN LE NG TN NE CG CN CE
~B_FC_TALOS            0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                     FT CL MA TH DR RA
~B_FC_TALOS            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/224_talos/b_2tal.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FC_E  K_FC_H  K_FC_HE  K_FC_G  K_FC_D  K_FC_HL  K_FC_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 8~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22401
SAY @22402
SAY @22403

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22403)
		STR_VAR
			kit_name = B_FC_TALOS
			clswpbon = ~0 0 3~
	END
END


//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2tal.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_FC_TALOS~ 
		kit_clab = ~b_2tal~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM fighter_cleric_talos_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 2
	u_maces 	 		= 2
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 2
	u_short_swords		= 2
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 0
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~b_2tal~
	class 			= ~fighter_cleric~
 END

/////////////////////////////////////////Cleric/Mage of Talos
COPY ~faiths_and_powers/kits/clerics/224_talos/b_2tal.2da~ ~override/b_3tal.2da~

 ADD_KIT ~B_CM_TALOS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                         T   S           F   Q             S S
//10                 L S                     W   C           L   U             W I
//9                  A M             B L S   O   I   W       A   A             O N
//8                  R A             A O H   H   M   A       I   R C   S       R G
//7                  G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                  E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CM_TALOS       1 1 1 1 1 1 1 1~
~B_CM_TALOS       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_TALOS           12   0   0   0  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_TALOS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_TALOS           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CM_TALOS           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                       LG LN LE NG TN NE CG CN CE
~B_CM_TALOS        0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                       FT CL MA TH DR RA
~B_CM_TALOS           1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~override/b_3tal.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CM_E  K_CM_H  K_CM_HE  K_CM_G  K_CM_D  K_CM_HL  K_CM_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 14~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22401
SAY @22402
SAY @22403

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22403)
		STR_VAR
			kit_name = B_CM_TALOS
			clswpbon = ~0 0 3~
	END
END

//KIT ABILITY FILES___________________________________________________________________
//
//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_3tal.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CM_TALOS~
		kit_clab = ~b_3tal~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_mage_talos_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_3tal~
	class 			= ~cleric_mage~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF CYRIC
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_cyric BEGIN

ADD_KIT ~B_CLERIC_CYRIC~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_CYRIC       1 1 1 1 1 1 1 1~
~B_CLERIC_CYRIC       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_CYRIC           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_CYRIC           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/225_cyric/b_ccyr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22501
SAY @22502
SAY @22503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22503)
		STR_VAR
			kit_name = B_CLERIC_CYRIC
			clswpbon = ~0 0 3~
	END
END

//CYRIC ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/225_cyric/b_ccyr.2da~ ~override~
//+1 vs. illusions
COPY ~faiths_and_powers/kits/clerics/225_cyric/B_CYR02.spl~ ~override~
COPY_EXISTING ~SPWI401.spl~ ~override/B_CYR03.spl~ // Confusion
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

COPY_EXISTING ~SPWI509.spl~ ~override/B_CYR04.spl~ // feeblemind
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

//protection from fear  (using the tempus spl.  It's basically the same...)
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~25818~ END     //text block
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~17427~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~14007~ END     //text block
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~35484~ END     //text block
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_cyric_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 2
	u_short_swords		= 2
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ccyr~
	class 			= ~cleric~
 END

//_____________________CLERIC/THIEF___________________________________________________

ADD_KIT ~B_CT_CYRIC~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CT_CYRIC           1 1 1 1 1 1 1 1~
~B_CT_CYRIC           1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                     LG LN LE NG TN NE CG CN CE
~B_CT_CYRIC            0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                     FT CL MA TH DR RA
~B_CT_CYRIC            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/225_cyric/b_ctcyr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CT_E  K_CT_H  K_CT_HE  K_CT_G  K_CT_D  K_CT_HL  K_CT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22501
SAY @22502
SAY @22503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22503)
		STR_VAR
			kit_name = B_CT_CYRIC
			clswpbon = ~0 0 3~
	END
END

COPY ~faiths_and_powers/kits/clerics/225_cyric/b_ctcyr.2da~ ~override~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_ctcyr.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CT_CYRIC~
		kit_clab = ~b_ctcyr~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_thief_cyric_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 2
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ctcyr~
	class 			= ~cleric_thief~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF UMBERLEE
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_umberlee BEGIN

ADD_KIT ~B_CLERIC_UMBERLEE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_UMBERLEE    1 1 1 1 1 1 1 1~
~B_CLERIC_UMBERLEE    1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE        0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                		 STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                		 STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                		 STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_UMBERLEE           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_UMBERLEE           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/226_umberlee/b_umb.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22601
SAY @22602
SAY @22603

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22603)
		STR_VAR
			kit_name = B_CLERIC_UMBERLEE
			clswpbon = ~0 0 3~
	END
END

//UMBERLEE ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/226_umberlee/b_umb.2da~ ~override~

//Smashing Wave______________________________________________________________________//
//Install it if it isn't already installed
ACTION_IF (GAME_IS ~bgee bg2ee eet~) AND (NOT FILE_EXISTS_IN_GAME ~b_IWD.itm~) THEN BEGIN   //
//Go over this spell head to toe first...

 END//end smashing wave

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAM cleric_umberlee_spheres

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_umb~
	class 			= ~cleric~
 END

END
//__________________________________________________________________________________

