
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							MAGE HUNTER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO mage_hunter BEGIN

ADD_KIT ~D5MAGEH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MAGEH       2 2 2 2 2 2 2 2~
~D5MAGEH       2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH           0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH           0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH           0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MAGEH           1  1  1  1  1  1  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MAGEH           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mageh.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_H    K_R_D   K_R_E   K_R_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @95301
SAY @95302
SAY @95303

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@95303)
		STR_VAR
			kit_name = D5MAGEH
			clswpbon = ~1 0 2~
	END
END

//MAGE HUNTER ABILITY FILES_________________________________________________________
//
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mageh.2da~ ~override~

COPY_EXISTING ~spwi318.spl~ ~override/d5_radfl.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi513.spl~ ~override/d5_rabre.spl~
	LPM spell_to_innate
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_savbo.spl~ ~override~
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mghs1.spl~ ~override~
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mghsa.eff~ ~override~
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mghsc.eff~ ~override~
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mghs2.spl~ ~override~
	SAY NAME1 @95311
	SAY UNIDENTIFIED_DESC @95312
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mghs1.eff~ ~override~
COPY ~faiths_and_powers/kits/scouts/953_mage_hunter/d5_mghs2.eff~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~d5_mageh~
	class 			= ~scout~
	s_Life 			= ~ranger~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~ranger~
	s_War 			= ~x~
	s_Exploration   = ~ranger~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~ranger~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~ranger~
	s_Shadow 		= ~x~
	s_Magic 		= ~ranger~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							BARBARIAN RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO barbarian_ranger BEGIN

ADD_KIT ~D5RBARB~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5RBARB       2 2 2 2 2 2 2 2~
~D5RBARB       2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 0 2 2 0 2 2 2 0 2 2 0 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RBARB           0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5RBARB           1  1  0  1  1  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5RBARB           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rbarb.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_R_H   K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x40000000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @95401
SAY @95402
SAY @95403

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@95403)
		STR_VAR
			kit_name = D5RBARB
			clswpbon = ~1 0 2~
	END
END

//BARBARIAN RANGER ABILITY FILES_____________________________________________________
//
COPY ~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rbarb.2da~ ~override~
COPY ~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rbaab.spl~ ~override~
COPY ~faiths_and_powers/kits/scouts/954_barbarian_ranger/d5_rback.spl~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~d5_rbarb~
	class 			= ~scout~
	s_Life 			= ~x~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Exploration   = ~ranger~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~ranger~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

//FIX BARB USABILITY__________________________________________________________________
//
 COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
		READ_BYTE 0x1f "use"
		READ_BYTE 0x29 "kit"
		PATCH_IF ((("%kit%" BAND 0b01000000) = 0b01000000) AND 
				(("%use%" BAND 0b00001000) = 0b00001000)) THEN BEGIN
			WRITE_BYTE 0x29 ("%kit%" BAND 0b10111111) 
		END
	END
 BUT_ONLY_IF_IT_CHANGES

END//____________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ELVEN ARCHER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO elven_archer BEGIN

ADD_KIT ~D5EARCH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5EARCH       1 1 1 1 0 0 0 5~
~D5EARCH       1 1 1 1 0 0 0 5 0 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 5 5 1 1 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5EARCH           0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5EARCH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5EARCH           0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5EARCH           0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5EARCH           1  1  0  1  1  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5EARCH           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/scouts/955_elven_archer/d5_earch.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_E~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00008000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @95501
SAY @95502
SAY @95503

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@95503)
		STR_VAR
			kit_name = D5EARCH
			clswpbon = ~1 0 2~
	END
END

//ELVEN ARCHER ABILITY FILES_________________________________________________________
//
COPY ~faiths_and_powers/kits/scouts/955_elven_archer/d5_earch.2da~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~d5_earch~
	class 			= ~scout~
	s_Life 			= ~ranger~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~ranger~
	s_War 			= ~x~
	s_Exploration   = ~ranger~
	s_Knowledge 	= ~ranger~
	s_Deception 	= ~ranger~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~ranger~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~ranger~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~ranger~
	s_Fire 			= ~x~
	s_Light 		= ~ranger~
	s_Shadow 		= ~x~
	s_Magic 		= ~ranger~
	s_Perdition     = ~x~
 END

//ADD ELVEN ARCHER TO MENUS__________________________________________________________
//
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~7~ "jrows"
OUTER_SET jrows -= 2
COPY_EXISTING ~K_R_E.2da~ ~override~
	REPLACE_TEXTUALLY ~[ %TAB%]7~ ~%TAB%%jrows%~
BUT_ONLY

//ARCHERS USE ELVEN CHAIN____________________________________________________________
//
ACTION_FOR_EACH elven_chain IN
	~chan12~
	~chan13~
	~chan14~
	~chan15~
	~chan16~
	~chan19~
	~clolth~
	~dwchan01~
	~a!bchan1~
	~bsingchn~
	~c2chan01~
	~chandrw~
	~cmarq02~
	~cmarq12~
	~cmtuch01~
	~cota~
	~dsjearm~
	~echan01~
	~echan02~
	~elfmail~
	~elvarmx~
	~fwchan02~
	~gcmch01~
	~illas04~
	~kimchain~
	~kiyoarm1~
	~kiyoarm2~
	~kiyoarm3~
	~kiyowed1~
	~mau006~
	~ntchan04~
	~rr#chn01~
	~s!chan02~
	~scal04~
	~sgchan2~ 
	~tzchan01~
	~u#chan01~
	~u#chan07~
	~ucmgch01~
	~zyplatn8~
	~chands06~
	~drowchn1~
	~drowchn2~
	~drowchn3~
	~efml01~
	~pchan~
	~AAITM127~
	~BGSX10~
	~KOVAWED1~
	~cmchan02~
	~elfchan~
	~kaychai~
	~ntchan06~
	~r#aspchn~
	~tcarmor5~
	~tcechan~
	~tcrihar1~
	~tcrihar2~
	~tcrivarm~
	~CMTCH02~
	~CMTCH03~
	~CMTCH05~
	~ESXCHA~
	~FWCHAN03~
	~SOAITM01~
  BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%elven_chain%.itm~ BEGIN
	  COPY_EXISTING ~%elven_chain%.itm~ ~override~
		WRITE_BYTE 0x2d ("0x00") //blocked: none
	  BUT_ONLY
	END
  END

END
//___________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							HALFLING SLINGER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO halfling_slinger BEGIN

ADD_KIT ~D5SLING~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5SLING       1 1 1 0 0 0 0 5~
~D5SLING       1 1 1 0 0 0 0 5 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 5 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5SLING           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5SLING           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/scouts/956_halfling_slinger/d5_sling.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_HL~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00008000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @95601
SAY @95602
SAY @95603

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@95603)
		STR_VAR
			kit_name = D5SLING
			clswpbon = ~1 0 2~
	END
END

//HALFLING SLINGER ABILITY FILES_____________________________________________________
//
 COPY ~faiths_and_powers/kits/scouts/956_halfling_slinger/d5_sling.2da~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name 		= ~d5_sling~
	class 			= ~scout~
	s_Life 			= ~ranger~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~ranger~
	s_War 			= ~x~
	s_Exploration   = ~ranger~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~ranger~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~ranger~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

//Halfling Rangers__________________________________________________________________
//
 COPY_EXISTING ~clsrcreq.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~ranger~ // read column value
	  PATCH_IF ~%ranger%~ STRING_EQUAL_CASE ~RANGER~ BEGIN
	    SET patch_row = (%row%)
	    SET_2DA_ENTRY (%patch_row%) 5 cols 1
	  END
	  PATCH_IF ~%ranger%~ STRING_EQUAL_CASE ~D5SLING~ BEGIN
	    SET patch_row = (%row%)
	    SET_2DA_ENTRY (%patch_row%) 5 cols 1
	  END
	END

//REPLACE ARCHER IN MENUS___________________________________________________________
//
 COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~7~ "jrows"
 OUTER_SET jrows -= 2
 COPY_EXISTING ~K_R_E.2da~ ~override~
	REPLACE_TEXTUALLY ~[ %TAB%]7~ ~%TAB%%jrows%~
 BUT_ONLY

END
//___________________________________________________________________________________

