
/*

//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							UR-Priest
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO cleric_ur_priest BEGIN

ADD_KIT ~B_CLERIC_UR_PRIEST~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_UR_PRIEST     1 1 1 1 1 1 1 1~
~B_CLERIC_UR_PRIEST     1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_UR_PRIEST  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_UR_PRIEST  0  1  1  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_UR_PRIEST  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/200_Ur_Priest/b_clur.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20001 //lower
SAY @20002 //Mixed
SAY @20003 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20003)
		STR_VAR
			kit_name = B_CLERIC_UR_PRIEST
			clswpbon = ~0 0 3~
	END
END

//Ur-Priest ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_clur.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01.spl~     ~override~  // sap the spirit
        SAY NAME1 @20004
        SAY NAME2 @20004
        SAY UNIDENTIFIED_DESC @20005
	SAY DESC @20005

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01a.spl~     ~override~  // sap the spirit
    LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR resource = ~b_ur01a~ END //+1 casting level notifier

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01a.eff~     ~override~  // +1 casting level notifier
  SAY 0x1c @20006    //+1 casting level notifier

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur01b.spl~     ~override~  // sap the spirit

COPY ~faiths_and_powers/kits/clerics/200_Ur_Priest/b_ur02.spl~     ~override~  // save penalty

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo101.spl~     ~override~  // Infravision Orison
//  SAY NAME1 @98504 //Infravision
//  SAY UNIDENTIFIED_DESC @98505   //Infravision

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo102.spl~     ~override~  // Fire bolt Orison
//  SAY NAME1 @98506 //Fire bolt
//  SAY UNIDENTIFIED_DESC @98507   //Fire bolt desc

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla02.spl~     ~override~  // Boon of Lathander
//  SAY UNIDENTIFIED_DESC @98534//

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla03.spl~     ~override~  // Hold Undead
//  SAY NAME1 @20107
//  SAY UNIDENTIFIED_DESC @20104//

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 0) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_clur~
	class 			= ~occultist~
	s_Life 			= ~x~
	s_Death 		= ~major~
	s_Benediction 	        = ~x~
	s_Destruction 	        = ~major~
	s_Protection 	        = ~major~
	s_War 			= ~major~
	s_Exploration   = ~x~
	s_Knowledge 	        = ~major~
	s_Deception 	        = ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~major~
	s_Affliction 	        = ~major~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~major~
	s_Water 		= ~major~
	s_Air 			= ~major~
	s_Fire 			= ~major~
	s_Light 		= ~x~
	s_Shadow 		= ~major~
	s_Magic 		= ~major~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________

*/



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					    	BEAST MYSTIC
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO beast_lord BEGIN

ADD_KIT ~D5_OC_BEAST~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_OC_BEAST     0 0 0 1 1 1 0 1~
~D5_OC_BEAST     0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   12  9   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                    STR DEX CON INT WIS CHR
~D5_OC_BEAST          0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                    LG LN LE NG TN NE CG CN CE
~D5_OC_BEAST          0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                    FT CL MA TH DR RA
~D5_OC_BEAST          1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/occultists/762_beast_lord/d5obst.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x20000000 11~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @76201
SAY @76202
SAY @76203

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@76204)
		STR_VAR
			kit_name = D5_OC_BEAST
			clswpbon = ~0 0 3~
	END
END

// ABILITY FILES_____________________________________________________________
//
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5obst.2da~ ~override~
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_clbe.spl~ ~override~
	SAY NAME1 @76211
	SAY UNIDENTIFIED_DESC @76211
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_clbe.itm~ ~override~
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_clno.spl~ ~override~
	SAY NAME1 @76212
	SAY UNIDENTIFIED_DESC @76212
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_wwmy.spl~ ~override~
	SAY NAME1 @76213
	SAY UNIDENTIFIED_DESC @76213
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_wwnf.spl~ ~override~
	SAY NAME1 @76214
	SAY UNIDENTIFIED_DESC @76214
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_wwcl1.itm~ ~override~
	SAY NAME1 @76215
	SAY UNIDENTIFIED_DESC @76215
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_wwcl2.itm~ ~override~
	SAY NAME1 @76215
	SAY UNIDENTIFIED_DESC @76215
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_ww01.cre~ ~override~
	SAY NAME1 @76216
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_ww02.cre~ ~override~
	SAY NAME1 @76217
COPY ~faiths_and_powers/kits/occultists/762_beast_lord/d5_ww03.cre~ ~override~
	SAY NAME1 @76218
COPY ~faiths_and_powers/kits/misc/d5cllv1.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5cstbo.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5disp1.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5disp2.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5disp3.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5disp4.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5disp5.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5disp6.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/misc/d5disp7.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_druids.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_D_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_D_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 17) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d5obst~
	class 			= ~occultist~
	s_Life 			= ~minor~
	s_Death 		= ~minor~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Exploration   = ~major~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~major~
	s_Dread 		= ~minor~
	s_Vigor 		= ~major~
	s_Affliction 	= ~major~
	s_Animal 		= ~focus~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~minor~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~minor~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					    	ELEMENTALIST
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO elementalist BEGIN

ADD_KIT ~D5_OC_ELEM~

//WEAPON PROFICIENCIES________________________________________________________________
//11	                                   T   S           F   Q             S S
//10	           L S                     W   C           L   U             W I
//9 	           A M             B L S   O   I   W       A   A             O N
//8 	           R A             A O H   H   M   A       I   R C   S       R G
//7 	           G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6 	           E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5 	           S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4 	           W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3 	           O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2 	           R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1 	           D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_OC_ELEM        0 0 0 1 1 1 0 1~
~D5_OC_ELEM        0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_OC_ELEM            0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_OC_ELEM            0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_OC_ELEM            0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_OC_ELEM            0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//  	               LG LN LE NG TN NE CG CN CE
~D5_OC_ELEM            1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//  	               FT CL MA TH DR RA
~D5_OC_ELEM            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/occultists/763_elementalist/d5oelm.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x20000000 11~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @76301
SAY @76302
SAY @76303

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@76304)
		STR_VAR
			kit_name = D5_OC_ELEM
			clswpbon = ~0 0 3~
	END
END

// ABILITY FILES_____________________________________________________________
//
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5oelm.2da~ ~override~
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5_elem1.spl~ ~override~
	SAY NAME1 @76316
	SAY UNIDENTIFIED_DESC @76317
//Text notification.  Ability defaults to IWDEE text notification.  	
ACTION_IF GAME_IS ~eet bg2ee~ THEN BEGIN
COPY_EXISTING ~d5_elem1.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = 8364 END  //Text Notification
END
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~d5_elem1.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = 26206 END  //Text Notification
END

COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5_elefo.spl~ ~override~
		SAY NAME1 @76311
		SAY UNIDENTIFIED_DESC @76311
//AIR
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelair.spl~ ~override~
		SAY NAME1 @76312
		SAY UNIDENTIFIED_DESC @76312
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelair.spl~ ~override/d5eela15.spl~  //15th lev
		SAY NAME1 @76312
		SAY UNIDENTIFIED_DESC @76312
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 3 parameter1 = 25 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 29 parameter1 = 25 END// string
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelair.spl~ ~override/d5eela20.spl~  //20th lev
		SAY NAME1 @76312
		SAY UNIDENTIFIED_DESC @76312
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 3 parameter1 = 35 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 29 parameter1 = 35 END// string
//Earth
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelear.spl~ ~override~
		SAY NAME1 @76313
		SAY UNIDENTIFIED_DESC @76313
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelear.spl~ ~override/d5eele15.spl~  //15th lev
		SAY NAME1 @76313
		SAY UNIDENTIFIED_DESC @76313
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 9 parameter1 = 25 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 87 parameter1 = 25 END// string
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelair.spl~ ~override/d5eela20.spl~  //20th lev
		SAY NAME1 @76313
		SAY UNIDENTIFIED_DESC @76313
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 9 parameter1 = 35 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 87 parameter1 = 35 END// string
//Fire
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelfir.spl~ ~override~
		SAY NAME1 @76314
		SAY UNIDENTIFIED_DESC @76314
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelfir.spl~ ~override/d5eelf15.spl~  //15th
		SAY NAME1 @76314
		SAY UNIDENTIFIED_DESC @76314
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 1 parameter1 = 25 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 30 parameter1 = 25 END// string
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelfir.spl~ ~override/d5eelf20.spl~  //20th
		SAY NAME1 @76314
		SAY UNIDENTIFIED_DESC @76314
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 1 parameter1 = 35 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 30 parameter1 = 35 END// string
//Water
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelwat.spl~ ~override~
		SAY NAME1 @76315
		SAY UNIDENTIFIED_DESC @76315
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelwat.spl~ ~override/d5eelw15.spl~ //15th
		SAY NAME1 @76315
		SAY UNIDENTIFIED_DESC @76315
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 4 parameter1 = 25 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 27 parameter1 = 25 END// string
COPY ~faiths_and_powers/kits/occultists/763_elementalist/d5eelwat.spl~ ~override/d5eelw20.spl~ //20th
		SAY NAME1 @76315
		SAY UNIDENTIFIED_DESC @76315
                LPF ALTER_EFFECT INT_VAR match_opcode = 332 match_parameter2 = 4 parameter1 = 35 END// string
                LPF ALTER_EFFECT INT_VAR match_opcode = 27 parameter1 = 35 END// string

COPY ~faiths_and_powers/kits/occultists/763_elementalist/b_elefo.2da~ ~override~
COPY ~faiths_and_powers/kits/occultists/763_elementalist/b_ele15.2da~ ~override~
COPY ~faiths_and_powers/kits/occultists/763_elementalist/b_ele20.2da~ ~override~


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d5oelm~
	class 			= ~occultist~
	s_Life 			= ~minor~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~minor~
	s_Protection 	= ~minor~
	s_War 			= ~x~
	s_Exploration   = ~x~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~major~
	s_Water 		= ~major~
	s_Air 			= ~major~
	s_Fire 			= ~major~
	s_Light 		= ~major~
	s_Shadow 		= ~minor~
	s_Magic 		= ~minor~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					    	CHAOS PRIEST
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO chaos_priest BEGIN

ADD_KIT ~D5XAOS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5XAOS        0 0 0 1 1 1 0 1~
~D5XAOS        0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5XAOS            0   0   0   0   12  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5XAOS            0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5XAOS            0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5XAOS            0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5XAOS            1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5XAOS            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~f_n_p/kits/occultists/765_chaos_priest/d5_xaos.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x80000000 11~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @76501
SAY @76502
SAY @76503

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@76504)
		STR_VAR
			kit_name = D5XAOS
			clswpbon = ~0 0 3~
	END
END

// ABILITY FILES_____________________________________________________________
//
COPY ~f_n_p/kits/occultists/765_chaos_priest/d5_xaos.2da~ ~override~
COPY_EXISTING ~spwi124.spl~ ~override/d5_xaos1.spl~
	WRITE_SHORT 0x1c 2
	SAY NAME1 ~Reckless Dweomer~
	READ_LONG 0x50 "valid"
	PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
		READ_STRREF 0x50 ~desc~
		INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
			REPLACE_TEXTUALLY ~Nahal's Reckless~ ~Reckless~
		END
		SAY_EVALUATED 0x50 ~%new_desc%~
	END
COPY_EXISTING ~spwi222.spl~ ~override/d5_xaos2.spl~
	WRITE_SHORT 0x1c 2
COPY_EXISTING ~spwi723.spl~ ~override/d5_xaos7.spl~
	WRITE_SHORT 0x1c 2


//DEFINE SPHERE ACCESS______________________________________________________________
//
//	...

END
//__________________________________________________________________________________

