
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF TYR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_tyr BEGIN

ADD_KIT ~B_CHAMP_TYR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_TYR            2 2 2 2 2 2 2 2~
~B_CHAMP_TYR            2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TYR  13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TYR  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TYR  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TYR  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_TYR        1  0  0  0  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_TYR        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/801_tyr/b_ch01.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80101 //lower
SAY @80102 //Mixed
SAY @80103 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80103)
		STR_VAR
			kit_name = B_CHAMP_TYR
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/801_tyr/b_ch01.2da~ ~override~
//Smite Evil
COPY ~faiths_and_powers/kits/champions/801_tyr/b_ch101.spl~ ~override~
        SAY NAME1 @80104
        SAY NAME2 @80104
        SAY UNIDENTIFIED_DESC @80105
	SAY DESC @80105
//effect
COPY ~faiths_and_powers/kits/champions/801_tyr/b_ch101a.eff~ ~override~
//sec spell
COPY ~faiths_and_powers/kits/champions/801_tyr/b_ch101a.spl~ ~override~
//3rd spell
COPY ~faiths_and_powers/kits/champions/801_tyr/b_ch101b.spl~ ~override~

//protection from evil
COPY ~faiths_and_powers/kits/champions/801_tyr/b_tyr01.spl~ ~override~

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_paladins.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_P_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_P_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 0) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch01~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~x~
	s_Benediction 	= ~paladin~
	s_Destruction 	= ~x~
	s_Protection  	= ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	= ~paladin~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~paladin~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~paladin~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF KELEMVOR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_kelemvor BEGIN

ADD_KIT ~B_CHAMP_KELE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_KELE           2 2 2 2 2 2 2 2~
~B_CHAMP_KELE           2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_KELE        1  1  1  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_KELE        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/802_Kelemvor/b_ch02.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80201 //lower
SAY @80202 //Mixed
SAY @80203 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80203)
		STR_VAR
			kit_name = B_CHAMP_KELE
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch02.2da~ ~override~
//Smite Undead
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102.spl~ ~override~
        SAY NAME1 @80204
        SAY NAME2 @80204
        SAY UNIDENTIFIED_DESC @80205
	SAY DESC @80205
//effects
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102a.eff~ ~override~
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102c.eff~ ~override~

//sec spell     Smite/apply death
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102a.spl~ ~override~
//3rd spell     Death to dead
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102b.spl~ ~override~
//4th spell     Apply xtra damage
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102c.spl~ ~override~
//5th spell     Xtra dam
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102d.spl~ ~override~
//Turn
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_kel01.spl~ ~override~

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_CHAMP_KELE 0~
  BUT_ONLY_IF_IT_CHANGES
END

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_paladins.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_D_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_P_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 6) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch02~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~paladin~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	= ~paladin~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~paladin~
	s_Vigor 		= ~x~
	s_Affliction 	= ~paladin~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________

DEFINE_ACTION_MACRO iwdee_champion_kelemvor BEGIN

ADD_KIT ~B_CHAMP_KELE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_KELE           2 2 2 2 2 2 2 2~
~B_CHAMP_KELE           2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_KELE  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_KELE        0  0  1  0  0  1  0  0  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_KELE        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/802_Kelemvor/b_ch02.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000021 6~  //blackguard usability

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80206 //lower
SAY @80207 //Mixed
SAY @80208 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80208)
		STR_VAR
			kit_name = B_CHAMP_KELE
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch02.2da~ ~override~
//Smite Undead
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102.spl~ ~override~
        SAY NAME1 @80204
        SAY NAME2 @80204
        SAY UNIDENTIFIED_DESC @80205
	SAY DESC @80205
//effects
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102a.eff~ ~override~
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102c.eff~ ~override~

//sec spell     Smite/apply death
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102a.spl~ ~override~
//3rd spell     Death to dead
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102b.spl~ ~override~
//4th spell     Apply xtra damage
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102c.spl~ ~override~
//5th spell     Xtra dam
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_ch102d.spl~ ~override~
//Turn
COPY ~faiths_and_powers/kits/champions/802_Kelemvor/b_kel01.spl~ ~override~

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	INSERT_2DA_ROW 3 0 ~B_CHAMP_KELE 0~
  BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch02~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~paladin~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	= ~paladin~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~paladin~
	s_Vigor 		= ~x~
	s_Affliction 	= ~paladin~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF TEMPUS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_tempus BEGIN

ADD_KIT ~B_CHAMP_TEMP~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_TEMP           2 2 2 2 2 2 2 2~
~B_CHAMP_TEMP           2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TEMP  13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TEMP  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TEMP  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TEMP  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_TEMP        1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_TEMP        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/803_tempus/b_ch03.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80301 //lower
SAY @80302 //Mixed
SAY @80303 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80303)
		STR_VAR
			kit_name = B_CHAMP_TEMP
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/803_tempus/b_ch03.2da~ ~override~
//Smite Foe
COPY ~faiths_and_powers/kits/champions/803_tempus/b_ch103.spl~ ~override~
        SAY NAME1 @80304
        SAY NAME2 @80304
        SAY UNIDENTIFIED_DESC @80305
	SAY DESC @80305
COPY ~faiths_and_powers/kits/champions/803_tempus/b_ch103a.spl~ ~override~
COPY ~faiths_and_powers/kits/champions/803_tempus/b_ch103a.eff~ ~override~
//effect
//COPY ~faiths_and_powers/kits/champions/803_tempus/b_ch101a.eff~ ~override~
//sec spell
//COPY ~faiths_and_powers/kits/champions/803_tempus/b_ch101a.spl~ ~override~
//3rd spell
//COPY ~faiths_and_powers/kits/champions/803_tempus/b_ch101b.spl~ ~override~

//protection from fear
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~25818~ END     //text block
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~17427~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~14007~ END     //text block
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~35484~ END     //text block
END

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_CHAMP_TEMP 0~
  BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch03~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~x~
	s_Benediction 	        = ~paladin~
	s_Destruction 	        = ~x~
	s_Protection 	        = ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	        = ~paladin~
	s_Deception 	        = ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~paladin~
	s_Affliction 	        = ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~paladin~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF BANE
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_bane BEGIN

ADD_KIT ~B_CHAMP_BANE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_BANE           2 2 2 2 2 2 2 2~
~B_CHAMP_BANE           2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_BANE        0  1  1  0  0  1  0  0  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_BANE        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/804_bane/b_ch04.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80401 //lower
SAY @80402 //Mixed
SAY @80403 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80403)
		STR_VAR
			kit_name = B_CHAMP_BANE
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch04.2da~ ~override~
//Smite Foe
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104.spl~ ~override~
        SAY NAME1 @80404
        SAY NAME2 @80404
        SAY UNIDENTIFIED_DESC @80405
	SAY DESC @80405
//effect
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104a.eff~ ~override~
//sec spell
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104a.spl~ ~override~
//3rd spell
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104b.spl~ ~override~

//protection from fear  (using the tempus spl.  It's basically the same...)
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_BAN01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~25818~ END     //text block
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_BAN01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~17427~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~14007~ END     //text block
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_BAN01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~35484~ END     //text block
END

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
	COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
		INSERT_2DA_ROW 3 0 ~B_CHAMP_BANE 0~
	BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch04~
	class 			= ~champion~
	s_Life 			= ~x~
	s_Death 		= ~paladin~
	s_Benediction 	= ~x~
	s_Destruction 	= ~paladin~
	s_Protection 	= ~x~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	= ~paladin~
	s_Deception 	= ~x~
	s_Thought 		= ~paladin~
	s_Dread 		= ~paladin~
	s_Vigor 		= ~x~
	s_Affliction 	= ~paladin~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~paladin~
 END

END
//__________________________________________________________________________________

DEFINE_ACTION_MACRO iwdee_champion_bane BEGIN

ADD_KIT ~B_CHAMP_BANE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_BANE           2 2 2 2 2 2 2 2~
~B_CHAMP_BANE           2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_BANE       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_BANE        0  0  1  0  0  1  0  0  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_BANE        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/804_bane/b_ch04.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000021 6~  //blackguard usability

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80401 //lower
SAY @80402 //Mixed
SAY @80406//Help  No lN and slight tweak in description

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80406)
		STR_VAR
			kit_name = B_CHAMP_BANE
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch04.2da~ ~override~
//Smite Foe
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104.spl~ ~override~
        SAY NAME1 @80404
        SAY NAME2 @80404
        SAY UNIDENTIFIED_DESC @80405
	SAY DESC @80405
//effect
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104a.eff~ ~override~
//sec spell
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104a.spl~ ~override~
//3rd spell
COPY ~faiths_and_powers/kits/champions/804_bane/b_ch104b.spl~ ~override~

//protection from fear  (using the tempus spl.  It's basically the same...)
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_BAN01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~25818~ END     //text block
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_BAN01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~17427~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~14007~ END     //text block
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_BAN01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~35484~ END     //text block
END

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
	COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
		INSERT_2DA_ROW 3 0 ~B_CHAMP_BANE 0~
	BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch04~
	class 			= ~champion~
	s_Life 			= ~x~
	s_Death 		= ~paladin~
	s_Benediction 	        = ~x~
	s_Destruction 	        = ~paladin~
	s_Protection 	        = ~x~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	        = ~paladin~
	s_Deception 	        = ~x~
	s_Thought 		= ~paladin~
	s_Dread 		= ~paladin~
	s_Vigor 		= ~x~
	s_Affliction 	        = ~paladin~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~paladin~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF HELM
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_helm BEGIN

ADD_KIT ~B_CHAMP_HELM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_HELM           2 2 2 2 2 2 2 2~
~B_CHAMP_HELM           2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_HELM        1  1  0  0  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_HELM        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/805_helm/b_ch05.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80501 //lower
SAY @80502 //Mixed
SAY @80503 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80503)
		STR_VAR
			kit_name = B_CHAMP_HELM
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/805_helm/b_ch05.2da~ ~override~

//save bonuses
COPY ~faiths_and_powers/kits/champions/805_helm/B_HAB03.spl~ ~override~
//Everwatch Sword
COPY_EXISTING ~spcl731.spl~ ~override/B_hel01.spl~ // sword spl
   SAY NAME1 @80504
   SAY NAME2 @80504
   SAY UNIDENTIFIED_DESC @80505
   SAY DESC @80505
   LPF ALTER_EFFECT INT_VAR match_opcode = 111 STR_VAR resource = EVAL ~B_hel01~ END
COPY ~faiths_and_powers/kits/champions/805_helm/B_hel01.itm~ ~override~
   SAY NAME1 @80504
   SAY NAME2 @80504
   SAY UNIDENTIFIED_DESC @80505
   SAY DESC @80505

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_CHAMP_HELM 0~
  BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch05~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~x~
	s_Benediction 	= ~paladin~
	s_Destruction 	= ~x~
	s_Protection 	= ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~paladin~
	s_Knowledge 	= ~paladin~
	s_Deception 	= ~x~
	s_Thought 		= ~paladin~
	s_Dread 		= ~x~
	s_Vigor 		= ~paladin~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________

DEFINE_ACTION_MACRO iwdee_champion_helm BEGIN

ADD_KIT ~B_CHAMP_HELM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_HELM           2 2 2 2 2 2 2 2~
~B_CHAMP_HELM           2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_HELM  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_HELM        1  1  0  0  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_HELM        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/805_helm/b_ch05.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80501 //lower
SAY @80502 //Mixed
SAY @80506 //Help  Falls

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80506)
		STR_VAR
			kit_name = B_CHAMP_HELM
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/805_helm/b_ch05.2da~ ~override~

//save bonuses
COPY ~faiths_and_powers/kits/champions/805_helm/B_HAB03.spl~ ~override~
//Everwatch Sword
COPY_EXISTING ~spcl731.spl~ ~override/B_hel01.spl~ // sword spl
   SAY NAME1 @80504
   SAY NAME2 @80504
   SAY UNIDENTIFIED_DESC @80505
   SAY DESC @80505
   LPF ALTER_EFFECT INT_VAR match_opcode = 111 STR_VAR resource = EVAL ~B_hel01~ END
COPY ~faiths_and_powers/kits/champions/805_helm/B_hel01.itm~ ~override~
   SAY NAME1 @80504
   SAY NAME2 @80504
   SAY UNIDENTIFIED_DESC @80505
   SAY DESC @80505

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_CHAMP_HELM 0~
  BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch05~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~x~
	s_Benediction 	        = ~paladin~
	s_Destruction 	        = ~x~
	s_Protection 	        = ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~paladin~
	s_Knowledge 	        = ~paladin~
	s_Deception 	        = ~x~
	s_Thought 		= ~paladin~
	s_Dread 		= ~x~
	s_Vigor 		= ~paladin~
	s_Affliction 	        = ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF TALOS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_talos BEGIN

ADD_KIT ~B_CHAMP_TALOS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_TALOS          2 2 2 2 2 2 2 2~
~B_CHAMP_TALOS          2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_TALOS       0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_TALOS        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/806_talos/b_ch06.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80601 //lower
SAY @80602 //Mixed
SAY @80603 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80603)
		STR_VAR
			kit_name = B_CHAMP_TALOS
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch06.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal01.spl~     ~override~  //  Electricity resist

//Smite Foe
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch106.spl~ ~override~
        SAY NAME1 @80604
        SAY NAME2 @80604
        SAY UNIDENTIFIED_DESC @80605
	SAY DESC @80605
//effect
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch106a.eff~ ~override~
//sec spell
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch106a.spl~ ~override~

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_CHAMP_TALOS 0~
  BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch06~
	class 			= ~champion~
	s_Life 			= ~x~
	s_Death 		= ~paladin~
	s_Benediction 	        = ~x~
	s_Destruction 	        = ~paladin~
	s_Protection 	        = ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~paladin~
	s_Knowledge 	        = ~x~
	s_Deception 	        = ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~paladin~
	s_Vigor 		= ~x~
	s_Affliction 	        = ~paladin~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~paladin~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________

DEFINE_ACTION_MACRO iwdee_champion_talos BEGIN

ADD_KIT ~B_CHAMP_TALOS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_TALOS          2 2 2 2 2 2 2 2~
~B_CHAMP_TALOS          2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_TALOS       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_TALOS       0  0  1  0  0  1  0  0  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_TALOS        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/806_talos/b_ch06.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000021 6~  //blackguard usability

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80601 //lower
SAY @80602 //Mixed
SAY @80606 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80606)
		STR_VAR
			kit_name = B_CHAMP_TALOS
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch06.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal01.spl~     ~override~  //  Electricity resist

//Smite Foe
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch106.spl~ ~override~
        SAY NAME1 @80604
        SAY NAME2 @80604
        SAY UNIDENTIFIED_DESC @80605
	SAY DESC @80605
//effect
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch106a.eff~ ~override~
//sec spell
COPY ~faiths_and_powers/kits/champions/806_talos/b_ch106a.spl~ ~override~

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_CHAMP_TALOS 0~
  BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch06~
	class 			= ~champion~
	s_Life 			= ~x~
	s_Death 		= ~paladin~
	s_Benediction 	        = ~x~
	s_Destruction 	        = ~paladin~
	s_Protection 	        = ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~paladin~
	s_Knowledge 	        = ~x~
	s_Deception 	        = ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~paladin~
	s_Vigor 		= ~x~
	s_Affliction 	        = ~paladin~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~paladin~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF MORADIN
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_moradin BEGIN

ADD_KIT ~B_CHAMP_MOR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_MOR            2 2 2 2 2 2 2 2~
~B_CHAMP_MOR            2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_MOR        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_MOR        1  1  0  0  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_MOR        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/807_Moradin/b_ch07.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_D~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80701 //lower
SAY @80702 //Mixed
SAY @80703 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80703)
		STR_VAR
			kit_name = B_CHAMP_MOR
			clsrcreq = ~0 0 0 1 0 0 0~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_ch07.2da~ ~override~
//+2ac/save vs magic
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_mor01.spl~ ~override~
//hammer
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_mor02.spl~ ~override~
        SAY NAME1 @80704
        SAY NAME2 @80704
        SAY UNIDENTIFIED_DESC @80705
	SAY DESC @80705
   LPF ALTER_EFFECT INT_VAR match_opcode = 111 STR_VAR resource = EVAL ~B_mor02~ END
//actual hammer
COPY ~faiths_and_powers/kits/champions/807_Moradin/b_mor02.itm~ ~override~
        SAY NAME1 @80704
        SAY NAME2 @80704
        SAY UNIDENTIFIED_DESC @80705
	SAY DESC @80705
//COPY ~faiths_and_powers/kits/champions/807_Moradin/b_ch101a.spl~ ~override~
//3rd spell
//COPY ~faiths_and_powers/kits/champions/807_Moradin/b_ch101b.spl~ ~override~

//protection from evil
//COPY ~faiths_and_powers/kits/champions/807_Moradin/b_tyr01.spl~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 0
	u_bows 				= 0
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch07~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~x~
	s_Benediction 	        = ~paladin~
	s_Destruction 	        = ~x~
	s_Protection 	        = ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	        = ~x~
	s_Deception 	        = ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~paladin~
	s_Affliction 	        = ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~paladin~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~paladin~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF AZUTH
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_azuth BEGIN

ADD_KIT ~B_CHAMP_AZUTH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_AZUTH            2 2 2 2 2 2 2 2~
~B_CHAMP_AZUTH            2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_AZUTH        13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_AZUTH        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_AZUTH        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_AZUTH        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_AZUTH       1  1  0  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_AZUTH        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/808_Azuth/b_ch08.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80801 //lower
SAY @80802 //Mixed
SAY @80803 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80803)
		STR_VAR
			kit_name = B_CHAMP_AZUTH
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/808_Azuth/b_ch08.2da~ ~override~
//Smite
COPY ~faiths_and_powers/kits/champions/808_Azuth/b_ch108.spl~ ~override~
        SAY NAME1 @80804
        SAY NAME2 @80804
        SAY UNIDENTIFIED_DESC @80805
	SAY DESC @80805
COPY ~faiths_and_powers/kits/champions/808_Azuth/b_ch108a.eff~ ~override~
COPY ~faiths_and_powers/kits/champions/808_Azuth/b_ch108a.spl~ ~override~
//sec eff
COPY ~faiths_and_powers/kits/champions/808_Azuth/b_ch108b.eff~ ~override~
//sec spl
COPY ~faiths_and_powers/kits/champions/808_Azuth/b_ch108b.spl~ ~override~

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_paladins.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_D_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_P_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 5) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch08~
	class 			= ~champion~
	s_Life 			= ~x~
	s_Death 		= ~x~
	s_Benediction 	        = ~paladin~
	s_Destruction 	        = ~x~
	s_Protection 	        = ~paladin~
	s_War 			= ~x~
	s_Exploration   = ~x~
	s_Knowledge 	        = ~paladin~
	s_Deception 	        = ~x~
	s_Thought 		= ~paladin~
	s_Dread 		= ~x~
	s_Vigor 		= ~x~
	s_Affliction 	        = ~paladin~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~paladin~
	s_Fire 			= ~paladin~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~paladin~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CHAMPION OF THE RED KNIGHT
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO champion_red BEGIN

ADD_KIT ~B_CHAMP_RED~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CHAMP_RED            2 2 2 2 2 2 2 2~
~B_CHAMP_RED            2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_RED  13   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_RED  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_RED  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CHAMP_RED  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CHAMP_RED        1  1  1  1  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CHAMP_RED        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/champions/809_red/b_ch09.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_P_E K_P_H K_P_HE K_P_G K_P_D K_P_HL K_P_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 6~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @80901 //lower
SAY @80902 //Mixed
SAY @80903 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@80903)
		STR_VAR
			kit_name = B_CHAMP_RED
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END

//ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/champions/809_red/b_ch09.2da~ ~override~

//save bonuses
COPY ~faiths_and_powers/kits/champions/809_red/b_red01.spl~ ~override~

//Knight's Move    b_ch109
COPY ~faiths_and_powers/kits/champions/809_red/b_ch109.spl~ ~override~
        SAY NAME1 @80904
        SAY NAME2 @80904
        SAY UNIDENTIFIED_DESC @80905
	SAY DESC @80905
//effect
COPY ~faiths_and_powers/kits/champions/809_red/b_ch109a.eff~ ~override~
//sec spell
COPY ~faiths_and_powers/kits/champions/809_red/b_ch109a.spl~ ~override~
//3rd spell
COPY ~faiths_and_powers/kits/champions/809_red/b_ch109b.spl~ ~override~

//nO FALL
ACTION_IF FILE_EXISTS_IN_GAME ~fallen.2da~ BEGIN
  COPY_EXISTING ~fallen.2da~ ~override~ //Remove possibility to fall
	              INSERT_2DA_ROW 3 0 ~B_CHAMP_RED 0~
  BUT_ONLY_IF_IT_CHANGES
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 2
	u_hammers	 		= 1
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 0
	u_daggers 			= 0
	u_short_swords		= 0
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 2
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 2
	u_bows 				= 2
	u_crossbows 		= 2
  STR_VAR
    clab_name = EVAL ~b_ch09~
	class 			= ~champion~
	s_Life 			= ~paladin~
	s_Death 		= ~x~
	s_Benediction 	        = ~paladin~
	s_Destruction 	        = ~x~
	s_Protection 	        = ~paladin~
	s_War 			= ~paladin~
	s_Exploration   = ~x~
	s_Knowledge 	        = ~paladin~
	s_Deception 	        = ~x~
	s_Thought 		= ~paladin~
	s_Dread 		= ~x~
	s_Vigor 		= ~paladin~
	s_Affliction 	        = ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________

