
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							FOREST DRUID
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO forest_druid BEGIN

ADD_KIT ~D5_DR_FOR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_DR_FOR       0 0 0 1 1 1 0 1~
~D5_DR_FOR       0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_FOR           0   0   0   0   12  7~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_FOR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_FOR           0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_FOR           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_DR_FOR           0  1  0  1  1  1  0  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_DR_FOR           1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/druids/731_forest_druid/d5dfor.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x08000000 11~ // totemic flag

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @73101
SAY @73102
SAY @73103

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@73104)
		STR_VAR
			kit_name = D5_DR_FOR
			clswpbon = ~0 0 3~
	END
END

//FOREST DRUID ABILITY FILES__________________________________________________________
//
COPY ~faiths_and_powers/kits/druids/731_forest_druid/d5dfor.2da~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drsc.spl~ ~override~
	SAY NAME1 @73111
	SAY UNIDENTIFIED_DESC @73112
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drinv.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drnf.spl~ ~override~
	SAY NAME1 @73113
	SAY UNIDENTIFIED_DESC @73114
COPY ~faiths_and_powers/kits/druids/shapechange/d5drwlf.spl~ ~override~
	SAY NAME1 @73115
	SAY UNIDENTIFIED_DESC @73116
COPY ~faiths_and_powers/kits/druids/shapechange/d5_wolf.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_wolfd.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clwlf.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drfer.spl~ ~override~
	SAY NAME1 @73117
	SAY UNIDENTIFIED_DESC @73118
COPY ~faiths_and_powers/kits/druids/shapechange/d5_feret.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clrat.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drbbl.spl~ ~override~
	SAY NAME1 @73119
	SAY UNIDENTIFIED_DESC @73120
COPY ~faiths_and_powers/kits/druids/shapechange/d5_berbl.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clber.itm~ ~override~

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_druids.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_D_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_D_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 0) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 0
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 0
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 1
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~d5dfor~
	class 			= ~druid~
	s_Life 			= ~minor~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Exploration   = ~minor~
	s_Knowledge 	= ~major~
	s_Deception 	= ~minor~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~major~
	s_Affliction 	= ~major~
	s_Animal 		= ~major~
	s_Plant 		= ~major~
	s_Earth 		= ~major~
	s_Water 		= ~major~
	s_Air 			= ~minor~
	s_Fire 			= ~x~
	s_Light 		= ~major~
	s_Shadow 		= ~minor~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							MOUNTAIN DRUID
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO mountain_druid BEGIN

ADD_KIT ~D5_DR_MOU~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_DR_MOU       0 0 0 1 1 1 0 1~
~D5_DR_MOU       0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_MOU           0   0   0   0   12  7~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_MOU           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_MOU           0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_MOU           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_DR_MOU           0  1  0  1  1  1  0  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_DR_MOU           1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/druids/732_mountain_druid/d5dmtn.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x08000000 11~ // totemic flag

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @73201
SAY @73202
SAY @73203

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@73204)
		STR_VAR
			kit_name = D5_DR_MOU
			clswpbon = ~0 0 3~
	END
END

//MOUNTAIN DRUID ABILITY FILES_______________________________________________________
//
COPY ~faiths_and_powers/kits/druids/732_mountain_druid/d5dmtn.2da~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drsc.spl~ ~override~
	SAY NAME1 @73111
	SAY UNIDENTIFIED_DESC @73112
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drinv.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drnf.spl~ ~override~
	SAY NAME1 @73113
	SAY UNIDENTIFIED_DESC @73114
COPY ~faiths_and_powers/kits/druids/shapechange/d5drlep.spl~ ~override~
	SAY NAME1 @73211
	SAY UNIDENTIFIED_DESC @73212
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drlep.bam~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_leprd.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clcat.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drrat.spl~ ~override~
	SAY NAME1 @73213
	SAY UNIDENTIFIED_DESC @73214
COPY ~faiths_and_powers/kits/druids/shapechange/d5_ratdr.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_ratdr.eff~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clrat.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drbbr.spl~ ~override~
	SAY NAME1 @73215
	SAY UNIDENTIFIED_DESC @73216
COPY ~faiths_and_powers/kits/druids/shapechange/d5_berbr.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clber.itm~ ~override~


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 0
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 0
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 1
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~d5dmtn~
	class 			= ~druid~
	s_Life 			= ~minor~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Exploration   = ~major~
	s_Knowledge 	= ~major~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~major~
	s_Affliction 	= ~minor~
	s_Animal 		= ~major~
	s_Plant 		= ~minor~
	s_Earth 		= ~major~
	s_Water 		= ~minor~
	s_Air 			= ~major~
	s_Fire 			= ~minor~
	s_Light 		= ~major~
	s_Shadow 		= ~minor~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							JUNGLE DRUID
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO jungle_druid BEGIN

ADD_KIT ~D5_DR_JUN~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_DR_JUN       0 0 0 1 1 1 0 1~
~D5_DR_JUN       0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_JUN           0   0   0   0   12  7~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_JUN           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_JUN           0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_JUN           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_DR_JUN           0  1  0  1  1  1  0  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_DR_JUN           1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/druids/733_jungle_druid/d5djun.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x08000000 11~ // totemic flag

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @73301
SAY @73302
SAY @73303

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@73304)
		STR_VAR
			kit_name = D5_DR_JUN
			clswpbon = ~0 0 3~
	END
END

//JUNGLE DRUID ABILITY FILES_________________________________________________________
//
COPY ~faiths_and_powers/kits/druids/733_jungle_druid/d5djun.2da~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drsc.spl~ ~override~
	SAY NAME1 @73111
	SAY UNIDENTIFIED_DESC @73112
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drinv.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drnf.spl~ ~override~
	SAY NAME1 @73113
	SAY UNIDENTIFIED_DESC @73114
COPY ~faiths_and_powers/kits/druids/shapechange/d5drpan.spl~ ~override~
	SAY NAME1 @73311
	SAY UNIDENTIFIED_DESC @73312
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drlep.bam~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_panth.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clcat.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drsp1.spl~ ~override~
	SAY NAME1 @73313
	SAY UNIDENTIFIED_DESC @73314
COPY ~faiths_and_powers/kits/druids/shapechange/d5_spid1.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clspi.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drwyv.spl~ ~override~
	SAY NAME1 @73315
	SAY UNIDENTIFIED_DESC @73316
COPY ~faiths_and_powers/kits/druids/shapechange/d5_wyvrn.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clwyv.itm~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 0
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 0
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 1
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~d5djun~
	class 			= ~druid~
	s_Life 			= ~minor~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Exploration   = ~minor~
	s_Knowledge 	= ~major~
	s_Deception 	= ~major~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~major~
	s_Affliction 	= ~major~
	s_Animal 		= ~major~
	s_Plant 		= ~focus~
	s_Earth 		= ~minor~
	s_Water 		= ~minor~
	s_Air 			= ~minor~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~minor~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

/*
//FALDORN___________________________________________________________________________
//
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS 8 "rows"
	FOR ( index = 31 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY "%index%" 5 8 "clab"
		PATCH_IF ("%clab%" STRING_EQUAL_CASE "d5djun" = 1) BEGIN
			SET "d5djun" = "%index%"-1
			SET "rows" = 0
		END
	END
BUT_ONLY
ACTION_FOR_EACH char IN ~faldor~ ~faldor5~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~%char%.cre~ ~override~
		WRITE_SHORT 0x244 0
		WRITE_SHORT 0x246 0x4000 + ~%d5djun%~ // changes kit
  END
END
*/

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							DESERT DRUID
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO desert_druid BEGIN

ADD_KIT ~D5_DR_DES~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_DR_DES       0 0 0 1 1 1 0 1~
~D5_DR_DES       0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_DES           0   0   0   0   12  7~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_DES           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_DES           0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_DES           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_DR_DES           0  1  0  1  1  1  0  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_DR_DES           1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/druids/734_desert_druid/d5ddes.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x08000000 11~ // totemic flag

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @73401
SAY @73402
SAY @73403

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@73404)
		STR_VAR
			kit_name = D5_DR_DES
			clswpbon = ~0 0 3~
	END
END

//DESERT DRUID ABILITY FILES_______________________________________________________
//
COPY ~faiths_and_powers/kits/druids/734_desert_druid/d5ddes.2da~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drsc.spl~ ~override~
	SAY NAME1 @73111
	SAY UNIDENTIFIED_DESC @73112
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drinv.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drnf.spl~ ~override~
	SAY NAME1 @73113
	SAY UNIDENTIFIED_DESC @73114
COPY ~faiths_and_powers/kits/druids/shapechange/d5drlep.spl~ ~override~
	SAY NAME1 @73411
	SAY UNIDENTIFIED_DESC @73412
COPY ~faiths_and_powers/kits/druids/shapechange/d5_leprd.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clcat.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drrab.spl~ ~override~
	SAY NAME1 @73413
	SAY UNIDENTIFIED_DESC @73414
COPY ~faiths_and_powers/kits/druids/shapechange/d5_hare.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clrat.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drbas.spl~ ~override~
	SAY NAME1 @73415
	SAY UNIDENTIFIED_DESC @73416
COPY ~faiths_and_powers/kits/druids/shapechange/d5_basil.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clber.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_basg.spl~ ~override~


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 0
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 0
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 1
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~d5ddes~
	class 			= ~druid~
	s_Life 			= ~minor~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Exploration   = ~major~
	s_Knowledge 	= ~major~
	s_Deception 	= ~minor~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~major~
	s_Affliction 	= ~minor~
	s_Animal 		= ~major~
	s_Plant 		= ~minor~
	s_Earth 		= ~minor~
	s_Water 		= ~x~
	s_Air 			= ~major~
	s_Fire 			= ~major~
	s_Light 		= ~major~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ARCTIC DRUID
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO arctic_druid BEGIN

ADD_KIT ~D5_DR_ARC~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_DR_ARC       0 0 0 1 1 1 0 1~
~D5_DR_ARC       0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_ARC           0   0   0   0   12  7~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_ARC           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_ARC           0   0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_DR_ARC           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_DR_ARC           0  1  0  1  1  1  0  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_DR_ARC           1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/druids/735_arctic_druid/d5darc.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_H    K_D_D   K_D_G   K_D_E   K_D_HE   K_D_HL   K_D_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x08000000 11~ // totemic flag

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Dr0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @73501
SAY @73502
SAY @73503

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@73504)
		STR_VAR
			kit_name = D5_DR_ARC
			clswpbon = ~0 0 3~
	END
END

//ARCTIC DRUID ABILITY FILES_______________________________________________________
//
COPY ~faiths_and_powers/kits/druids/735_arctic_druid/d5darc.2da~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drsc.spl~ ~override~
	SAY NAME1 @73111
	SAY UNIDENTIFIED_DESC @73112
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drinv.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/druids/shapechange/d5_drnf.spl~ ~override~
	SAY NAME1 @73113
	SAY UNIDENTIFIED_DESC @73114
COPY ~faiths_and_powers/kits/druids/shapechange/d5drwnt.spl~ ~override~
	SAY NAME1 @73511
	SAY UNIDENTIFIED_DESC @73512
COPY ~faiths_and_powers/kits/druids/shapechange/d5_wolfw.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clwlf.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_wlfw.spl~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drrab.spl~ ~override~
	SAY NAME1 @73513
	SAY UNIDENTIFIED_DESC @73514
COPY ~faiths_and_powers/kits/druids/shapechange/d5_hare.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clrat.itm~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5drbpo.spl~ ~override~
	SAY NAME1 @73515
	SAY UNIDENTIFIED_DESC @73516
COPY ~faiths_and_powers/kits/druids/shapechange/d5_berpo.cre~ ~override~
COPY ~faiths_and_powers/kits/druids/shapechange/d5_clber.itm~ ~override~


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 0
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 0
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 1
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~d5darc~
	class 			= ~druid~
	s_Life 			= ~minor~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Exploration   = ~major~
	s_Knowledge 	= ~major~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~major~
	s_Affliction 	= ~minor~
	s_Animal 		= ~major~
	s_Plant 		= ~minor~
	s_Earth 		= ~minor~
	s_Water 		= ~major~
	s_Air 			= ~major~
	s_Fire 			= ~x~
	s_Light 		= ~major~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~x~
 END

END
//__________________________________________________________________________________


