
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF ILMATER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_ilmater BEGIN

ADD_KIT ~B_PRIEST_ILMATER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_ILMATER  	0 0 0 0 1 1 0 1~
~B_PRIEST_ILMATER       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_ILMATER  1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_ILMATER  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/314_ilmater/b_ailm.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31401
SAY @31402
SAY @31403

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31403)
		STR_VAR
			kit_name = B_PRIEST_ILMATER
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//ILMATER ABILITY FILES_______________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/314_ilmater/b_ailm.2da~ ~override~
COPY ~faiths_and_powers/kits/acolytes/314_ilmater/b_ilm01.spl~ ~override~  // Remove Fear
	SAY NAME1 @31411
	SAY NAME2 @31411
	SAY UNIDENTIFIED_DESC @31412  //
	SAY IDENTIFIED_DESC @31412  //
COPY ~faiths_and_powers/kits/acolytes/314_ilmater/b_ilm02.spl~ ~override~  // +4 vs death
COPY ~faiths_and_powers/kits/acolytes/314_ilmater/b_ilm06.spl~ ~override~  // fire/cold resist
COPY ~faiths_and_powers/kits/acolytes/314_ilmater/b_ilm03.spl~ ~override~  // Endurance of Ilmater
	SAY NAME1 @31413
	SAY NAME2 @31413
	SAY UNIDENTIFIED_DESC @31414  //
	SAY IDENTIFIED_DESC @31414  //

//COPY_EXISTING ~spwi102.spl~ ~override/b_ilm04.spl~          // Armor
//	WRITE_SHORT 0x1c 2
//COPY_EXISTING ~spwi317.spl~ ~override/b_ilm05.spl~          // Ghost Armor
//	WRITE_SHORT 0x1c 2

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_ailm~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~minor~
	s_Benediction 	= ~major~
	s_Destruction 	= ~minor~
	s_Protection 	= ~focus~
	s_War 			= ~minor~
	s_Knowledge 	= ~major~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~minor~
	s_Vigor 		= ~major~
	s_Affliction 	= ~major~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~major~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF DENEIR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_deneir BEGIN

ADD_KIT ~B_PRIEST_DENEIR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_DENEIR  	0 0 0 0 1 1 0 1~
~B_PRIEST_DENEIR       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_DENEIR  1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_DENEIR  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/315_deneir/b_aden.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31501
SAY @31502
SAY @31503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31503)
		STR_VAR
			kit_name = B_PRIEST_DENEIR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

// ABILITY FILES_______________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/315_deneir/b_aden.2da~ ~override~
COPY ~faiths_and_powers/kits/acolytes/315_deneir/b_den01.spl~ ~override~  //immunities

COPY_EXISTING ~SPPR205.spl~ ~override/b_den02.spl~ // detect traps
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x84 1//Casting time
  WRITE_BYTE 0x74 4//Location

COPY_EXISTING ~SPPR304.spl~ ~override/b_den03.spl~ // glyph of warding
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
 LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

COPY_EXISTING ~SPPR303.spl~ ~override/b_den04.spl~ // dispel magic
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
 LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_aden~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~x~
	s_Protection 	= ~major~
	s_War 			= ~minor~
	s_Knowledge 	= ~focus~
	s_Deception 	= ~minor~
	s_Thought 		= ~major~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~minor~
	s_Plant 		= ~minor~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~major~
	s_Shadow 		= ~x~
	s_Magic 		= ~major~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF SUNE
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_sune BEGIN

ADD_KIT ~B_PRIEST_SUNE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_SUNE  	0 0 0 0 1 1 0 1~
~B_PRIEST_SUNE       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  0   0   0   0   12  15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_SUNE     0  0  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_SUNE  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/316_sune/b_asun.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_HL~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31601
SAY @31602
SAY @31603

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31603)
		STR_VAR
			kit_name = B_PRIEST_SUNE
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//SUNE ABILITY FILES__________________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/316_sune/b_asun.2da~ ~override~
COPY ~faiths_and_powers/kits/acolytes/316_sune/b_sun01.spl~ ~override~  // potent charm
//	SAY NAME1 @31411
//	SAY NAME2 @31411
	SAY UNIDENTIFIED_DESC @31606 //
	SAY IDENTIFIED_DESC @31606  //
COPY ~faiths_and_powers/kits/acolytes/316_sune/b_sun02.spl~ ~override~  // spell save
//Make not dependant on iWDEE...
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
COPY_EXISTING ~SPWI429.spl~ ~override/b_sun03.spl~ // Emotion: hope
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321
      STR_VAR resource = EVAL ~b_sun03~
     END
END

COPY ~faiths_and_powers/kits/acolytes/316_sune/b_sun04.spl~ ~override~  // cha bonus

/*
COPY_EXISTING ~SPWI104.spl~ ~override/b_sun01.spl~ // Charm person
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~b_sun01~
     END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 5
      savebonus = 0
     END
*/

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_asun~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~x~
	s_Protection 	= ~major~
	s_War 			= ~x~
	s_Knowledge 	= ~major~
	s_Deception 	= ~major~
	s_Thought 		= ~focus~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~major~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~minor~
	s_Shadow 		= ~minor~
	s_Magic 		= ~minor~
END

//CLERIC/THIEF________________________________________________________________________

ADD_KIT ~B_CT_SUNE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                        T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CT_SUNE  		0 0 0 0 1 1 0 1~
~B_CT_SUNE       	1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_SUNE   	   0   0   0   0   12  15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_SUNE   	   0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_SUNE   	   0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CT_SUNE   	   0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_CT_SUNE   	   0  0  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_CT_SUNE   	   0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/316_sune/b_2sun.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CT_E  K_CT_H  K_CT_HE  K_CT_G  K_CT_D  K_CT_HL  K_CT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31601
SAY @31602
SAY @31603

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31603)
		STR_VAR
			kit_name = B_CT_SUNE
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

COPY ~faiths_and_powers/kits/acolytes/316_sune/b_asun.2da~ ~override/b_2sun.2a~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2sun.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CT_SUNE~ 
		kit_clab = ~b_2sun~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_thief 	= 1
  STR_VAR
    clab_name 		= ~b_2sun~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~x~
	s_Protection 	= ~major~
	s_War 			= ~x~
	s_Knowledge 	= ~major~
	s_Deception 	= ~major~
	s_Thought 		= ~focus~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~major~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~minor~
	s_Shadow 		= ~minor~
	s_Magic 		= ~minor~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF TEMPUS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_tempus BEGIN

ADD_KIT ~B_PRIEST_TEMPUS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_TEMPUS  	0 0 0 0 1 1 0 1~
~B_PRIEST_TEMPUS        1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_TEMPUS   1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_TEMPUS   1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/322_tempus/b_atem.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @32201
SAY @32202
SAY @32203

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@32203)
		STR_VAR
			kit_name = B_PRIEST_TEMPUS
			clswpbon = ~0 0 3~
	END
END

//TEMPUS ABILITY FILES_______________________________________________________________
//
COPY_EXISTING ~SPPR203.spl~ ~override/B_TEM01.spl~ // Chant
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x84 1//Casting time
  WRITE_BYTE 0x74 4//Location
  SAY UNIDENTIFIED_DESC @32206     //Should figure out how to edit the spell level for compatibility purposes


COPY ~faiths_and_powers/kits/acolytes/322_tempus/b_tem02.spl~ ~override~  // WP Axe

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_atem~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~minor~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~focus~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~minor~
	s_Vigor 		= ~major~
	s_Affliction 	= ~major~
	s_Animal 		= ~minor~
	s_Plant 		= ~x~
	s_Earth 		= ~minor~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~minor~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						ACOLYTE OF MYSTRA
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_mystra BEGIN

ADD_KIT ~D5_AC_MYS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_MYS     0 1 0 0 1 0 0 1~
~D5_AC_MYS     0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   13  13  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_MYS          1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_MYS          0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/325_mystra/d5acmys.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_E  K_C_E  K_C_G  K_C_H  K_C_HE  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x02000000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @32501
SAY @32502
SAY @32503

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@32503)
		STR_VAR
			kit_name = D5_AC_MYS
			clswpbon = ~0 0 3~
	END
END

//MYSTRA ABILITY FILES___________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/325_mystra/d5acmys.2da~ ~override~
COPY ~faiths_and_powers/kits/misc/d5_cllv1.spl~ ~override~
//	SAY NAME1 @6
//	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm1.spl~ ~override~
	SAY NAME1 @46605
	SAY UNIDENTIFIED_DESC @46606
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm1.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc1b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc1c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm2.spl~ ~override~
	SAY NAME1 @46607
	SAY UNIDENTIFIED_DESC @46608
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm2.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc2b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc2c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm3.spl~ ~override~
	SAY NAME1 @46609
	SAY UNIDENTIFIED_DESC @46610
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm3.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc3b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc3c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm4.spl~ ~override~
	SAY NAME1 @46611
	SAY UNIDENTIFIED_DESC @46612
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm4.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc4b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc4c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm5.spl~ ~override~
	SAY NAME1 @46613
	SAY UNIDENTIFIED_DESC @46614
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm5.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc5b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc5c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm6.spl~ ~override~
	SAY NAME1 @46615
	SAY UNIDENTIFIED_DESC @46616
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm6.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc6b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc6c.bam~ ~override~
//Huge thanks to DreamSlaveOne at forums.gibberlings3.net for providing the .BAMs for these abilities!
/*
ACTION_IF FILE_EXISTS_IN_GAME ~d5_wiz.d5~ THEN BEGIN
	COPY_EXISTING ~d5_inmys.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~faiths_and_powers/kits/acolytes/325_mystra/mystracant.txt~
END
*/

//DEFINE SPHERE ACCESS______________________________________________________________
//
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~d5acmys~
	race 			= ~human~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~x~
	s_Knowledge 	= ~major~
	s_Deception 	= ~minor~
	s_Thought 		= ~minor~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~minor~
	s_Light 		= ~major~
	s_Shadow 		= ~minor~
	s_Magic 		= ~major~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						ACOLYTE OF MASK
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_mask BEGIN

ADD_KIT ~D5_AC_MASK~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_MASK      0 1 0 0 1 0 0 1~
~D5_AC_MASK      0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MASK        0   12  0   0   10  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MASK        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MASK        0   15  0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MASK        0   15  0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_MASK        0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_MASK        0  0  0  1  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~faiths_and_powers/kits/acolytes/329_mask/d5amas.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @32901
SAY @32902
SAY @32903

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@32904)
		STR_VAR
			kit_name = D5_AC_MASK
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//NIGHTRUNNER ABILITY FILES__________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/329_mask/d5amas.2da~ ~override~
COPY ~faiths_and_powers/kits/acolytes/329_mask/d5his20.spl~ ~override~
COPY ~faiths_and_powers/kits/acolytes/329_mask/d5mask1.spl~ ~override~
	SAY NAME1 @32911
	SAY UNIDENTIFIED_DESC @32912
COPY ~faiths_and_powers/kits/acolytes/329_mask/d5mask2.spl~ ~override~
	SAY NAME1 @32913
	SAY UNIDENTIFIED_DESC @32914
COPY ~faiths_and_powers/kits/acolytes/329_mask/d5mask3.spl~ ~override~
	SAY NAME1 @32915
	SAY UNIDENTIFIED_DESC @32916
COPY ~faiths_and_powers/kits/acolytes/329_mask/d5_mask3.eff~ ~override~
COPY ~faiths_and_powers/kits/acolytes/329_mask/d5_mask3.cre~ ~override~
	SAY NAME1 @32917
//Nightrunner's Summon Shadow ability generously provided by Demivrgvs of Item/Spell/Kit Revisions fame. Big thanks!

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~d5amas~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~minor~
	s_Benediction 	= ~major~
	s_Destruction 	= ~minor~
	s_Protection 	= ~minor~
	s_War 			= ~x~
	s_Knowledge 	= ~major~
	s_Deception 	= ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~focus~
	s_Magic 		= ~minor~
 END

//CLERIC/THIEF______________________________________________________________________

ADD_KIT ~D5_CT_MASK~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CT_MASK     0 1 0 0 1 0 0 1~
~D5_CT_MASK     0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_MASK        0   12  0   0   10  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_MASK        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_MASK        0   15  0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CT_MASK        0   15  0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CT_MASK        0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CT_MASK        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~faiths_and_powers/kits/acolytes/329_mask/d52mas.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~K_CT_E  K_CT_H  K_CT_HE  K_CT_G   K_CT_D  K_CT_HL  K_CT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @32901
SAY @32902
SAY @32903

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@32904)
		STR_VAR
			kit_name = D5_CT_MASK
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

COPY ~faiths_and_powers/kits/acolytes/329_mask/d5amas.2da~ ~override/d52mas.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d52mas.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_CT_MASK~ 
		kit_clab = ~d52mas~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_thief 	= 1
  STR_VAR
    clab_name 		= ~d52mas~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~minor~
	s_Benediction 	= ~major~
	s_Destruction 	= ~minor~
	s_Protection 	= ~minor~
	s_War 			= ~x~
	s_Knowledge 	= ~major~
	s_Deception 	= ~focus~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~major~
	s_Magic 		= ~minor~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF SHAR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_shar BEGIN

ADD_KIT ~D5_AC_SHAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_SHAR      0 0 0 0 1 1 0 1~
~D5_AC_SHAR      0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_SHAR        0  1  1  0  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_SHAR        0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/330_shar/d5asha.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33001
SAY @33002
SAY @33003

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33004)
		STR_VAR
			kit_name = D5_AC_SHAR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//DARKCLOAK ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/330_shar/d5asha.2da~ ~override~
COPY_EXISTING ~spwi220.spl~ ~override/d5shasl.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi201.spl~ ~override/d5shabr.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi518.spl~ ~override/d5shaph.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi815.spl~ ~override/d5shabl.spl~
	LPM spell_to_innate

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~d5asha~
	race 			= ~all~
	s_Life 			= ~minor~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~major~
	s_Protection 	= ~minor~
	s_War 			= ~x~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	 = ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~focus~
	s_Magic 		= ~major~
 END

//____________________________CLERIC/MAGE_____________________________________________

ADD_KIT ~D5_CM_SHAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CM_SHAR      0 0 0 0 1 1 0 1~
~D5_CM_SHAR      0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_SHAR        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CM_SHAR        0  1  1  0  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CM_SHAR        0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/330_shar/d52sha.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CM_E  K_CM_H  K_CM_HE  K_CM_G  K_CM_D  K_CM_HL  K_CM_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 14~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33001
SAY @33002
SAY @33003

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33004)
		STR_VAR
			kit_name = D5_CM_SHAR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

COPY ~faiths_and_powers/kits/acolytes/330_shar/d5asha.2da~ ~override/d52sha.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d52sha.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_CM_SHAR~ 
		kit_clab = ~d52sha~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_mage	= 1
  STR_VAR
    clab_name 		= ~d52sha~
	race 			= ~all~
	s_Life 			= ~minor~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~major~
	s_Protection 	= ~minor~
	s_War 			= ~x~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~focus~
	s_Magic 		= ~major~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF MOANDER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_moander BEGIN

ADD_KIT ~B_CLERIC_MOANDER~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_MOANDER     1 1 1 1 1 1 1 1~
~B_CLERIC_MOANDER     1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_MOANDER         0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_MOANDER           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/331_moander/b_cmoa.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33101
SAY @33102
SAY @33103

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33103)
		STR_VAR
			kit_name = B_CLERIC_MOANDER
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//MOANDER ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/331_moander/b_cmoa.2da~ ~override~

COPY_EXISTING ~sppr105.spl~ ~override/B_moa1.spl~ // innate
  WRITE_SHORT 0x1c 4//Innate
  WRITE_SHORT 0x74 4//Innate
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~B_moa1~
  END
COPY ~faiths_and_powers/kits/acolytes/331_moander/b_moa2.spl~ ~override~    //Assassin vines
        SAY NAME1 @51404
        SAY NAME2 @51404
        SAY UNIDENTIFIED_DESC @51405
	SAY DESC @51405

COPY ~faiths_and_powers/kits/acolytes/331_moander/b_moa3.spl~ ~override~    //Immunities

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_cmoa~
	race 			= ~all~
	s_Life 			= ~x~
	s_Death 		= ~major~
	s_Benediction 	= ~x~
	s_Destruction   = ~major~
	s_Protection    = ~x~
	s_War 			= ~minor~
	s_Knowledge     = ~x~
	s_Deception     = ~minor~
	s_Thought 		= ~x~
	s_Dread 		= ~major~
	s_Vigor 		= ~x~
	s_Affliction    = ~major~
	s_Animal 		= ~minor~
	s_Plant 		= ~focus~
	s_Earth 		= ~major~
	s_Water 		= ~minor~
	s_Air 			= ~minor~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~major~
	s_Magic 		= ~minor~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF BESHABA
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_beshaba BEGIN

ADD_KIT ~B_PRIEST_BESHABA~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_BESHABA     1 1 1 1 1 1 1 1~
~B_PRIEST_BESHABA     1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_PRIEST_BESHABA         0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_PRIEST_BESHABA           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/332_beshaba/b_abes.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33201
SAY @33202
SAY @33203

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33203)
		STR_VAR
			kit_name = B_PRIEST_BESHABA
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//MOANDER ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/332_beshaba/b_abes.2da~ ~override~

COPY_EXISTING ~SPPR113.spl~ ~override/B_BES01.spl~ // Doom
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 999 opcode = 206 target = 2 timing = 0 duration = 2400 STR_VAR resource = EVAL ~B_BES01~ END

COPY_EXISTING ~B_BES01.spl~ ~override~
	PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
		   READ_SHORT 0x1c spell_type
PATCH_IF  (%spell_type% = 4) BEGIN
        READ_LONG 	0x64	ab_off			// Abilities Offset
	READ_SHORT	0x68	ab_num			// Number of Abilities
	READ_SHORT	0x6a	fx_off			// Effects Offset
	READ_SHORT	0x70	glob_fx			// Number of Global Effects
	SET	glob_add = 0

        INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 171			// opcode
	  WRITE_BYTE (fx_off + 0x2) 1			// Target (self)
	 // WRITE_BYTE (fx_off + 0x4) 1			// Level 1
	//  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// timing (Perm)
       //   WRITE_LONG (fx_off + 0xe) 10                  //duration
	  WRITE_BYTE (fx_off + 0x12) 100			// Probability 1
          WRITE_ASCII (fx_off + 0x14) ~B_BES01~               //  resource
	++glob_add

	INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 172			// opcode
	  WRITE_BYTE (fx_off + 0x2) 1			// Target (self)
	 // WRITE_BYTE (fx_off + 0x4) 1			// Level 1
	//  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// timing (Perm)
       //   WRITE_LONG (fx_off + 0xe) 10                  //duration
	  WRITE_BYTE (fx_off + 0x12) 100			// Probability 1
          WRITE_ASCII (fx_off + 0x14) ~B_BES01~               //  resource
	++glob_add
	
//	INSERT_BYTES (fx_off) 0x30			//Second effect
//	  WRITE_etc...
//	++glob_add

	glob_fx += glob_add
	WRITE_SHORT 0x70 glob_fx			// Increment Number of Global Effects
	FOR (i = 0; i < ab_num; ++i) BEGIN		// Offset Effect Index for all Abilities
	  READ_SHORT (ab_off + i * 0x28 + 0x20) fx_idx
	  WRITE_SHORT (ab_off + i * 0x28 + 0x20) (fx_idx + glob_add)
	END
END
END

COPY ~faiths_and_powers/kits/acolytes/332_beshaba/b_bes02.spl~ ~override~
//bes03
COPY ~faiths_and_powers/spheres/spells/dread/b_c501b.bam~ ~override~ // Misfire
COPY ~faiths_and_powers/spheres/spells/dread/b_c501c.bam~ ~override~ // Misfire
//spl etc
COPY ~faiths_and_powers/spheres/spells/dread/b_c501.eff~ ~override~ // Misfire
  SAY 0x1c @50901     //Misfire

COPY ~faiths_and_powers/spheres/spells/dread/b_c501.spl~ ~override/b_bes03.spl~ // Misfire
        SAY NAME1 @50901
        SAY NAME2 @50901
        SAY UNIDENTIFIED_DESC @50902
	SAY DESC @50902
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  WRITE_BYTE 0x9C 4//Location
  WRITE_BYTE 0xC4 4//Location  +28
  WRITE_BYTE 0xEC 4//Location  +28
  WRITE_BYTE 0x114 4//Location  +28
  WRITE_BYTE 0x13C 4//Location  +28
  WRITE_BYTE 0x164 4//Location  +28
  WRITE_BYTE 0x18C 4//Location  +28
  WRITE_BYTE 0x1B4 4//Location  +28
  WRITE_BYTE 0x1DC 4//Location  +28
  WRITE_BYTE 0x204 4//Location  +28
  WRITE_BYTE 0x22C 4//Location  +28
  WRITE_BYTE 0x254 4//Location  +28
             LPF ALTER_EFFECT
              INT_VAR match_opcode = 321
              STR_VAR resource = EVAL ~b_bes03~
             END
COPY ~faiths_and_powers/kits/acolytes/332_beshaba/b_bes04.spl~ ~override~
        SAY NAME1 @33206
        SAY NAME2 @33206
        SAY UNIDENTIFIED_DESC @33207
	SAY DESC @33207

COPY ~faiths_and_powers/spheres/spells/dread/b_c501.eff~ ~override/b_bes04.eff~ // Misfire
  SAY 0x1c @33206     //Misfortune

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_abes~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~major~
	s_Benediction 	        = ~major~
	s_Destruction           = ~minor~
	s_Protection            = ~major~
	s_War 			= ~minor~
	s_Knowledge             = ~minor~
	s_Deception             = ~minor~
	s_Thought 		= ~major~
	s_Dread 		= ~focus~
	s_Vigor 		= ~minor~
	s_Affliction            = ~major~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC KITS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_MACRO acolyte_baervan BEGIN

ADD_KIT ~D5_AC_BAERVAN~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_BAERVAN   0 0 0 0 0 0 0 0~
~D5_AC_BAERVAN   0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_BAERVAN      1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_BAERVAN      0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/342_baervan/d5baerv.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_G~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @34201
SAY @34202
SAY @34203

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@34204)
		STR_VAR
			kit_name = D5_AC_BAERVAN
			clswpbon = ~0 0 3~
	END
END

//BAERVAN ABILITY FILES_______________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/acolytes/342_baervan/d5baerv.2da~ ~override~

//DEFINE SPHERE ACCESS________________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~d5baerv~
	race 			= ~gnome~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~x~
	s_Protection 	= ~major~
	s_War 			= ~x~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~focus~
	s_Plant 		= ~major~
	s_Earth 		= ~major~
	s_Water 		= ~minor~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~minor~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
 END

//CLERIC/MAGE_______________________________________________________________________

ADD_KIT ~D5_CM_BAERVAN~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CM_BAERVAN   0 0 0 0 0 0 0 0~
~D5_CM_BAERVAN   0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_BAERVAN      0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_BAERVAN      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_BAERVAN      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CM_BAERVAN      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CM_BAERVAN      1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CM_BAERVAN      0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/342_baervan/d5baer2.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_G~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 14~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @34201
SAY @34202
SAY @34203

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@34204)
		STR_VAR
			kit_name = D5_AC_BAERVAN
			clswpbon = ~0 0 3~
	END
END

COPY_EXISTING ~faiths_and_powers/kits/acolytes/342_baervan/d5baerv.2da~ ~override/d5baer2.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5baer2.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_AC_BAERVAN~
		kit_clab = ~d5baer2~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_mage 	= 1
  STR_VAR
    clab_name 		= ~d5baer2~
	race 			= ~gnome~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~x~
	s_Protection 	= ~major~
	s_War 			= ~x~
	s_Knowledge 	= ~minor~
	s_Deception 	= ~x~
	s_Thought 		= ~minor~
	s_Dread 		= ~x~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~focus~
	s_Plant 		= ~major~
	s_Earth 		= ~major~
	s_Water 		= ~minor~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~minor~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
 END

END
//__________________________________________________________________________________


