
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						APPLY SPHERE SYSTEM TO KITS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION apply_spheres BEGIN

INCLUDE ~faiths_and_powers/lib/hla_actions.tpa~

COPY ~faiths_and_powers/spheres/d5spmem.spl~ ~override~
	SAY NAME1 @6
COPY ~faiths_and_powers/spheres/d5spmem.itm~ ~override~
	SAY NAME1 @1100
	SAY UNIDENTIFIED_DESC @1101
COPY ~faiths_and_powers/spheres/d5spmema.bam~ ~override~
COPY ~faiths_and_powers/spheres/d5spmemb.bam~ ~override~

OUTER_SPRINT sphere_access @1002
OUTER_SPRINT focus_access @1003
OUTER_SPRINT major_access @1004
OUTER_SPRINT minor_access @1005
OUTER_SPRINT advantages @1006
OUTER_SPRINT abilities @1007
OUTER_SPRINT disadvantages @1008
OUTER_SPRINT restrictions @1009
OUTER_TEXT_SPRINT focus_sphere_list ~~
OUTER_TEXT_SPRINT major_sphere_list ~~
OUTER_TEXT_SPRINT minor_sphere_list ~~
OUTER_TEXT_SPRINT paladin_sphere_list ~~
OUTER_TEXT_SPRINT ranger_sphere_list ~~
OUTER_TEXT_SPRINT total_sphere_list ~~

//LAM ~READ_FNP_KIT_INFO~

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_kitlist~ 10
  FOR (row = 3; row < r2en_kitlist; row += 1) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 5 kit_clab
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 0 kit_index
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kit_label
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 kit_desc
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 9 kit_code
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 8 kit_class
	PATCH_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~%kit_clab%~)) BEGIN
	  SPRINT $d5_kitlist_spheres (~%kit_clab%~ ~%kit_index%~ ~%kit_label%~ ~%kit_desc%~ ~%kit_code%~) ~%kit_class%~
	END
  END
BUT_ONLY
ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~CLERIC~ BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~cleric_desc~
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~DRUID~ BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~druid_desc~
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~PALADIN~ BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~paladin_desc~
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~RANGER~ BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~ranger_desc~
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~SHAMAN~ BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~shaman_desc~
	  END
	END
  BUT_ONLY
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABPR01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABPR01~ ~pr~ ~CLERIC~ ~%cleric_desc%~ ~0x00004000~) ~3~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABDR01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABDR01~ ~dr~ ~DRUID~ ~%druid_desc%~ ~0x00004000~) ~11~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABPA01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABPA01~ ~pa~ ~PALADIN~ ~%paladin_desc%~ ~0x00004000~) ~6~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABRN01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABRN01~ ~rn~ ~RANGER~ ~%ranger_desc%~ ~0x00004000~) ~12~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABSH01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABSH01~ ~sh1~ ~SHAMAN~ ~%shaman_desc%~ ~0x00004000~) ~21~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABSHGS~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABSHGS~ ~sh2~ ~SHAMAN~ ~%shaman_desc%~ ~0x00004000~) ~21~
  END
END
ACTION_PHP_EACH d5_kitlist_spheres AS goo => roo BEGIN
	APPEND ~%goo%.2da~ ~SPHERES     AP_D5SPMEM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	ACTION_IF (%roo% = 3) OR  
 			(%roo% = 11) OR  
 			(%roo% = 8) OR  
 			(%roo% = 14) OR  
 			(%roo% = 15) OR  
 			(%roo% = 18) BEGIN
	  COPY_EXISTING ~luabbr.2da~ ~override~
		REPLACE_TEXTUALLY ~^\(%goo_2%[ %TAB%]+\).+$~ ~\1b_%goo_1%~
	  BUT_ONLY
	END
	COPY ~faiths_and_powers/spheres/hlas/luclxyz.2da~ ~override/lub_%goo_1%.2da~
	ACTION_IF (%roo% = 11) BEGIN 	// druid
	  COPY ~faiths_and_powers/spheres/hlas/ludrxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 8) BEGIN 	// f/c
	  COPY ~faiths_and_powers/spheres/hlas/lufcxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 18) BEGIN 	// c/r
	  COPY ~faiths_and_powers/spheres/hlas/lucrxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 15) BEGIN 	// c/t
	  COPY ~faiths_and_powers/spheres/hlas/luctxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 14) BEGIN 	// c/m
	  COPY ~faiths_and_powers/spheres/hlas/lucmxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_PHP_EACH d5_fnp_spheres AS sphere => val BEGIN
//	  LAM ~set_sphere_names~
	  OUTER_INNER_PATCH_SAVE sphere_name ~%sphere%~ BEGIN
		PHP_EACH sphere_name_changes AS fnp_sphere => new_sphere BEGIN
		  REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH ~%fnp_sphere%~ ~%new_sphere%~
		END
	  END
	  ACTION_IF (VARIABLE_IS_SET $d5_fnp_kit_sphere_access(~%sphere%~ ~%goo%~)) BEGIN
		OUTER_TEXT_SPRINT access $d5_fnp_kit_sphere_access(~%sphere%~ ~%goo%~)
		OUTER_INNER_PATCH ~%sphere%~ BEGIN
		  SNPRINT 3 ~shortsphere~ ~%sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~) && ~%access%~ STRING_EQUAL_CASE ~FOCUS~) BEGIN
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/hlas/%sphere%/hlas_%sphere%.txt~
		  BUT_ONLY
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]zzz~ ~~
		  BUT_ONLY
		  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SF%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		  OUTER_TEXT_SPRINT focus_sphere_list ~%focus_sphere_list% %sphere_name%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~) && ~%access%~ STRING_EQUAL_CASE ~MAJOR~) BEGIN
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/hlas/%sphere%/hlas_%sphere%.txt~
		  BUT_ONLY
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]zzz~ ~~
		  BUT_ONLY
		  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		  OUTER_TEXT_SPRINT major_sphere_list ~%major_sphere_list% %sphere_name%,~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~) && ~%access%~ STRING_EQUAL_CASE ~MINOR~) BEGIN
		  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SM%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list% %sphere_name%,~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~) && ~%access%~ STRING_EQUAL_CASE ~PALADIN~) BEGIN
		  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list% %sphere_name%,~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~) && ~%access%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
		  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list% %sphere_name%,~
		END
	  END
	END
	ACTION_IF NOT (~%focus_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT focus_sphere_list ~%WNL%%focus_access%%focus_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%focus_sphere_list%~
	ACTION_IF NOT (~%major_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT major_sphere_list ~%WNL%%major_access%%major_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%major_sphere_list%~
	ACTION_IF NOT (~%minor_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT minor_sphere_list ~%WNL%%minor_access%%minor_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%minor_sphere_list%~
	OUTER_TEXT_SPRINT kit_sphere_list ~Abilities: %total_sphere_list%~
	ACTION_IF IS_AN_INT ~%goo_3%~ BEGIN
		ACTION_GET_STRREF %goo_3% kit_description 
		OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
			REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
//			REPLACE_TEXTUALLY ~%abilities%~ ~%kit_sphere_list%~
			REPLACE_TEXTUALLY ~%advantages%~ ~%kit_sphere_list%~
		END
		STRING_SET_EVALUATE %goo_3% ~%kit_description%~
	END
	OUTER_TEXT_SPRINT focus_sphere_list ~~
	OUTER_TEXT_SPRINT major_sphere_list ~~
	OUTER_TEXT_SPRINT minor_sphere_list ~~
	OUTER_TEXT_SPRINT total_sphere_list ~~
	ACTION_IF (%roo% = 8) OR  
 			(%roo% = 14) OR  
 			(%roo% = 15) OR  
 			(%roo% = 18) OR
 			(%roo% = 16) BEGIN
	  ACTION_IF (%roo% = 8) OR  
 				(%roo% = 14) OR  
 				(%roo% = 15) OR  
 				(%roo% = 18) BEGIN
 	 	OUTER_TEXT_SPRINT class_letter ~P~
 	  END
	  ACTION_IF (%roo% = 16) BEGIN
 	 	OUTER_TEXT_SPRINT class_letter ~D~
 	  END
	  ACTION_IF IS_AN_INT ~%goo_4%~ BEGIN
		COPY_EXISTING ~%goo%.2da~ ~override~ //copy the clab of the base kit 
		  COUNT_2DA_COLS cols // amount of columns
		  READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
		  FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
			READ_2DA_ENTRY_FORMER rows row 0 sphere // read first column
			PATCH_IF (~%sphere%~ STRING_EQUAL_CASE ~SPHERES~) BEGIN	
			  FOR (col = 1; col < cols; ++col) BEGIN // iterate over columns
				READ_2DA_ENTRY_FORMER rows row col ability // read column value
				PATCH_IF (NOT ~%ability%~ STRING_EQUAL ~****~) BEGIN 
				  SET string_length = (STRING_LENGTH ~%ability%~) - 3
				  LPF SUBSTRING INT_VAR start = 3 length = EVAL %string_length% STR_VAR string = EVAL ~%ability%~ RET abil_new = substring END
				  INNER_ACTION BEGIN 
					COPY ~faiths_and_powers/lib/qd_mc/QD_MC_AP.eff~ ~override/%abil_new%#.eff~
					  WRITE_EVALUATED_ASCII 0x30 ~%abil_new%~
					  SET col_length = STRING_LENGTH ~%col%~
					ACTION_IF (%col_length% = 1) BEGIN 
					  COPY_EXISTING ~override/QD_MC%class_letter%0%col%.spl~ ~override~ 
						LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 timing = 9 resist_dispel = 0 power = 0 parameter1 = %goo_4% parameter2 = 9 STR_VAR resource = EVAL ~%abil_new%#~ END  
					END 
					ACTION_IF (%col_length% = 2) BEGIN
					  COPY_EXISTING ~override/QD_MC%class_letter%%col%.spl~ ~override~ 
						LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 timing = 9 resist_dispel = 0 power = 0 parameter1 = %goo_4% parameter2 = 9 STR_VAR resource = EVAL ~%abil_new%#~ END  
					END 
				  END 
				END
			  END 
			END 
		  END
		BUT_ONLY
	  END
	END
END
//___________________________________________________________________________________

CLEAR_ARRAYS

//copy HLAs and related files________________________________________________________
//
ACTION_IF GAME_IS ~tob bg2ee eet~ BEGIN
	INCLUDE ~faiths_and_powers/lib/hlas.tpa~
END
//___________________________________________________________________________________

//multi sorcerer HLAs________________________________________________________________
//
COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols 
  READ_2DA_ENTRIES_NOW rows 10
  FOR (row = 1; row < rows; ++row) BEGIN 
    READ_2DA_ENTRY_FORMER rows row 1 ~kit_name~ 
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_FIGHTER_SORCERER~ BEGIN
      SET fighter_sorcerer_row = %row%
      READ_2DA_ENTRY_FORMER rows fighter_sorcerer_row 0 fighter_sorcerer_index
    END
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_RANGER_SORCERER~ BEGIN
      SET ranger_sorcerer_row = %row%
      READ_2DA_ENTRY_FORMER rows ranger_sorcerer_row 0 ranger_sorcerer_index
    END
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_SORCERER_THIEF~ BEGIN
      SET sorcerer_thief_row = %row%
      READ_2DA_ENTRY_FORMER rows sorcerer_thief_row 0 sorcerer_thief_index
    END
  END
BUT_ONLY

ACTION_IF FILE_EXISTS_IN_GAME ~LUFM0.2da~ BEGIN
  COPY_EXISTING ~LUFM0.2DA~ ~override/lub_%fighter_sorcerer_index%.2da~
	REPLACE_TEXTUALLY ~spwi920~ ~d5hl920~
	REPLACE_TEXTUALLY ~spwi921~ ~d5hl921~
	REPLACE_TEXTUALLY ~spwi922~ ~d5hl922~
	REPLACE_TEXTUALLY ~spwi923~ ~d5hl923~
	REPLACE_TEXTUALLY ~spwi924~ ~d5hl924~
	REPLACE_TEXTUALLY ~spwi925~ ~d5hl925~
	REPLACE_TEXTUALLY ~spcl928~ ~d5hl928~
	REPLACE_TEXTUALLY ~spcl929~ ~d5hl929~
	REPLACE_TEXTUALLY ~spcl930~ ~d5hl930~
  COPY_EXISTING ~LUFM0.2DA~ ~override/lub_%ranger_sorcerer_index%.2da~
	REPLACE_TEXTUALLY ~spwi920~ ~d5hl920~
	REPLACE_TEXTUALLY ~spwi921~ ~d5hl921~
	REPLACE_TEXTUALLY ~spwi922~ ~d5hl922~
	REPLACE_TEXTUALLY ~spwi923~ ~d5hl923~
	REPLACE_TEXTUALLY ~spwi924~ ~d5hl924~
	REPLACE_TEXTUALLY ~spwi925~ ~d5hl925~
	REPLACE_TEXTUALLY ~spcl928~ ~d5hl928~
	REPLACE_TEXTUALLY ~spcl929~ ~d5hl929~
	REPLACE_TEXTUALLY ~spcl930~ ~d5hl930~
END
ACTION_IF FILE_EXISTS_IN_GAME ~LUMT0.2da~ BEGIN
  COPY_EXISTING ~LUMT0.2DA~ ~override/lub_%sorcerer_thief_index%.2da~
	REPLACE_TEXTUALLY ~spwi920~ ~d5hl920~
	REPLACE_TEXTUALLY ~spwi921~ ~d5hl921~
	REPLACE_TEXTUALLY ~spwi922~ ~d5hl922~
	REPLACE_TEXTUALLY ~spwi923~ ~d5hl923~
	REPLACE_TEXTUALLY ~spwi924~ ~d5hl924~
	REPLACE_TEXTUALLY ~spwi925~ ~d5hl925~
	REPLACE_TEXTUALLY ~spcl928~ ~d5hl928~
	REPLACE_TEXTUALLY ~spcl929~ ~d5hl929~
	REPLACE_TEXTUALLY ~spcl930~ ~d5hl930~
END
//___________________________________________________________________________________

//multi druid HLAs___________________________________________________________________
//
LAF action_remove_hla STR_VAR kit_name = ~D5_DR_FIGHTER~ remove_ability = ~AP_D5PHLA5~ END
LAF action_remove_hla STR_VAR kit_name = ~D5_DR_RANGER~ remove_ability = ~AP_D5PHLA5~ END
LAF action_remove_hla STR_VAR kit_name = ~D5_DR_THIEF~ remove_ability = ~AP_D5PHLA5~ END
LAF action_remove_hla STR_VAR kit_name = ~D5_DR_MAGE~ remove_ability = ~AP_D5PHLA5~ END

LAF action_add_hla STR_VAR kit_name = ~D5_DR_FIGHTER~ ability = ~AP_D5PHLA4~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5_DR_RANGER~ ability = ~AP_D5PHLA4~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5_DR_THIEF~ ability = ~AP_D5PHLA4~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5_DR_MAGE~ ability = ~AP_D5PHLA4~ num_allowed = ~1~ END

LAF action_add_hla STR_VAR kit_name = ~D5_DR_FIGHTER~ ability = ~GA_TG#SPIR~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5_DR_RANGER~ ability = ~GA_TG#SPIR~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5_DR_THIEF~ ability = ~GA_TG#SPIR~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5_DR_MAGE~ ability = ~GA_TG#SPIR~ num_allowed = ~1~ END
//___________________________________________________________________________________

//fix contingency spells_____________________________________________________________
//
ACTION_FOR_EACH contingency IN ~d5pw617~ ~d5fw617~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%contingency%.spl~ BEGIN
	COPY_EXISTING ~%contingency%.spl~ ~override~
	  LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
	  LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 146 target = 1 power = 6 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~spwi617~ END
	BUT_ONLY
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5hkno1.spl~ BEGIN
  COPY_EXISTING ~d5hkno1.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
	LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 146 target = 1 power = 6 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~spwi908~ END
  BUT_ONLY
END
//___________________________________________________________________________________


/*
//tell SCS not to process sphere spells for AI_______________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~noscsai.2da~ BEGIN

<<<<<<<< %MOD_FOLDER%/inline/noscsai.2da
2DA V1.0
****
QDMulti     QD_MC>>>>>>>> 

 COPY ~%MOD_FOLDER%/inline/noscsai.2da~ ~override/noscsai.2da~ 

END

APPEND ~override/noscsai.2da~ ~FNP         D5SM 
FNP         D5SP 
FNP         D5SF ~
//___________________________________________________________________________________
*/

END // end function
