
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CREATE SPHERE SYSTEM
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION create_spheres BEGIN

//copy marker file___________________________________________________________________
//
COPY ~faiths_and_powers/lib/markers/d5_spheres.d5~ ~override~ 
//___________________________________________________________________________________


//game check_________________________________________________________________________
//
ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END
//___________________________________________________________________________________


//create sphere spells______________________________________________________________
//
//life
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5splif.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sflif.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smlif.spl~
//death
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdea.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdea.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdea.spl~
//benediction
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spben.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfben.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smben.spl~
//Destruction
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdes.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdes.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdes.spl~
//Protection
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sppro.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfpro.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smpro.spl~
//war
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spwar.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfwar.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smwar.spl~
//exploration
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spexp.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfexp.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smexp.spl~
//knowledge
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spkno.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfkno.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smkno.spl~
//deception
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdec.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdec.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdec.spl~
//thought
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sptho.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sftho.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smtho.spl~
//dread
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdre.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdre.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdre.spl~
//Vigor
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spvig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfvig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smvig.spl~
//affliction
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spaff.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfaff.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smaff.spl~
//animal
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spani.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfani.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smani.spl~
//plant
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sppla.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfpla.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smpla.spl~
//earth
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spear.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfear.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smear.spl~
//air
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spair.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfair.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smair.spl~
//water
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spwat.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfwat.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smwat.spl~
//fire
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spfir.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sffir.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smfir.spl~
//light
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5splig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sflig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smlig.spl~
//shadow
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spsha.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfsha.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smsha.spl~
//magic
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spmag.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfmag.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smmag.spl~
//perdition
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spper.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfper.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smper.spl~
//__________________________________________________________________________________


//prepare spell conversions_________________________________________________________
//
/*
ACTION_IF FILE_EXISTS_IN_GAME ~smcudge.itm~ BEGIN
COPY_EXISTING ~smcudge.itm~ ~override~
	WRITE_BYTE 0x8a 2
END                         
*/

/*
COPY_EXISTING ~sppr737.spl~ ~override/d5_1stal.spl~
	LPF DELETE_EFFECT INT_VAR header=1 END

COPY_EXISTING ~sppr108.spl~ ~override~
	SAY NAME1 ~Courage~
	SAY UNIDENTIFIED_DESC ~Courage: the artist formerly known as remove fear~
COPY_EXISTING ~sppr313.spl~ ~override~
	SAY NAME1 ~Divine Wrath~
	SAY UNIDENTIFIED_DESC ~Divine Wrath: the artist formerly known as holy smite~
COPY_EXISTING ~sppr314.spl~ ~override~
	SAY NAME1 ~Infernal Wrath~
	SAY UNIDENTIFIED_DESC ~Infernal Wrath: the artist formerly known as unholy blight~
COPY_EXISTING ~sppr201.spl~ ~override~
	SAY NAME1 ~Invigorate~
	SAY UNIDENTIFIED_DESC ~Invigorate: the artist formerly known as aid~
COPY_EXISTING ~sppr208.spl~ ~override~
	SAY NAME1 ~Paralyze~
	SAY UNIDENTIFIED_DESC ~Paralyze: the artist formerly known as hold person~
*/
//__________________________________________________________________________________


//add new spells____________________________________________________________________

ACTION_CLEAR_ARRAY aoe_spell

//INCLUDE ~%mod_folder%/lib/fnp_wiz.tpa~
INCLUDE ~%mod_folder%/lib/fnp_new_spells.tpa~


/*
//add new SR spells_________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN

  INCLUDE ~faiths_and_powers/lib/spell_revisions/sr_%game%.tpa~

END
//__________________________________________________________________________________
*/

//no spells for anyone!______________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~
	READ_SHORT 0x1c ~spelltype~
	PATCH_IF (~spelltype~ = 2) BEGIN
		WRITE_BYTE 0x21 (THIS | 0b11000000)
	END
BUT_ONLY


//erase spell alignment restrictions_________________________________________________

COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~ //copies all spl files
	PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BAND 0b11111001)
	END
BUT_ONLY
//___________________________________________________________________________________


//remove priest spells from joinable NPCs____________________________________________
//
OUTER_FOR (level = 1; level <= 7; level += 1) BEGIN
  OUTER_SET $spell(~all~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~cleric~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~druid~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~bogus~ ~%level%~ ~length~) = 0
END

COPY_EXISTING_REGEXP GLOB ~^SPPR[1-7]\(0[1-9]\|[1-4][0-9]\|50\)\.spl$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_SHORT 0x1c spell_type
    PATCH_IF (spell_type == 2) BEGIN // divine, just to be sure
      READ_SHORT 0x20 priest_type
      READ_SHORT 0x1e exclusion_flags
      READ_LONG  0x34 level
      TO_UPPER SOURCE_RES
      PATCH_IF (priest_type == 0x0000) BEGIN // all priests
        SPRINT type ~all~
      END
      ELSE PATCH_IF (priest_type == 0x4000) BEGIN // druid/ranger
        SPRINT type ~druid~
      END
      ELSE PATCH_IF (priest_type == 0x8000) BEGIN // cleric/paladin
        SPRINT type ~cleric~
      END
      ELSE BEGIN // no priests
        SPRINT type ~bogus~
      END
      PATCH_IF (level > 0 && level <= 7) BEGIN
        SET index = $spell(~%type%~ ~%level%~ ~length~)
        SPRINT $spell(~%type%~ ~%level%~ ~%index%~) ~%SOURCE_RES%~
        SET $spell(~%type%~ ~%level%~ ~length~) += 1
        SET $spell(~%type%~ ~%SOURCE_RES%~) = 1
        SET $spell(~%SOURCE_RES%~ ~excl~) = (exclusion_flags BAND 0b111111) // store just the alignment bits
        SET $spell(~%SOURCE_RES%~ ~level~) = level
      END
    END
  END
  BUT_ONLY

DEFINE_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~ BEGIN
  FOR (level = 1; level <= 7; level += 1) BEGIN
    SET length = $spell(~%type%~ ~%level%~ ~length~)
    FOR (i = 0; i < length; i += 1) BEGIN
      SPRINT spell $spell(~%type%~ ~%level%~ ~%i%~)
      REMOVE_KNOWN_SPELL ~%spell%~
    END
  END
END

DEFINE_PATCH_FUNCTION ~REMOVE_BAD_KNOWN_SPELLS~
 // INT_VAR spell_type = 0 // 1 = cleric, 2 = druid, 3 = both
BEGIN
  PATCH_IF (spell_type == 1) BEGIN // remove druid spells from clerics
    SPRINT type ~druid~
    LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
  END
  ELSE PATCH_IF (spell_type = 2) BEGIN // remove cleric spells from druids
    SPRINT type ~cleric~
    LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
  END

  // remove bogus spells from all classes
  SPRINT type ~bogus~
  LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
END

LAM JOINABLE_NPC_ARRAYS

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
//  PRINT ~%cre% => %dv%~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  READ_BYTE 0x273 class
      PATCH_IF (class == 3 || class == 6 || class == 8 || class == 11 || class == 12 || class == 14 || class == 15 || class == 16 || class == 17 || class == 18) BEGIN // divine casters
        LAUNCH_PATCH_FUNCTION ~REMOVE_BAD_KNOWN_SPELLS~ END
//        REMOVE_MEMORIZED_SPELLS
      END
    END
  BUT_ONLY
END
//__________________________________________________________________________________


/*
//certain spells for everyone_______________________________________________________
//
COPY_EXISTING ~sppr103.spl~ ~override~ // cure light wounds
			~sppr210.spl~ ~override~ // resist fire/cold
			~sppr307.spl~ ~override~ // remove curse
			~sppr417.spl~ ~override~ // lesser restoration
			~sppr502.spl~ ~override~ // cure critical
			~sppr611.spl~ ~override~ // wondrous recall
			~sppr710.spl~ ~override~ // holy word
			~sppr715.spl~ ~override~ // unholy word
	WRITE_BYTE 0x21 (THIS & 0b00111111)
BUT_ONLY

<<<<<<<< d5/d5unvrsl.2da
2DA V1.0 
SPLRES
			UNIVERSAL
>>>>>>>> 

COPY ~d5/d5unvrsl.2da~ ~override/d5unvrsl.2da~ 
APPEND ~d5unvrsl.2da~ ~SPPR103		cure_light_wounds
SPPR210		resist_fire_cold
SPPR212		slow_poison
SPPR307		remove_curse
SPPR417		lesser_restoration
SPPR502		cure_crit_wounds
SPPR508		chaotic_commands
SPPR611		wondrous_recall
SPPR710		holy_word
SPPR715		unholy_word~


COPY ~faiths_and_powers/spheres/d5ph000.spl~ ~override~

COPY_EXISTING ~clabpr01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
COPY_EXISTING ~clabdr01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
COPY_EXISTING ~clabpa01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
COPY_EXISTING ~clabrn01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
ACTION_IF FILE_EXISTS_IN_GAME ~clabsh01.2da~ BEGIN
  COPY_EXISTING ~clabsh01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
END  
ACTION_IF FILE_EXISTS_IN_GAME ~clabshgs.2da~ BEGIN
  COPY_EXISTING ~clabshgs.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
END

COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_base_spell_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY

ACTION_PHP_EACH d5_base_spell_array AS bo => zo BEGIN
	ACTION_IF (%zo% = 3) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
	END
	ACTION_IF (%zo% = 11) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
	END
	ACTION_IF (%zo% = 21) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
	END
	ACTION_IF (%zo% = 6) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
	END
	ACTION_IF (%zo% = 12) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/universal_spells.txt~
	END
END
//__________________________________________________________________________________
*/


//some vanilla spell modifications__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518a.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518a.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518b.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518b.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr150.spl~ THEN BEGIN
  COPY_EXISTING ~sppr150.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 219 parameter1 = 121 END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 219 opcode = 100 parameter1 = 9 parameter2 = 7 END
	SAY UNIDENTIFIED_DESC @59999
  BUT_ONLY
END

COPY_EXISTING - ~spell.ids~ ~faiths_and_powers/backup~
  COUNT_REGEXP_INSTANCES ~CLERIC_ALICORN_LANCE~ spell_exists
ACTION_IF (spell_exists) BEGIN
  LAF RES_NUM_OF_SPELL_NAME
	STR_VAR spell_name = ~CLERIC_ALICORN_LANCE~ RET spell_res 
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~%spell_res%.spl~ BEGIN
	COPY_EXISTING ~%spell_res%.spl~ ~override~
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 12 parameter2 = (0 + 64 << 16) savingthrow = 0 END
	BUT_ONLY
  END
END
//__________________________________________________________________________________


//apply sphere system to spells_____________________________________________________
//
<<<<<<<< d5/d5sphspl.2da
2DA V1.0 
SPHERE
			SPELL		LEVEL
>>>>>>>> 

COPY ~d5/d5sphspl.2da~ ~override/d5sphspl.2da~ 

LAM d5_minor_access_levels

ACTION_PHP_EACH spellsphere AS spl => sph BEGIN 
//
  OUTER_SET lvl = spl_1
  OUTER_SET mlvl = (%lvl% + 1)
  OUTER_SET flvl = (%lvl% - 1)
//
 ACTION_IF !(~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
 
  OUTER_INNER_PATCH ~%sph%~ BEGIN
    SNPRINT 3 ~shortsphere~ ~%sph%~ 
    SPRINT sphere ~d5sp%shortsphere%~
    SPRINT fsphere ~d5sf%shortsphere%~
    SPRINT msphere ~d5sm%shortsphere%~
  END
//
//  COPY_EXISTING - ~spell.ids~ ~faiths_and_powers/backup~
//	COUNT_REGEXP_INSTANCES ~%spl%~ ids_exists
//  ACTION_IF (ids_exists) THEN BEGIN
  ACTION_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~%spl%~)) BEGIN
	LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spl%~ RET spell_res spell_num END
	OUTER_TEXT_SPRINT the_spell ~%spell_res%~
  END
  ELSE BEGIN
	OUTER_TEXT_SPRINT the_spell ~%spl%~
  END  
  APPEND ~d5sphspl.2da~ ~%sph%	%the_spell%	%lvl%~
  OUTER_INNER_PATCH_SAVE minor_res ~%the_spell%~ BEGIN
	REPLACE_TEXTUALLY ~^[Ss][Pp][Pp][Rr]~ ~d5mp~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5mw~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Cc][Ll]~ ~d5ml~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ii][Nn]~ ~d5mn~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ss][Dd]~ ~d5ms~
	REPLACE_TEXTUALLY ~^[Bb]_[Cc]~ ~d5mb~
	REPLACE_TEXTUALLY ~^[Bb]_[Pp][Rr]~ ~d5m8~
	REPLACE_TEXTUALLY ~^[Dd]5[Ff][Nn][Pp]~ ~d5m5~
  END
  OUTER_INNER_PATCH_SAVE focus_res ~%the_spell%~ BEGIN
	REPLACE_TEXTUALLY ~^[Ss][Pp][Pp][Rr]~ ~d5fp~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5fw~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Cc][Ll]~ ~d5fl~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ii][Nn]~ ~d5fn~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ss][Dd]~ ~d5fs~
	REPLACE_TEXTUALLY ~^[Bb]_[Cc]~ ~d5fb~
	REPLACE_TEXTUALLY ~^[Bb]_[Pp][Rr]~ ~d5f8~
	REPLACE_TEXTUALLY ~^[Dd]5[Ff][Nn][Pp]~ ~d5f5~
  END
  OUTER_INNER_PATCH_SAVE priest_res ~%the_spell%~ BEGIN
	REPLACE_TEXTUALLY ~^[Ss][Pp][Pp][Rr]~ ~d5pp~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5pw~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Cc][Ll]~ ~d5pl~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ii][Nn]~ ~d5pn~
	REPLACE_TEXTUALLY ~^[Ss][Pp][Ss][Dd]~ ~d5ps~
	REPLACE_TEXTUALLY ~^[Bb]_[Cc]~ ~d5pb~
	REPLACE_TEXTUALLY ~^[Bb]_[Pp][Rr]~ ~d5p8~
	REPLACE_TEXTUALLY ~^[Dd]5[Ff][Nn][Pp]~ ~d5p5~
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~%the_spell%.spl~ BEGIN 
	COPY_EXISTING ~%the_spell%.spl~ ~override~ 
	  READ_SHORT 0x1c spell_type
	  READ_LONG 0x34 spell_lvl
	BUT_ONLY
   ACTION_IF (%spell_type% = 2) BEGIN  // priest spells: add to spheres
	ACTION_IF (%lvl% = %spell_lvl%) BEGIN
	  COPY_EXISTING ~%the_spell%.spl~ ~override~ 
		READ_LONG 0x50 "valid"
		PATCH_IF (%valid% >= 0) BEGIN 
		  READ_STRREF 0x50 ~desc~
		  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
			REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %lvl%~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
			REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %sph% %WNL%Range:~
		  END
		  SAY_EVALUATED 0x50 ~%new_desc%~
		END
	  BUT_ONLY
	  COPY_EXISTING ~%sphere%.spl~ ~override~ 
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%the_spell%~ END
	  BUT_ONLY
	  ACTION_IF (%lvl% = 1) OR (%lvl% = 7) BEGIN
		COPY_EXISTING ~%fsphere%.spl~ ~override~
		  LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%the_spell%~ END
		BUT_ONLY
	  END
	END
	ACTION_IF (%lvl% != %spell_lvl%) BEGIN
	  COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
	  	WRITE_LONG 0x34 %lvl%
		READ_LONG 0x64 abil_offset
		READ_SHORT 0x68 abil_number
		READ_BYTE (%abil_offset% + 0x0c) abil_target					
		READ_SHORT (%abil_offset% + 0x0e) abil_range
		READ_LONG 0x6a eff_offset
		WHILE (%abil_number% > 0) BEGIN
		  SET abil_number = (%abil_number% - 1)
		  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		END
		READ_BYTE (%eff_offset% + 0x02) eff_target
		LPF DELETE_EFFECT INT_VAR match_probability2 = 0 END
		PATCH_IF (%abil_target% = 4) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %lvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
		  PATCH_IF (%abil_range% < 35) BEGIN
			PATCH_IF (%abil_range% > 4) BEGIN
				LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			END
			PATCH_IF (%abil_range% < 5) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// what the hell??  why did I do this??
//			  LPF ALTER_SPELL_HEADER INT_VAR range = 2 END	// maybe this is what I meant to do
			END
		  END
		END
		ELSE BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = %eff_target% power = %lvl% parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
		END
		READ_LONG 0x50 "valid"
		PATCH_IF (%valid% >= 0) BEGIN 
		  READ_STRREF 0x50 ~desc~
		  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
			REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %lvl%~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
			REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %sph% %WNL%Range:~
		  END
		  SAY_EVALUATED 0x50 ~%new_desc%~
		END
	  BUT_ONLY
	  COPY_EXISTING ~%sphere%.spl~ ~override~ 
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%priest_res%~ END
	  BUT_ONLY
	  ACTION_IF (%lvl% = 1) OR (%lvl% = 7) BEGIN
		COPY_EXISTING ~%fsphere%.spl~ ~override~
		  LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%priest_res%~ END
		BUT_ONLY
	  END
	END
	ACTION_IF (%lvl% < 4) BEGIN
	  COPY_EXISTING ~%the_spell%.spl~ ~override/%minor_res%.spl~ 
		PATCH_IF (%d5_minor_shift% = 1) BEGIN
		  WRITE_LONG 0x34 %mlvl%
		END
		PATCH_IF (%d5_minor_shift% = 0) BEGIN
		  WRITE_LONG 0x34 %lvl%
		END
		READ_LONG 0x64 abil_offset
		READ_SHORT 0x68 abil_number
		READ_BYTE (%abil_offset% + 0x0c) abil_target
		READ_SHORT (%abil_offset% + 0x0e) abil_range
		READ_LONG 0x6a eff_offset
		WHILE (%abil_number% > 0) BEGIN
		  SET abil_number = (%abil_number% - 1)
		  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		END
		READ_BYTE (%eff_offset% + 0x02) eff_target
		LPF DELETE_EFFECT INT_VAR match_probability2 = 0 END
		PATCH_IF (%abil_target% = 4) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %lvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
		  PATCH_IF (%abil_range% < 35) BEGIN
			PATCH_IF (%abil_range% > 4) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			END
			PATCH_IF (%abil_range% < 5) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// what the hell??  why did I do this??
 //			  LPF ALTER_SPELL_HEADER INT_VAR range = 2 END	// maybe this is what I meant to do
			END
		  END
		END
		ELSE BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = %eff_target% power = %lvl% parameter1 = 0 parameter2 = 1 timing = 2 STR_VAR resource = EVAL ~%the_spell%~ END
		END
	  COPY_EXISTING ~%msphere%.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%minor_res%~ END
	  BUT_ONLY
	END
	ACTION_IF (1 < %lvl%) BEGIN
	  COPY_EXISTING ~%the_spell%.spl~ ~override/%focus_res%.spl~ 	
		WRITE_LONG 0x34 %flvl%
		READ_LONG 0x64 abil_offset
		READ_SHORT 0x68 abil_number
		READ_BYTE (%abil_offset% + 0x0c) abil_target
		READ_SHORT (%abil_offset% + 0x0e) abil_range
		READ_LONG 0x6a eff_offset
		WHILE (%abil_number% > 0) BEGIN
		  SET abil_number = (%abil_number% - 1)
		  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		END
		READ_BYTE (%eff_offset% + 0x02) eff_target
		LPF DELETE_EFFECT INT_VAR match_probability2 = 0 END
		PATCH_IF (%abil_target% = 4) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %lvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
		  PATCH_IF (%abil_range% < 35) BEGIN
			PATCH_IF (%abil_range% > 4) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			END
			PATCH_IF (%abil_range% < 5) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// what the hell??  why did I do this??
 //			  LPF ALTER_SPELL_HEADER INT_VAR range = 2 END	// maybe this is what I meant to do
			END
		  END
		END
		ELSE BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = %eff_target% power = %lvl% parameter1 = 0 parameter2 = 1 timing = 2 STR_VAR resource = EVAL ~%the_spell%~ END
		END
	  COPY_EXISTING ~%fsphere%.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%focus_res%~ END
	  BUT_ONLY
	END
   END // end type = priest spells
//
   ELSE BEGIN // non-priest spells: make clones
// NOTE: STRIP OUT 216 EFFECTS FROM TNB LEVEL 1 CANTRIPS
	COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
	  WRITE_SHORT 0x1c 2
	  LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
	  WRITE_LONG 0x34 %lvl%
	  READ_LONG 0x50 "valid"
	  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
		READ_STRREF 0x50 ~desc~
		INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
		  REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %lvl%~
		  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
		  REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %sph% %WNL%Range:~
		END
		SAY_EVALUATED 0x50 ~%new_desc%~
	  END
	COPY_EXISTING ~%sphere%.spl~ ~override~
	  LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%priest_res%~ END
	BUT_ONLY
	ACTION_IF (%lvl% = 7) BEGIN
		COPY_EXISTING ~%fsphere%.spl~ ~override~
		  LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%priest_res%~ END
		BUT_ONLY
	END
	ACTION_IF (%lvl% < 4) BEGIN
	  COPY_EXISTING ~%the_spell%.spl~ ~override/%minor_res%.spl~ 
		WRITE_SHORT 0x1c 2
		LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
		PATCH_IF (%d5_minor_shift% = 1) BEGIN
		  WRITE_LONG 0x34 %mlvl%
		END
		PATCH_IF (%d5_minor_shift% = 0) BEGIN
		  WRITE_LONG 0x34 %lvl%
		END
		READ_LONG 0x64 abil_offset
		READ_SHORT 0x68 abil_number
		READ_BYTE (%abil_offset% + 0x0c) abil_target
		READ_SHORT (%abil_offset% + 0x0e) abil_range
		READ_LONG 0x6a eff_offset
		WHILE (%abil_number% > 0) BEGIN
		  SET abil_number = (%abil_number% - 1)
		  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		END
		READ_BYTE (%eff_offset% + 0x02) eff_target
		LPF DELETE_EFFECT INT_VAR match_probability2 = 0 END
		PATCH_IF (%abil_target% = 4) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %lvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
		  PATCH_IF (%abil_range% < 35) BEGIN
			PATCH_IF (%abil_range% > 4) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			END
			PATCH_IF (%abil_range% < 5) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// what the hell??  why did I do this??
 //			  LPF ALTER_SPELL_HEADER INT_VAR range = 2 END	// maybe this is what I meant to do
			END
		  END
		END
		ELSE BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = %eff_target% power = %lvl% parameter1 = 0 parameter2 = 1 timing = 2 STR_VAR resource = EVAL ~%the_spell%~ END
		END
	  COPY_EXISTING ~%msphere%.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%minor_res%~ END
	  BUT_ONLY
	END
	ACTION_IF (1 < %lvl%) BEGIN
	  COPY_EXISTING ~%the_spell%.spl~ ~override/%focus_res%.spl~ 	
		WRITE_SHORT 0x1c 2
		LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
		WRITE_LONG 0x34 %flvl%
		READ_LONG 0x64 abil_offset
		READ_SHORT 0x68 abil_number
		READ_BYTE (%abil_offset% + 0x0c) abil_target
		READ_SHORT (%abil_offset% + 0x0e) abil_range
		READ_LONG 0x6a eff_offset
		WHILE (%abil_number% > 0) BEGIN
		  SET abil_number = (%abil_number% - 1)
		  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		END
		READ_BYTE (%eff_offset% + 0x02) eff_target
		LPF DELETE_EFFECT INT_VAR match_probability2 = 0 END
		PATCH_IF (%abil_target% = 4) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %lvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
		  PATCH_IF (%abil_range% < 35) BEGIN
			PATCH_IF (%abil_range% > 4) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			END
			PATCH_IF (%abil_range% < 5) BEGIN
			  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// what the hell??  why did I do this??
 //			  LPF ALTER_SPELL_HEADER INT_VAR range = 2 END	// maybe this is what I meant to do
			END
		  END
		END
		ELSE BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = %eff_target% power = %lvl% parameter1 = 0 parameter2 = 1 timing = 2 STR_VAR resource = EVAL ~%the_spell%~ END
		END
	  COPY_EXISTING ~%fsphere%.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%focus_res%~ END
	  BUT_ONLY
	END
   END
  END
 END
 ACTION_IF (~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
  ACTION_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~%spl%~)) BEGIN
	LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spl%~ RET spell_res spell_num END
	OUTER_TEXT_SPRINT the_spell ~%spell_res%~
  END
  ELSE BEGIN
	OUTER_TEXT_SPRINT the_spell ~%spl%~
  END  
  ACTION_IF FILE_EXISTS_IN_GAME ~%the_spell%.spl~ BEGIN
	COPY_EXISTING ~%the_spell%.spl~ ~override~
	  WRITE_BYTE 0x21 (THIS & 0b00111111)
	BUT_ONLY
  END
 END
END
//__________________________________________________________________________________

/*
//add new spells to 206/318/321/324 effects_________________________________________
//
PRINT ~*Please be patient, this should take 1-2 minutes...*~
COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~fsphere~ END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~fsphere~ END
BUT_ONLY
//__________________________________________________________________________________
*/

/*
//set spell alignment restrictions__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~sppr601.spl~ BEGIN  //  aerial servant = good
	COPY_EXISTING ~sppr601.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f1601.spl~ BEGIN  //  aerial servant = good
	COPY_EXISTING ~d5f1601.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5s2707.spl~ BEGIN  //  cacofiend = evil
	COPY_EXISTING ~d5s2707.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f2707.spl~ BEGIN  //  cacofiend = evil
	COPY_EXISTING ~d5f2707.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr710.spl~ BEGIN  //  holy word = good
	COPY_EXISTING ~sppr710.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f1710.spl~ BEGIN  //  holy word = good
	COPY_EXISTING ~d5f1710.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr715.spl~ BEGIN  //  unholy word = evil
	COPY_EXISTING ~sppr715.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f1715.spl~ BEGIN  //  unholy word = evil
	COPY_EXISTING ~d5f1715.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
//__________________________________________________________________________________
*/

//clean up spell-adding effects_____________________________________________________
//
COPY_EXISTING 
			 ~d5splif.spl~ ~override~
			 ~d5sflif.spl~ ~override~
			 ~d5smlif.spl~ ~override~
			 ~d5spdea.spl~ ~override~
			 ~d5sfdea.spl~ ~override~
			 ~d5smdea.spl~ ~override~
			 ~d5spben.spl~ ~override~
			 ~d5sfben.spl~ ~override~
			 ~d5smben.spl~ ~override~
			 ~d5spdes.spl~ ~override~
			 ~d5sfdes.spl~ ~override~
			 ~d5smdes.spl~ ~override~
			 ~d5sppro.spl~ ~override~
			 ~d5sfpro.spl~ ~override~
			 ~d5smpro.spl~ ~override~
			 ~d5spwar.spl~ ~override~
			 ~d5sfwar.spl~ ~override~
			 ~d5smwar.spl~ ~override~
			 ~d5spexp.spl~ ~override~
			 ~d5sfexp.spl~ ~override~
			 ~d5smexp.spl~ ~override~
			 ~d5spkno.spl~ ~override~
			 ~d5sfkno.spl~ ~override~
			 ~d5smkno.spl~ ~override~
			 ~d5spdec.spl~ ~override~
			 ~d5sfdec.spl~ ~override~
			 ~d5smdec.spl~ ~override~
			 ~d5sptho.spl~ ~override~
			 ~d5sftho.spl~ ~override~
			 ~d5smtho.spl~ ~override~
			 ~d5spdre.spl~ ~override~
			 ~d5sfdre.spl~ ~override~
			 ~d5smdre.spl~ ~override~
			 ~d5spvig.spl~ ~override~
			 ~d5sfvig.spl~ ~override~
			 ~d5smvig.spl~ ~override~
			 ~d5spaff.spl~ ~override~
			 ~d5sfaff.spl~ ~override~
			 ~d5smaff.spl~ ~override~
			 ~d5spani.spl~ ~override~
			 ~d5sfani.spl~ ~override~
			 ~d5smani.spl~ ~override~
			 ~d5sppla.spl~ ~override~
			 ~d5sfpla.spl~ ~override~
			 ~d5smpla.spl~ ~override~
			 ~d5spear.spl~ ~override~
			 ~d5sfear.spl~ ~override~
			 ~d5smear.spl~ ~override~
			 ~d5spair.spl~ ~override~
			 ~d5sfair.spl~ ~override~
			 ~d5smair.spl~ ~override~
			 ~d5spwat.spl~ ~override~
			 ~d5sfwat.spl~ ~override~
			 ~d5smwat.spl~ ~override~
			 ~d5spfir.spl~ ~override~
			 ~d5sffir.spl~ ~override~
			 ~d5smfir.spl~ ~override~
			 ~d5splig.spl~ ~override~
			 ~d5sflig.spl~ ~override~
			 ~d5smlig.spl~ ~override~
			 ~d5spsha.spl~ ~override~
			 ~d5sfsha.spl~ ~override~
			 ~d5smsha.spl~ ~override~
			 ~d5spmag.spl~ ~override~
			 ~d5sfmag.spl~ ~override~
			 ~d5smmag.spl~ ~override~
			 ~d5spper.spl~ ~override~
			 ~d5sfper.spl~ ~override~
			 ~d5smper.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ END
//__________________________________________________________________________________


//clean up shere-spell .2da_________________________________________________________
//
COPY_EXISTING ~d5sphspl.2da~ ~override~
  PRETTY_PRINT_2DA
//__________________________________________________________________________________

END // end function