
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								UR-Priest
//__________________________________________________________________________________
//__________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
//ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN	//	not needed anymore, fnP_system.tpa handles it
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_clur~
	sphere_list		= ~ur_priest_spheres~
	class 			= ~cleric~
 END
// END
END
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION ur_priest_spheres 
  RET_ARRAY ur_priest_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ur_priest_spheres_array BEGIN
	Healing		 		=> x
	Necromantic		 	=> major
	Creation			=> x
	Decay			 	=> major
	Protection		 	=> major
	Combat		 		=> major
	Travelers			=> major
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 			=> minor
	Fire		 		=> minor
	Sun		 			=> major
	Shadow		 		=> major
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________




//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF AZUTH
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_azuth BEGIN

ADD_KIT ~D5_PRIEST_AZUTH~

//WEAPON PROFICIENCIES________________________________________________________________
//11     		                              T   S           F   Q             S S
//10     		      L S                     W   C           L   U             W I
//9      		      A M             B L S   O   I   W       A   A             O N
//8      		      R A             A O H   H   M   A       I   R C   S       R G
//7      		      G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6      		      E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5      		      S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4      		      W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3      		      O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2      		      R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1      		      D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_PRIEST_AZUTH      0 0 0 0 0 0 0 0~
~D5_PRIEST_AZUTH      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 		STR DEX CON INT WIS CHR
~D5_PRIEST_AZUTH         0   0   0   13  13  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 		STR DEX CON INT WIS CHR
~D5_PRIEST_AZUTH         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 		STR DEX CON INT WIS CHR
~D5_PRIEST_AZUTH         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 		STR DEX CON INT WIS CHR
~D5_PRIEST_AZUTH         0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 		LG LN LE NG TN NE CG CN CE
~D5_PRIEST_AZUTH         1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 		FT CL MA TH DR RA
~D5_PRIEST_AZUTH         0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/325_azuth/d5clazu.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_E  K_C_E  K_C_G  K_C_H  K_C_HE  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x02000000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @32501
SAY @32502
SAY @32503

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@32503)
		STR_VAR
			kit_name = D5_PRIEST_AZUTH
			clswpbon = ~0 0 3~
	END
END

//MYSTRA ABILITY FILES___________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/325_azuth/d5clazu.2da~ ~override~
COPY ~faiths_and_powers/kits/misc/d5_cllv1.spl~ ~override~
//	SAY NAME1 @6
//	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5arcm1.spl~ ~override~
	SAY NAME1 @46605
	SAY UNIDENTIFIED_DESC @46606
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arcm1.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc1b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc1c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5arcm2.spl~ ~override~
	SAY NAME1 @46607
	SAY UNIDENTIFIED_DESC @46608
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arcm2.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc2b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc2c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5arcm3.spl~ ~override~
	SAY NAME1 @46609
	SAY UNIDENTIFIED_DESC @46610
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arcm3.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc3b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc3c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5arcm4.spl~ ~override~
	SAY NAME1 @46611
	SAY UNIDENTIFIED_DESC @46612
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arcm4.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc4b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc4c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5arcm5.spl~ ~override~
	SAY NAME1 @46613
	SAY UNIDENTIFIED_DESC @46614
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arcm5.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc5b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc5c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5arcm6.spl~ ~override~
	SAY NAME1 @46615
	SAY UNIDENTIFIED_DESC @46616
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arcm6.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc6b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_bender/d5_arc6c.bam~ ~override~
//Huge thanks to DreamSlaveOne at forums.gibberlings3.net for providing the .BAMs for these abilities!
/*
ACTION_IF FILE_EXISTS_IN_GAME ~d5_wiz.d5~ THEN BEGIN
	COPY_EXISTING ~d5_inmys.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~faiths_and_powers/kits/clerics/325_azuth/mystracant.txt~
END
*/

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 0
	u_slings		 	= 1
	u_bows 				= 0
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~d5clazu~
	sphere_list		= ~azuth_spheres~
	class 			= ~cleric~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF BESHABA
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_beshaba BEGIN

ADD_KIT ~B_PRIEST_BESHABA~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_BESHABA     0 0 0 0 0 0 0 0~
~B_PRIEST_BESHABA     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_BESHABA           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_PRIEST_BESHABA         0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_PRIEST_BESHABA           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/332_beshaba/b_abes.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33201
SAY @33202
SAY @33203

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33203)
		STR_VAR
			kit_name = B_PRIEST_BESHABA
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//BESHABA ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/332_beshaba/b_abes.2da~ ~override~

COPY_EXISTING ~SPPR113.spl~ ~override/B_BES01.spl~ // Doom
  WRITE_BYTE 0x1c 4//Innate
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END //innate
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 999 opcode = 206 target = 2 timing = 0 duration = 2400 STR_VAR resource = EVAL ~B_BES01~ END

COPY_EXISTING ~B_BES01.spl~ ~override~
	PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
		   READ_SHORT 0x1c spell_type
PATCH_IF  (%spell_type% = 4) BEGIN
        READ_LONG 	0x64	ab_off			// Abilities Offset
	READ_SHORT	0x68	ab_num			// Number of Abilities
	READ_SHORT	0x6a	fx_off			// Effects Offset
	READ_SHORT	0x70	glob_fx			// Number of Global Effects
	SET	glob_add = 0

        INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 171			// opcode
	  WRITE_BYTE (fx_off + 0x2) 1			// Target (self)
	 // WRITE_BYTE (fx_off + 0x4) 1			// Level 1
	//  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// timing (Perm)
       //   WRITE_LONG (fx_off + 0xe) 10                  //duration
	  WRITE_BYTE (fx_off + 0x12) 100			// Probability 1
          WRITE_ASCII (fx_off + 0x14) ~B_BES01~               //  resource
	++glob_add

	INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 172			// opcode
	  WRITE_BYTE (fx_off + 0x2) 1			// Target (self)
	 // WRITE_BYTE (fx_off + 0x4) 1			// Level 1
	//  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// timing (Perm)
       //   WRITE_LONG (fx_off + 0xe) 10                  //duration
	  WRITE_BYTE (fx_off + 0x12) 100			// Probability 1
          WRITE_ASCII (fx_off + 0x14) ~B_BES01~               //  resource
	++glob_add
	
//	INSERT_BYTES (fx_off) 0x30			//Second effect
//	  WRITE_etc...
//	++glob_add

	glob_fx += glob_add
	WRITE_SHORT 0x70 glob_fx			// Increment Number of Global Effects
	FOR (i = 0; i < ab_num; ++i) BEGIN		// Offset Effect Index for all Abilities
	  READ_SHORT (ab_off + i * 0x28 + 0x20) fx_idx
	  WRITE_SHORT (ab_off + i * 0x28 + 0x20) (fx_idx + glob_add)
	END
END
END

COPY ~faiths_and_powers/kits/clerics/332_beshaba/b_bes02.spl~ ~override~
//bes03
COPY ~faiths_and_powers/spheres/spells/dread/b_c501b.bam~ ~override~ // Misfire
COPY ~faiths_and_powers/spheres/spells/dread/b_c501c.bam~ ~override~ // Misfire
//spl etc
COPY ~faiths_and_powers/spheres/spells/dread/b_c501.eff~ ~override~ // Misfire
  SAY 0x1c @50901     //Misfire

COPY ~faiths_and_powers/spheres/spells/dread/b_c501.spl~ ~override/b_bes03.spl~ // Misfire
        SAY NAME1 @50901
        SAY NAME2 @50901
        SAY UNIDENTIFIED_DESC @50902
	SAY DESC @50902
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  WRITE_BYTE 0x9C 4//Location
  WRITE_BYTE 0xC4 4//Location  +28
  WRITE_BYTE 0xEC 4//Location  +28
  WRITE_BYTE 0x114 4//Location  +28
  WRITE_BYTE 0x13C 4//Location  +28
  WRITE_BYTE 0x164 4//Location  +28
  WRITE_BYTE 0x18C 4//Location  +28
  WRITE_BYTE 0x1B4 4//Location  +28
  WRITE_BYTE 0x1DC 4//Location  +28
  WRITE_BYTE 0x204 4//Location  +28
  WRITE_BYTE 0x22C 4//Location  +28
  WRITE_BYTE 0x254 4//Location  +28
             LPF ALTER_EFFECT
              INT_VAR match_opcode = 321
              STR_VAR resource = EVAL ~b_bes03~
             END
COPY ~faiths_and_powers/kits/clerics/332_beshaba/b_bes04.spl~ ~override~
        SAY NAME1 @33206
        SAY NAME2 @33206
        SAY UNIDENTIFIED_DESC @33207
	SAY DESC @33207

COPY ~faiths_and_powers/spheres/spells/dread/b_c501.eff~ ~override/b_bes04.eff~ // Misfire
  SAY 0x1c @33206     //Misfortune

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_abes~
	sphere_list		= ~beshaba_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF CYRIC
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_cyric BEGIN

ADD_KIT ~B_CLERIC_CYRIC~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_CYRIC       0 0 0 0 0 0 0 0~
~B_CLERIC_CYRIC       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_CYRIC           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_CYRIC           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/225_cyric/b_ccyr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22501
SAY @22502
SAY @22503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22503)
		STR_VAR
			kit_name = B_CLERIC_CYRIC
			clswpbon = ~0 0 3~
	END
END

//CYRIC ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/225_cyric/b_ccyr.2da~ ~override~
//+1 vs. illusions
COPY ~faiths_and_powers/kits/clerics/225_cyric/B_CYR02.spl~ ~override~
COPY_EXISTING ~SPWI401.spl~ ~override/B_CYR03.spl~ // Confusion
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

COPY_EXISTING ~SPWI509.spl~ ~override/B_CYR04.spl~ // feeblemind
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

//protection from fear  (using the tempus spl.  It's basically the same...)
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~25818~ END     //text block
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~17427~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~14007~ END     //text block
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~35484~ END     //text block
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
  LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 2
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ccyr~
	sphere_list		= ~cyric_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc_ct~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF DENEIR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_deneir BEGIN

ADD_KIT ~B_PRIEST_DENEIR~

//WEAPON PROFICIENCIES________________________________________________________________
//11             	                               T   S           F   Q             S S
//10           			L S                     W   C           L   U             W I
//9            			A M             B L S   O   I   W       A   A             O N
//8            			R A             A O H   H   M   A       I   R C   S       R G
//7            			G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            			E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            			S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            			W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            			O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            			R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            			D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_DENEIR	  	0 0 0 0 0 0 0 0~
~B_PRIEST_DENEIR      	0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_DENEIR  1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_DENEIR  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/315_deneir/b_aden.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31501
SAY @31502
SAY @31503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31503)
		STR_VAR
			kit_name = B_PRIEST_DENEIR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

// ABILITY FILES_______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/315_deneir/b_aden.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/315_deneir/b_den01.spl~ ~override~  //immunities

COPY_EXISTING ~SPPR205.spl~ ~override/b_den02.spl~ // detect traps
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x84 1//Casting time
  WRITE_BYTE 0x74 4//Location

COPY_EXISTING ~SPPR304.spl~ ~override/b_den03.spl~ // glyph of warding
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
 LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

COPY_EXISTING ~SPPR303.spl~ ~override/b_den04.spl~ // dispel magic
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
 LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 			= 0
	u_darts 			= 0
	u_slings 			= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_aden~
	sphere_list		= ~deneir_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF HELM
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_helm BEGIN

ADD_KIT ~B_CLERIC_HELM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                         T   S           F   Q             S S
//10                 L S                     W   C           L   U             W I
//9                  A M             B L S   O   I   W       A   A             O N
//8                  R A             A O H   H   M   A       I   R C   S       R G
//7                  G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                  E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_HELM       0 0 0 0 0 0 0 0~
~B_CLERIC_HELM       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           12   0   0   0  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_HELM           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                       LG LN LE NG TN NE CG CN CE
~B_CLERIC_HELM           1  1  0  0  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                       FT CL MA TH DR RA
~B_CLERIC_HELM           1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/208_helm/b_chel.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20801
SAY @20802
SAY @20803

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20803)
		STR_VAR
			kit_name = B_CLERIC_HELM
			clswpbon = ~0 0 3~
	END
END

//WATCHER ABILITY FILES____________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/clerics/208_helm/b_chel.2da~ ~override~

//COPY ~faiths_and_powers/kits/clerics/208_helm/b_hsp01.spl~     ~override~  // Seeking Sword
//  SAY NAME1 @98518
//  SAY UNIDENTIFIED_DESC @98519
COPY ~faiths_and_powers/kits/clerics/208_helm/SW1HSEEK.itm~     ~override~  // Seeking Sword
//For the champions, but that's fine
COPY ~faiths_and_powers/kits/clerics/208_helm/b_hab01.spl~     ~override~  // AC/Save Bonus/wp longsword

COPY ~faiths_and_powers/kits/clerics/208_helm/b_hsp02.spl~     ~override~  // Helm's Eye
  SAY NAME1 @20806
  SAY UNIDENTIFIED_DESC @20807

//COPY ~faiths_and_powers/kits/clerics/208_helm/b_hsp03.spl~     ~override~  // Farsight
//  SAY NAME1 @98522
//  SAY UNIDENTIFIED_DESC @98523

//COPY ~faiths_and_powers/kits/clerics/208_helm/b_hab02.spl~     ~override~  // Glyph of warding
//  SAY NAME1 @98532
//  SAY UNIDENTIFIED_DESC @98533

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 20) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 2
	u_2hand_swords 		= 1
	u_halberds 			= 1
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_chel~
	sphere_list		= ~helm_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF ILMATER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_ilmater BEGIN

ADD_KIT ~B_PRIEST_ILMATER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           			L S                     W   C           L   U             W I
//9            			A M             B L S   O   I   W       A   A             O N
//8            			R A             A O H   H   M   A       I   R C   S       R G
//7            			G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            			E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            			S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            			W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            			O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            			R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            			D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_ILMATER  		0 0 0 0 0 0 0 0~
~B_PRIEST_ILMATER   	0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_ILMATER  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_ILMATER  1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_ILMATER  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/314_ilmater/b_ailm.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31401
SAY @31402
SAY @31403

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31403)
		STR_VAR
			kit_name = B_PRIEST_ILMATER
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//ILMATER ABILITY FILES_______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/314_ilmater/b_ailm.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/314_ilmater/b_ilm01.spl~ ~override~  // Remove Fear
	SAY NAME1 @31411
	SAY NAME2 @31411
	SAY UNIDENTIFIED_DESC @31412  //
	SAY IDENTIFIED_DESC @31412  //
COPY ~faiths_and_powers/kits/clerics/314_ilmater/b_ilm02.spl~ ~override~  // +4 vs death
COPY ~faiths_and_powers/kits/clerics/314_ilmater/b_ilm06.spl~ ~override~  // fire/cold resist
COPY ~faiths_and_powers/kits/clerics/314_ilmater/b_ilm03.spl~ ~override~  // Endurance of Ilmater
	SAY NAME1 @31413
	SAY NAME2 @31413
	SAY UNIDENTIFIED_DESC @31414  //
	SAY IDENTIFIED_DESC @31414  //

//COPY_EXISTING ~spwi102.spl~ ~override/b_ilm04.spl~          // Armor
//	WRITE_SHORT 0x1c 2
//COPY_EXISTING ~spwi317.spl~ ~override/b_ilm05.spl~          // Ghost Armor
//	WRITE_SHORT 0x1c 2

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 			= 0
	u_darts 			= 1
	u_slings 			= 1
	u_bows 				= 0
	u_crossbows 		= 1  
  STR_VAR
    clab_name 		= ~b_ailm~
	sphere_list		= ~ilmater_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF KELEMVOR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_kelemvor BEGIN

ADD_KIT ~B_CLERIC_KELEMVOR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                 	                        T   S           F   Q             S S
//10                 	L S                     W   C           L   U             W I
//9                  	A M             B L S   O   I   W       A   A             O N
//8                  	R A             A O H   H   M   A       I   R C   S       R G
//7                  	G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                  	E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                  	S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                  	W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                  	O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                  	R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                  	D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_KELEMVOR      0 0 0 0 0 0 0 0~
~B_CLERIC_KELEMVOR      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR      12   0   0   0  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                      STR DEX CON INT WIS CHR
~B_CLERIC_KELEMVOR       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                       LG LN LE NG TN NE CG CN CE
~B_CLERIC_KELEMVOR       1  1  0  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                       FT CL MA TH DR RA
~B_CLERIC_KELEMVOR       1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/209_kelemvor/b_ckel.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20901
SAY @20902
SAY @20903

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20903)
		STR_VAR
			kit_name = B_CLERIC_KELEMVOR
			clswpbon = ~0 0 3~
	END
END

//KIT ABILITY FILES___________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/209_kelemvor/b_ckel.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/201_lathander/b_turn.spl~     ~override~  // Turn Undead +4 Levels
COPY ~faiths_and_powers/kits/clerics/314_ilmater/b_ilm02.spl~ ~override~  // +4 vs death
//CHECK COMPATIBILITY WITH IWDEE AND SR
COPY_EXISTING ~SPPR409.spl~ ~override/b_kel01.spl~ // Works?
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 169
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 267
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 101
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 328
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 282
      timing = 9
      resist_dispel = 0
  END
//CHECK COMPATIBILITY WITH IWDEE AND SR
COPY_EXISTING ~SPPR413.spl~ ~override/b_kel02.spl~ // Works?
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 267
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 169
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 101
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142
      timing = 9
      resist_dispel = 0
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 282
      timing = 9
      resist_dispel = 0
  END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ckel~
	sphere_list		= ~kelemvor_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF LATHANDER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_lathander BEGIN

ADD_KIT ~B_CLERIC_LATHANDER~

//WEAPON PROFICIENCIES________________________________________________________________
//11              	                     		T   S           F   Q             S S
//10           			L S                     W   C           L   U             W I
//9            			A M             B L S   O   I   W       A   A             O N
//8            			R A             A O H   H   M   A       I   R C   S       R G
//7            			G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            			E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            			S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            			W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            			O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            			R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            			D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_LATHANDER     0 0 0 0 0 0 0 0~
~B_CLERIC_LATHANDER     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LATHANDER  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_LATHANDER  1  1  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_LATHANDER  1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/201_lathander/b_clat.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20101 //lower
SAY @20102 //Mixed
SAY @20103 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20103)
		STR_VAR
			kit_name = B_CLERIC_LATHANDER
			clswpbon = ~0 0 3~
	END
END

//LATHANDER ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/201_lathander/b_clat.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/201_lathander/b_turn.spl~     ~override~  // Turn Undead +4 Levels
//  SAY NAME1 @#####
//  SAY UNIDENTIFIED_DESC @#####
//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo101.spl~     ~override~  // Infravision Orison
//  SAY NAME1 @98504 //Infravision
//  SAY UNIDENTIFIED_DESC @98505   //Infravision

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_lo102.spl~     ~override~  // Fire bolt Orison
//  SAY NAME1 @98506 //Fire bolt
//  SAY UNIDENTIFIED_DESC @98507   //Fire bolt desc

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla02.spl~     ~override~  // Boon of Lathander
//  SAY UNIDENTIFIED_DESC @98534//

//COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla03.spl~     ~override~  // Hold Undead
//  SAY NAME1 @20107
//  SAY UNIDENTIFIED_DESC @20104//

COPY ~faiths_and_powers/kits/clerics/201_lathander/b_cla04.spl~     ~override~  // False Dawn
  SAY NAME1 @20108
  SAY UNIDENTIFIED_DESC @20105

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 21) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
   INT_VAR
	u_leather_armor 	= 1		// for armor, enter '1' or 0' to indicate usability
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 1 	// for weapons, enter 1 to 5 for the allowed proficiency level
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
   STR_VAR
    clab_name 		= ~b_clat~
	sphere_list		= ~lathander_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc_cm~
  END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF LEIRA
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_leira BEGIN

ADD_KIT ~D5_CL_LEIRA~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11        	                           T   S           F   Q             S S
//10        	   L S                     W   C           L   U             W I
//9         	   A M             B L S   O   I   W       A   A             O N
//8         	   R A             A O H   H   M   A       I   R C   S       R G
//7         	   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         	   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         	   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         	   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         	   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2         	   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1         	   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CL_LEIRA	   0 0 0 0 0 0 0 0~
~D5_CL_LEIRA	   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_LEIRA       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CL_LEIRA       0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CL_LEIRA       0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/212_leira/d5clei.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21201
SAY @21202
SAY @21203

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21204)
		STR_VAR
			kit_name = D5_CL_LEIRA
			clswpbon = ~0 0 3~
	END
END

//MISTWALKER ABILITY FILES____________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/clerics/212_leira/d5clei.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/kits/clerics/212_leira/d5_lei1.spl~ ~override~
	SAY NAME1 @21211
	SAY UNIDENTIFIED_DESC @21212

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d5clei~
	sphere_list		= ~leira_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF LOVIATAR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_loviatar BEGIN

ADD_KIT ~B_CLERIC_LOVIATAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11         	                          		T   S           F   Q             S S
//10         	  		L S                     W   C           L   U             W I
//9          	  		A M             B L S   O   I   W       A   A             O N
//8          	  		R A             A O H   H   M   A       I   R C   S       R G
//7          	  		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6          	  		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5          	  		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4          	  		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3          	  		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2          	  		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1          	  		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_LOVIATAR      0 0 0 0 0 0 0 0~
~B_CLERIC_LOVIATAR      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   11  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_LOVIATAR  0  1  1  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_LOVIATAR  1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21901 //lower
SAY @21902 //Mixed
SAY @21903 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21903)
		STR_VAR
			kit_name = B_CLERIC_LOVIATAR
			clswpbon = ~0 0 3~
	END
END

//LOVIATAR ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.spl~     ~override~  // Pain Touch
	SAY NAME1 @21911
	SAY NAME2 @21911
	SAY UNIDENTIFIED_DESC @21912  //
	SAY IDENTIFIED_DESC @21912  //
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.itm~     ~override~  // Pain Touch
  SAY NAME1 @21911
  SAY NAME2 @21911
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov02.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov03.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov04.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov05.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov06.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov02.spl~     ~override~  // Pain Touch
  SAY NAME1 @6
  SAY NAME2 @6
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov03.spl~     ~override~  // Loviatar's Caress
	SAY NAME1 @21914
	SAY NAME2 @21914
	SAY UNIDENTIFIED_DESC @21915  //
	SAY IDENTIFIED_DESC @21915  //
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov04.spl~     ~override~  // Suppress Pain Touch
  SAY NAME1 @21916
  SAY NAME2 @21916

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_clov~
	sphere_list		= ~loviatar_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc_ct_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF MOANDER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_moander BEGIN

ADD_KIT ~B_CLERIC_MOANDER~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_MOANDER     0 0 0 0 0 0 0 0~
~B_CLERIC_MOANDER     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_MOANDER           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_MOANDER         0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_MOANDER           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/331_moander/b_cmoa.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33101
SAY @33102
SAY @33103

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33103)
		STR_VAR
			kit_name = B_CLERIC_MOANDER
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//MOANDER ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/331_moander/b_cmoa.2da~ ~override~

COPY_EXISTING ~sppr105.spl~ ~override/B_moa1.spl~ // innate
  WRITE_SHORT 0x1c 4//Innate
  WRITE_SHORT 0x74 4//Innate
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~B_moa1~
  END
COPY ~faiths_and_powers/kits/clerics/331_moander/b_moa2.spl~ ~override~    //Assassin vines
        SAY NAME1 @51404
        SAY NAME2 @51404
        SAY UNIDENTIFIED_DESC @51405
	SAY DESC @51405

COPY ~faiths_and_powers/kits/clerics/331_moander/b_moa3.spl~ ~override~    //Immunities

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 1
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~b_cmoa~
	sphere_list		= ~moander_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc_ct~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF SHAR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_shar BEGIN

ADD_KIT ~D5_AC_SHAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_SHAR      0 0 0 0 0 0 0 0~
~D5_AC_SHAR      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_SHAR        0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_SHAR        0  1  1  0  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_SHAR        0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/330_shar/d5asha.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @33001
SAY @33002
SAY @33003

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@33004)
		STR_VAR
			kit_name = D5_AC_SHAR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//DARKCLOAK ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/330_shar/d5asha.2da~ ~override~
COPY_EXISTING ~spwi220.spl~ ~override/d5shasl.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi201.spl~ ~override/d5shabr.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi518.spl~ ~override/d5shaph.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi815.spl~ ~override/d5shabl.spl~
	LPM spell_to_innate

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		=1
  STR_VAR
    clab_name 		= ~d5asha~
	sphere_list		= ~shar_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF SUNE
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_sune BEGIN

ADD_KIT ~B_PRIEST_SUNE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_SUNE  	0 0 0 0 0 0 0 0~
~B_PRIEST_SUNE      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  	0   0   0   0   12  15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  	0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  	0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_SUNE  	0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_SUNE     0  0  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_SUNE  	0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/316_sune/b_asun.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_HL~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31601
SAY @31602
SAY @31603

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31603)
		STR_VAR
			kit_name = B_PRIEST_SUNE
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END

//SUNE ABILITY FILES__________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/316_sune/b_asun.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/316_sune/b_sun01.spl~ ~override~  // potent charm
//	SAY NAME1 @31411
//	SAY NAME2 @31411
	SAY UNIDENTIFIED_DESC @31606 //
	SAY IDENTIFIED_DESC @31606  //
COPY ~faiths_and_powers/kits/clerics/316_sune/b_sun02.spl~ ~override~  // spell save
//Make not dependant on iWDEE...
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
COPY_EXISTING ~SPWI429.spl~ ~override/b_sun03.spl~ // Emotion: hope
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321
      STR_VAR resource = EVAL ~b_sun03~
     END
END

COPY ~faiths_and_powers/kits/clerics/316_sune/b_sun04.spl~ ~override~  // cha bonus

/*
COPY_EXISTING ~SPWI104.spl~ ~override/b_sun01.spl~ // Charm person
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~b_sun01~
     END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 5
      savebonus = 0
     END
*/

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1	
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 1
	u_slings		 	= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_asun~
	sphere_list		= ~sune_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF TALOS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_talos BEGIN

ADD_KIT ~B_CLERIC_TALOS~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TALOS       0 0 0 0 0 0 0 0~
~B_CLERIC_TALOS       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_TALOS           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_TALOS           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_TALOS           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/224_talos/b_ctal.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22401
SAY @22402
SAY @22403

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22403)
		STR_VAR
			kit_name = B_CLERIC_TALOS
			clswpbon = ~0 0 3~
	END
END

//TALOS ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/224_talos/b_ctal.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal01.spl~     ~override~  //  Electricity resist
COPY ~faiths_and_powers/kits/clerics/224_talos/b_Tal10.spl~     ~override~  //  Lightning Bolt
	SAY UNIDENTIFIED_DESC @22406  //
	SAY IDENTIFIED_DESC @22406  //

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_clerics.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_C_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_C_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		SET rows_removed = 0
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 19) BEGIN
			REMOVE_2DA_ROW (row - rows_removed) cols
//			SET rows_removed += 1
		  END
		END
	  BUT_ONLY
	END
  END
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 1
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ctal~
	sphere_list		= ~talos_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc_cm~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							BATTLEGUARD OF TEMPUS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_tempus BEGIN

ADD_KIT ~B_CLERIC_TEMPUS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TEMPUS    0 0 0 0 0 0 0 0~
~B_CLERIC_TEMPUS    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TEMPUS    9   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_TEMPUS    1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_TEMPUS    1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21001 //lower
SAY @21002 //Mixed
SAY @21003 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21003)
		STR_VAR
			kit_name = B_CLERIC_TEMPUS
			clswpbon = ~0 0 3~
	END
END

//TEMPUS ABILITY FILES______________________________________________________________
// Incite Rage
ACTION_IF FILE_EXISTS_IN_GAME ~spcl321.spl~ BEGIN
COPY_EXISTING ~spcl321.spl~ ~override/B_TEM03.spl~ // Incite Rage
	SAY NAME1 @21004
	SAY NAME2 @21004
	SAY UNIDENTIFIED_DESC @21006  //
	SAY IDENTIFIED_DESC @21006  //
  WRITE_BYTE 0x7e 1//Target 1 cre
END

COPY ~faiths_and_powers/kits/clerics/210_tempus/b_tem05.spl~ ~override~    //+1 damage

COPY ~faiths_and_powers/kits/clerics/210_tempus/b_ctem.2da~ ~override~

//REPLACE VANILLA KIT_________________________________________________________________
//... should do this for IWD
ACTION_IF FILE_EXISTS_IN_GAME ~d5_menu.d5~ BEGIN
	COPY_EXISTING ~kitlist.2da~ ~override~
		COUNT_2DA_ROWS ~7~ "kit_row"
	OUTER_SET kit_row -= 2
	COPY_EXISTING ~K_C_D.2da~ ~override~
			~K_C_E.2da~ ~override~
			~K_C_G.2da~ ~override~
			~K_C_H.2da~ ~override~
			~K_C_HE.2da~ ~override~
			~K_C_HL.2da~ ~override~
			~K_C_HO.2da~ ~override~
		REPLACE_TEXTUALLY ~21~ ~%kit_row%~
	BUT_ONLY
END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 2
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 1
	u_katanas 			= 1
	u_bastard_swords 	= 1
	u_2hand_swords 		= 2
	u_halberds 			= 1
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ctem~
	sphere_list		= ~tempus_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF TEMPUS
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION priest_tempus BEGIN

ADD_KIT ~B_PRIEST_TEMPUS~

//WEAPON PROFICIENCIES________________________________________________________________
//11             	                               T   S           F   Q             S S
//10           			L S                     W   C           L   U             W I
//9            			A M             B L S   O   I   W       A   A             O N
//8            			R A             A O H   H   M   A       I   R C   S       R G
//7            			G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            			E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            			S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            			W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            			O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            			R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            			D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_TEMPUS	  	0 0 0 0 0 0 0 0~
~B_PRIEST_TEMPUS        0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_TEMPUS  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_TEMPUS   1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_TEMPUS   1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/322_tempus/b_atem.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @32201
SAY @32202
SAY @32203

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@32203)
		STR_VAR
			kit_name = B_PRIEST_TEMPUS
			clswpbon = ~0 0 3~
	END
END

//TEMPUS ABILITY FILES_______________________________________________________________
//
COPY_EXISTING ~SPPR203.spl~ ~override/B_TEM01.spl~ // Chant
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x84 1//Casting time
  WRITE_BYTE 0x74 4//Location
  SAY UNIDENTIFIED_DESC @32206     //Should figure out how to edit the spell level for compatibility purposes


COPY ~faiths_and_powers/kits/clerics/322_tempus/b_tem02.spl~ ~override~  // WP Axe

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 2
	u_maces 	 		= 2
	u_flails 			= 0
	u_axes 				= 2
	u_daggers 			= 0
	u_short_swords		= 2
	u_long_swords		= 2
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 2
	u_darts 			= 0
	u_slings			= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_atem~
	sphere_list		= ~tempus_spheres~
	class 			= ~cleric~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF TORM
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_torm BEGIN

ADD_KIT ~B_CLERIC_TORM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_TORM      0 0 0 0 0 0 0 0~
~B_CLERIC_TORM      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_TORM  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_TORM      1  1  0  1  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_TORM  1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/202_torm/b_ctor.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20201 //lower
SAY @20202 //Mixed
SAY @20203 //Help

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20103)
		STR_VAR
			kit_name = B_CLERIC_TORM
			clswpbon = ~0 0 3~
	END
END

//TORM ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/202_torm/b_ctor.2da~ ~override~
COPY_EXISTING ~SPPR102.spl~ ~override/b_tor01.spl~ // dispel magic
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x74 4//Location
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~b_tor01~
  END

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 1
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 1
	u_2hand_swords 		= 0
	u_halberds 			= 1
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_ctor~
	sphere_list		= ~torm_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc~
 END

END

//____________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF TYMORA
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_tymora BEGIN

ADD_KIT ~D5_CL_TYMORA~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                     T   S           F   Q             S S
//10             L S                     W   C           L   U             W I
//9              A M             B L S   O   I   W       A   A             O N
//8              R A             A O H   H   M   A       I   R C   S       R G
//7              G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6              E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5              S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4              W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3              O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2              R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1              D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CL_TYMORA    0 0 0 0 0 0 0 0~
~D5_CL_TYMORA    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   12  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_CL_TYMORA      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_CL_TYMORA      0  0  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_CL_TYMORA      1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/205_tymora/d5ctym.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E  K_C_H  K_C_HE  K_C_G  K_C_D  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20501
SAY @20502
SAY @20503

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20504)
		STR_VAR
			kit_name = D5_CL_TYMORA
			clswpbon = ~0 0 3~
	END
END

//TYMORA ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5ctym.2da~ ~override~
COPY ~faiths_and_powers/kits/misc/d5luckp.spl~ ~override~
	SAY NAME1 @20511
	SAY UNIDENTIFIED_DESC @20511
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5_tym1.spl~ ~override~
	SAY NAME1 @20513
	SAY UNIDENTIFIED_DESC @20514
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5_tym1a.spl~ ~override~
	SAY NAME1 @20513
COPY ~faiths_and_powers/kits/clerics/205_tymora/d5_tym1b.spl~ ~override~
	SAY NAME1 @20513

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d5ctym~
	sphere_list		= ~tymora_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF UMBERLEE
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_umberlee BEGIN

ADD_KIT ~B_CLERIC_UMBERLEE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_UMBERLEE    0 0 0 0 0 0 0 0~
~B_CLERIC_UMBERLEE    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE        0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                		 STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                		 STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                		 STR DEX CON INT WIS CHR
~B_CLERIC_UMBERLEE           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_UMBERLEE           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_UMBERLEE           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/226_umberlee/b_umb.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22601
SAY @22602
SAY @22603

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22603)
		STR_VAR
			kit_name = B_CLERIC_UMBERLEE
			clswpbon = ~0 0 3~
	END
END

//UMBERLEE ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/226_umberlee/b_umb.2da~ ~override~

//Smashing Wave______________________________________________________________________//
//Install it if it isn't already installed
ACTION_IF (GAME_IS ~bgee bg2ee eet~) AND (NOT FILE_EXISTS_IN_GAME ~b_IWD.itm~) THEN BEGIN   //
//Go over this spell head to toe first...

 END//end smashing wave

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_umb~
	sphere_list		= ~umberlee_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc_cm~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF CLANGEDDIN
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_clangeddin BEGIN

ADD_KIT ~D5_CLANGEDDIN~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                         T   S           F   Q             S S
//10                 L S                     W   C           L   U             W I
//9                  A M             B L S   O   I   W       A   A             O N
//8                  R A             A O H   H   M   A       I   R C   S       R G
//7                  G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                  E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CLANGEDDIN       0 0 0 0 0 0 0 0~
~D5_CLANGEDDIN       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 1 1 1 0 0 0 0 1 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~D5_CLANGEDDIN       9   0   12   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~D5_CLANGEDDIN       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~D5_CLANGEDDIN       15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~D5_CLANGEDDIN       15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~D5_CLANGEDDIN       1  1  0  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~D5_CLANGEDDIN       0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/471_clangeddin/d5clcla.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_D~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @47101
SAY @47102
SAY @47103

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@47103)
		STR_VAR
			kit_name = D5_CLANGEDDIN
			clswpbon = ~1 0 3~
	END
END

//ALAGHOR ABILITY FILES_______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5clcla.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5alag1.spl~ ~override~
	SAY NAME1 @47113
	SAY UNIDENTIFIED_DESC @47114
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5alag1~ END
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5alag1.bam~ ~override~
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5_alag1.itm~ ~override~
	SAY NAME1 @47113
	SAY NAME2 @47113
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5_alag2.itm~ ~override~
	SAY NAME1 @47113
	SAY NAME2 @47113
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5_alag3.itm~ ~override~
	SAY NAME1 @47113
	SAY NAME2 @47113
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5alag2.spl~ ~override~
	SAY NAME1 @47111
	SAY UNIDENTIFIED_DESC @47112
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5alag2~ END
COPY ~faiths_and_powers/kits/clerics/471_clangeddin/d5alag2.bam~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 1
	u_hammers	 		= 2
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 2
	u_daggers 			= 0
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 0
	u_darts 			= 0
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~d5clcla~
	sphere_list		= ~clangeddin_spheres~
	class 			= ~cleric~
	multiclass 		= ~fc~
 END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PRIEST OF BAERVAN
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_baervan BEGIN

ADD_KIT ~D5_AC_BAERVAN~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11            	                         T   S           F   Q             S S
//10            	 L S                     W   C           L   U             W I
//9             	 A M             B L S   O   I   W       A   A             O N
//8             	 R A             A O H   H   M   A       I   R C   S       R G
//7             	 G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             	 E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             	 S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             	 W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             	 O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             	 R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             	 D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_BAERVAN  	 0 0 0 0 0 0 0 0~
~D5_AC_BAERVAN  	 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_BAERVAN      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_BAERVAN      1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_BAERVAN      0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/342_baervan/d5baerv.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_G~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @34201
SAY @34202
SAY @34203

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@34204)
		STR_VAR
			kit_name = D5_AC_BAERVAN
			clswpbon = ~0 0 3~
	END
END

//BAERVAN ABILITY FILES_______________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/clerics/342_baervan/d5baerv.2da~ ~override~

//DEFINE SPHERE ACCESS________________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 0
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 0
  STR_VAR
    clab_name 		= ~d5baerv~
	sphere_list		= ~baervan_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END

//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								CLERIC OF BARAVAR
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION cleric_baravar BEGIN

ADD_KIT ~B_CLERIC_BARAVAR~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11       		                            T   S           F   Q             S S
//10       		    L S                     W   C           L   U             W I
//9        		    A M             B L S   O   I   W       A   A             O N
//8        		    R A             A O H   H   M   A       I   R C   S       R G
//7        		    G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6        		    E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5        		    S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4        		    W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3        		    O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2        		    R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1        		    D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_BARAVAR   0 0 0 0 0 0 0 0~
~B_CLERIC_BARAVAR   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//              	   STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   12  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//              	   STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//              	   STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//              	   STR DEX CON INT WIS CHR
~B_CLERIC_BARAVAR       0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//              	   LG LN LE NG TN NE CG CN CE
~B_CLERIC_BARAVAR       0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//              	   FT CL MA TH DR RA
~B_CLERIC_BARAVAR       0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/213_baravar/b_bara.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_G~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21301
SAY @21302
SAY @21303

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21303)
		STR_VAR
			kit_name = B_CLERIC_BARAVAR
			clswpbon = ~0 0 3~
	END
END

//KIT ABILITY FILES__________________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/kits/clerics/213_baravar/b_bara.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/kits/clerics/212_leira/d5_lei1.spl~ ~override/b_bar01~ //it's the same ability with a different name, so...
	SAY NAME1 @21311
	SAY UNIDENTIFIED_DESC @21312

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 0
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 0
	u_crossbows 		= 1
  STR_VAR
    clab_name 		= ~b_bara~
	sphere_list		= ~baravar_spheres~
	class 			= ~cleric~
	multiclass 		= ~ct_cm~
 END

END

//__________________________________________________________________________________
