
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								HLA SYSTEM
//__________________________________________________________________________________
//__________________________________________________________________________________


//copy HLAs and related files________________________________________________________
//
//
//general____________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/general/d5phla1.spl~ ~override~ // purity of body
    SAY NAME1 @60011
    SAY UNIDENTIFIED_DESC @60012 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)

COPY ~faiths_and_powers/spheres/hlas/general/d5phla2.spl~ ~override~ // negative plane protection
    SAY NAME1 @60021
    SAY UNIDENTIFIED_DESC @60022 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)

COPY ~faiths_and_powers/spheres/hlas/general/d5phla3.spl~ ~override~ // casting speed bonus
    SAY NAME1 @60031
    SAY UNIDENTIFIED_DESC @60032 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)

COPY ~faiths_and_powers/spheres/hlas/general/d5phla4.spl~ ~override~ // free action
    SAY NAME1 @60041
    SAY UNIDENTIFIED_DESC @60042 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)

COPY ~faiths_and_powers/spheres/hlas/general/d5_enli.spl~ ~override~ // enlightenment
    SAY NAME1 @60051
    SAY UNIDENTIFIED_DESC @60052 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)

ACTION_IF ENGINE_IS ~soa tob bgt~ BEGIN
  COPY ~faiths_and_powers/spheres/hlas/general/d5phla5.spl~ ~override~ // courage + bless
    SAY NAME1 @60061
    SAY UNIDENTIFIED_DESC @60062 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)
END
ACTION_IF ENGINE_IS ~bg2ee~ BEGIN
  COPY ~faiths_and_powers/spheres/hlas/general/d5phla5_ee.spl~ ~override/d5phla5.spl~ // courage + aoe bless
    SAY NAME1 @60061
    SAY UNIDENTIFIED_DESC @60063 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)
  COPY ~faiths_and_powers/spheres/hlas/general/d5chanta.eff~ ~override~
  COPY ~faiths_and_powers/spheres/hlas/general/d5chantb.eff~ ~override~
  COPY ~faiths_and_powers/spheres/hlas/general/d5chanta.spl~ ~override~
  COPY ~faiths_and_powers/spheres/hlas/general/d5chantb.spl~ ~override~
//	SAY NAME1 @60064
END

COPY ~faiths_and_powers/spheres/hlas/general/tg#enli.spl~ ~override~ // spiritual attunement
    SAY NAME1 @60071
    SAY UNIDENTIFIED_DESC @60072 // ***
    WRITE_SHORT 0x1c 4
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/general/li#enli.vvc~ ~override~

COPY ~faiths_and_powers/spheres/hlas/general/tg#spir.spl~ ~override~ // ancestral spirit
    SAY NAME1 @60081
    SAY UNIDENTIFIED_DESC @60082 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/general/tg#spir.cre~ ~override~
    SAY NAME1 @60081
    SAY NAME2 @60081
COPY ~faiths_and_powers/spheres/hlas/general/tg#spir.eff~ ~override~
COPY ~faiths_and_powers/spheres/hlas/general/tg#spir.itm~ ~override~
COPY ~faiths_and_powers/spheres/hlas/general/tg#spirb.bam~ ~override~
COPY ~faiths_and_powers/spheres/hlas/general/tg#spia.spl~ ~override~
COPY ~faiths_and_powers/spheres/hlas/general/tg#spi2.itm~ ~override~
COMPILE ~faiths_and_powers/spheres/hlas/general/tb#spir.baf~ 

//life_______________________________________________________________________________
COPY_EXISTING ~sppr729.spl~ ~override~ // mass raise dead
//	LPM spell_to_innate
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

COPY ~faiths_and_powers/spheres/hlas/life/b_ph05.spl~ ~override~ // panacea
  SAY NAME1 @60111
  SAY UNIDENTIFIED_DESC @60112
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

//death______________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~ENGINEST.2DA~ BEGIN
//2.0 only
 COPY ~faiths_and_powers/spheres/hlas/death/B_ph02.spl~ ~override~ // Extract Soul
	SAY NAME1 @60201
	SAY UNIDENTIFIED_DESC @60202
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
 COPY ~faiths_and_powers/spheres/hlas/death/B_ph02a.spl~ ~override~ // Spl
 COPY ~faiths_and_powers/spheres/hlas/death/b_ani01.eff~ ~override~ // eff
 COPY ~faiths_and_powers/spheres/hlas/death/b_ani01.2da~ ~override~ // 2da
 COPY ~faiths_and_powers/spheres/hlas/death/B_ph02.eff~ ~override~   //eff
	SAY 0x1c @60203     //Con Drain
 COPY ~faiths_and_powers/spheres/hlas/death/b_gho1.itm~ ~override~ // itm
 COPY ~faiths_and_powers/spheres/hlas/death/b_gho2.itm~ ~override~ // itm
 COPY ~faiths_and_powers/spheres/hlas/death/b_skmon.cre~ ~override~ // cre
END //end 2.0 only

COPY ~faiths_and_powers/spheres/hlas/death/B_ph07.spl~ ~override~ // Undead Plague
	SAY NAME1 @60211
	SAY UNIDENTIFIED_DESC @60212
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
COPY ~faiths_and_powers/spheres/hlas/death/B_ph07.eff~ ~override~ // Spl
COPY ~faiths_and_powers/spheres/hlas/death/B_ph07.cre~ ~override~ // Spl
COPY ~faiths_and_powers/spheres/hlas/death/B_ph07.2da~ ~override~ // Spl

//benediction________________________________________________________________________
COPY_EXISTING ~sppr726.spl~ ~override~ // summon deva
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

COPY_EXISTING ~spwi905.spl~ ~override/d5hben1.spl~ // gate
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

COPY_EXISTING ~sppr722.spl~ ~override~ // storm of vengeance
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

//destruction________________________________________________________________________
COPY_EXISTING ~sppr728.spl~ ~override~ // implosion
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

//protection_________________________________________________________________________
COPY_EXISTING ~spwi907.spl~ ~override/d5hpro1.spl~ // absolute immunity
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

ACTION_IF FILE_EXISTS_IN_GAME ~ENGINEST.2DA~ BEGIN
//2.0 only
 COPY ~faiths_and_powers/spheres/hlas/protection/b_ph06.spl~ ~override~ // divine aura
	SAY NAME1 @60511
	SAY UNIDENTIFIED_DESC @60512
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
 COPY ~faiths_and_powers/spheres/hlas/protection/b_ph06a.spl~ ~override~ // sec spell
END //End 2.0 only

//war________________________________________________________________________________
COPY_EXISTING ~sppr725.spl~ ~override~ // globe of blades
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

//knowledge__________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/knowledge/tg#fors.spl~ ~override~ // Refinements foresight
    SAY NAME1 @60701
    SAY UNIDENTIFIED_DESC @60702 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/knowledge/tg#forsb.bam~ ~override~
COPY ~faiths_and_powers/spheres/hlas/knowledge/tg#forsc.bam~ ~override~

COPY_EXISTING ~spwi908.spl~ ~override/d5hkno1.spl~ // chain contingency
	LPM spell_to_innate
	LPF ALTER_EFFECT INT_VAR match_opcode = 234 parameter1 = 7 END

//deception__________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/deception/li#micl.spl~ ~override~ // Refinements mirrored clones
    SAY NAME1 @60801
    SAY UNIDENTIFIED_DESC @60802 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/deception/li#miclb.bam~ ~override~
COPY ~faiths_and_powers/spheres/hlas/deception/li#miclc.bam~ ~override~
COPY ~faiths_and_powers/spheres/hlas/deception/li#micl.vvc~ ~override~

//thought____________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~ENGINEST.2DA~ BEGIN
//2.0 only
 COPY ~faiths_and_powers/spheres/hlas/thought/B_ph10.spl~ ~override~ // Divine Presence
	SAY NAME1 @60901
	SAY UNIDENTIFIED_DESC @60902
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
 COPY ~faiths_and_powers/spheres/hlas/thought/B_ph10a.spl~ ~override~ // Spl
 COPY ~faiths_and_powers/spheres/hlas/thought/B_ph10a.eff~ ~override~ // Spl
	SAY 0x1c @60903     //Overwhelmed by divine presence
END //End 2.0 only

//dread______________________________________________________________________________
COPY_EXISTING ~spwi913.spl~ ~override/d5hdre1.spl~ // wail of the banshee
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

//vigor______________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~ENGINEST.2DA~ BEGIN
//2.0 only
 COPY ~faiths_and_powers/spheres/hlas/vigor/B_ph11.spl~ ~override~ // Divine Might
	SAY NAME1 @61101
	SAY UNIDENTIFIED_DESC @61102
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
END //End 2.0 only

//affliction_________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/affliction/tg#natw.spl~ ~override~ // Refinements nature's wrath
    SAY NAME1 @61201
    SAY UNIDENTIFIED_DESC @61202 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/affliction/tg#natwb.bam~ ~override~
COPY ~faiths_and_powers/spheres/hlas/affliction/tg#natwc.bam~ ~override~

//animal_____________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/animal/B_ph01.spl~ ~override~ // animal horde
	SAY NAME1 @61301
	SAY UNIDENTIFIED_DESC @61302
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
COPY ~faiths_and_powers/spheres/hlas/animal/b_ani05.eff~ ~override~ // eff that casts the summon
COPY ~faiths_and_powers/spheres/hlas/animal/b_ani05.2da~ ~override~ // list of animals
COPY ~faiths_and_powers/spheres/hlas/animal/b_bear1.itm~ ~override~ // bear claw
COPY ~faiths_and_powers/spheres/hlas/animal/b_pbear1.itm~ ~override~ // bear claw
COPY ~faiths_and_powers/spheres/hlas/animal/b_wlf1.itm~ ~override~ // wolf claw
COPY ~faiths_and_powers/spheres/hlas/animal/b_wlf2.itm~ ~override~ // wolf claw
COPY ~faiths_and_powers/spheres/hlas/animal/b_cat1.itm~ ~override~ // cat claw
COPY ~faiths_and_powers/spheres/hlas/animal/b_cat1.cre~ ~override~ // cat
COPY ~faiths_and_powers/spheres/hlas/animal/b_bear1.cre~ ~override~ // bear
COPY ~faiths_and_powers/spheres/hlas/animal/b_pbear1.cre~ ~override~ // bear
COPY ~faiths_and_powers/spheres/hlas/animal/b_wlf.cre~ ~override~ // wolf

COPY ~faiths_and_powers/kits/mystics/702_beast_mystic/d5_wwmy.spl~ ~override~
	SAY NAME1 @70213
	SAY UNIDENTIFIED_DESC @70213
COPY ~faiths_and_powers/kits/mystics/702_beast_mystic/d5_wwnf.spl~ ~override~
	SAY NAME1 @70214
	SAY UNIDENTIFIED_DESC @70214
COPY ~faiths_and_powers/kits/mystics/702_beast_mystic/d5_wwcl1.itm~ ~override~
	SAY NAME1 @70215
	SAY UNIDENTIFIED_DESC @70215
COPY ~faiths_and_powers/kits/mystics/702_beast_mystic/d5_wwcl2.itm~ ~override~
	SAY NAME1 @70215
	SAY UNIDENTIFIED_DESC @70215
COPY ~faiths_and_powers/kits/mystics/702_beast_mystic/d5_ww01.cre~ ~override~
	SAY NAME1 @70216
COPY ~faiths_and_powers/kits/mystics/702_beast_mystic/d5_ww02.cre~ ~override~
	SAY NAME1 @70217
COPY ~faiths_and_powers/kits/mystics/702_beast_mystic/d5_ww03.cre~ ~override~
	SAY NAME1 @70218

//plant______________________________________________________________________________
//LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_STALKER~ RET spell_res END
COPY ~faiths_and_powers/spheres/hlas/plant/d5_shmb.spl~ ~override~
	SAY NAME1 @61401
	SAY UNIDENTIFIED_DESC @61402
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 STR_VAR resource = EVAL ~%spell_res%~ END 

COPY ~faiths_and_powers/spheres/hlas/plant/d5_sham.cre~ ~override~
	SAY NAME1 @61403
COPY ~faiths_and_powers/spheres/hlas/plant/d5_clsha.itm~ ~override~
	SAY NAME1 @61404
	SAY UNIDENTIFIED_DESC @61404
COPY ~faiths_and_powers/spheres/hlas/plant/d5_nfsha.spl~ ~override~
	SAY NAME1 @61405
	SAY UNIDENTIFIED_DESC @61405

/*
ACTION_IF FILE_EXISTS_IN_GAME ~cdid723.cre~ BEGIN
	COPY_EXISTING ~cdid723.cre~ ~override~
	WRITE_BYTE 0x59 50
//	WRITE_BYTE 0x5a 50
	WRITE_BYTE 0x5b 100
	WRITE_BYTE 0x5c 50
	WRITE_BYTE 0x5e 50
	WRITE_BYTE 0x5f 50
	WRITE_BYTE 0x60 50
	WRITE_BYTE 0x61 75
	WRITE_BYTE 0x62 50
	WRITE_BYTE 0x63 50
END
ACTION_IF FILE_EXISTS_IN_GAME ~sshamb.cre~ BEGIN
	COPY_EXISTING ~sshamb.cre~ ~override~
	WRITE_BYTE 0x59 50
//	WRITE_BYTE 0x5a 50
	WRITE_BYTE 0x5b 100
	WRITE_BYTE 0x5c 50
	WRITE_BYTE 0x5e 50
	WRITE_BYTE 0x5f 50
END
*/

//earth______________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/earth/li#drear.spl~ ~override~ // Refinements earth transformation
    SAY NAME1 @61501
    SAY UNIDENTIFIED_DESC @61502 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/earth/transformation~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~spinhum.spl~ BEGIN
	COPY_EXISTING ~spinhum.spl~ ~override~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1  STR_VAR resource = ~li#druea~ END
END


COPY ~faiths_and_powers/spheres/hlas/earth/d5elsuea.spl~ ~override~ // Refinements summon earth elemental
    SAY NAME1 @61511
    SAY UNIDENTIFIED_DESC @61512 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/earth/summon~ ~override~
COMPILE ~faiths_and_powers/spheres/hlas/earth/elemsunn.baf~

//water______________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/water/li#drwat.spl~ ~override~ // Refinements water transformation
    SAY NAME1 @61601
    SAY UNIDENTIFIED_DESC @61602 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/water/transformation~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~spinhum.spl~ BEGIN
	COPY_EXISTING ~spinhum.spl~ ~override~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1  STR_VAR resource = ~li#druwa~ END
END

COPY ~faiths_and_powers/spheres/hlas/water/d5elsuwa.spl~ ~override~ // Refinements summon water elemental
    SAY NAME1 @61611
    SAY UNIDENTIFIED_DESC @61612 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/water/summon~ ~override~
COMPILE ~faiths_and_powers/spheres/hlas/water/elembenh.baf~

//air________________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/air/li#drair.spl~ ~override~ // Refinements air transformation
    SAY NAME1 @61701
    SAY UNIDENTIFIED_DESC @61702 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/air/transformation~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~spinhum.spl~ BEGIN
	COPY_EXISTING ~spinhum.spl~ ~override~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1  STR_VAR resource = ~li#druai~ END
END

COPY ~faiths_and_powers/spheres/hlas/air/d5elsuai.spl~ ~override~ // Refinements summon air elemental
    SAY NAME1 @61711
    SAY UNIDENTIFIED_DESC @61712 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/air/summon~ ~override~
COMPILE ~faiths_and_powers/spheres/hlas/air/elemchan.baf~

ACTION_IF FILE_EXISTS_IN_GAME ~ENGINEST.2DA~ BEGIN
//2.0 only
 COPY ~faiths_and_powers/spheres/hlas/air/B_ph04.spl~ ~override~ // Wind Ward
	SAY NAME1 @61721
	SAY UNIDENTIFIED_DESC @61722
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
 COPY ~faiths_and_powers/spheres/hlas/air/B_ph04a.spl~ ~override~ // subspl
 COPY ~faiths_and_powers/spheres/hlas/air/B_ph04.eff~ ~override~ // the announcing eff
	SAY 0x1c @61723     //Protected by Warding Winds
 COPY ~faiths_and_powers/spheres/hlas/air/b_wind1.bam~ ~override~ // Invisiblish winds
END //End 2.0 only

//fire_______________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/fire/li#drfir.spl~ ~override~ // Refinements fire transformation
    SAY NAME1 @61801
    SAY UNIDENTIFIED_DESC @61802 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/fire/transformation~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~spinhum.spl~ BEGIN
	COPY_EXISTING ~spinhum.spl~ ~override~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1  STR_VAR resource = ~li#drufi~ END
END

COPY ~faiths_and_powers/spheres/hlas/fire/d5elsufi.spl~ ~override~ // Refinements summon fire elemental
    SAY NAME1 @61811
    SAY UNIDENTIFIED_DESC @61812 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/fire/summon~ ~override~
COMPILE ~faiths_and_powers/spheres/hlas/fire/elemzaam.baf~

//light______________________________________________________________________________
COPY ~faiths_and_powers/spheres/hlas/light/d5hlig1.spl~ ~override~ // inner radiance
    SAY NAME1 @61901
    SAY UNIDENTIFIED_DESC @61902 // ***
    WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
    WRITE_BYTE 0x21 (THIS & 0b00111111)
COPY ~faiths_and_powers/spheres/hlas/light/d5hli1a.eff~ ~override~
COPY ~faiths_and_powers/spheres/hlas/light/d5_ffire.vvc~ ~override~

//shadow_____________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~ENGINEST.2DA~ BEGIN
//2.0 only
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08.spl~ ~override~ // Greater Shades
	SAY NAME1 @62001
	SAY UNIDENTIFIED_DESC @62002
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08.2da~ ~override~ // 2da
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08b.cre~ ~override~ // cre
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08c.cre~ ~override~ // cre
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08d.cre~ ~override~ // cre
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08.itm~ ~override~ // itm
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08d.itm~ ~override~ // itm
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08c.itm~ ~override~ // itm
 COPY ~faiths_and_powers/spheres/hlas/shadow/B_ph08.eff~ ~override~ // eff
END //End 2.0 only

//magic______________________________________________________________________________
COPY_EXISTING ~sppr721.spl~ ~override~ // energy blades
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END

COPY_EXISTING ~spwi903.spl~ ~override/d5hmag1.spl~ // spellstrike
	WRITE_SHORT 0x1c 4
    WRITE_LONG 0x34 1
	WRITE_BYTE 0x21 (THIS & 0b00111111)
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
//___________________________________________________________________________________
