//Informal prefix seperating different spelltypes

//xx = consecutive, but otherwise random, numbers
//n = spell level

//zero level cantrips: b_wc_1xx (wizard cantrips)
//zero level cantrips: b_pc_1xx (priest cantrips)

//1st level cantrips: b_1w1xx (wizard cantrips)
//1st level cantrips: b_2c1xx (priest cantrips)

//Regular added spells b_wnxx(wizard spells)
//Regular added spells b_pnxx(priest spells)

/*opcode = 177
target = 2
power = 0
timing = 4
parameter1 = 5
parameter2 = 160
power = 0
resist_dispel = 2
duration = 1
probability1 = 100
probability2 = 0
dicenumber = 0
dicesize = 0
savingthrow = 0
savebonus = 0
header =
insert_point = 7

FYI   */

//SPell REVISIONS COMPATIBLITY:  Check for it in original tp2. Install all 'extra' spells using addspell so there is no issue.  (I think this applies to v4 only)


//IMPLEMENT SPHERE CODE (0URS). PROBABLY MUST BE INSTALLED BEFORE SPHERE.TPA.  THAT COMPONENT COULD CHECK TO SEE IF THIS, IWDEE OR IWDIFICATION IS NOT INSTALLED AND INSTALL THIS FIRST IF SO
//DECIDE WHAT TO DO IF IWDIFICATION DIVINE SPELLS ARE INSTALLED (PROBABLY NOT INSTALL SPECIFIC SPELLS, THOUGH KEEP SOME COMPATIBILITY CODE)


ACTION_IF NOT MOD_IS_INSTALLED ~setup-iwdification.tp2~ ~30~ BEGIN  // if IWDification arcane pack not installed...

ACTION_CLEAR_ARRAY aoe_spell

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             WIZARD SPELLS               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 2   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Snilloc's Snowball Swarm_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_2/IDPRO217.pro~   //projectile
//VVC
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/#SSSWARM.vvc~ ~override~   //animation
//bam
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/SSSWART.BAM~ ~override~   //animation
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/SSSWARR.BAM~ ~override~   //animation
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/SSSWARX.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/TRA_18.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/RNG_M02.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_2/b_w204.spl~ 2 2 ~WIZARD_SNILLOCS_SNOWBALL_SWARM~ //
        SAY NAME1 @2040000
        SAY NAME2 @2040000
        SAY UNIDENTIFIED_DESC @2040001
	SAY DESC @2040001
	WRITE_SHORT 0x098 ~%IDPRO217%~  //Projectile
	WRITE_SHORT 0x0c0 ~%IDPRO217%~  //Projectile     (+28)
	WRITE_SHORT 0x0e8 ~%IDPRO217%~  //Projectile     (+28)
	WRITE_SHORT 0x110 ~%IDPRO217%~  //Projectile     (+28)
	WRITE_SHORT 0x138 ~%IDPRO217%~  //Projectile     (+28)
	WRITE_SHORT 0x160 ~%IDPRO217%~  //Projectile     (+28)

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SNILLOCS_SNOWBALL_SWARM~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/SPWI204a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/SPWI204b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_2/SPWI204c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~

OUTER_SET $aoe_spell(~WIZARD_SNILLOCS_SNOWBALL_SWARM~)=1

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 3   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Icelance_____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_3/IDPRO251.pro~   //projectile
//VVC
//bam
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_3/ICELANT.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_3/#TRA_19.wav~ ~override~   //animation
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_3/b_w327.spl~ 2 3 ~WIZARD_ICELANCE~ //
        SAY NAME1 @3270000
        SAY NAME2 @3270000
        SAY UNIDENTIFIED_DESC @3270001
	SAY DESC @3270001
	WRITE_SHORT 0x098 ~%IDPRO251%~  //Projectile

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_ICELANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 26050    //stun notification bgee
  END
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_3/SPWI327a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_3/SPWI327b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_3/SPWI327c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 4   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________vitriolic sphere_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_4/idpro316.pro~   //projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_4/SMLLARNC.pro~   //projectile
//VVC
//bam
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/VSPHERT.BAM~ ~override~   //animation
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/VSPHERX.BAM~ ~override~   //animation
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/ACIDH.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/#TRA_60.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/TRA_06.WAV~ ~override~   //
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_w432.spl~ 2 4 ~WIZARD_VITRIOLIC_SPHERE~ //
        SAY NAME1 @4320000
        SAY NAME2 @4320000
        SAY UNIDENTIFIED_DESC @4320001
	SAY DESC @4320001
	WRITE_SHORT 0x098 ~%idpro316%~  //Projectile
	WRITE_SHORT 0x0c0 ~%idpro316%~  //Projectile     (+28)
	WRITE_SHORT 0x0e8 ~%idpro316%~  //Projectile     (+28)
	WRITE_SHORT 0x110 ~%idpro316%~  //Projectile     (+28)
	WRITE_SHORT 0x138 ~%idpro316%~  //Projectile     (+28)
	WRITE_SHORT 0x160 ~%idpro316%~  //Projectile     (+28)
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_VITRIOLIC_SPHERE~
  RET spell_res
END
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_w432y.spl~ ~override/%spell_res%y.spl~   //sec spell
	WRITE_SHORT 0x098 ~%SMLLARNC%~  //Projectile
	WRITE_SHORT 0x0c0 ~%SMLLARNC%~  //Projectile     (+28)
	WRITE_SHORT 0x0e8 ~%SMLLARNC%~  //Projectile     (+28)
	WRITE_SHORT 0x110 ~%SMLLARNC%~  //Projectile     (+28)
	WRITE_SHORT 0x138 ~%SMLLARNC%~  //Projectile     (+28)
	WRITE_SHORT 0x160 ~%SMLLARNC%~  //Projectile     (+28)
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_w432z.spl~ ~override/%spell_res%z.spl~   //sec spell
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 146            //
      STR_VAR resource = EVAL ~%spell_res%y~
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 146 STR_VAR resource = EVAL ~%spell_res%z~ END     //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI432a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI432b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI432c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Shadow Monsters_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//2da
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_sh01.2da~ ~override~   //animation
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_sh02.2da~ ~override~   //animation
//bam
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/MSumm1X.bam~ ~override~   //animation
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/MSumm1H.bam~ ~override~   //animation
//animations
//3d animation
//itm
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/TRANS20.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SUMRING.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/P1-6.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/S1-12.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/M1D7SLSH.itm~ ~override~   //
//sounds
//effs
//cre
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1gob1.cre~ ~override~   //
        SAY NAME1 ~goblin~
        SAY NAME2 ~goblin~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1GOB2.cre~ ~override~   //
        SAY NAME1 ~goblin~
        SAY NAME2 ~goblin~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1GOB3.cre~ ~override~   //
        SAY NAME1 ~goblin~
        SAY NAME2 ~goblin~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1liz3.cre~ ~override~   //
        SAY NAME1 ~Lizard Man~
        SAY NAME2 ~Lizard Man~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1liz4.cre~ ~override~   //
        SAY NAME1 ~Lizard Man~
        SAY NAME2 ~Lizard Man~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1TRL6.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1TRL7.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SS1TRL8.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_w426.spl~ 2 4 ~WIZARD_SHADOW_MONSTERS~ //
        SAY NAME1 @4260000
        SAY NAME2 @4260000
        SAY UNIDENTIFIED_DESC @4260001
	SAY DESC @4260001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHADOW_MONSTERS~
  RET spell_res
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI426a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI426b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI426c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x036E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0396 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03E6 ~%spell_res%B~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 331            //
      STR_VAR resource = EVAL ~B_SH02~
  END      //

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Emotion: Courage_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_4/idpro407.pro~   //projectile
//VVC
//bam
//bam
//animations
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/#EFF_M05.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_w427.spl~ 2 4 ~WIZARD_EMOTION_COURAGE~ //
        SAY NAME1 @4270000
        SAY NAME2 @4270000
        SAY UNIDENTIFIED_DESC @4270001
	SAY DESC @4270001
	WRITE_SHORT 0x098 ~%idpro407%~  //Projectile
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EMOTION_COURAGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI427a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI427b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI427c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Emotion: Fear________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_4/IDPRO255.pro~   //projectile
//VVC
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/#GENENCH.VVC~ ~override~   //
//bam
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/ENCHANX.BAM~ ~override~   //
//bam
//animations
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/ARE_M21.WAV~ ~override~   //#EFF_E05.WAV
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/#EFF_E05.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/#EFF_M05.WAV~ ~override~   //#EFF_E05.WAV
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_w428.spl~ 2 4 ~WIZARD_EMOTION_FEAR~ //
        SAY NAME1 @4280000
        SAY NAME2 @4280000
        SAY UNIDENTIFIED_DESC @4280001
	SAY DESC @4280001
	WRITE_SHORT 0x098 ~%IDPRO255%~  //Projectile
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EMOTION_FEAR~
  RET spell_res
END
ACTION_IF GAME_IS ~bgee~ BEGIN
 COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139  parameter1 = 25818 END// string
END     //
ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
 COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139  parameter1 = 14007 END// string
END     //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI428a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI428b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI428c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~WIZARD_EMOTION_FEAR~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Emotion: Hope________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_4/idpro407.pro~   //projectile
//VVC
//bam
//bam
//animations
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/#EFF_M05.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/#EFF_E03.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_4/b_w429.spl~ 2 4 ~WIZARD_EMOTION_HOPE~ //
        SAY NAME1 @4290000
        SAY NAME2 @4290000
        SAY UNIDENTIFIED_DESC @4290001
	SAY DESC @4290001
	WRITE_SHORT 0x098 ~%idpro407%~  //Projectile
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EMOTION_HOPE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI429a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI429b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_4/SPWI429c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 6   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Shades_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//2da
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/b_sh03.2da~ ~override~   //animation
//bam
//animations
//3d animation
//itm
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/TRANS40.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/S1-8.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/B1-12.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/REG1HP2.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/TRANS60.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SUMAMU.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/UMBERHLK.itm~ ~override~   //
//sounds
//effs
//cre
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS2gob2.cre~ ~override~   //
        SAY NAME1 ~Goblin Elite~
        SAY NAME2 ~Goblin Elite~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS2gob3.cre~ ~override~   //
        SAY NAME1 ~Goblin Elite~
        SAY NAME2 ~Goblin Elite~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS2liz5.cre~ ~override~   //
        SAY NAME1 ~Tough Lizard Man~
        SAY NAME2 ~Tough Lizard Man~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS2liz6.cre~ ~override~   //
        SAY NAME1 ~Tough Lizard Man~
        SAY NAME2 ~Tough Lizard Man~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS2liz7.cre~ ~override~   //
        SAY NAME1 ~Tough Lizard Man~
        SAY NAME2 ~Tough Lizard Man~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS3trl7.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS3trl8.cre~ ~override~   // Check animations...actually check all animations
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS3umb8.cre~ ~override~   //
        SAY NAME1 ~Umber Hulk~
        SAY NAME2 ~Umber Hulk~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SS3umb9.cre~ ~override~   //
        SAY NAME1 ~Umber Hulk~
        SAY NAME2 ~Umber Hulk~
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_6/B_W629.spl~ 2 6 ~WIZARD_SHADES~ //
        SAY NAME1 @6290000
        SAY NAME2 @6290000
        SAY UNIDENTIFIED_DESC @6290001
	SAY DESC @6290001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHADES~
  RET spell_res
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SPWI629a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SPWI629b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SPWI629c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 331            //
      STR_VAR resource = EVAL ~B_SH03~
  END      //

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Soul Eater__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_6/idpro299.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SEATERA.bam~ ~override~   //animation
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_6/B_W631.spl~ 2 6 ~WIZARD_SOUL_EATER~ //
        SAY NAME1 @6310000
        SAY NAME2 @6310000
        SAY UNIDENTIFIED_DESC @6310001
	SAY DESC @6310001
	WRITE_SHORT 0x098 ~%idpro299%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SOUL_EATER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 326            //
      STR_VAR resource = EVAL ~%spell_res%b~
  END      //
//secondary spells
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/B_W631b.spl~ ~override/%spell_res%b.spl~   //sec spell
//creature for secspell
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/AD3SKLM.cre~ ~override~   //sec spell cre
        SAY NAME1 ~Skeleton~
        SAY NAME2 ~Skeleton~
//cre items
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/RNDTRE40.itm~ ~override~   //sec spell cre itm
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/RING95.itm~ ~override~   //sec spell cre itm
//cre script
  COMPILE ~faiths_and_powers/spheres/iwd_spells/wizard_6/GNSUMMM.baf~ 
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SPWI631a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SPWI631b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_6/SPWI631c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~WIZARD_SOUL_EATER~)=1

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 7   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Acid Storm___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/wizard_7/idpro211.pro~   //projectile
//VVC
//bam
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_7/ASTORMA.bam~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_7/ARE_M04.WAV~ ~override~   //
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/wizard_7/b_w724.spl~ 2 7 ~WIZARD_ACID_STORM~ //
        SAY NAME1 @7240000
        SAY NAME2 @7240000
        SAY UNIDENTIFIED_DESC @7240001
	SAY DESC @7240001
	WRITE_SHORT 0x098 ~%idpro211%~  //Projectile
	WRITE_SHORT 0x0c0 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x0e8 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x110 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x138 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x160 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x188 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x1B0 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x1D8 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x200 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x228 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x250 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x278 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x2A0 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x2C8 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x2F0 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x318 ~%idpro211%~  //Projectile     (+28)
	WRITE_SHORT 0x340 ~%idpro211%~  //Projectile     (+28)
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_ACID_STORM~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_7/SPWI724a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_7/SPWI724b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/wizard_7/SPWI724c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~

END

OUTER_SET $aoe_spell(~WIZARD_ACID_STORM~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             DIVINE SPELLS               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 1   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________________Curse___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_1/b_p112.pro~   //projectile
//VVC
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/#BLESS.vvc~ ~override~   //
//bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/AREA1X.bam~ ~override~   //animation
//animations
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/CURSEH.bam~ ~override~   //animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/#EFF_P99.WAV~ ~override~   //sound
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/#EFF_P32.wav~ ~override~   //sound
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/#EFF_E04.WAV~ ~override~   //sound
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_1/b_p112.spl~ 1 1 ~CLERIC_CURSE~ //Curse Spell
        SAY NAME1 @11200000
        SAY NAME2 @11200000
        SAY UNIDENTIFIED_DESC @11200001
	SAY DESC @11200001
	WRITE_SHORT 0x098 ~%b_p112%~  //Projectile

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURSE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 17426    //Cursed notification
  END
//compatibility
//orisons. mal.  does not stack with it.
ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = EVAL ~b_po030~ END     //FIrst (hopefully only) clone of 321, so...okay.  May have compatibility issues with other mods
  LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
END
//Spell Revisions (Break Enchantment removes Curse)
ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN   //any version of sr
COPY_EXISTING ~sppr307.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 221 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END
COPY_EXISTING ~spwi410.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 221 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END
END
//globe of invuln immunity:
//minor globe of invuln
COPY_EXISTING ~spwi406.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 155 opcode = 206 STR_VAR resource = EVAL ~%spell_res%~ END
//globe of invuln
COPY_EXISTING ~spwi602.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 155 opcode = 206 STR_VAR resource = EVAL ~%spell_res%~ END
ACTION_IF FILE_EXISTS_IN_GAME ~SPWM126.spl~ BEGIN
COPY_EXISTING ~SPWM126.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 155 opcode = 206 STR_VAR resource = EVAL ~%spell_res%~ END
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr112a.bam~ ~override/%spell_res%a.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr112b.bam~ ~override/%spell_res%b.bam~
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr112c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_CURSE~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cause Light Wounds_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//not installed if SRv4 is installed (though, see revisions to alter that version)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
//Projectile
//animations
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/cldamah.bam~ ~override~   //animation
//sounds
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_1/b_p114.spl~ 1 1 ~CLERIC_CAUSE_LIGHT_WOUNDS~ //CLW Spell
        SAY NAME1 @11400000
        SAY NAME2 @11400000
        SAY UNIDENTIFIED_DESC @11400001
	SAY DESC @11400001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_LIGHT_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//compatibility spheres (ours) sphere: life
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
        SAY UNIDENTIFIED_DESC @11400002
	SAY DESC @11400002
END
//compatibity revised spells
//20% damage + 6 damage (save vs death for half) and name changed to 'inflict'
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY NAME1 @11400005
        SAY NAME2 @11400005
        SAY UNIDENTIFIED_DESC @11400003
	SAY DESC @11400003
  LPF DELETE_EFFECT INT_VAR match_opcode= 12 END//
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 3 parameter2 = 4194304 savingthrow = 0 STR_VAR resource = EVAL ~ ~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 savingthrow = 4 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 parameter2 = 4194307 END
//spheres installed, change sphere to 'life'
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
        SAY UNIDENTIFIED_DESC @11400004
	SAY DESC @11400004
END
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr114a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr114b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr114c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Sunscorch_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//Not installed if any version of SR is installed:
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN

COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/SUNSCOH.bam~ ~override~   //pro bam
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_1/SUNSCOH.pro~   //projectile
//animations
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr115a.bam~ ~override~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr115b.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr115c.bam~ ~override~   //bam
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/#EFF_P39.wav~ ~override~   //sound
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_1/b_p115.spl~ 1 1 ~CLERIC_SUNSCORCH~ //CLW Spell
        SAY NAME1 @11500000
        SAY NAME2 @11500000
        SAY UNIDENTIFIED_DESC @11500001
	SAY DESC @11500001
	WRITE_SHORT 0x098 ~%SUNSCOH%~  //Projectile   (add 29 more)
	WRITE_SHORT 0x0c0 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x0e8 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x110 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x138 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x160 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x188 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x1B0 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x1D8 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x200 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x228 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x250 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x278 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x2A0 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x2C8 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x2F0 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x318 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x340 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x368 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x390 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x3B8 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x3E0 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x408 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x430 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x458 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x480 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x4A8 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x4D0 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x4F8 ~%SUNSCOH%~  //Projectile     (+28)
	WRITE_SHORT 0x520 ~%SUNSCOH%~  //Projectile     (+28)
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SUNSCORCH~
  RET spell_res
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //change blind notification
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 1474    //blinded notification
  END      //
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 326            //
      STR_VAR resource = EVAL ~%spell_res%D~
  END      //

//secondary spells
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr115D.spl~ ~override/%spell_res%D.spl~   //sec spell
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr115a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr115b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_1/sppr115c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x036E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0396 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03E6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x040E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0436 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x045E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0486 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x04AE ~%spell_res%B~
END
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 2   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Resist Fire and Cold___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////
//Not installed if any version of SR is installed (but, see revised spells)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN    //SR installs resist elements (sppr210)
//Projectile
//animations
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/ALTERH.bam~ ~override~   //animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/#EFF_P07.WAV~ ~override~   //sound
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/#EFF_E03.WAV~ ~override~   //sound
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_2/b_p216.spl~ 1 2 ~CLERIC_RESIST_FIRE_AND_COLD~ //CMW Spell
        SAY NAME1 @21600000
        SAY NAME2 @21600000
        SAY UNIDENTIFIED_DESC @21600001
	SAY DESC @21600001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_RESIST_FIRE_AND_COLD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr210a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr210b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr210c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x036E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0396 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03E6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x040E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0436 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x045E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0486 ~%spell_res%B~
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cure Moderate Wounds___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////
//Not installed if any version of SR is installed (but, see revised spells)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN

//Projectile
//animations
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/cmwounh.bam~ ~override~   //animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/#EFF_P26.WAV~ ~override~   //sound
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_2/b_p217.spl~ 1 2 ~CLERIC_CURE_MODERATE_WOUNDS~ //CMW Spell
        SAY NAME1 @21700000
        SAY NAME2 @21700000
        SAY UNIDENTIFIED_DESC @21700001
	SAY DESC @21700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURE_MODERATE_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//COMPATIBILITY: REVISED CURE SPELLS
//cure moderate wound 30%
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50102
	SAY DESC @50102
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 6
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 30 parameter2 = 2 END
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr217a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr217b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr217c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Alicorn Lance______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_2/b_lance.pro~   //projectile
//animations
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/ALANCET.BAM~ ~override~   //Pro bam

//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/#EFF_E08.WAV~ ~override~   //sound
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/#TRA_57.WAV~ ~override~   //Pro sound
//effs
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/b_p218.eff~ ~override~   //for notification
  SAY 0x1c @21800003    //Notification
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_2/b_p218.spl~ 1 2 ~CLERIC_ALICORN_LANCE~ // Spell
        SAY NAME1 @21800000
        SAY NAME2 @21800000
        SAY UNIDENTIFIED_DESC @21800001
	SAY DESC @21800001
	WRITE_SHORT 0x098 ~%b_lance%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ALICORN_LANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr218a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr218b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr218c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________________Beast claw_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/ALTERH.BAM~ ~override~   //sound
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/#EFF_P07.WAV~ ~override~   //sound
//itm
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/BCLAW.itm~ ~override~   //item
        SAY NAME1 @21900000
        SAY NAME2 @21900000
//itm icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/IBCLAW.BAM~ ~override~   //item
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_2/b_p219.spl~ 1 2 ~CLERIC_BEAST_CLAW~ // Spell
        SAY NAME1 @21900000
        SAY NAME2 @21900000
        SAY UNIDENTIFIED_DESC @21900001
	SAY DESC @21900001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_BEAST_CLAW~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr219a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr219b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr219c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//________________________________________________________________Cause Moderate Wounds_________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//not installed if SRv4 is installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
//Projectile
//animations
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/CMDAMAH.BAM~ ~override~   //animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/#FF_P103.WAV~ ~override~   //sound
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_2/b_p220.spl~ 1 2 ~CLERIC_CAUSE_MODERATE_WOUNDS~ //CMW Spell
        SAY NAME1 @22000000
        SAY NAME2 @22000000
        SAY UNIDENTIFIED_DESC @22000001
	SAY DESC @22000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_MODERATE_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//compatibity revised spells
//30% damage + 8 damage (save vs death for half) and name changed to 'inflict'
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY NAME1 @11400005
        SAY NAME2 @11400005
        SAY UNIDENTIFIED_DESC @11400003
	SAY DESC @11400003
  LPF DELETE_EFFECT INT_VAR match_opcode= 12 END//
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 3 parameter2 = 4194304 savingthrow = 0 STR_VAR resource = EVAL ~ ~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 savingthrow = 4 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 parameter2 = 4194307 END
//spheres installed, change sphere to 'life'
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
        SAY UNIDENTIFIED_DESC @11400004
	SAY DESC @11400004
END
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr220a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr220b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_2/sppr220c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
END


//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 3   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________________Prayer_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/PRAYERH.BAM~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/PRAYERG.BAM~ ~override~   //
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#EFF_P31.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/EFF_E03.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#PRAYERB.SPL~ ~override~   //spl
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 7160            //combat penalties
  END      //
STRING_SET 7160 @31600002
COPY_EXISTING ~book09.itm~ ~override~
	SAY NAME2 @31600003
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#PRAYERG.SPL~ ~override~   //spl
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 13086      //combat bonuses
  END      //
STRING_SET 13086 @31600004
COPY_EXISTING ~book10.itm~ ~override~
	SAY NAME2 @31600005

//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p316.spl~ 1 3 ~CLERIC_PRAYER~ // Spell
        SAY NAME1 @31600000
        SAY NAME2 @31600000
        SAY UNIDENTIFIED_DESC @31600001
	SAY DESC @31600001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END

//Compatibility
ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po030~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po040~ END
//non-sphere description
COPY_EXISTING ~b_po020.spl~ ~override~
        SAY UNIDENTIFIED_DESC @102000005
	SAY DESC @102000005
COPY_EXISTING ~b_po030.spl~ ~override~
        SAY UNIDENTIFIED_DESC @103000002
	SAY DESC @103000002
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000003
	SAY DESC @104000003
//sphere description
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po020.spl~ ~override~
        SAY UNIDENTIFIED_DESC @102000005
	SAY DESC @102000005
COPY_EXISTING ~b_po030.spl~ ~override~
        SAY UNIDENTIFIED_DESC @103000004
	SAY DESC @103000004
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000005
	SAY DESC @104000005
END
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr316a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr316b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr316c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Cause Disease_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//icons
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/CDISEAH.BAM~ ~override~   //
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#FF_P108.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/EFF_E03.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p320.spl~ 1 3 ~CLERIC_CAUSE_DISEASE~ // Spell
        SAY NAME1 @32000000
        SAY NAME2 @32000000
        SAY UNIDENTIFIED_DESC @32000001
	SAY DESC @32000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_DISEASE~
  RET spell_res
END
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 142 opcode = 139 parameter1 = 31238 parameter2 = 0 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 142 opcode = 139 parameter1 = 54337 parameter2 = 0 END
END

COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr320a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr320b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr320c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Exaltation________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/EXALTAH.BAM~ ~override~   //
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#FF_P106.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
//Need to remove blood rage (prob animal rage, too?)
//Copied over for protections
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   // ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
  COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/bgee/b_p321.spl~ ~override~   //
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
  COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/bg2ee/b_p321.spl~ ~override~   //
END
//not added yet.  Add after Blood rage has been added

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Moonblade_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#EFF_M06.WAV~ ~override~   //itm sound
//itm
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/MOONBLA.itm~ ~override~   //itm
        SAY NAME1 @32200000
        SAY NAME2 @32200000
//itm icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/MOONBLA.BAM~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/GSW1H01.BAM~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/INVOCH.BAM~ ~override~   //itm 3d
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p322.spl~ 1 3 ~CLERIC_MOONBLADE~ // Spell
        SAY NAME1 @32200000
        SAY NAME2 @32200000
        SAY UNIDENTIFIED_DESC @32200001
	SAY DESC @32200001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MOONBLADE~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr322a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr322b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr322c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Circle of Bones______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/COBONH1.BAM~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/COBONH2.BAM~ ~override~   //
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#ARE_P21.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#AFT_P22.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/SPPR323D.spl~ ~override~   //
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p323.spl~ 1 3 ~CLERIC_CIRCLE_OF_BONES~ // Spell
        SAY NAME1 @32300000
        SAY NAME2 @32300000
        SAY UNIDENTIFIED_DESC @32300001
	SAY DESC @32300001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CIRCLE_OF_BONES~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr323a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr323b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr323c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Spike Growth_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//not installed if SRv4 is installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_3/b_spikeg.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sgrowta.BAM~ ~override~   //pro bam
//3d animation
//sounds
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p324.spl~ 1 3 ~CLERIC_SPIKE_GROWTH~ // Spell
        SAY NAME1 @32400000
        SAY NAME2 @32400000
        SAY UNIDENTIFIED_DESC @32400001
	SAY DESC @32400001
	WRITE_SHORT 0x098 ~%b_spikeg%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SPIKE_GROWTH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr324a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr324b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr324c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
END

OUTER_SET $aoe_spell(~CLERIC_SPIKE_GROWTH~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Cloudburst___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//COME BACK TO THIS ONE.  NEED TO LOOK UP RELEVANT MONSTERS AND ABILITIES


//REMOVE Shroud of Flame (wizard spell) once added
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_3/b_clobu.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sgrowta.BAM~ ~override~   //pro bam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/CLOUDBA.bam~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/CLOUDBH.BAM~ ~override~   // bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/ARE_P24.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p325.spl~ 1 3 ~CLERIC_CLOUDBURST~ // Spell
        SAY NAME1 @32500000
        SAY NAME2 @32500000
        SAY UNIDENTIFIED_DESC @32500001
	SAY DESC @32500001
	WRITE_SHORT 0x098 ~%b_clobu%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CLOUDBURST~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr325a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr325b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr325c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Mold Touch___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_3/B_MOLD.pro~   //projectile
//probam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/MTOUCHH.BAM~ ~override~   // bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#FF_P107.WAV~ ~override~   //
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p326.spl~ 1 3 ~CLERIC_MOLD_TOUCH~ // Spell
        SAY NAME1 @32600000
        SAY NAME2 @32600000
        SAY UNIDENTIFIED_DESC @32600001
	SAY DESC @32600001

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MOLD_TOUCH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//secondary spells
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/SPPR326B.spl~ ~override/%spell_res%B.spl~   // bam  NEEDED?
	WRITE_SHORT 0x098 ~%B_MOLD%~  //Projectile
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr326a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr326b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr326c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Storm Shell__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr327a.bam~ ~override~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr327b.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr327c.bam~ ~override~   //bam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/ISTORMA.BAM~ ~override~   // bam
//sounds
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p327.spl~ 1 3 ~CLERIC_STORM_SHELL~ // Spell
        SAY NAME1 @32700000
        SAY NAME2 @32700000
        SAY UNIDENTIFIED_DESC @32700001
	SAY DESC @32700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STORM_SHELL~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr327a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr327b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr327c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Cause Medium Wounds_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//not installed if SRv4 is installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN

//Projectile
//probam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/CMDAMAH.BAM~ ~override~   // bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#FF_P103.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p330.spl~ 1 3 ~CLERIC_CAUSE_MEDIUM_WOUNDS~ // Spell
        SAY NAME1 @33000000
        SAY NAME2 @33000000
        SAY UNIDENTIFIED_DESC @33000001
	SAY DESC @33000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_MEDIUM_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr330a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr330b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr330c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Favor of Ilmater________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//unfamilliar opcode.  Hope it's good
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_3/SPARKLPU.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/TRAVEL.bam~ ~override~   //pro bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/STTRAVL5.BMP~ ~override~   //bmp
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/CMWOUNH.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/CMDAMAH.BAM~ ~override~   // bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#EFF_P26.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/#FF_P103.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_3/b_p327.spl~ 1 3 ~CLERIC_FAVOR_OF_ILMATER~ // Spell
        SAY NAME1 @33100000
        SAY NAME2 @33100000
        SAY UNIDENTIFIED_DESC @33100001
	SAY DESC @33100001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_FAVOR_OF_ILMATER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr331a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr331b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr331c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 4   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Giant Insect____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/cldamah.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/CURSEH.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbma1.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbma1e.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbma4.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbma4e.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmca.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmcae.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmde.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmdee.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmgh.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmghe.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmgu.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmgue.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmsc.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmsce.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmsd.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmsde.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmsl.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmsle.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmsp.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmspe.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmtw.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmtwe.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmwk.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbmwke.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbeta1.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbeta1e.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetca.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetcae.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetde.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetdee.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetgh.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetghe.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetgu.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetgue.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetsc.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetsce.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetsd.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetsde.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetsl.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetsle.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetsp.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetspe.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbettw.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbettwe.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetwk.BAM~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbetwke.BAM~ ~override~   // bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#EFF_E04.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#EFF_P32.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#EFF_P39.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba01.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba02.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba03a.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba03b.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba03c.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba07.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba08.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba09a.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba09b.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bomba11.WAV~ ~override~   //
//cre
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/b_bebom.cre~ ~override~   //  bomba beetle
        SAY NAME1 @41800003
        SAY NAME2 @41800003
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/b_bebor.cre~ ~override~   // boring beetle
        SAY NAME1 @41800004
        SAY NAME2 @41800004
//2da
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/b_ginsc.2da~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbbm.2da~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/mbet.2da~ ~override~   //
//itm
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/fartrng.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/s1-12.itm~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/s5-20.itm~ ~override~   //
//itm icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/pincers.BAM~ ~override~   // bam
//effs
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/b_ginsc.eff~ ~override~   // actual summon eff
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p418.spl~ 1 4 ~CLERIC_GIANT_INSECT~ // Spell
        SAY NAME1 @41800000
        SAY NAME2 @41800000
        SAY UNIDENTIFIED_DESC @41800001
	SAY DESC @41800001

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_GIANT_INSECT~
  RET spell_res
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr418a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr418b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr418c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Produce Fire_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//_______________________________________________________
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/b_pfire.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/PFIREA.bam~ ~override~   // bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/PFIREX.bam~ ~override~   // bam
//vvc
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#PRFIRE.vvc~ ~override~   // bam
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#EFF_P45.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#ARE_P03.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p419.spl~ 1 4 ~CLERIC_PRODUCE_FIRE~ // Spell
        SAY NAME1 @41900000
        SAY NAME2 @41900000
        SAY UNIDENTIFIED_DESC @41900001
	SAY DESC @41900001
	WRITE_SHORT 0x098 ~%b_pfire%~  //Projectile
	WRITE_SHORT 0x0c0 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x0e8 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x110 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x138 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x160 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x188 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x1B0 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x1D8 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x200 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x228 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x250 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x278 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x2A0 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x2C8 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x2F0 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x318 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x340 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x368 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x390 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x3B8 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x3E0 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x408 ~%b_pfire%~  //Projectile     (+28)
	WRITE_SHORT 0x430 ~%b_pfire%~  //Projectile     (+28)
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRODUCE_FIRE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr419a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr419b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr419c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x036E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0396 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03E6 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_PRODUCE_FIRE~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//________________________________________________________________Static Charge_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//secondary projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/IDSTATIC.pro~   //projectile
//probam
//vvc
//icons
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SCHARGH.BAM~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/EFF_P42.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs

//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p420.spl~ 1 4 ~CLERIC_STATIC_CHARGE~ // Spell
        SAY NAME1 @42000000
        SAY NAME2 @42000000
        SAY UNIDENTIFIED_DESC @42000001
	SAY DESC @42000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STATIC_CHARGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 333            //
      STR_VAR resource = EVAL ~%spell_res%B~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142            //
      parameter2 = 94 //magnitized portrait icon for now
  END      //

//secondary spell
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr420b.spl~ ~override/%spell_res%B.spl~   //sec spell
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 13107
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%b~
  END      //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p420a.eff~ ~override~   //text notification
  SAY 0x1c @42000004    //Notification

/* this was insane!
STRING_SET 13107 @42000004
COPY_EXISTING ~book32.itm~ ~override~
	SAY NAME2 @42000003   */
//must add projectile
COPY_EXISTING ~%spell_res%B.spl~ ~override~
	WRITE_SHORT 0x098 ~%IDSTATIC%~  //Projectile

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr420a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr420b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr420c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x036E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0396 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03E6 ~%spell_res%B~




//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Recitation__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p421a.pro~   //projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p421b.pro~   //projectile
//probam
//vvc
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/RECITAH.BAM~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/B_RECR.bam~ ~override~   //bam (missing, so created)
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#EFF_P44.WAV~ ~override~   //Wav
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/EFF_E03.WAV~ ~override~   //Wav
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#RECITEG.spl~ ~override~   //
	WRITE_SHORT 0x098 ~%b_p421a%~  //Projectile
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 13086      //combat bonuses
  END      //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#RECITEB.spl~ ~override~   //
	WRITE_SHORT 0x098 ~%b_p421b%~  //Projectile
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 7160            //combat penalties
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 215            //
      STR_VAR resource = EVAL ~B_RECR~ //missing bam
  END      //

//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p421.spl~ 1 4 ~CLERIC_RECITATION~ // Spell
        SAY NAME1 @42100000
        SAY NAME2 @42100000
        SAY UNIDENTIFIED_DESC @42100001
	SAY DESC @42100001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_RECITATION~
  RET spell_res
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr421a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr421b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr421c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Blood Rage__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//icons
//3d animation
//sounds
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bgee/b_p422.spl~ ~override~   //
END
//
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //BGEE VERSION
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/bg2ee/b_p422.spl~ ~override~   //
END
//RIGHT NOW DOES NOT DISPLAY THE BLOOD RAGE SPECIAL EFFECT.  USED BESERK INSTEAD
//NOT SURE ABOUT "STATE 35"...Not sure if AI CAN OR CANNOT HANDLE THIS SPELL.  DLTCEP SAYS THAT IT SHOULD BE 4 SO, COnfused
//MAKE IMMUNE TO NEWLY CREATED SYMBOL SPELLS BEFORE ADDING (SEE BELOW)!
//MAKE PROTECT FROM WIZARD EMOTION SPELLS ONCE ADDED

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cloud of Pestilence____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//will anything remove or prevent this spell?
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/b_pest.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/copesta.BAM~ ~override~   //
//vvc
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/ARE_P25.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/bgee/b_p423.spl~ 1 4 ~CLERIC_CLOUD_OF_PESTILENCE~ // Spell
        SAY NAME1 @42300000
        SAY NAME2 @42300000
        SAY UNIDENTIFIED_DESC @42300001
	SAY DESC @42300001
	WRITE_SHORT 0x098 ~%b_pest%~  //Projectile
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/bg2ee/b_p423.spl~ 1 4 ~CLERIC_CLOUD_OF_PESTILENCE~ // Spell
        SAY NAME1 @42300000
        SAY NAME2 @42300000
        SAY UNIDENTIFIED_DESC @42300001
	SAY DESC @42300001
	WRITE_SHORT 0x098 ~%b_pest%~  //Projectile
END

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CLOUD_OF_PESTILENCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr423a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr423b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr423c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_CLOUD_OF_PESTILENCE~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Unfailing Endurance____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/NECROH.BAM~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#FF_P112.WAV~ ~override~   //Wav
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p424.spl~ 1 4 ~CLERIC_UNFAILING_ENDURANCE~ // Spell
        SAY NAME1 @42400000
        SAY NAME2 @42400000
        SAY UNIDENTIFIED_DESC @42400001
	SAY DESC @42400001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNFAILING_ENDURANCE~
  RET spell_res
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr424a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr424b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr424c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Star Metal Cudgel______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/ISMCUDGE.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/CONJUH.bam~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#EFF_P02.WAV~ ~override~   //
//cre
//2da
//itm
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SMCUDGE.itm~ ~override~   //
        SAY NAME1 @42500000
        SAY NAME2 @42500000
//itm icons
//effs
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SMCUDGE.eff~ ~override~   //eff
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p425.spl~ 1 4 ~CLERIC_STAR_METAL_CUDGEL~ // Spell
        SAY NAME1 @42500000
        SAY NAME2 @42500000
        SAY UNIDENTIFIED_DESC @42500001
	SAY DESC @42500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STAR_METAL_CUDGEL~
  RET spell_res
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr425a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr425b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr425c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Smashing Wave______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/B_SWAVE.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SWAVEX.bam~ ~override~   //
//vvc
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SWAVEX.bam~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SWAVEH.BAM~ ~override~   //
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#FF_P110.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs  missing stun display (check for immunities...)
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p426.spl~ 1 4 ~CLERIC_SMASHING_WAVE~ // Spell
        SAY NAME1 @42600000
        SAY NAME2 @42600000
        SAY UNIDENTIFIED_DESC @42600001
	SAY DESC @42600001
	WRITE_SHORT 0x098 ~%B_SWAVE%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SMASHING_WAVE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN   //
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 149            //
      opcode = 139 //
  END      //
END      //

ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //   ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 149            //
      opcode = 139 //
      parameter1 = 26050
  END      //
END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr426a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr426b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr426c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_SMASHING_WAVE~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Thorn Spray________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/b_thorn.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/TSPRAYT.bam~ ~override~   //
//vvc
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/#TRA_61.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/b_p427.spl~ 1 4 ~CLERIC_THORN_SPRAY~ // Spell
        SAY NAME1 @42700000
        SAY NAME2 @42700000
        SAY UNIDENTIFIED_DESC @42700001
	SAY DESC @42700001
	WRITE_SHORT 0x098 ~%b_thorn%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_THORN_SPRAY~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr427a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr427b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr427c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_THORN_SPRAY~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Wall of Moonlight___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_4/WOMOON.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/WOMOONX.bam~ ~override~   //
//vvc
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/WOMOONX.vvc~ ~override~   //
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/ARE_P22.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/AFT_P21.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_4/B_P428.spl~ 1 4 ~CLERIC_WALL_OF_MOONLIGHT~ // Spell
        SAY NAME1 @42800000
        SAY NAME2 @42800000
        SAY UNIDENTIFIED_DESC @42800001
	SAY DESC @42800001
	WRITE_SHORT 0x098 ~%WOMOON%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_WALL_OF_MOONLIGHT~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 326            //
      STR_VAR resource = EVAL ~%spell_res%A~
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 326 parameter2 = 1 STR_VAR resource = EVAL ~%spell_res%B~ END
//Secondary Spells
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SPPR428A.spl~ ~override/%spell_res%A.spl~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/SPPR428B.spl~ ~override/%spell_res%B.spl~   //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr428a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr428b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr428c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 5   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________Righteous Wrath of the Faithful______________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//display icon not yet available (ADD THEM!)  Using 'Heroism' for now...
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_5/b_wrath.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/ABJURAX.bam~ ~override~   //
//vvc
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#GENABJU.vvc~ ~override~   //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr518a.bam~ ~override~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr518b.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr518c.bam~ ~override~   //bam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/RWOTFAH.BAM~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#EFF_P36.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#EFF_E01.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_5/B_P518.spl~ 1 5 ~CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL~ // Spell
        SAY NAME1 @51800000
        SAY NAME2 @51800000
        SAY UNIDENTIFIED_DESC @51800001
	SAY DESC @51800001
	WRITE_SHORT 0x098 ~%b_wrath%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 318 parameter2 = 50 STR_VAR resource = EVAL ~%spell_res%B~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 146 STR_VAR resource = EVAL ~%spell_res%B~ END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 0            //
      opcode = 318
      parameter2 = 50
      STR_VAR resource = EVAL ~%spell_res%A~
  END      //
//secondary spells
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   // ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/bgee/SPPR518A.spl~ ~override/%spell_res%A.spl~   //
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/bg2ee/SPPR518A.spl~ ~override/%spell_res%A.spl~   //
END
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/SPPR518B.spl~ ~override/%spell_res%B.spl~   // CHECK STRINGS, SOUND EFFECTS AND ANIMATIONS
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%B~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr518a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr518b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr518c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Spike Stones_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_5/b_spkst.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/SSTONEA.BAM~ ~override~   //
//vvc
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/ARE_P04.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/EFF_P48.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#CRE_P03.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_5/B_P519.spl~ 1 5 ~CLERIC_SPIKE_STONES~ // Spell
        SAY NAME1 @51900000
        SAY NAME2 @51900000
        SAY UNIDENTIFIED_DESC @51900001
	SAY DESC @51900001
	WRITE_SHORT 0x098 ~%b_spkst%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SPIKE_STONES~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr519a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr519b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr519c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_SPIKE_STONES~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Shield of Lathander____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/SPSTRENH.bam~ ~override~   //bams  missing! using 'boon of lath' instead (already included)
//sounds
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_5/B_P520.spl~ 1 5 ~CLERIC_SHIELD_OF_LATHANDER~ // Spell
        SAY NAME1 @52000000
        SAY NAME2 @52000000
        SAY UNIDENTIFIED_DESC @52000001
	SAY DESC @52000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SHIELD_OF_LATHANDER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr520a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr520b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr520c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Undead Ward_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_5/UWARD.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/UWARDX.BAM~ ~override~   //
//vvc
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/UWARDX.vvc~ ~override~   //
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#ARE_P28.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#AFT_P27.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_5/B_P521.spl~ 1 5 ~CLERIC_UNDEAD_WARD~ // Spell
        SAY NAME1 @52100000
        SAY NAME2 @52100000
        SAY UNIDENTIFIED_DESC @52100001
	SAY DESC @52100001
	WRITE_SHORT 0x098 ~%UWARD%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNDEAD_WARD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr521a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr521b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr521c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Animal Rage_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#ARE_P28.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#AFT_P27.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_5/b_p522.spl~ 1 5 ~CLERIC_ANIMAL_RAGE~ // Spell
        SAY NAME1 @52200000
        SAY NAME2 @52200000
        SAY UNIDENTIFIED_DESC @52200001
	SAY DESC @52200001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ANIMAL_RAGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//secondary spell
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/SPPR522B.spl~ ~override/%spell_res%b.spl~   //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr522a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr522b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr522c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Mass Cause Light Wounds________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_5/SPARRENP.pro~   //projectile
//probam
//vvc
//bmp
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/STTRAVL6.BMP~ ~override~   //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr523a.bam~ ~override~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr523b.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr523c.bam~ ~override~   //bam
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/TRAVEL.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/CLDAMAH.bam~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/#FF_P103.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_5/b_p523.spl~ 1 5 ~CLERIC_MASS_CAUSE_LIGHT_WOUNDS~ // Spell
        SAY NAME1 @52300000
        SAY NAME2 @52300000
        SAY UNIDENTIFIED_DESC @52300001
	SAY DESC @52300001
	WRITE_SHORT 0x098 ~%SPARRENP%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MASS_CAUSE_LIGHT_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr523a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr523b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_5/sppr523c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x036E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0396 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x03BE ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_MASS_CAUSE_LIGHT_WOUNDS~)=1

//CONTINUE FROM HERE

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 6   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//Double CHECK from here
//FIND ACTUAL UPDATED VERSION (on comp at work?)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Entropy Shield_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//PROTECT FROM ICELANCE when added!  Right now, the description says that it's immune to icelance, though the spell doesn't exist in
//protect from all cantrips/orison missile spells (if implemented)
//added sol's searing orb (seemed approapriate)
//make sure to update description such that all protected spells are listed in description

//Projectile
//probam
//vvc
//bmp
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/ABJURH.bam~ ~override~   //bam
//COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/#ENTROPY.bam~ ~override~   //bam  Missing #ENTROPY.bam
//sounds
//cre
//2da
//itm
//itm icons
//effs
//sunscorch immunity

//if SR not installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SUNSCORCH~
  RET spell_res
END
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/b_p615.spl~ ~override~   //Immunity to sunscorch
  LPF CLONE_EFFECT INT_VAR match_opcode = 325 opcode = 318 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END

//immunity to Icelance
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_ICELANCE~
  RET spell_res
END
COPY_EXISTING ~b_p615.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 325 opcode = 318 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END

END//end if not SR installed

//If SR IS installed
ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN

//immunity to Icelance
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_ICELANCE~
  RET spell_res
END
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/b_p615.spl~ ~override~   //
  LPF CLONE_EFFECT INT_VAR match_opcode = 325 opcode = 318 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END //icelance
  LPF CLONE_EFFECT INT_VAR match_opcode = 325 opcode = 318 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~sppr116~ END //sun scorch
END  //end SR compatibility

//Spell itself
ADD_SPELL ~override/b_p615.spl~ 1 6 ~CLERIC_ENTROPY_SHIELD~ // Spell
        SAY NAME1 @61500000
        SAY NAME2 @61500000
        SAY UNIDENTIFIED_DESC @61500001
	SAY DESC @61500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ENTROPY_SHIELD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321           //
      STR_VAR resource = EVAL ~%spell_res%~
  END
// now sol's searing orb projectile immunity
  LPF CLONE_EFFECT INT_VAR match_opcode = 0 opcode = 83 parameter1 = 0 parameter2 = 257 END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr615a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr615b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr615c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x031E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0346 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x036E ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Whirlwind__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_6/WHIRLW.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/WHIRLWX.bam~ ~override~   //bam
//vvc
//bmp
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/EFF_P105.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_6/b_p617.spl~ 1 6 ~CLERIC_WHIRLWIND~ // Spell
        SAY NAME1 @61700000
        SAY NAME2 @61700000
        SAY UNIDENTIFIED_DESC @61700001
	SAY DESC @61700001
	WRITE_SHORT 0x098 ~%WHIRLW%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_WHIRLWIND~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //change stun notification
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139           //
      parameter1 = 1280
  END      //
END
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //change stun notification ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139           //
      parameter1 = 26050
  END      //
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr617a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr617b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr617c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_WHIRLWIND~)=1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Spiritual Wrath____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_6/IDPRO312.pro~   //projectile
//sec pro
//ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_6/IDPRO207.pro~   //projectile
//don't know how to add this...use an existing one that is similar enough (a non-bouncing lightning bolt...) seems to automatically use the bg2ee equiv
//probam
//vvc
//bmp
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/INVOCH.bam~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/TRA_08.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/TRA_09.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/#EFF_P05.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_6/b_p618.spl~ 1 6 ~CLERIC_SPIRITUAL_WRATH~ // Spell
        SAY NAME1 @61800000
        SAY NAME2 @61800000
        SAY UNIDENTIFIED_DESC @61800001
	SAY DESC @61800001
	WRITE_SHORT 0x098 ~%IDPRO312%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SPIRITUAL_WRATH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr616a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr616b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_6/sppr616c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

OUTER_SET $aoe_spell(~CLERIC_SPIRITUAL_WRATH~)=1

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 7   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Symbol, Pain_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Portrait icon: Nauseated. Update portrait icons and change to pain
//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_7/ICEGLYP.pro~   //projectile
//probam
//vvc
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/ICSPAIN.vvc~ ~override~   //bam
//bmp
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SPGLYPTI.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SHGLYPH.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SPSPAINI.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/CONJUH.bam~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/#EFF_P02.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/#EFF_E04.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/EFF_P22A.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/B_P714a.eff~ ~override~   //
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p714.spl~ 1 7 ~CLERIC_SYMBOL_OF_PAIN~ // Spell
        SAY NAME1 @71400000
        SAY NAME2 @71400000
        SAY UNIDENTIFIED_DESC @71400001
	SAY DESC @71400001
	WRITE_SHORT 0x098 ~%ICEGLYP%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SYMBOL_OF_PAIN~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr714a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr714b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr714c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//BLood Rage immunities
COPY_EXISTING ~b_p422.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 6 opcode = 318 STR_VAR resource = EVAL ~%spell_res%~ END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Symbol, Hopelessness___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_7/b_hpless.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SOHOPEX.bam~ ~override~   //bam
//vvc
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SOHOPEX.vvc~ ~override~   //bam
//bmp
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/PARALH.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SPGLYPTI.bam~ ~override~   //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SHGLYPH.bam~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/#EFF_P02.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/#EFF_E04.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p716.spl~ 1 7 ~CLERIC_SYMBOL_OF_HOPELESSNESS~ // Spell
        SAY NAME1 @71600000
        SAY NAME2 @71600000
        SAY UNIDENTIFIED_DESC @71600001
	SAY DESC @71600001
	WRITE_SHORT 0x098 ~%b_hpless%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SYMBOL_OF_HOPELESSNESS~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr716a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr716b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr716c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//BLood Rage immunities
COPY_EXISTING ~b_p422.spl~ ~override~
  LPF ALTER_EFFECT
   INT_VAR match_opcode = 6 opcode = 318 STR_VAR resource = EVAL ~%spell_res%~ END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Impervious Sanctity of Mind_______________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//bmp
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/ABJURH.BAM~ ~override~   //
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/#EFF_E03.WAV~ ~override~   //
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/#EFF_P01.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
//First, we must copy the spell to protect from symbol of hopelessness
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SYMBOL_OF_HOPELESSNESS~
  RET spell_res
END
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p733.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 0
      opcode = 318
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________________Destruction_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//bmp
//3d animation
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/DESTRUH.BAM~ ~override~   //bam
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/#FF_P113.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p734.spl~ 1 7 ~CLERIC_DESTRUCTION~ // Spell
        SAY NAME1 @73400000
        SAY NAME2 @73400000
        SAY UNIDENTIFIED_DESC @73400001
	SAY DESC @73400001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_DESTRUCTION~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr734a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr734b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr734c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Greater Shield of Lathander__________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 //Note: portrait display icon uses 'shielded'
//Projectile
//probam
//vvc
//bmp
//3d animation
//missing! Using shield (ie first lev wiz spell) in its place
//sounds
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p735.spl~ 1 7 ~CLERIC_GREATER_SHIELD_OF_LATHANDER~ // Spell
        SAY NAME1 @73500000
        SAY NAME2 @73500000
        SAY UNIDENTIFIED_DESC @73500001
	SAY DESC @73500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_GREATER_SHIELD_OF_LATHANDER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr735a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr735b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr735c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  
  
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Mist of Eldath_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~faiths_and_powers/spheres/iwd_spells/priest_7/IDPRO307.pro~   //projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/MOELDAA.BAM~ ~override~   //bam
//vvc
//bmp
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/EFF_P104.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p736.spl~ 1 7 ~CLERIC_MIST_OF_ELDATH~ // Spell
        SAY NAME1 @73600000
        SAY NAME2 @73600000
        SAY UNIDENTIFIED_DESC @73600001
	SAY DESC @73600001
	WRITE_SHORT 0x098 ~%IDPRO307%~  //Projectile
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MIST_OF_ELDATH~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr736a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr736b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr736c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Stalker____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/MOELDAA.BAM~ ~override~   //bam
//vvc
//bmp
//3d animation
//sounds
//cre
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SSHAMB.cre~ ~override~   //
//script
//COMPILE if Needed
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p737.spl~ 1 7 ~CLERIC_STALKER~ // Spell
        SAY NAME1 @73700000
        SAY NAME2 @73700000
        SAY UNIDENTIFIED_DESC @73700001
	SAY DESC @73700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STALKER~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr737a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr737b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr737c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Energy Drain_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//bmp
//3d animation
//sounds
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/EFF_M07.WAV~ ~override~   //
//cre
//script
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p739.spl~ 1 7 ~CLERIC_ENERGY_DRAIN~ // Spell
        SAY NAME1 @73900000
        SAY NAME2 @73900000
        SAY UNIDENTIFIED_DESC @73900001
	SAY DESC @73900001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ENERGY_DRAIN~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 25803 //text display
  END      //
END
//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SPWI914a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SPWI914b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SPWI914c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________________Wither_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Projectile
//probam
//vvc
//bmp
//3d animation
//missing! Using Dust?  Why not
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/DUST.BAM~ ~override~   //
//sounds
//cre
//2da
//itm
//itm icons
//secondary spell
//Spell itself
ADD_SPELL ~faiths_and_powers/spheres/iwd_spells/priest_7/b_p740.spl~ 1 7 ~CLERIC_WITHER~ // Spell
        SAY NAME1 @74000000
        SAY NAME2 @74000000
        SAY UNIDENTIFIED_DESC @74000001
	SAY DESC @74000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_WITHER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 54337 //text display  'diseased'
  END      //
END
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 31238 //text display  'diseased'
  END      //
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 272
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//eff
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/SPPR740.eff~ ~override/%spell_res%.eff~   //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr740a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr740b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr740c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  Special   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//Now add Blood Rage

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Blood Rage________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ADD_SPELL ~override/b_p422.spl~ 1 4 ~CLERIC_BLOOD_RAGE~ // Spell
        SAY NAME1 @42200000
        SAY NAME2 @42200000
        SAY UNIDENTIFIED_DESC @42200001
	SAY DESC @42200001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_BLOOD_RAGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 0 opcode = 321 STR_VAR resource = EVAL ~%spell_res%~ END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 1 opcode = 318 STR_VAR resource = EVAL ~%spell_res%~ END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr422a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr422b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_4/sppr422c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//Now add ISoM
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Impervious Sanctity of Mind_______________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Immunity to Blood Rage first
COPY_EXISTING ~b_p733.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 1
      opcode = 206
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//Now add spell
ADD_SPELL ~override/b_p733.spl~ 1 7 ~CLERIC_IMPERVIOUS_SANCTITY_OF_MIND~ // Spell
        SAY NAME1 @73300000
        SAY NAME2 @73300000
        SAY UNIDENTIFIED_DESC @73300001
	SAY DESC @73300001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_IMPERVIOUS_SANCTITY_OF_MIND~
  RET spell_res
END

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr733a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr733b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_7/sppr733c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x009E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00C6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x00EE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0116 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x013E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0166 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x018E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01B6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x01DE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0206 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x022E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x0256 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x027E ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02A6 ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02CE ~%spell_res%B~
  WRITE_EVALUATED_ASCII 0x02F6 ~%spell_res%B~

//Now add Exaltation
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Exaltation________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//exaltation protection from blood rage
COPY_EXISTING ~b_p321.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 4 opcode = 321 timing = 0 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 106 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END
//now add spell
ADD_SPELL ~override/b_p321.spl~ 1 3 ~CLERIC_EXALTATION~ // Spell
        SAY NAME1 @32100000
        SAY NAME2 @32100000
        SAY UNIDENTIFIED_DESC @32100001
	SAY DESC @32100001

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_EXALTATION~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr321a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr321b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~faiths_and_powers/spheres/iwd_spells/priest_3/sppr321c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SR NWN-style Deflection

ACTION_IF MOD_IS_INSTALLED ~spell_rev.tp2~ ~55~ BEGIN

 ACTION_PHP_EACH aoe_spell AS spell_name => r2 BEGIN
  
  OUTER_SET spell_num = (IDS_OF_SYMBOL (~spell~ ~%spell_name%~))
  ACTION_IF spell_num > 0 BEGIN
	OUTER_SNPRINT 1 spell_type ~%spell_num%~
	OUTER_SNPRINT (0 - 3) type_num ~%spell_num%~
	ACTION_IF spell_type = 2 BEGIN
      OUTER_SPRINT i2 ~spwi%type_num%~
    END
	ACTION_IF spell_type = 1 BEGIN
      OUTER_SPRINT i2 ~sppr%type_num%~
    END

	  OUTER_SET found=0
	  OUTER_SPRINT letter ~d~
	  ACTION_FOR_EACH char_check IN d e f g h i j k l m BEGIN
	    ACTION_IF found=0 BEGIN
	      ACTION_IF NOT FILE_EXISTS_IN_GAME ~%i2%%char_check%.spl~ BEGIN
	        OUTER_SET found=1
	        OUTER_SPRINT letter ~%char_check%~
	      END
	    END
	  END

	  ACTION_IF found && r2 && (FILE_EXISTS_IN_GAME ~%i2%.spl~) BEGIN
		PRINT ~%i2% is arcane AoE~
	    COPY_EXISTING ~%i2%.spl~ ~override/%i2%%letter%.spl~ // cloning original into the secondary spell
	      WRITE_ASCII 0x8 ~~ (8) // clearing out the name
	      GET_OFFSET_ARRAY headers 0x64 4 0x68 2 0 0 0x28
	      PHP_EACH headers AS i => r BEGIN
	        WRITE_SHORT (r+0x0c) 1 // target = creature
	        WRITE_SHORT (r+0x26) 1 // projectile = none
	      END
	    BUT_ONLY

	    COPY_EXISTING ~%i2%.spl~ ~override~        // modifying the original
	      READ_LONG 0x34  level
	      READ_LONG 0x64  ab_off
	      READ_SHORT 0x68 ab_num
	      READ_LONG 0x6a  ef_off
	      READ_SHORT 0x70 cast_num // global effects aka casting features

	      total_eff=cast_num
	      FOR (i=0;i<ab_num;i+=1) BEGIN
	        READ_SHORT  (ab_off+i*0x28+0x1e) ef_num  // effect number
	        READ_SHORT  (ab_off+i*0x28+0x20) ef_ind  // effect index
	        total_eff+=ef_num
	      END

	      DELETE_BYTES ef_off ((total_eff - 1)*0x30)
	      DELETE_BYTES ab_off ((ab_num - 1)*0x28)
	      WRITE_SHORT 0x68 1
	      WRITE_LONG 0x6a  (ef_off - (ab_num - 1)*0x28)
	      WRITE_SHORT 0x70 0
	      WRITE_SHORT (ab_off+0x1e) 1
	      WRITE_SHORT (ab_off+0x20) 0

      // ability header
	      WRITE_SHORT (ab_off+0x10) 1 // level required

      // effect
	      offset=(ef_off - (ab_num - 1)*0x28)
	      WRITE_SHORT (offset+0x00) 146   // opcode = cast spell on creature
	      WRITE_BYTE  (offset+0x02) 2     // target = pre-target
	      WRITE_BYTE  (offset+0x03) level   // power level = spell level
	      WRITE_LONG  (offset+0x04) 0     // parameter 1 = caster's level
	      WRITE_LONG  (offset+0x08) 1     // parameter 2 = instant
	      WRITE_BYTE  (offset+0x0c) 1     // timing mode = permanent
	      WRITE_ASCII (offset+0x0d) ~~ (5)  // clearing out the space
	      WRITE_BYTE  (offset+0x12) 100   // probability 1 = 100%
	      WRITE_BYTE  (offset+0x13) 0     // probability 2 = 0%
	      WRITE_ASCIIE (offset+0x14) ~%i2%%letter%~ (8) // resource
	      WRITE_ASCII (offset+0x1c) ~~ (20) // clearing out the space
	    BUT_ONLY
    
	  END
  END
 END // ACTION_PHP_EACH

END
