// SPHERE NAMES___________________________________________________________________
//
// You can define the names of your spheres in the right-hand column
// There can be 23 spheres at most; they must correspond to the FnP spheres
// So DO NOT change anything in the left column.

DEFINE_ACTION_MACRO d5_define_sphere_names BEGIN

<<<<<<<< d5/d5altsph.2da
2DA
Universal		Universal
Life 			Life
Death 			Necromantic
Benediction 	Common
Destruction 	Law
Protection 		Protection
War 			Combat
Exploration     Travelers
Knowledge 		Knowledge
Deception 		Chaos
Thought 		Thought
Dread 			Doom
Vigor 			Vigor
Affliction 		Chaos
Animal 			Animal
Plant 			Plant
Earth 			Earth
Air 			Air
Water 			Water
Fire 			Fire
Light 			Light
Shadow 			Shadow
Magic 			...
Astral	 		Astral
>>>>>>>> 

END	//	end sphere names macro
//____________________________________________________________________________________

// spell spheres

// First item: spell IDS name *or* RES filename
// numeric value in the middle: desired spell level, can be 0 (no change) or 1-7
// Item after equals sign: sphere

// To change which sphere a spell belongs to, 
// simply change the entry in the right-most column to the new sphere.
// You don't have to actually move the spell, though you can if you want to.

//  UNIVERSAL
// 	universal spells will be available to every kit, regardless of their defined sphere assignments
//	this is basically the "All" sphere
// 	this "sphere" MUST MUST MUST have at least one spell of each spell level
// 	and their spell level MUST NOT be changed from the vanilla game (use 0)
// 	those are the rules you MUST abide by if you want to change which spells are uiniversal

DEFINE_ACTION_MACRO d5_define_sphere_spells BEGIN

<<<<<<<< d5/d5spsph.2da
2DA V1.0 
SPELL
			LEVEL		FnP_SPHERE		DESC_SPHERE
CLERIC_BLESS                           	0	=	Universal // level 1
CLERIC_CURSE                           	0	=	Universal // level 1
CLERIC_CHANT                           	0	=	Universal // level 2
CLERIC_PRAYER                          	0	=	Universal // level 3
CLERIC_DISPEL_MAGIC                    	0	=	Universal // level 3
CLERIC_REMOVE_CURSE                    	0	=	Universal // level 3
CLERIC_LESSER_RESTORATION              	0	=	Universal // level 4
CLERIC_RECITATION                      	0	=	Universal // level 4
CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL 	0	=	Universal // level 5
CLERIC_WONDROUS_RECALL                 	0	=	Universal // level 6
CLERIC_HOLY_WORD                       	0	=	Universal // level 7
CLERIC_UNHOLY_WORD                     	0	=	Universal // level 7
CLERIC_CURE_LIGHT_WOUNDS               	1	=	Common 
CLERIC_SLOW_POISON                     	1	=	Common  //B_Spells protection from  - 2nd level protection
CLERIC_BLESS_WATER                     	1	=	Common
CLERIC_CAUSE_LIGHT_WOUNDS              	1	=	Common
WIZARD_PROTECTION_FROM_PETRIFICATION    1	=	Exploration
CLERIC_CURSE                            1	=	Dread
CLERIC_DOOM                             1	=	Dread
CLERIC_CURE_MODERATE_WOUNDS            	2	=	Common  //SR accounted for
CLERIC_CURE_DISEASE                    	2	=	Common
CLERIC_CAUSE_MODERATE_WOUNDS           	2	=	Decay  //SR accounted for
CLERIC_REMOVE_PARALYSIS                 2	=	Exploration
WIZARD_BATTERING_RAM                    2	=	Destruction // sr battering ram... make level 2?
CLERIC_REMOVE_FEAR                      2	=	War
CLERIC_DRAW_UPON_HOLY_MIGHT             2	=	Vigor
CLERIC_HOLD_PERSON                      3	=	Dread
CLERIC_CURE_MEDIUM_WOUNDS              	3	=	Common
CLERIC_CAUSE_MEDIUM_WOUNDS              3	=	Destruction
CLERIC_HOLY_SMITE                       3	=	Destruction
CLERIC_UNHOLY_BLIGHT                    3	=	Destruction
CLERIC_INVISIBILITY_PURGE               3	=	Knowledge
CLERIC_FREE_ACTION                      3	=	Exploration
CLERIC_EXALTATION                       3	=	Thought
CLERIC_NEGATIVE_PLANE_PROTECTION       	4	=	Necromantic
CLERIC_CURE_SERIOUS_WOUNDS             	4	=	Common
CLERIC_DEATH_WARD                      	4	=	Necromantic
CLERIC_CURE_CRITICAL_WOUNDS            	5	=	Common
CLERIC_MASS_CURE                       	5	=	Common
CLERIC_CHAOTIC_COMMANDS                 5	=	Thought
CLERIC_HEAL                            	6	=	Common
CLERIC_RESTORATION                     	7	=	Common

CLERIC_EXALTATION                      	3	=	Thought
CLERIC_DISRUPT_UNDEAD                  	1	=	Necromantic
CLERIC_RESURRECTION                    	7	=	Healing
CLERIC_EYES_OF_THE_DEAD                	1	=	Necromantic
CLERIC_PACIFY_DEAD                     	2	=	Necromantic
CLERIC_CIRCLE_OF_BONES                 	3	=	Necromantic  //Sr accounted for
CLERIC_FAVOR_OF_ILMATER                	3	=	Necromantic
CLERIC_ANIMATE_DEAD                    	3	=	Necromantic
CLERIC_RAISE_DEAD                      	5	=	Necromantic
CLERIC_REPULSE_UNDEAD                  	5	=	Necromantic  // SR repulsion
B_W631                                 	6	=	Necromantic  //soul eater (needed???)
CLERIC_FINGER_OF_DEATH                 	7	=	Necromantic
CLERIC_BINDING                         	1	=	Creation
WIZARD_GREASE                          	2	=	Creation 
WIZARD_GLITTERDUST                     	2	=	Creation 
WIZARD_WEB                             	3	=	Creation
WIZARD_PRISMATIC_SPRAY                 	7	=	Creation
CLERIC_CAUSE_DISEASE                   	1	=	Decay  //SR accounted for
WIZARD_BLINDNESS                       	2	=	Decay
WIZARD_RAY_OF_ENFEEBLEMENT             	2	=	Decay
CLERIC_MOLD_TOUCH                      	3	=	Decay
CLERIC_CAUSE_MEDIUM_WOUNDS             	3	=	Decay
CLERIC_CAUSE_SERIOUS_WOUNDS            	4	=	Decay
CLERIC_POISON                          	4	=	Decay
CLERIC_CAUSE_CRITICAL_WOUNDS           	5	=	Decay
CLERIC_MASS_CAUSE_LIGHT_WOUNDS         	5	=	Decay  //SR accounted for
CLERIC_SLAY_LIVING                     	5	=	Decay
CLERIC_HARM                            	6	=	Decay
CLERIC_DOLOROUS_DECAY                  	6	=	Decay
CLERIC_WITHER                          	7	=	Decay
CLERIC_DESTRUCTION                     	7	=	Decay

CLERIC_HAND_OF_CARNAGE                  1	=	Destruction
CLERIC_SHATTER                          2	=	Destruction
WIZARD_SHOUT                            3	=	Destruction
b_w431                                  4	=	Destruction // shout
CLERIC_CAUSE_SERIOUS_WOUNDS             4	=	Destruction
CLERIC_CAUSE_CRITICAL_WOUNDS            5	=	Destruction
CLERIC_MASS_CAUSE_LIGHT_WOUNDS          5	=	Destruction
CLERIC_HARM                             6	=	Destruction
WIZARD_DISINTEGRATE                     6	=	Destruction
CLERIC_DESTRUCTION                      7	=	Destruction
CLERIC_PROTECT_FROM_EVIL                1	=	Protection
CLERIC_ARMOR_OF_FAITH                   1	=	Protection
WIZARD_SHIELD                           2	=	Protection
CLERIC_GLYPH_OF_WARDING                 3	=	Protection
CLERIC_PROTECTION_FROM_EVIL_10_FOOT     4	=	Protection
CLERIC_REPULSION                        5	=	Protection // sr repulsion
CLERIC_SHIELD_OF_LATHANDER              5	=	Protection
CLERIC_PHYSICAL_MIRROR                  6	=	Protection
CLERIC_SHIELD_OF_THE_ARCHONS            7	=	Protection
CLERIC_GREATER_SHIELD_OF_LATHANDER      7	=	Protection
CLERIC_ABUNDANT_AMMO                    1	=	War
CLERIC_MAGIC_WEAPON                     1	=	War
CLERIC_SPIRITUAL_HAMMER                 2	=	War
CLERIC_STRENGTH_OF_ONE                  3	=	War
CLERIC_HOLY_POWER                       3	=	War
CLERIC_DEFENSIVE_HARMONY                4	=	War
CLERIC_STAR_METAL_CUDGEL                4	=	War
CLERIC_RIGHTEOUS_MAGIC                  5	=	War
CLERIC_BLADE_BARRIER                    6	=	War
CLERIC_SYMBOL_FEAR                      7	=	War
SR_WIZARD_EXPEDITIOUS_RETREAT           1	=	Exploration // SR exped. retreat
NOSR_b_w101                             1	=	Exploration // FnP Expeditious Retreat
CLERIC_FIND_TRAPS                       1	=	Exploration
d5fnp02                                 2	=	Exploration // mazzy haste (self-only)
CLERIC_FAR_SIGHT                        3	=	Exploration
WIZARD_EYE                              4	=	Exploration
WIZARD_DIMENSION_DOOR                   5	=	Exploration
WIZARD_TELEPORT_FIELD                   6	=	Exploration
WIZARD_IMPROVED_HASTE                   6	=	Exploration
WIZARD_FREEDOM                          7	=	Exploration
WIZARD_MAZE                             7	=	Exploration
d5fnp03                                 0	=	knowledge // identify
CLERIC_DETECT_EVIL                      1	=	Knowledge
WIZARD_TRUE_STRIKE                      2	=	Knowledge // sr true strike
WIZARD_CLAIRVOYANCE                     2	=	Knowledge
WIZARD_ORACLE                           5	=	Knowledge
CLERIC_TRUE_SIGHT                       6	=	Knowledge
CLERIC_SYMBOL_STUN                      7	=	Knowledge
CLERIC_CAMOUFLAGE                       1	=	Deception
CLERIC_CHARM_PERSON                     1	=	Thought
CLERIC_ENTHRALL                         2	=	Thought
CLERIC_MURDEROUS_COMMAND                3	=	Thought
CLERIC_DICTATE                          3	=	Thought
CLERIC_RIGID_THINKING                   3	=	Thought
CLERIC_MENTAL_DOMINATION                4	=	Thought
CLERIC_BLOOD_RAGE                       4	=	Thought
b_w428                                  4	=	Thought // Emotion: Fear
WIZARD_EMOTION_FEAR                     4	=	Thought
b_w429                                  4	=	Thought // Emotion: Hope
WIZARD_EMOTION_HOPE                     4	=	Thought
b_w427                                  5	=	Thought // Emotion: Courage
WIZARD_EMOTION_COURAGE                  5	=	Thought
CLERIC_GREATER_COMMAND                  5	=	Thought
CLERIC_CONFUSION                        6	=	Thought
CLERIC_NATURE_BEAUTY                    7	=	Thought
CLERIC_IMPERVIOUS_SANCTITY_OF_MIND      7	=	Thought
CLERIC_COMMAND                          1	=	Thought
CLERIC_FORBID                           2	=	Dread
CLERIC_CLOAK_OF_FEAR                    3	=	Dread
WIZARD_GREATER_MALISON                  4	=	Dread
WIZARD_EMOTION_FEAR                     4	=	Dread
WIZARD_WAVES_OF_FATIGUE                 5	=	Dread
CLERIC_MISFIRE                          5	=	Dread
WIZARD_EMOTION_HOPELESSNESS             5	=	Dread
CLERIC_SPIRITUAL_WRATH                  6	=	Dread
CLERIC_SYMBOL_OF_HOPELESSNESS           7	=	Dread
CLERIC_AID                              1	=	Vigor
CLERIC_UNFAILING_ENDURANCE              1	=	Vigor
WIZARD_STRENGTH                         2	=	Vigor
CLERIC_CURE_DISEASE                     2	=	Vigor
CLERIC_REMOVE_PARALYSIS                 2	=	Vigor
CLERIC_FAVOR_OF_ILMATER                 3	=	Vigor
CLERIC_NEUTRALIZE_POISON                3	=	Vigor
CLERIC_CHAMPIONS_STRENGTH               4	=	Vigor
CLERIC_ANIMAL_RAGE                      5	=	Vigor
CLERIC_REGENERATE                       6	=	Vigor
CLERIC_CAUSE_DISEASE                    1	=	Affliction
WIZARD_BLINDNESS                        2	=	Affliction
WIZARD_RAY_OF_ENFEEBLEMENT              2	=	Affliction
CLERIC_MOLD_TOUCH                       3	=	Affliction
WIZARD_CONTAGION                        3	=	Affliction
CLERIC_POISON                           4	=	Affliction
CLERIC_WAVES_OF_AGONY                   5	=	Affliction
CLERIC_CLOUD_OF_PESTILENCE              5	=	Affliction
CLERIC_DOLOROUS_DECAY                   6	=	Affliction
CLERIC_SYMBOL_OF_PAIN                   6	=	Affliction
CLERIC_WITHER                           7	=	Affliction
CLERIC_ANIMAL_EYES                      1	=	Animal
CLERIC_HOLD_ANIMAL                      1	=	Animal
CLERIC_ANIMAL_SUMMONING_LEVEL_1         1	=	Animal // SR Animal Summon 1
CLERIC_BEAST_CLAW                       2	=	Animal
CLERIC_ANIMAL_SUMMONING_LEVEL_2         2	=	Animal // SR Animal Summon 2
CLERIC_SUMMON_INSECTS                   3	=	Animal
CLERIC_FERAL_INSTINCT                   3	=	Animal
CLERIC_ANIMAL_SUMMONING_LEVEL_3         3	=	Animal // SR Animal Summon 3
d5fnp04                                 3	=	Animal // Magic Fang
SR_CLERIC_ANIMAL_SUMMONING_LEVEL_4      4	=	Animal // SR Animal Summon 4
NOSR_CLERIC_ANIMAL_SUMMONING_1          4	=	Animal
CLERIC_GIANT_INSECT                     4	=	Animal
SR_CLERIC_ANIMAL_SUMMONING_LEVEL_5      5	=	Animal // SR Animal Summon 5
NOSR_CLERIC_ANIMAL_SUMMONING_2          5	=	Animal
CLERIC_INSECT_PLAGUE                    5	=	Animal
d5fnp05                                 5	=	Animal // Animal Growth
SR_CLERIC_ANIMAL_SUMMONING_LEVEL_6      6	=	Animal // SR Animal Summon 6
NOSR_CLERIC_ANIMAL_SUMMONING_3          6	=	Animal
SR_CLERIC_ANIMAL_SUMMONING_LEVEL_7      7	=	Animal // SR Animal Summon 7
NOSR_CLERIC_CONJURE_ANIMALS             7	=	Animal
CLERIC_CREEPING_DOOM                    7	=	Animal
CLERIC_ENTANGLE                         1	=	Plant
CLERIC_GOOD_BERRIES                     1	=	Plant
CLERIC_GOODBERRY                        1	=	Plant
CLERIC_SHILLELAGH                       1	=	Plant
CLERIC_BARKSKIN                         2	=	Plant
CLERIC_THORN_SPRAY                      3	=	Plant
CLERIC_SNARE                            3	=	Plant
CLERIC_SPIKE_GROWTH                     4	=	Plant
CLERIC_CALL_WOODLAND_BEINGS             5	=	Plant
CLERIC_NATURES_WRATH                    6	=	Plant
CLERIC_ASSASSIN_VINES                   6	=	Plant
CLERIC_STALKER                          7	=	Plant
CLERIC_MAGIC_STONE                      1	=	Earth
CLERIC_PROTECTION_FROM_LIGHTNING        2	=	Earth
CLERIC_STONE_FIST                       3	=	Earth
CLERIC_SPIKE_STONES                     4	=	Earth
CLERIC_IRONSKIN                         5	=	Earth
WIZARD_STONE_TO_FLESH                   5	=	Earth
CLERIC_CONJURE_EARTH_ELEMENTAL          6	=	Earth
WIZARD_FLESH_TO_STONE                   6	=	Earth
CLERIC_EARTHQUAKE                       7	=	Earth
WIZARD_IRON_BODY                        7	=	Earth // need to add for non-IWD
CLERIC_ZONE_OF_SWEET_AIR                1	=	Air
CLERIC_OBSCURING_MIST                   1	=	Air // SR obscuring mist
WIZARD_STINKING_CLOUD                   2	=	Air
NOSR_CLERIC_STORM_SHELL                 3	=	Air
SR_CLERIC_STORM_SHIELD                  3	=	Air // SR storm shield
CLERIC_CLOUDBURST                       3	=	Air
CLERIC_STORMWALL                        4	=	Air
b_c401                                  4	=	Air // stormwall
CLERIC_CALL_LIGHTNING                   4	=	Air
CLERIC_STATIC_CHARGE                    5	=	Air
CLERIC_WHIRLWIND                        5	=	Air
//CLERIC_PROTECTION_FROM_LIGHTNING        5	=	Air // SR pro. lightning
CLERIC_ENTROPY_SHIELD                   6	=	Air
WIZARD_CHAIN_LIGHTNING                  6	=	Air
SR_CLERIC_CONJURE_AIR_ELEMENTAL         6	=	Air // SR air elemental
WIZARD_DEATH_FOG                        7	=	Air
CLERIC_AERIAL_SERVANT                   7	=	Air
CLERIC_FROST_FINGERS                    1	=	Water
b_c103                                  1	=	Water // frost fingers
CLERIC_RESIST_COLD                      1	=	Water
CLERIC_WATERY_FIST                      2	=	Water
CLERIC_ICE_BLADE                        2	=	Water
b_c203                                  2	=	Water // ice blade
WIZARD_SNILLOCS_SNOWBALL_SWARM          2	=	Water
b_w204                                  2	=	Water // Snowball Swarm
WIZARD_ICELANCE                         3	=	Water
b_w327                                  3	=	Water // icelance
CLERIC_SMASHING_WAVE                    4	=	Water
WIZARD_VITRIOLIC_SPHERE                 4	=	Water
b_w432                                  4	=	Water // vitriolic sphere
WIZARD_CONE_OF_COLD                     4	=	Water
WIZARD_ICE_STORM                        5	=	Water
CLERIC_PROTECTION_FROM_ACID             5	=	Water // SR pro. acid
CLERIC_PROTECTION_FROM_COLD             5	=	Water // SR pro. cold
CLERIC_MIST_OF_ELDATH                   6	=	Water
CLERIC_CONJURE_WATER_ELEMENTAL          6	=	Water
b_pr602                                 6	=	Water // water elemental
WIZARD_ACID_STORM                       7	=	Water
b_w724                                  7	=	Water // acid storm
WIZARD_BURNING_HANDS                    1	=	Fire
CLERIC_RESIST_FIRE                      1	=	Fire
CLERIC_FLAME_BLADE                      2	=	Fire
CLERIC_FIRE_TRAP                        2	=	Fire
NOSR_CLERIC_PROTECTION_FROM_FIRE        3	=	Fire
CLERIC_PRODUCE_FIRE                     3	=	Fire
WIZARD_FLAME_ARROW                      4	=	Fire
SR_CLERIC_PROTECTION_FROM_FIRE          4	=	Fire
WIZARD_FIRE_SHIELD_RED                  5	=	Fire
CLERIC_FLAME_STRIKE                     5	=	Fire
CLERIC_CONJURE_FIRE_ELEMENTAL           6	=	Fire
CLERIC_FIRE_SEEDS                       6	=	Fire
CLERIC_FIRE_STORM                       7	=	Fire
CLERIC_SUNSCORCH                        1	=	Light
CLERIC_ALICORN_LANCE                    2	=	Light
WIZARD_GLITTERDUST                      2	=	Light
NOSR_CLERIC_REPULSE_UNDEAD              3	=	Light
CLERIC_MOONBLADE                        3	=	Light
CLERIC_WALL_OF_MOONLIGHT                4	=	Light
CLERIC_FALSE_DAWN                       5	=	Light
CLERIC_PIXIE_DUST                       6	=	Deception
CLERIC_SOL_SEARING_ORB                  6	=	Light
CLERIC_SUNRAY                           7	=	Light
CLERIC_SANCTUARY                        1	=	Shadow
NOSR_WIZARD_BLINDNESS                   2	=	Shadow
SR_b_w206                               2	=	Shadow // Blindness (and no conflicts with SR)
CLERIC_CLOAK_DARKNESS                   3	=	Shadow
WIZARD_SHADOW_MONSTERS                  3	=	Shadow
b_w426                                  3	=	Shadow // Shadow Monsters
WIZARD_PHANTOM_BLADE                    4	=	Shadow
B_SSTEP                                 4	=	Shadow // shadowstep
WIZARD_SHADOW_DOOR                      5	=	Shadow
d5fnp01                                 5	=	Shadow // summon shadow
WIZARD_SHADES                           6	=	Shadow
B_W629                                  6	=	Shadow // Shades
WIZARD_WRAITH_FORM                      7	=	Shadow
WIZARD_POWER_WORD_BLIND                 7	=	Shadow
CLERIC_MISCAST_MAGIC                    1	=	Magic
CLERIC_SILENCE_15_FOOT                  2	=	Magic
CLERIC_DISPEL_MAGIC                     3	=	Magic
WIZARD_MINOR_SPELL_DEFLECTION           3	=	Magic
WIZARD_SECRET_WORD                      4	=	Magic
NOSR_WIZARD_MINOR_SPELL_TURNING         5	=	Magic
SR_WIZARD_SPELL_DEFLECTION              5	=	Magic
WIZARD_BREACH                           5	=	Magic
CLERIC_MAGIC_RESISTANCE                 6	=	Magic
WIZARD_GLOBE_OF_INVULNERABILITY         6	=	Magic
WIZARD_PIERCE_SHIELD                    7	=	Magic
CLERIC_FAERIE_FIRE                      1	=	Astral
CLERIC_SPIRIT_WARD                      1	=	Astral // modify to work against all planar creatures
CLERIC_WRITHING_FOG                     2	=	Astral
CLERIC_SPIRITUAL_CLARITY                3	=	Astral
CLERIC_SPIRIT_FIRE                      4	=	Astral // modify to work against all planar creatures
CLERIC_SPIRITUAL_LOCK                   5	=	Astral // modify to work against all planar creatures
WIZARD_BANISHMENT                       5	=	Astral // sr banishment
CLERIC_RECALL_SPIRIT                    6	=	Astral
CLERIC_BOLT_OF_GLORY                    6	=	Astral
CLERIC_ETHER_GATE                       7	=	Astral
WIZARD_SUMMON_FIEND                     7	=	Astral
>>>>>>>>

END	//	end sphere spells macro

/*

NOTES:
//B_CLERIC_SLOW_POISON                 , 2 => Protection  //B_Spells protection from poison/disease
//WIZARD_INCENDIARY_CLOUD                , 7 => Fire //QUEST???

ADD:
//Divine Symbol                        , 2 => Creation //NEW SPELL
//Minor Creation                       , 2 => Creation // NEW SPELL http://pathfinder.d20srd.org/coreRulebook/spells/minorCreation.html#minor-creation //create norm objects 10 mins/level
//Amanuensis                           , 4 => Creation // NEW SPELL Creates temporary scrolls p 22
//Disable Construct                    , 4 => Creation // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/d/disable-construct no save 1st round. Save each round after
//Vesting                              , 5 => Creation // NEW SPELL Create magic potions or wands
//Heroes' feast                        , 6 => Creation // NEW SPELL
//Animate Weapon                       , 7 => Creation // NEW SPELL p37, but 7th lev, so mordy like
//d5clgol /*clay golem*/                 , 5
//d5stgol /*stone golem*/                , 6
//d5jugol /*juggernaut golem*/           , 7 // or make this the HLA...?
//WIZARD_MORDENKAINENS_SWORD             , 7 // or 6
//Forced match                         , 2 => Combat //NEW SPELL
//Liberation                           , 1 => Travelers // NEW SPELL  (save to remove hold/charm like effects)
//Lighten Load                         , 2 => Travelers //Creates a temporary bag of holding that lasts for 8 hours.  Warning! Empty before duration ends.  Only 1 spell of this kind can be active at any given time.  (MAYBE dup objects and replacing with 1/2 weight replacements p375) 
//Longstrider                          , 3 => Travelers // NEW SPELL  (2x move 8 hr; not in combat)
//Priest Wiz eye type thing            , 4 => Travelers // NEW SPELL (as wiz)
//Dimensional Jump                     , 4 => Travelers // NEW SPELL (as wiz)
//Clear the Path                       , 5 => Travelers // NEW SPELL p122 Constantly Dispel spells like web and entangle over a period of time (remove traps possible???) 
//Helping Hand                         , 5 => Travelers // NEW SPELL Creates a 'hand' that can perform thief duties or carry load (by opening a store).  Cannot fight or do anything combat related.                     
//Foresight                            , 5 => Divination //NEW SPELL 1 round cast, lasts 1 hour, +2 AC, saves, immune to backstab, +2 bonus to weapon and casting speed caster only
//Thief's Lament                       , 4 => Wards //NEW SPELL (creates an 'imaginary' trap, doing 1d8 non-lethal dam/2 lev
//Impart knowledge                     , 2 => Thought //Give a proficiency p347
//Iron Mind                            , 2 => Thought  //NEW SPELL As wiz spell
//Agonizing rebuke                     , 3 => Thought //NEW SPELL Source???? Cre that hits caster suffers magic damage if no save
//Forget                               , 4 => Thought //NEW SPELL Target forgets a spell or 2
//Impgrenatable Mind                   , 4 => Thought //NEW SPELL +4 saves vs. spell, save where no save allowed (doable? relevant?) 2 turn duration p349
//Mind Sight                           , 5 => Thought //NEW SPELL as wiz spell
//Disbelief                            , 6 => Thought //NEW SPELL p208.  Caster gains prot vs. all creatures, but cannot target other creatues with spells/abilities (??)
//Vigil                                , 1 => Charm // NEW SPELL p.20 no Exhaustion 1 hour, immune to sleep effects
//Compassion                           , 2 => Charm // NEW SPELL
//Bliss                                , 2 => Charm // NEW SPELL p76 sim to waves of pain
//Attraction                           , 2 => Charm // NEW SPELL p 44 Like Friends
//Bad Medicine                         , 4 => Charm //NEW SPELL p52
//Calm                                 , 1 => Law //NEW SPELL Target saves to have fear and other emotion spells removed
//Uncertainty                          , 2 => Law    // NEW SPELL p22 Speed/weapon/casting/movement penalty
//Still Mind                           , 5 => Law  // NEW SPELL Remove and protect against Fear, other emotion spells and charm/dominate effects
//Rebuke                               , 5 => Law // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/r/rebuke
//Dispel Chaos                         , 5 => Law // NEW SPELL Dispels chaos inducing spells (confusion, etc.)
//Shield of Law                        , 5 => Law // NEW SPELL http://pathfinder.d20srd.org/coreRulebook/spells/shieldOfLaw.html#shield-of-law Not just effective vs. chaotic creatures
//Berserk                              , 1 => Chaos // NEW SPELL Touch a creature to instill a berserker rage,like the berserk ability
//Chaos Ward                           , 1 => Chaos // NEW SPELL p111
//Hideous Laughter                     , 2 => Chaos // NEW SPELL wiz p918
//Havoc                                , 7 => Chaos //NEW SPELL Creates a vortex around the caster.  Enemies are damaged and can be knocked back p74 pfrpg
//Chain Madness                        , 7 => Chaos //NEW SPELL Confusion but like chain lightning p108
//Heat Metal                           , 2 => Earth // NEW SPELL p328
//Animate Rock                         , 7 => Earth //NEW SPELL 'creature' rock that can attack for caster) P36
// Whispering wind                     , 1 => Air // NEW SPELL as aud glammer
//Gaseous form                         , 4 => Air // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/g/gaseous-form no attack, slow move, almost invulnerable, wind spells push
//Adaption                             , 4 => Air //NEW SPELL immune to poison/clouds p
//winds of vengeance                   , 7 => Air  // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/w/winds-of-vengeance
//CLERIC_FLAME_SPHERE                  , 2 => Fire // NEW SPELL  Summons a 'creature' with fire elem anim, any creature within 5' save vs. breath or take x dam
//CLERIC_WALL_Of_FIRE                  , 4 => Fire   //NEW SPELL   AMIM IN IWD2
//Blinding Ray                         , 2 => Sun // NEW SPELL
//Heat Exhaustion                      , 3 => Sun //NEW SPELL p327
//CLERIC_BLESSED_WARMTH                 , 4 => Sun  //NEW SPELL Protections vs. cold and heat p75
//CLERIC_SUNBEAM                       , 7 => Sun // NEW SPELL like MMM but 1x/level http://pathfinder.d20srd.org/coreRulebook/spells/sunbeam.html#sunbeam
//Storm of Vengeance                    , 7 => Weather //NEW SPELL  http://www.d20srd.org/srd/spells/stormOfVengeance.htm

*/

//___________________________________________________________________________________




// FnP DEITY/KIT SPHERE ASSIGNMENTS___________________________________________________

DEFINE_ACTION_MACRO d5_deity_kit_sphere_lists BEGIN

// UR-PRIEST__________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ur_priest_spheres 
  RET_ARRAY ur_priest_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ur_priest_spheres_array BEGIN
	Healing		 		=> x
	Necromantic		 	=> major
	Creation			=> x
	Decay			 	=> major
	Protection		 	=> major
	Combat		 		=> major
	Travelers			=> major
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 			=> minor
	Fire		 		=> minor
	Sun		 			=> major
	Shadow		 		=> major
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________


// MAIN PANTHEON_____________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION auril_spheres 
  RET_ARRAY auril_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY auril_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> minor
	Creation	 		=> major
	Decay				=> major
	Protection 			=> major
	Combat 				=> minor
	Travelers	 		=> major
	Divination 			=> major
	Wards	 			=> x
	Thought 			=> major
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> major
	Air 				=> x
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> minor
	Weather 			=> minor
	Astral	 			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION azuth_spheres 
  RET_ARRAY azuth_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY azuth_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> major
	Decay		 		=> major
	Protection 			=> major
	Combat 				=> x
	Travelers	  		=> minor
	Divination 			=> major
	Wards	 			=> minor
	Thought 			=> minor
	Charm 				=> minor
	Law	 				=> minor
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> minor
	Sun	 				=> major
	Shadow 				=> x
	Weather 			=> minor
	Astral	   			=> major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION bane_spheres 
  RET_ARRAY bane_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY bane_spheres_array BEGIN
	Healing				=> major
	Necromantic			=> major
	Creation	 		=> minor
	Decay		 		=> major
	Protection 			=> major
	Combat 				=> major
	Travelers			=> minor
	Divination			=> minor
	Wards				=> x
	Thought 			=> major
	Charm 				=> x
	Law	 				=> major
	Chaos				=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> minor
	Weather 			=> x
	Astral				=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION beshaba_spheres 
  RET_ARRAY beshaba_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY beshaba_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> minor
	Creation			=> minor
	Decay			 	=> minor
	Protection		 	=> major
	Combat		 		=> major
	Travelers		  	=> x
	Divination		 	=> minor
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION cyric_spheres 
  RET_ARRAY cyric_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY cyric_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> major
	Creation			=> x
	Decay				=> major
	Protection		 	=> minor
	Combat		 		=> major
	Travelers		  	=> x
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION deneir_spheres 
  RET_ARRAY deneir_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY deneir_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> major
	Decay				=> x
	Protection		 	=> major
	Combat		 		=> x
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> x
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

// __________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION eldath_spheres 
  RET_ARRAY eldath_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY eldath_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> minor
	Creation	 		=> major
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> x
	Travelers	 		=> minor
	Divination 			=> major
	Wards	 			=> major
	Thought 			=> x
	Charm 				=> major
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> minor
	Plant 				=> minor
	Earth 				=> x
	Water 				=> major
	Air 				=> x
	Fire 				=> x
	Sun	 				=> major
	Shadow 				=> x
	Weather 			=> x
	Astral	   			=> major
 END
END
//___________________________________________________________________________________

// __________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION garagos_spheres 
  RET_ARRAY garagos_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY garagos_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> x
	Creation	 		=> major
	Decay		 		=> major
	Protection 			=> minor
	Combat 				=> major
	Travelers	 		=> minor
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> x
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> major
	Sun	 				=> x
	Shadow 				=> x
	Weather 			=> x
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

// extra_____________________________________________________________________________
//
DEFINE_ACTION_FUNCTION grumbar_spheres 
  RET_ARRAY grumbar_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY grumbar_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> minor
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> major
	Travelers	 		=> x
	Divination 			=> minor
	Wards	 			=> minor
	Thought 			=> x
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> minor
	Earth 				=> major
	Water 				=> minor
	Air 				=> x
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> x
	Weather 			=> x
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION helm_spheres 
  RET_ARRAY helm_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY helm_spheres_array BEGIN
	Healing		 		=> minor
	Necromantic		 	=> x
	Creation			=> minor
	Decay				=> x
	Protection		 	=> major
	Combat		 		=> major
	Travelers		 	=> minor
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ilmater_spheres 
  RET_ARRAY ilmater_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ilmater_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> minor
	Creation			=> major
	Decay				=> x
	Protection		 	=> major
	Combat		 		=> x
	Travelers		 	=> major
	Divination			=> major
	Wards		 		=> minor
	Thought		 		=> x
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> minor
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION kelemvor_spheres 
  RET_ARRAY kelemvor_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY kelemvor_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> major
	Creation			=> x
	Decay				=> x
	Protection		 	=> minor
	Combat		 		=> major
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> major
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 			=> minor
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> x
	Astral			    => major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION kossuth_spheres 
  RET_ARRAY kossuth_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY kossuth_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> minor
	Combat 				=> major
	Travelers	 		=> x
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> x
	Charm 				=> minor
	Law	 				=> minor
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> minor
	Fire 				=> major
	Sun	 				=> major
	Shadow 				=> x
	Weather 			=> minor
	Astral	 			=> major
 END
END
//___________________________________________________________________________________

// _______________________________________________________________
//
DEFINE_ACTION_FUNCTION lathander_spheres 
  RET_ARRAY lathander_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY lathander_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> major
	Decay				=> x
	Protection		 	=> minor
	Combat		 		=> minor
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> minor
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> minor
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => major
  END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION leira_spheres 
  RET_ARRAY leira_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY leira_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> major
	Decay			 	=> x
	Protection		 	=> minor
	Combat		 		=> x
	Travelers		  	=> major
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION loviatar_spheres 
  RET_ARRAY loviatar_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY loviatar_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> major
	Creation			=> x
	Decay				=> major
	Protection		 	=> x
	Combat		 		=> major
	Travelers		  	=> x
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> minor
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION malar_spheres 
  RET_ARRAY malar_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY malar_spheres_array BEGIN
	Healing 		=> minor
	Necromantic		=> minor
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> major
	Travelers	 	=> major
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> major
	Charm 			=> minor
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> major
	Plant 			=> x
	Earth 			=> minor
	Water 			=> x
	Air 			=> minor
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> minor
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mask_spheres 
  RET_ARRAY mask_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mask_spheres_array BEGIN
	Healing		 		=> minor
	Necromantic		 	=> minor
	Creation			=> minor
	Decay				=> major
	Protection		 	=> major
	Combat		 		=> minor
	Travelers		  	=> x
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mielikki_spheres 
  RET_ARRAY mielikki_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mielikki_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> major
	Travelers	 		=> major
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> x
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> minor
	Plant 				=> major
	Earth 				=> minor
	Water 				=> minor
	Air 				=> minor
	Fire 				=> x
	Sun	 				=> minor
	Shadow 				=> x
	Weather 			=> major
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION milil_spheres 
  RET_ARRAY milil_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY milil_spheres_array BEGIN
	Healing 			=> major
	Necromantic 		=> x
	Creation 			=> minor
	Decay 				=> minor
	Protection 			=> major
	Combat 				=> x
	Travelers 			=> minor
	Divination 			=> major
	Wards 				=> minor
	Thought 			=> major
	Charm 				=> major
	Law 				=> minor
	Chaos 				=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> major
	Fire 				=> x
	Sun 				=> major
	Shadow 				=> x
	Weather 			=> x
	Astral   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION moander_spheres 
  RET_ARRAY moander_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY moander_spheres_array BEGIN
	Healing		 		=> minor
	Necromantic		 	=> major
	Creation			=> x
	Decay				=> major
	Protection		 	=> x
	Combat		 		=> x
	Travelers		  	=> minor
	Divination		 	=> x
	Wards		 		=> minor
	Thought		 		=> x
	Charm		 		=> x
	Law			 		=> x
	Chaos			 	=> major
	Animal		 		=> minor
	Plant		 		=> major
	Earth		 		=> major
	Water		 		=> major
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mystra_spheres 
  RET_ARRAY mystra_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mystra_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> major
	Decay				=> major
	Protection		 	=> major
	Combat		 		=> x
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 			=> minor
	Fire		 		=> major
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION oghma_spheres 
  RET_ARRAY oghma_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY oghma_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> minor
	Creation	 		=> minor
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> x
	Travelers	 		=> major
	Divination 			=> major
	Wards	 			=> major
	Thought 			=> major
	Charm 				=> x
	Law	 				=> minor
	Chaos	 			=> minor
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> minor
	Shadow 				=> x
	Weather 			=> x
	Astral	 			=> major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION redknight_spheres 
  RET_ARRAY redknight_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY redknight_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> major
	Decay		 		=> minor
	Protection 			=> major
	Combat 				=> major
	Travelers	 		=> major
	Divination 			=> minor
	Wards	 			=> major
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> minor
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> minor
	Shadow 				=> x
	Weather 			=> x
	Astral	 			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION selune_spheres 
  RET_ARRAY selune_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY selune_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> x
	Travelers	 		=> minor
	Divination 			=> major
	Wards	 			=> minor
	Thought 			=> major
	Charm 				=> major
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> minor
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> minor
	Shadow 				=> minor
	Weather 			=> major
	Astral	 			=> major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION shar_spheres 
  RET_ARRAY shar_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY shar_spheres_array BEGIN
	Healing		 		=> minor
	Necromantic		 	=> major
	Creation			=> minor
	Decay				=> major
	Protection		 	=> major
	Combat		 		=> major
	Travelers		 	=> x
	Divination		 	=> major
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> x
	Law			 		=> x
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> x
	Astral			    => major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION shaundakul_spheres 
  RET_ARRAY shaundakul_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY shaundakul_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> minor
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> major
	Travelers	 		=> major
	Divination 			=> minor
	Wards	 			=> minor
	Thought 			=> x
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> minor
	Plant 				=> minor
	Earth 				=> x
	Water 				=> x
	Air 				=> major
	Fire 				=> x
	Sun	 				=> major
	Shadow 				=> x
	Weather 			=> major
	Astral	   			=> major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION sune_spheres 
  RET_ARRAY sune_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY sune_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> minor
	Decay				=> x
	Protection		 	=> major
	Combat		 		=> x
	Travelers			=> minor
	Divination		 	=> major
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION talos_spheres 
  RET_ARRAY talos_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY talos_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> x
	Decay				=> major
	Protection		 	=> major
	Combat		 		=> minor
	Travelers			=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> x
	Law			 		=> x
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> major
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION tempus_spheres 
  RET_ARRAY tempus_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY tempus_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> major
	Decay				=> major
	Protection		 	=> major
	Combat		 		=> major
	Travelers			=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________

// __________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION torm_spheres 
  RET_ARRAY torm_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY torm_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> major
	Decay				=> minor
	Protection		 	=> major
	Combat		 		=> major
	Travelers			=> minor
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> x
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION tymora_spheres 
  RET_ARRAY tymora_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY tymora_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> minor
	Decay				=> minor
	Protection		 	=> major
	Combat		 		=> x
	Travelers			=> major
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> x
	Charm		 		=> minor
	Law			 		=> x
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> major
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather				=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION tyr_spheres 
  RET_ARRAY tyr_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY tyr_spheres_array BEGIN
	Healing				=> major
	Necromantic			=> x
	Creation			=> major
	Decay				=> minor
	Protection			=> major
	Combat				=> major
	Travelers			=> minor
	Divination			=> minor
	Wards				=> major
	Thought				=> minor
	Charm				=> x
	Law					=> major
	Chaos				=> x
	Animal				=> x
	Plant				=> x
	Earth				=> x
	Water				=> x
	Air					=> x
	Fire				=> x
	Sun					=> major
	Shadow				=> x
	Weather				=> x
	Astral				=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ulutiu_spheres 
  RET_ARRAY ulutiu_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ulutiu_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> minor
	Travelers	 		=> major
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> x
	Plant 				=> minor
	Earth 				=> minor
	Water 				=> major
	Air 				=> minor
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> x
	Weather 			=> major
	Astral	 			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION umberlee_spheres 
  RET_ARRAY umberlee_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY umberlee_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> x
	Decay				=> x
	Protection		 	=> minor
	Combat		 		=> major
	Travelers			=> major
	Divination		 	=> x
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> x
	Chaos			 	=> major
	Animal		 		=> minor
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> major
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION xvim_spheres 
  RET_ARRAY xvim_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY xvim_spheres_array BEGIN
	Healing				=> minor
	Necromantic			=> major
	Creation	 		=> minor
	Decay		 		=> major
	Protection 			=> major
	Combat 				=> major
	Travelers			=> minor
	Divination			=> minor
	Wards				=> x
	Thought 			=> major
	Charm 				=> x
	Law	 				=> x
	Chaos				=> major
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> minor
	Weather 			=> x
	Astral				=> x
 END
END
//___________________________________________________________________________________


// DEMIHUMAN PANTHEONS_______________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION corellon_spheres 
  RET_ARRAY corellon_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY corellon_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> major
	Decay		 		=> minor
	Protection 			=> major
	Combat 				=> major
	Travelers	 		=> major
	Divination 			=> major
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> minor
	Earth 				=> x
	Water 				=> minor
	Air 				=> minor
	Fire 				=> x
	Sun	 				=> major
	Shadow 				=> x
	Weather 			=> minor
	Astral	 			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION eilistraee_spheres 
  RET_ARRAY eilistraee_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY eilistraee_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> minor
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> x
	Travelers	  		=> major
	Divination 			=> minor
	Wards	 			=> minor
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> major
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> minor
	Fire 				=> x
	Sun	 				=> major
	Shadow 				=> major
	Weather 			=> x
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION moradin_spheres 
  RET_ARRAY moradin_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY moradin_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> major
	Decay		 		=> major
	Protection 			=> major
	Combat 				=> minor
	Travelers	 		=> minor
	Divination 			=> major
	Wards	 			=> major
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> major
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> major
	Water 				=> minor
	Air 				=> x
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> x
	Weather 			=> x
	Astral	  			=> minor
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION clangeddin_spheres 
  RET_ARRAY clangeddin_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY clangeddin_spheres_array BEGIN
	Healing				=> major
	Necromantic			=> x
	Creation	 		=> major
	Decay		 		=> major
	Protection 			=> major
	Combat 				=> major
	Travelers	 		=> minor
	Divination 			=> minor
	Wards	 			=> minor
	Thought 			=> x
	Charm 				=> x
	Law	 				=> major
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> major
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> minor
	Shadow 				=> x
	Weather 			=> x
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION marthammor_spheres 
  RET_ARRAY marthammor_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY marthammor_spheres_array BEGIN
	Healing				=> major
	Necromantic			=> x
	Creation	 		=> minor
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> minor
	Travelers	 		=> major
	Divination 			=> minor
	Wards	 			=> minor
	Thought 			=> x
	Charm 				=> minor
	Law	 				=> major
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> major
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> minor
	Shadow 				=> x
	Weather 			=> major
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION haela_spheres 
  RET_ARRAY haela_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY haela_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> major
	Decay				=> major
	Protection		 	=> major
	Combat		 		=> major
	Travelers			=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION baravar_spheres 
  RET_ARRAY baravar_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY baravar_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> minor
	Decay				=> x
	Protection		 	=> major
	Combat		 		=> x
	Travelers			=> major
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> minor
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION baervan_spheres 
  RET_ARRAY baervan_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY baervan_spheres_array BEGIN
	Healing		 		=> major
	Necromantic		 	=> x
	Creation			=> minor
	Decay				=> x
	Protection		 	=> major
	Combat		 		=> x
	Travelers			=> major
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> minor
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> major
	Plant		 		=> major
	Earth		 		=> major
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION urdlen_spheres 
  RET_ARRAY urdlen_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY urdlen_spheres_array BEGIN
	Healing 		=> minor
	Necromantic		=> major
	Creation	 	=> x
	Decay		 	=> major
	Protection 		=> x
	Combat 			=> major
	Travelers	 	=> x
	Divination 		=> minor
	Wards	 		=> minor
	Thought 		=> major
	Charm 			=> minor
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> x
	Plant 			=> x
	Earth 			=> major
	Water 			=> x
	Air 			=> x
	Fire 			=> minor
	Sun	 			=> x
	Shadow 			=> major
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION yondalla_spheres 
  RET_ARRAY yondalla_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY yondalla_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> major
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> x
	Travelers	 		=> minor
	Divination 			=> major
	Wards	 			=> major
	Thought 			=> x
	Charm 				=> major
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> minor
	Earth 				=> minor
	Water 				=> x
	Air 				=> minor
	Fire 				=> x
	Sun	 				=> major
	Shadow 				=> x
	Weather 			=> minor
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION arvoreen_spheres 
  RET_ARRAY arvoreen_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY arvoreen_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> x
	Creation	 		=> minor
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> major
	Travelers	 		=> major
	Divination 			=> minor
	Wards	 			=> major
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> major
	Chaos	 			=> x
	Animal 				=> minor
	Plant 				=> x
	Earth 				=> major
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> major
	Shadow 				=> x
	Weather 			=> x
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION brandobaris_spheres 
  RET_ARRAY brandobaris_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY brandobaris_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> major
	Combat 				=> x
	Travelers	 		=> major
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> major
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> x
	Plant 				=> minor
	Earth 				=> x
	Water 				=> x
	Air 				=> major
	Fire 				=> x
	Sun	 				=> minor
	Shadow 				=> minor
	Weather 			=> major
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION gruumsh_spheres 
  RET_ARRAY gruumsh_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY gruumsh_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> minor
	Creation	 		=> minor
	Decay		 		=> major
	Protection 			=> minor
	Combat 				=> major
	Travelers	 		=> x
	Divination 			=> x
	Wards	 			=> x
	Thought 			=> x
	Charm 				=> major
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> minor
	Plant 				=> x
	Earth 				=> major
	Water 				=> x
	Air 				=> x
	Fire 				=> minor
	Sun	 				=> x
	Shadow 				=> x
	Weather 			=> x
	Astral	 			=> major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION luthic_spheres 
  RET_ARRAY luthic_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY luthic_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> major
	Creation	 		=> minor
	Decay		 		=> major
	Protection 			=> major
	Combat 				=> minor
	Travelers	 		=> x
	Divination 			=> major
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> major
	Law	 				=> minor
	Chaos	 			=> minor
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> x
	Weather 			=> minor
	Astral	 			=> x
 END
END
//___________________________________________________________________________________


// DRUIDS / MYSTICS / OCCULTISTS / RANGERS___________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION druid_forest_spheres 
  RET_ARRAY druid_forest_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY druid_forest_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	  		=> minor
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> major
	Plant 				=> major
	Earth 				=> major
	Water 				=> major
	Air 				=> major
	Fire 				=> minor
	Sun	 				=> major
	Shadow 				=> minor
	Weather 			=> major
	Astral	    		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION druid_totemic_spheres
  RET_ARRAY druid_totemic_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY druid_totemic_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	  		=> minor
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> major
	Plant 				=> major
	Earth 				=> major
	Water 				=> major
	Air 				=> major
	Fire 				=> minor
	Sun	 				=> major
	Shadow 				=> minor
	Weather 			=> major
	Astral	    		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION druid_hivekeeper_spheres 
  RET_ARRAY druid_hivekeeper_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY druid_hivekeeper_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	  		=> minor
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> major
	Plant 				=> major
	Earth 				=> major
	Water 				=> minor
	Air 				=> major
	Fire 				=> minor
	Sun	 				=> major
	Shadow 				=> minor
	Weather 			=> major
	Astral	    		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION druid_northern_spheres 
  RET_ARRAY druid_northern_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY druid_northern_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	  		=> minor
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> major
	Plant 				=> major
	Earth 				=> major
	Water 				=> major
	Air 				=> major
	Fire 				=> minor
	Sun	 				=> major
	Shadow 				=> minor
	Weather 			=> major
	Astral	    		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION druid_shadow_spheres 
  RET_ARRAY druid_shadow_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY druid_shadow_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	  		=> minor
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> major
	Plant 				=> major
	Earth 				=> major
	Water 				=> major
	Air 				=> major
	Fire 				=> minor
	Sun	 				=> minor
	Shadow 				=> major
	Weather 			=> major
	Astral	    		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION druid_gray_spheres 
  RET_ARRAY druid_gray_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY druid_gray_spheres_array BEGIN
	Healing 			=> major
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	  		=> major
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> major
	Plant 				=> major
	Earth 				=> major
	Water 				=> major
	Air 				=> major
	Fire 				=> minor
	Sun	 				=> x
	Shadow 				=> major
	Weather 			=> major
	Astral	    		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION druid_lost_spheres 
  RET_ARRAY druid_lost_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY druid_lost_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> major
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	  		=> minor
	Divination 			=> minor
	Wards	 			=> x
	Thought 			=> minor
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> major
	Animal 				=> major
	Plant 				=> major
	Earth 				=> major
	Water 				=> major
	Air 				=> major
	Fire 				=> minor
	Sun	 				=> x
	Shadow 				=> minor
	Weather 			=> major
	Astral	    		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mystic_earth_spheres 
  RET_ARRAY mystic_earth_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mystic_earth_spheres_array BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> major
	Combat 			=> x
	Travelers	 	=> minor
	Divination 		=> minor
	Wards	 		=> minor
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> x
	Plant 			=> major
	Earth 			=> focus
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mystic_water_spheres 
  RET_ARRAY mystic_water_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mystic_water_spheres_array BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> x
	Travelers	 	=> major
	Divination 		=> major
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> minor
	Plant 			=> minor
	Earth 			=> x
	Water 			=> focus
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mystic_air_spheres 
  RET_ARRAY mystic_air_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mystic_air_spheres_array BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> minor
	Combat 			=> x
	Travelers	 	=> major
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> focus
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mystic_fire_spheres 
  RET_ARRAY mystic_fire_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mystic_fire_spheres_array BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> major
	Combat 			=> x
	Travelers	 	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> minor
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> focus
	Sun	 			=> major
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mystic_light_spheres 
  RET_ARRAY mystic_light_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mystic_light_spheres_array BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> major
	Combat 			=> x
	Travelers	 	=> minor
	Divination 		=> minor
	Wards	 		=> major
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> minor
	Fire 			=> minor
	Sun	 			=> focus
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mystic_shadow_spheres 
  RET_ARRAY mystic_shadow_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mystic_shadow_spheres_array BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> major
	Protection 		=> x
	Combat 			=> x
	Travelers	 	=> minor
	Divination 		=> major
	Wards	 		=> minor
	Thought 		=> major
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> focus
	Weather 		=> x
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION beast_lord_spheres 
  RET_ARRAY beast_lord_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY beast_lord_spheres_array BEGIN
	Healing 		=> minor
	Necromantic		=> minor
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> major
	Travelers	 	=> major
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> major
	Charm 			=> minor
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> focus
	Plant 			=> x
	Earth 			=> x
	Water 			=> minor
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> minor
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION elementalist_spheres 
  RET_ARRAY elementalist_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY elementalist_spheres_array BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> minor
	Combat 			=> x
	Travelers	 	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> minor
	Animal 			=> x
	Plant 			=> x
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> major
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> major
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ranger_forest_spheres 
  RET_ARRAY ranger_forest_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ranger_forest_spheres_array BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	 	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ranger_mountain_spheres 
  RET_ARRAY ranger_mountain_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ranger_mountain_spheres_array BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> ranger
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> ranger
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ranger_desert_spheres 
  RET_ARRAY ranger_desert_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ranger_desert_spheres_array BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ranger_jungle_spheres 
  RET_ARRAY ranger_jungle_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ranger_jungle_spheres_array BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> ranger
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> ranger
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ranger_arctic_spheres 
  RET_ARRAY ranger_arctic_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ranger_arctic_spheres_array BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> ranger
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________


//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION ranger_beastmaster_spheres 
  RET_ARRAY ranger_beastmaster_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY ranger_beastmaster_spheres_array BEGIN
	Healing 			=> ranger
	Necromantic			=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION barbarian_ranger_spheres 
  RET_ARRAY barbarian_ranger_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY barbarian_ranger_spheres_array BEGIN
	Healing 			=> x
	Necromantic			=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION mage_hunter_spheres 
  RET_ARRAY mage_hunter_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY mage_hunter_spheres_array BEGIN
	Healing 			=> ranger
	Necromantic			=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION elven_archer_spheres 
  RET_ARRAY elven_archer_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY elven_archer_spheres_array BEGIN
	Healing 			=> ranger
	Necromantic			=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> ranger
	Combat 			=> x
	Travelers	  	=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> ranger
	Astral	   		=> x
 END
END
//___________________________________________________________________________________


// DEFAULT KIT SPHERE ASSIGNMENTS____________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION vanilla_shaman_spheres 
  RET_ARRAY vanilla_shaman_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY vanilla_shaman_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> minor
	Combat 			=> x
	Travelers	  	=> major
	Divination 		=> major	
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> major
	Plant 			=> major
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> major
	Weather 		=> x
	Astral	     	=> major
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_cleric_spheres BEGIN
  LAF QD_ENSURE_QDMC_SPL STR_VAR base_class = ~P~ END 
  LAF QD_ENSURE_BASE_CLAB STR_VAR base_class = ~P~ END 
  COPY_EXISTING ~QD_MCP01.spl~ ~override~ // trueclass spheres via .eff
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5splif#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5splif#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smdea#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smdea#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spben#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spben#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spdes#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spdes#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5sppro#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5sppro#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smwar#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smwar#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smexp#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smexp#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spkno#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spkno#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smtho#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smtho#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spdre#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spdre#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smvig#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smvig#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smfir#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smfir#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5splig#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5splig#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smmag#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smmag#~ END
  IF_EXISTS BUT_ONLY
  ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpr01_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> x
	Travelers	 	=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	 		=> x
  END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_druid_spheres BEGIN
  LAF QD_ENSURE_QDMC_SPL STR_VAR base_class = ~D~ END 
  LAF QD_ENSURE_BASE_CLAB STR_VAR base_class = ~D~ END 
  COPY_EXISTING ~QD_MCD01.spl~ ~override~ // trueclass spheres via .eff
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spexp#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spexp#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spvig#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spvig#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spani#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spani#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5sppla#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5sppla#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spear#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spear#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spwat#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spwat#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spair#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spair#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5splig#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5splig#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smlif#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smlif#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smkno#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smkno#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smtho#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smtho#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smaff#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smaff#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smfir#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smfir#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smsha#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smsha#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5smast#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smast#~ END
  IF_EXISTS BUT_ONLY
  ACTION_DEFINE_ASSOCIATIVE_ARRAY clabdr01_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> x
	Travelers	 	=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	 		=> x
  END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_ranger_spheres BEGIN
  LAF QD_ENSURE_QDMC_SPL STR_VAR base_class = ~R~ END 
  LAF QD_ENSURE_BASE_CLAB STR_VAR base_class = ~R~ END 
  COPY_EXISTING ~QD_MCR01.spl~ ~override~ // trueclass spheres via .eff
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spexp#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spexp#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spear#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spear#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spani#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5spani#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5sppla#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5sppla#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5sppro#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5sppro#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5splig#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5splig#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5splif#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smlif#~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 0x4000 match_parameter2 = 9 STR_VAR match_resource = ~d5spkno#~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0x4000 parameter2 = 9 STR_VAR resource = ~d5smkno#~ END
  IF_EXISTS BUT_ONLY
  ACTION_DEFINE_ASSOCIATIVE_ARRAY clabrn01_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> x
	Travelers	 	=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	 		=> x
  END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION vanilla_avenger_spheres 
  RET_ARRAY vanilla_avenger_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY vanilla_avenger_spheres_array BEGIN
	Healing 			=> minor
	Necromantic			=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> x
	Travelers	  	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> major
	Animal 			=> minor
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 			=> minor
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION vanilla_paladin_spheres 
  RET_ARRAY vanilla_paladin_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY vanilla_paladin_spheres_array BEGIN
	Healing 			=> paladin
	Necromantic			=> x
	Creation	 	=> paladin
	Decay		 	=> paladin
	Protection 		=> paladin
	Combat 			=> paladin
	Travelers	 	=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 			=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION vanilla_cavalier_spheres 
  RET_ARRAY vanilla_cavalier_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY vanilla_cavalier_spheres_array BEGIN
	Healing 			=> paladin
	Necromantic			=> x
	Creation	 	=> paladin
	Decay		 	=> paladin
	Protection 		=> paladin
	Combat 			=> paladin
	Travelers	  	=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 			=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION vanilla_inquisitor_spheres 
  RET_ARRAY vanilla_inquisitor_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY vanilla_inquisitor_spheres_array BEGIN
	Healing 			=> paladin
	Necromantic			=> x
	Creation	 	=> paladin
	Decay		 	=> x
	Protection 		=> paladin
	Combat 			=> x
	Travelers	 	=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> paladin
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 			=> paladin
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION vanilla_undead_hunter_spheres 
  RET_ARRAY vanilla_undead_hunter_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY vanilla_undead_hunter_spheres_array BEGIN
	Healing 			=> paladin
	Necromantic			=> paladin
	Creation	 	=> paladin
	Decay		 	=> x
	Protection 		=> paladin
	Combat 			=> paladin
	Travelers	 	=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 			=> x
	Astral	   		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_FUNCTION vanilla_blackguard_spheres 
  RET_ARRAY vanilla_blackguard_spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY vanilla_blackguard_spheres_array BEGIN
	Healing 			=> x
	Necromantic			=> paladin
	Creation	 	=> x
	Decay		 	=> paladin
	Protection 		=> x
	Combat 			=> paladin
	Travelers	 	=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> paladin
	Law	 			=> paladin
	Chaos	 		=> paladin
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> paladin
	Weather 			=> x
	Astral	   		=> paladin
 END
END
//___________________________________________________________________________________


// OTHER MOD KIT SPHERE ASSIGNMENTS__________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_MACRO DR_oozemaster_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#ooze_spheres BEGIN
	Healing 			=> major
	Necromantic			=> minor
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> x
	Travelers	 	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> x
	Chaos	 		=> major
	Animal 			=> x
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> minor
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> minor
	Weather 			=> x
	Astral	 		=> x
 END
END
//___________________________________________________________________________________

//___________________________________________________________________________________
//
DEFINE_ACTION_MACRO DR_justifier_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#justif_spheres BEGIN
	Healing 			=> ranger
	Necromantic			=> x
	Creation	 	=> x
	Decay		 	=> x
	Protection 		=> x
	Combat 			=> ranger
	Travelers	 	=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 			=> x
	Astral	 		=> x
 END
END
//___________________________________________________________________________________

END	// end define sphere lists macro

/*
// extra_____________________________________________________________________________
//
DEFINE_ACTION_FUNCTION _spheres 
  RET_ARRAY _spheres_array
 BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY _spheres_array BEGIN
	Healing 			=> x
	Necromantic			=> x
	Creation	 		=> x
	Decay		 		=> x
	Protection 			=> x
	Combat 				=> x
	Travelers	 		=> x
	Divination 			=> x
	Wards	 			=> x
	Thought 			=> x
	Charm 				=> x
	Law	 				=> x
	Chaos	 			=> x
	Animal 				=> x
	Plant 				=> x
	Earth 				=> x
	Water 				=> x
	Air 				=> x
	Fire 				=> x
	Sun	 				=> x
	Shadow 				=> x
	Weather 			=> x
	Astral	   			=> x
 END
END
//___________________________________________________________________________________

*/