
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								 SPHERE SYSTEM
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION create_spheres BEGIN

//create sphere spells______________________________________________________________
//
//all/universal
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spuni.spl~
//life
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5splif.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sflif.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smlif.spl~
//death
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdea.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdea.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdea.spl~
//benediction
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spben.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfben.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smben.spl~
//Destruction
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdes.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdes.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdes.spl~
//Protection
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sppro.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfpro.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smpro.spl~
//war
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spwar.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfwar.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smwar.spl~
//exploration
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spexp.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfexp.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smexp.spl~
//knowledge
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spkno.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfkno.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smkno.spl~
//deception
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdec.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdec.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdec.spl~
//thought
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sptho.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sftho.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smtho.spl~
//dread
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spdre.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfdre.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smdre.spl~
//Vigor
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spvig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfvig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smvig.spl~
//affliction
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spaff.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfaff.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smaff.spl~
//animal
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spani.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfani.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smani.spl~
//plant
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sppla.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfpla.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smpla.spl~
//earth
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spear.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfear.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smear.spl~
//air
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spair.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfair.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smair.spl~
//water
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spwat.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfwat.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smwat.spl~
//fire
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spfir.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sffir.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smfir.spl~
//light
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5splig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sflig.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smlig.spl~
//shadow
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spsha.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfsha.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smsha.spl~
//magic
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spmag.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfmag.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smmag.spl~
//astral
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5spast.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5sfast.spl~
COPY ~faiths_and_powers/spheres/d5sxyz.spl~ ~override/d5smast.spl~
//__________________________________________________________________________________


//remove priest spells from joinable NPCs____________________________________________
//
OUTER_FOR (level = 1; level <= 7; level += 1) BEGIN
  OUTER_SET $spell(~all~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~cleric~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~druid~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~bogus~ ~%level%~ ~length~) = 0
END

COPY_EXISTING_REGEXP GLOB ~^SPPR[1-7]\(0[1-9]\|[1-4][0-9]\|50\)\.spl$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_SHORT 0x1c spell_type
    PATCH_IF (spell_type == 2) BEGIN // divine, just to be sure
      READ_SHORT 0x20 priest_type
      READ_SHORT 0x1e exclusion_flags
      READ_LONG  0x34 level
      TO_UPPER SOURCE_RES
      PATCH_IF (priest_type == 0x0000) BEGIN // all priests
        SPRINT type ~all~
      END
      ELSE PATCH_IF (priest_type == 0x4000) BEGIN // druid/ranger
        SPRINT type ~druid~
      END
      ELSE PATCH_IF (priest_type == 0x8000) BEGIN // cleric/paladin
        SPRINT type ~cleric~
      END
      ELSE BEGIN // no priests
        SPRINT type ~bogus~
      END
      PATCH_IF (level > 0 && level <= 7) BEGIN
        SET index = $spell(~%type%~ ~%level%~ ~length~)
        SPRINT $spell(~%type%~ ~%level%~ ~%index%~) ~%SOURCE_RES%~
        SET $spell(~%type%~ ~%level%~ ~length~) += 1
        SET $spell(~%type%~ ~%SOURCE_RES%~) = 1
        SET $spell(~%SOURCE_RES%~ ~excl~) = (exclusion_flags BAND 0b111111) // store just the alignment bits
        SET $spell(~%SOURCE_RES%~ ~level~) = level
      END
    END
  END
  BUT_ONLY

DEFINE_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~ BEGIN
  FOR (level = 1; level <= 7; level += 1) BEGIN
    SET length = $spell(~%type%~ ~%level%~ ~length~)
    FOR (i = 0; i < length; i += 1) BEGIN
      SPRINT spell $spell(~%type%~ ~%level%~ ~%i%~)
      REMOVE_KNOWN_SPELL ~%spell%~
    END
  END
END

DEFINE_PATCH_FUNCTION ~REMOVE_BAD_KNOWN_SPELLS~
 // INT_VAR spell_type = 0 // 1 = cleric, 2 = druid, 3 = both
BEGIN
  PATCH_IF (spell_type == 1) BEGIN // remove druid spells from clerics
    SPRINT type ~druid~
    LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
  END
  ELSE PATCH_IF (spell_type = 2) BEGIN // remove cleric spells from druids
    SPRINT type ~cleric~
    LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
  END

  // remove bogus spells from all classes
  SPRINT type ~bogus~
  LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
END

LAM JOINABLE_NPC_ARRAYS

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
//  PRINT ~%cre% => %dv%~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  READ_BYTE 0x273 class
      PATCH_IF (class == 3 || class == 6 || class == 8 || class == 11 || class == 12 || class == 14 || class == 15 || class == 16 || class == 17 || class == 18) BEGIN // divine casters
        LAUNCH_PATCH_FUNCTION ~REMOVE_BAD_KNOWN_SPELLS~ END
//        REMOVE_MEMORIZED_SPELLS
      END
    END
  BUT_ONLY
END
//__________________________________________________________________________________


//some vanilla spell modifications__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518a.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518a.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518b.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518b.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr150.spl~ THEN BEGIN
  COPY_EXISTING ~sppr150.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 219 parameter1 = 121 END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 219 opcode = 100 parameter1 = 9 parameter2 = 7 END
	SAY UNIDENTIFIED_DESC @59999
  BUT_ONLY
END

COPY_EXISTING - ~spell.ids~ ~faiths_and_powers/backup~
  COUNT_REGEXP_INSTANCES ~CLERIC_ALICORN_LANCE~ spell_exists
ACTION_IF (spell_exists) BEGIN
  LAF RES_NUM_OF_SPELL_NAME
	STR_VAR spell_name = ~CLERIC_ALICORN_LANCE~ RET spell_res 
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~%spell_res%.spl~ BEGIN
	COPY_EXISTING ~%spell_res%.spl~ ~override~
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 12 parameter2 = (0 + 64 << 16) savingthrow = 0 END
	BUT_ONLY
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr314.spl~ THEN BEGIN
  COPY_EXISTING ~sppr314.spl~ ~override~
	WRITE_ASCII 0x3a ~sppr313c~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~sppr313b~ END
  BUT_ONLY
END
//__________________________________________________________________________________


//apply spells to sphere system_____________________________________________________
//
COPY ~d5/d5altsph.2da~ ~override~

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5spsph.2da~) BEGIN
  COPY ~d5/d5spsph.2da~ ~override~
END

COPY_EXISTING ~d5spsph.2da~ ~override~
  REPLACE_TEXTUALLY ~//.*$~ ~~
  PATCH_IF !(FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
	REPLACE_TEXTUALLY ~NOSR_~ ~~
  END
  PATCH_IF (FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
	REPLACE_TEXTUALLY ~SR_~ ~~
  END
  PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) BEGIN
	REPLACE_TEXTUALLY ~CLERIC_MISCAST_MAGIC~ ~WIZARD_SPELL_THRUST~
  END
BUT_ONLY

COPY_EXISTING ~d5altsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 2
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~fnp_sphere~
	READ_2DA_ENTRY_FORMER rows row 1 ~alt_sphere~
	SPRINT $altspheres(~%alt_sphere%~) ~%fnp_sphere%~
  END
BUT_ONLY

COPY_EXISTING ~d5spsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 4
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 3 nu_sph
	PATCH_IF (~%nu_sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
	  SET_2DA_ENTRY row 2 4 ~Universal~
	END
	PHP_EACH altspheres AS alt_sph => fnp_sph BEGIN
	  PATCH_IF (~%alt_sph%~ STRING_EQUAL_CASE ~%nu_sph%~) BEGIN
		SET_2DA_ENTRY row 2 4 ~%fnp_sph%~
	  END
	END
  END
BUT_ONLY

<<<<<<<< d5/d5fnplst.2da
2DA V1.0 
SPLRES
		MAJOR	MINOR	FOCUS	SPHERE	SYSTEM	SPONT_IND	SPONT_PROC
>>>>>>>> 
COPY ~d5/d5fnplst.2da~ ~override/d5fnplst.2da~ 

<<<<<<<<  d5/d5spontsphere.2da
 >>>>>>>>
 COPY ~d5/d5spontsphere.2da~ ~override/d5tpuni.2da~


OUTER_SET spl_ind = 101

COPY_EXISTING ~d5spsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 4
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 spl
	READ_2DA_ENTRY_FORMER rows row 1 lvl
//	READ_2DA_ENTRY_FORMER rows row 2 sph
	READ_2DA_ENTRY_FORMER rows row 3 desc_sph
	PHP_EACH altspheres AS alt_sph => fnp_sph BEGIN
	  PATCH_IF (~%alt_sph%~ STRING_EQUAL_CASE ~%desc_sph%~) BEGIN
		SPRINT sph ~%fnp_sph%~
	  END
	END
	INNER_ACTION BEGIN
/*
	  ACTION_IF (~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
 	 	OUTER_INNER_PATCH ~%sph%~ BEGIN
		  SNPRINT 3 ~shortsphere~ ~%sph%~ 
		  SPRINT sphere ~d5sp%shortsphere%~
		  SPRINT fsphere ~d5sf%shortsphere%~
		  SPRINT msphere ~d5sm%shortsphere%~
		END
	  END
	  ACTION_IF !(~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
*/
 	 	OUTER_INNER_PATCH ~%sph%~ BEGIN
		  SNPRINT 3 ~shortsphere~ ~%sph%~ 
		  SPRINT sphere ~d5sp%shortsphere%~
		  SPRINT fsphere ~d5sf%shortsphere%~
		  SPRINT msphere ~d5sm%shortsphere%~
		END
		ACTION_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~[ %TAB%]%spl%[ %TAB%%LNL%%MNL%%WNL%]~)) || (FILE_EXISTS_IN_GAME ~%spl%.spl~) BEGIN
		  ACTION_FOR_EACH type IN ~p~ ~m~ /*~f~*/ BEGIN
			ACTION_IF !(FILE_EXISTS_IN_GAME ~d5t%type%%shortsphere%.2da~) BEGIN
			  COPY ~d5/d5spontsphere.2da~ ~override/d5t%type%%shortsphere%.2da~
//			  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5t%type%%shortsphere%.spl~
			END
		  END
		  ACTION_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~[ %TAB%]%spl%[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN
			LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spl%~ RET spell_res spell_num END
			OUTER_TEXT_SPRINT the_spell ~%spell_res%~
			OUTER_TEXT_SPRINT priest_res ~d5p%spell_num%~
			OUTER_TEXT_SPRINT minor_res ~d5m%spell_num%~
			OUTER_TEXT_SPRINT focus_res ~d5f%spell_num%~
			OUTER_TEXT_SPRINT spont_ind ~%spl_ind%~
		  END
	   	  ELSE BEGIN
			OUTER_TEXT_SPRINT the_spell ~%spl%~
			OUTER_TEXT_SPRINT priest_res ~d5pp%spl_ind%~
			OUTER_TEXT_SPRINT minor_res ~d5mm%spl_ind%~
			OUTER_TEXT_SPRINT focus_res ~d5ff%spl_ind%~
			OUTER_TEXT_SPRINT spont_ind ~%spl_ind%~
		  END 
		  ACTION_IF FILE_EXISTS_IN_GAME ~%the_spell%.spl~ BEGIN 
			COPY_EXISTING ~%the_spell%.spl~ ~override~ 
			  READ_SHORT 0x1c spell_type
			  READ_LONG 0x34 spell_lvl
			BUT_ONLY
			ACTION_IF (%lvl% = 0) BEGIN
			  OUTER_SET plvl = %spell_lvl%
			  OUTER_SET flvl = (%spell_lvl% - 1)
			END ELSE BEGIN
			  OUTER_SET plvl = %lvl%
			  OUTER_SET flvl = (%lvl% - 1)
			END
			ACTION_IF (%spell_type% = 2) BEGIN 							 // priest spells: add to spheres
			  ACTION_IF (%plvl% = %spell_lvl%) BEGIN
				OUTER_SPRINT major_spl ~%the_spell%~
				COPY_EXISTING ~%the_spell%.spl~ ~override~ 
				  READ_LONG 0x50 "valid"
				  PATCH_IF (%valid% >= 0) BEGIN 
					READ_STRREF 0x50 ~desc~
					INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
					  REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
					  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
					  REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					END
					SAY_EVALUATED 0x50 ~%new_desc%~
				  END
				BUT_ONLY
				COPY_EXISTING ~%sphere%.spl~ ~override~ 
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%the_spell%	3~
				ACTION_IF (%plvl% < 4) BEGIN
				  OUTER_SPRINT minor_spl ~%the_spell%~
				  COPY_EXISTING ~%msphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tm%shortsphere%.2da~ ~%sph%	%the_spell%	3~
				END
				ACTION_IF (%plvl% = 1) OR (%plvl% = 7) BEGIN
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%the_spell%	3~
				END
			  END	//	end if level unchanged
			  ACTION_IF !(%plvl% = %spell_lvl%) BEGIN
				OUTER_SPRINT major_spl ~%priest_res%~
				ACTION_IF (FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				  COPY_EXISTING ~%priest_res%.spl~ ~override~ 
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN 
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%sphere%.spl~ ~override~ 
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
				ACTION_IF !(FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				  COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
				  	WRITE_LONG 0x34 %plvl%
					READ_LONG 0x64 abil_offset
					READ_SHORT 0x68 abil_number
					READ_BYTE (%abil_offset% + 0x0c) abil_target					
					READ_SHORT (%abil_offset% + 0x0e) abil_range
					READ_LONG 0x6a eff_offset
					WHILE (%abil_number% > 0) BEGIN
					  SET abil_number = (%abil_number% - 1)
					  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
					END
					LPF DELETE_EFFECT END
					PATCH_IF (%abil_target% = 4) BEGIN
					  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %plvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
					  PATCH_IF (%abil_range% < 35) BEGIN
						PATCH_IF (%abil_range% > 4) BEGIN
							LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
						END
						PATCH_IF (%abil_range% < 5) BEGIN
						  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	
						END
					  END
					END
					ELSE BEGIN
					  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %plvl% parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
					END
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN 
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
						REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%sphere%.spl~ ~override~ 
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
				ACTION_IF (%plvl% = 1) OR (%plvl% = 7) BEGIN
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
				ACTION_IF (%plvl% < 4) BEGIN
				  OUTER_SPRINT minor_spl ~%priest_res%~
				  COPY_EXISTING ~%msphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tm%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
			  END	//	end level differs from vanilla
			  ACTION_IF (%plvl% > 1) BEGIN
				  ACTION_IF (FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
					COPY_EXISTING ~%focus_res%.spl~ ~override~
					  READ_LONG 0x50 "valid"
					  PATCH_IF (%valid% >= 0) BEGIN 
						READ_STRREF 0x50 ~desc~
						INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
						END
						SAY_EVALUATED 0x50 ~%new_desc%~
					  END
					BUT_ONLY
					COPY_EXISTING ~%fsphere%.spl~ ~override~
					  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
					IF_EXISTS BUT_ONLY
//				 	APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				  END
				  ACTION_IF !(FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
					COPY_EXISTING ~%the_spell%.spl~ ~override/%focus_res%.spl~ 	
					  WRITE_LONG 0x34 %flvl%
					  READ_LONG 0x64 abil_offset
					  READ_SHORT 0x68 abil_number
					  READ_BYTE (%abil_offset% + 0x0c) abil_target
					  READ_SHORT (%abil_offset% + 0x0e) abil_range
					  READ_LONG 0x6a eff_offset
					  WHILE (%abil_number% > 0) BEGIN
						SET abil_number = (%abil_number% - 1)
						WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
					  END
					  LPF DELETE_EFFECT END
					  PATCH_IF (%abil_target% = 4) BEGIN
						LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %plvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
						PATCH_IF (%abil_range% < 35) BEGIN
						  PATCH_IF (%abil_range% > 4) BEGIN
							LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
						  END
						  PATCH_IF (%abil_range% < 5) BEGIN
							LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	
						  END
						END
					  END
					  ELSE BEGIN
						LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %plvl% parameter1 = 0 parameter2 = 1 timing = 2 STR_VAR resource = EVAL ~%the_spell%~ END
					  END
					  READ_LONG 0x50 "valid"
					  PATCH_IF (%valid% >= 0) BEGIN 
						READ_STRREF 0x50 ~desc~
						INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						  REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
						  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
						  REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
						END
						SAY_EVALUATED 0x50 ~%new_desc%~
					  END
					BUT_ONLY
					COPY_EXISTING ~%fsphere%.spl~ ~override~
					  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
					IF_EXISTS BUT_ONLY
//				 	APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				  END
			  END 	//	end focus spells
			  ACTION_IF (%plvl% > 3) BEGIN
				OUTER_SPRINT minor_spl ~****~
			  END
			END // end type = priest spells
//
			ELSE BEGIN // non-priest spells: make clones
//	 NOTE: STRIP OUT 216 EFFECTS FROM TNB LEVEL 1 CANTRIPS
			  OUTER_SPRINT major_spl ~%priest_res%~
			  ACTION_IF (FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
				  READ_LONG 0x50 "valid"
				  PATCH_IF (%valid% >= 0) BEGIN 
					READ_STRREF 0x50 ~desc~
					INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
					  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
					END
					SAY_EVALUATED 0x50 ~%new_desc%~
				  END
				BUT_ONLY
				COPY_EXISTING ~%sphere%.spl~ ~override~
//				  LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%priest_res%~ END
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF !(FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
				  WRITE_SHORT 0x1c 2
				  LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
				  WRITE_LONG 0x34 %plvl%
				  READ_LONG 0x50 "valid"
				  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
					READ_STRREF 0x50 ~desc~
					INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
					  REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
					  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
					  REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					END
					SAY_EVALUATED 0x50 ~%new_desc%~
				  END
				BUT_ONLY
				COPY_EXISTING ~%sphere%.spl~ ~override~
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF (%plvl% = 1) OR (%plvl% = 7) BEGIN
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF (%plvl% < 4) BEGIN
				OUTER_SPRINT minor_spl ~%priest_res%~
				COPY_EXISTING ~%msphere%.spl~ ~override~
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tm%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF (%plvl% > 1) BEGIN
				ACTION_IF (FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
				  COPY_EXISTING ~%focus_res%.spl~ ~override~ 
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN 
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				END
				ACTION_IF !(FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
				  COPY_EXISTING ~%the_spell%.spl~ ~override/%focus_res%.spl~ 	
					WRITE_SHORT 0x1c 2
					LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
					WRITE_LONG 0x34 %flvl%
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
						REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				END
			  END
			  ACTION_IF (%plvl% > 3) BEGIN
				OUTER_SPRINT minor_spl ~****~
			  END
			END
			ACTION_IF !(FILE_CONTAINS_EVALUATED (~d5fnplst.2da~ ~%the_spell%[ %TAB%]~)) BEGIN
			  APPEND ~d5fnplst.2da~ ~%the_spell%	%major_spl%	%minor_spl%	%focus_res%	%desc_sph%	%sph%	%spont_ind% 	no ~
			END
		  END
		END
//	  END
	END
	SET spl_ind = (spl_ind + 1)
  END
BUT_ONLY
//__________________________________________________________________________________


//UI work for contingency___________________________________________________________
//

COPY_EXISTING ~ui.menu~ ~override~
	REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~contingencyDescription = mageBookStrings[contingencyResRef].tip~ ~			if not pcall(me_problem) then
				contingencyDescription = 0
			end~
	REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~--reload language~ ~function me_problem()
	contingencyDescription = mageBookStrings[contingencyResRef].tip
end
--reload language~
//__________________________________________________________________________________


//set up HLA tables_________________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/spheres/hlas/luclxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/spheres/hlas/ludrxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/spheres/hlas/lufcxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/spheres/hlas/lucrxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/spheres/hlas/luctxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/spheres/hlas/lucmxyz.2da~ ~override~
//__________________________________________________________________________________


LAM ~BACKFILL_FNP_KIT_INFO~


END // end create spheres function
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION prep_vanilla_spells BEGIN

//no spells for anyone!______________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
	READ_SHORT 0x1c ~spelltype~
	PATCH_IF (~spelltype~ = 2) BEGIN
		WRITE_BYTE 0x21 (THIS | 0b11000000)
	END
  END
BUT_ONLY

//erase spell alignment restrictions_________________________________________________

COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BAND 0b11111001)
	END
BUT_ONLY

END // end prep vanilla spells function
//___________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION apply_spheres BEGIN

COPY ~faiths_and_powers/spheres/d5spmem.spl~ ~override~
	SAY NAME1 @1100
	SAY UNIDENTIFIED_DESC @1101
	WRITE_ASCII 0x3a ~d5spm3mb~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5spm3mb~ END
COPY ~faiths_and_powers/spheres/d5spm3m.spl~ ~override~
	SAY NAME1 @1100
	SAY UNIDENTIFIED_DESC @1101
	WRITE_ASCII 0x3a ~d5spm3mb~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 0 target = 7 STR_VAR icon = ~d5spm3mb~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5spm3m~ END
COPY ~faiths_and_powers/spheres/d5spm3mb.bam~ ~override~

OUTER_SPRINT sphere_access @1002
OUTER_SPRINT focus_access @1003
OUTER_SPRINT major_access @1004
OUTER_SPRINT minor_access @1005
OUTER_SPRINT advantages @1006
OUTER_SPRINT abilities @1007
OUTER_SPRINT disadvantages @1008
OUTER_SPRINT restrictions @1009
OUTER_TEXT_SPRINT focus_sphere_list ~~
OUTER_TEXT_SPRINT major_sphere_list ~~
OUTER_TEXT_SPRINT minor_sphere_list ~~
OUTER_TEXT_SPRINT paladin_sphere_list ~~
OUTER_TEXT_SPRINT ranger_sphere_list ~~
OUTER_TEXT_SPRINT total_sphere_list ~~

LAM ~READ_FNP_KIT_INFO~

COPY_EXISTING ~d5_class.2da~ ~override~
  READ_2DA_ENTRIES_NOW ~r2en_d5_class~ 2
  FOR (row = 1; row < r2en_d5_class; row += 1) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_d5_class~ row 0 kit
	READ_2DA_ENTRY_FORMER ~r2en_d5_class~ row 1 type
	TEXT_SPRINT $d5_fnp_kit_caster_type(~%kit%~) ~%type%~
  END
BUT_ONLY

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_kitlist~ 10
  FOR (row = 3; row < r2en_kitlist; row += 1) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 5 kit_clab
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 0 kit_index
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kit_label
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 kit_desc
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 9 kit_code
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 8 kit_class
	PATCH_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~%kit_clab%~)) BEGIN
	  SPRINT $d5_kitlist_spheres (~%kit_clab%~ ~%kit_index%~ ~%kit_label%~ ~%kit_desc%~ ~%kit_code%~) ~%kit_class%~
	END
  END
BUT_ONLY
ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~CLERIC~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~cleric_desc~
	  END
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~DRUID~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~druid_desc~
	  END
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~PALADIN~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~paladin_desc~
	  END
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~ranger_desc~
	  END
//	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~SHAMAN~) BEGIN
//	    READ_2DA_ENTRY_FORMER rows row 4 ~shaman_desc~
//	  END
	END
  BUT_ONLY
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABPR01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABPR01~ ~pr~ ~CLERIC~ ~%cleric_desc%~ ~0x00004000~) ~3~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABDR01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABDR01~ ~dr~ ~DRUID~ ~%druid_desc%~ ~0x00004000~) ~11~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABPA01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABPA01~ ~pa~ ~PALADIN~ ~%paladin_desc%~ ~0x00004000~) ~6~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABRN01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABRN01~ ~rn~ ~RANGER~ ~%ranger_desc%~ ~0x00004000~) ~12~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABSH01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABSH01~ ~sh1~ ~SHAMAN~ ~%shaman_desc%~ ~0x00004000~) ~21~
  END

END
ACTION_FOR_EACH base_kit IN ~clabpr01~ ~clabdr01~ BEGIN
  APPEND ~%base_kit%.2da~ ~SPHERES     AP_D5SPMEM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
	UNLESS ~AP_D5SPMEM~
END
ACTION_PHP_EACH d5_kitlist_spheres AS goo => roo BEGIN
	ACTION_IF (%roo% = 3) OR  
 			(%roo% = 11) OR  
 			(%roo% = 8) OR  
 			(%roo% = 14) OR  
 			(%roo% = 15) OR  
 			(%roo% = 18) OR
 			(%roo% = 21) BEGIN
	  COPY_EXISTING ~luabbr.2da~ ~override~
		REPLACE_TEXTUALLY ~^\(%goo_2%[ %TAB%]+\).+$~ ~\1b_%goo_1%~
	  BUT_ONLY
	END
	COPY_EXISTING ~luclxyz.2da~ ~override/lub_%goo_1%.2da~
	ACTION_IF (%roo% = 11) BEGIN 	// druid
	  COPY_EXISTING ~ludrxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 8) BEGIN 	// f/c
	  COPY_EXISTING ~lufcxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 18) BEGIN 	// c/r
	  COPY_EXISTING ~lucrxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 15) BEGIN 	// c/t
	  COPY_EXISTING ~luctxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 14) BEGIN 	// c/m
	  COPY_EXISTING ~lucmxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	APPEND ~%goo%.2da~ ~SPHERES     AP_D5SPUNI  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
	ACTION_PHP_EACH d5_fnp_spheres AS sphere => val BEGIN
	  COPY_EXISTING ~d5altsph.2da~ ~override~
		READ_2DA_ENTRIES_NOW rows 2
		FOR (row = 0; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 0 ~fnp_sphere~
		  READ_2DA_ENTRY_FORMER rows row 1 ~alt_sphere~
		  PATCH_IF (~%sphere%~ STRING_EQUAL_CASE ~%fnp_sphere%~) BEGIN
			SPRINT ~text_sphere~ ~%alt_sphere%~
		  END
		END
	  BUT_ONLY
	  ACTION_IF (VARIABLE_IS_SET $d5_fnp_kit_sphere_access(~%sphere%~ ~%goo%~)) BEGIN
		OUTER_TEXT_SPRINT access $d5_fnp_kit_sphere_access(~%sphere%~ ~%goo%~)
		OUTER_INNER_PATCH ~%sphere%~ BEGIN
		  SNPRINT 3 ~shortsphere~ ~%sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~FOCUS~) BEGIN
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
		   COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/hlas/%sphere%/hlas_%sphere%.txt~
		   BUT_ONLY
		  END
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]zzz~ ~~
		  BUT_ONLY
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__5E_casting_divine.d5~) /*AND !(FILE_EXISTS_IN_GAME ~d5__fnp_spont_casting.d5~)*/ BEGIN
			    APPEND ~%goo%.2da~ ~SPHERES     AP_D5SF%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			  END
			  ACTION_IF (FILE_EXISTS_IN_GAME ~d5__5E_casting_divine.d5~) OR (FILE_EXISTS_IN_GAME ~d5__fnp_spont_casting.d5~) BEGIN
			    APPEND ~%goo%.2da~ ~SPHERES     AP_D5ZF%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			  END
			END
		  END
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && (~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT focus_sphere_list ~%focus_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~MAJOR~) BEGIN
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
		   COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~faiths_and_powers/spheres/hlas/%sphere%/hlas_%sphere%.txt~
		   BUT_ONLY
		  END
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]zzz~ ~~
		  BUT_ONLY
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT major_sphere_list ~%major_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~MINOR~) BEGIN
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SM%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~PALADIN~) BEGIN
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list%, %text_sphere%~
		END
	  END
	END
	ACTION_IF !(~%focus_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT focus_sphere_list ~%WNL%%focus_access%%focus_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%focus_sphere_list%~
	ACTION_IF !(~%major_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT major_sphere_list ~%WNL%%major_access%%major_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%major_sphere_list%~
	ACTION_IF !(~%minor_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT minor_sphere_list ~%WNL%%minor_access%%minor_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%minor_sphere_list%~
	OUTER_INNER_PATCH_SAVE total_sphere_list ~%total_sphere_list%~ BEGIN
		REPLACE_TEXTUALLY ~:,~ ~:~
	END
	OUTER_TEXT_SPRINT kit_sphere_list ~%abilities% %total_sphere_list%~
	ACTION_IF IS_AN_INT ~%goo_3%~ BEGIN
		ACTION_GET_STRREF %goo_3% kit_description 
		OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
			REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
			REPLACE_TEXTUALLY ~%advantages%~ ~%kit_sphere_list%~
		END
		STRING_SET_EVALUATE %goo_3% ~%kit_description%~
	END
	OUTER_TEXT_SPRINT focus_sphere_list ~~
	OUTER_TEXT_SPRINT major_sphere_list ~~
	OUTER_TEXT_SPRINT minor_sphere_list ~~
	OUTER_TEXT_SPRINT total_sphere_list ~~
	ACTION_IF (%roo% = 3) OR  
 			(%roo% = 11) OR  
 			(%roo% = 6) OR  
 			(%roo% = 12) BEGIN
	  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SPMEM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	    UNLESS ~AP_D5SPMEM~
 	END
	ACTION_IF (%roo% = 8) OR  
 			(%roo% = 14) OR  
 			(%roo% = 15) OR  
 			(%roo% = 18) OR
 			(%roo% = 16) BEGIN
	  ACTION_IF (%roo% = 8) OR  
 				(%roo% = 14) OR  
 				(%roo% = 15) OR  
 				(%roo% = 18) BEGIN
 	 	OUTER_TEXT_SPRINT class_letter ~P~
 	  END
	  ACTION_IF (%roo% = 16) BEGIN
 	 	OUTER_TEXT_SPRINT class_letter ~D~
 	  END
	  ACTION_IF IS_AN_INT ~%goo_4%~ BEGIN
		COPY_EXISTING ~%goo%.2da~ ~override~ 
		  COUNT_2DA_COLS cols 
		  READ_2DA_ENTRIES_NOW rows cols  
		  FOR (row = 1; row < rows; ++row) BEGIN 
			READ_2DA_ENTRY_FORMER rows row 0 sphere
			PATCH_IF (~%sphere%~ STRING_EQUAL_CASE ~SPHERES~) BEGIN	
			  FOR (col = 1; col < cols; ++col) BEGIN 
				READ_2DA_ENTRY_FORMER rows row col ability
				PATCH_IF (NOT ~%ability%~ STRING_EQUAL ~****~) BEGIN 
				  SET string_length = (STRING_LENGTH ~%ability%~) - 3
				  LPF SUBSTRING INT_VAR start = 3 length = EVAL %string_length% STR_VAR string = EVAL ~%ability%~ RET abil_new = substring END
				  INNER_ACTION BEGIN 
					ACTION_IF !(FILE_EXISTS_IN_GAME ~QD_MC_AP.eff~) BEGIN
					  CREATE EFF ~QD_MC_AP~ 
						WRITE_LONG   0x10 146 //cast spell
						WRITE_LONG   0x14 2   //preset target 
						WRITE_LONG   0x20 1   //cast instantly (ignore level) 
						WRITE_SHORT  0x24 1   //permament until death
						WRITE_SHORT  0x2c 100 //probability 100% 
					END
					COPY_EXISTING ~QD_MC_AP.eff~ ~override/%abil_new%#.eff~
					  WRITE_EVALUATED_ASCII 0x30 ~%abil_new%~
					  SET col_length = STRING_LENGTH ~%col%~
					LAF QD_ENSURE_QDMC_SPL STR_VAR base_class = EVAL ~%class_letter%~ END
					ACTION_IF (%col_length% = 1) BEGIN 
					  COPY_EXISTING ~override/QD_MC%class_letter%0%col%.spl~ ~override~ 
						LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 timing = 9 resist_dispel = 0 power = 0 parameter1 = %goo_4% parameter2 = 9 STR_VAR resource = EVAL ~%abil_new%#~ END  
					END 
					ACTION_IF (%col_length% = 2) BEGIN
					  COPY_EXISTING ~override/QD_MC%class_letter%%col%.spl~ ~override~ 
						LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 timing = 9 resist_dispel = 0 power = 0 parameter1 = %goo_4% parameter2 = 9 STR_VAR resource = EVAL ~%abil_new%#~ END  
					END 
				  END 
				END
			  END 
			END 
		  END
		BUT_ONLY
	  END
	END
END
ACTION_FOR_EACH base_kit IN ~clabpr01~ ~clabdr01~ BEGIN
  APPEND ~%base_kit%.2da~ ~SPHERES     AP_D5SPMEM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
	UNLESS ~AP_D5SPMEM~
END
COPY_EXISTING ~QD_MCP01.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~QD#MCP01~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~QD#MCP01~ END
IF_EXISTS BUT_ONLY
COPY_EXISTING ~QD_MCD01.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~QD#MCD01~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~QD#MCD01~ END
IF_EXISTS BUT_ONLY
//___________________________________________________________________________________

CLEAR_ARRAYS

//copy HLAs and related files________________________________________________________
//
ACTION_IF GAME_IS ~tob bg2ee eet~ BEGIN
	INCLUDE ~faiths_and_powers/lib/hlas.tpa~
END
//___________________________________________________________________________________

//fix contingency spells_____________________________________________________________
//
ACTION_FOR_EACH contingency IN ~d5pw617~ ~d5fw617~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%contingency%.spl~ BEGIN
	COPY_EXISTING ~%contingency%.spl~ ~override~
	  LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
	  LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 146 target = 1 power = 6 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~spwi617~ END
	BUT_ONLY
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5hkno1.spl~ BEGIN
  COPY_EXISTING ~d5hkno1.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
	LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 146 target = 1 power = 6 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~spwi908~ END
  BUT_ONLY
END
//___________________________________________________________________________________


END // end apply spheres function


//___________________________________________________________________________________
//___________________________________________________________________________________


DEFINE_ACTION_FUNCTION universal_spells BEGIN

//finally, make sure universal spells are universal_________________________________
//
COPY_EXISTING ~d5spsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 4
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 spl
	READ_2DA_ENTRY_FORMER rows row 2 sph
	PATCH_IF (~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
	  PATCH_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~%spl%[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN
		LPF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spl%~ RET spell_res spell_num END
		TEXT_SPRINT the_spell ~%spell_res%~
	  END
	  ELSE BEGIN
		TEXT_SPRINT the_spell ~%spl%~
	  END  
	  PATCH_IF FILE_EXISTS_IN_GAME ~%the_spell%.spl~ BEGIN
		INNER_ACTION BEGIN
		  COPY_EXISTING ~%the_spell%.spl~ ~override~
			WRITE_BYTE 0x21 (THIS BAND 0b00111111)
		  BUT_ONLY
		END
	 END
	END
  END
BUT_ONLY
//__________________________________________________________________________________

END // end universal spells function


//__________________________________________________________________________________
//__________________________________________________________________________________

