
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								 SPHERE SYSTEM
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_MACRO which_sphere_strings BEGIN

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT life_string @12102
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT death_string @12103
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT benediction_string @12104
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT destruction_string @12105
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT protection_string @12106
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT war_string @12207
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT exploration_string @12108
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT knowledge_string @12109
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT deception_string @12110
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT thought_string @12111
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT dread_string @12112
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT vigor_string @12113
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT affliction_string @12114
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT animal_string @12115
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT plant_string @12116
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT earth_string @12117
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT air_string @12118
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT water_string @12119
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT fire_string @12120
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT light_string @12121
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT shadow_string @12122
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT magic_string @12123
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spheres.d5~) BEGIN
  OUTER_SPRINT astral_string @12124
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT life_string @12202
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT death_string @12203
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT benediction_string @12204
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT destruction_string @12205
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT protection_string @12206
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT war_string @12207
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT exploration_string @12208
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT knowledge_string @12209
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT deception_string @12210
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT thought_string @12211
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT dread_string @12212
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT vigor_string @12213
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT affliction_string @12214
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT animal_string @12215
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT plant_string @12216
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT earth_string @12217
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT air_string @12218
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT water_string @12219
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT fire_string @12220
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT light_string @12221
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT shadow_string @12222
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT magic_string @12223
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__2e_spheres.d5~) BEGIN
  OUTER_SPRINT astral_string @12224
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT life_string @12302
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT death_string @12303
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT benediction_string @12304
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT destruction_string @12305
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT protection_string @12306
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT war_string @12307
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT exploration_string @12308
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT knowledge_string @12309
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT deception_string @12310
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT thought_string @12311
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT dread_string @12312
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT vigor_string @12313
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT affliction_string @12314
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT animal_string @12315
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT plant_string @12316
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT earth_string @12317
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT air_string @12318
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT water_string @12319
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT fire_string @12320
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT light_string @12321
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT shadow_string @12322
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT magic_string @12323
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__vanilla_spheres.d5~) OR (FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
  OUTER_SPRINT astral_string @12324
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT life_string @12502
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT death_string @12503
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT benediction_string @12504
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT destruction_string @12505
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT protection_string @12506
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT war_string @12507
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT exploration_string @12508
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT knowledge_string @12509
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT deception_string @12510
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT thought_string @12511
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT dread_string @12512
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT vigor_string @12513
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT affliction_string @12514
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT animal_string @12515
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT plant_string @12516
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT earth_string @12517
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT air_string @12518
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT water_string @12519
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT fire_string @12520
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT light_string @12521
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT shadow_string @12522
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT magic_string @12523
END
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__nu_fnp_spheres.d5~) BEGIN
  OUTER_SPRINT astral_string @12524
END

OUTER_SET dlg_life = RESOLVE_STR_REF (~%life_string%~)
OUTER_SET dlg_death = RESOLVE_STR_REF (~%death_string%~)
OUTER_SET dlg_benediction = RESOLVE_STR_REF (~%benediction_string%~)
OUTER_SET dlg_destruction = RESOLVE_STR_REF (~%destruction_string%~)
OUTER_SET dlg_protection = RESOLVE_STR_REF (~%protection_string%~)
OUTER_SET dlg_war = RESOLVE_STR_REF (~%war_string%~)
OUTER_SET dlg_exploration = RESOLVE_STR_REF (~%exploration_string%~)
OUTER_SET dlg_knowledge = RESOLVE_STR_REF (~%knowledge_string%~)
OUTER_SET dlg_deception = RESOLVE_STR_REF (~%deception_string%~)
OUTER_SET dlg_thought = RESOLVE_STR_REF (~%thought_string%~)
OUTER_SET dlg_dread = RESOLVE_STR_REF (~%dread_string%~)
OUTER_SET dlg_vigor = RESOLVE_STR_REF (~%vigor_string%~)
OUTER_SET dlg_affliction = RESOLVE_STR_REF (~%affliction_string%~)
OUTER_SET dlg_animal = RESOLVE_STR_REF (~%animal_string%~)
OUTER_SET dlg_plant = RESOLVE_STR_REF (~%plant_string%~)
OUTER_SET dlg_earth = RESOLVE_STR_REF (~%earth_string%~)
OUTER_SET dlg_air = RESOLVE_STR_REF (~%air_string%~)
OUTER_SET dlg_water = RESOLVE_STR_REF (~%water_string%~)
OUTER_SET dlg_fire = RESOLVE_STR_REF (~%fire_string%~)
OUTER_SET dlg_light = RESOLVE_STR_REF (~%light_string%~)
OUTER_SET dlg_shadow = RESOLVE_STR_REF (~%shadow_string%~)
OUTER_SET dlg_magic = RESOLVE_STR_REF (~%magic_string%~)
OUTER_SET dlg_astral = RESOLVE_STR_REF (~%astral_string%~)

END // end macro
//__________________________________________________________________________________


//___________________________________________________________________________________
//___________________________________________________________________________________


DEFINE_ACTION_MACRO define_sphere_names BEGIN

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5altsph.2da~) BEGIN

WITH_TRA ~faiths_and_powers/language/english/setup.tra~ BEGIN
  OUTER_SPRINT universal_string @12101
END

COPY ~faiths_and_powers/data/sphere_systems/d5altsph.2da~ ~override~

LAM which_sphere_strings

COPY_EXISTING ~d5altsph.2da~ ~override~
  REPLACE_TEXTUALLY ~new_Universal~ ~%universal_string%~
  REPLACE_TEXTUALLY ~new_Life~ ~%life_string%~
  REPLACE_TEXTUALLY ~new_Death~ ~%death_string%~
  REPLACE_TEXTUALLY ~new_Benediction~ ~%benediction_string%~
  REPLACE_TEXTUALLY ~new_Destruction~ ~%destruction_string%~
  REPLACE_TEXTUALLY ~new_Protection~ ~%protection_string%~
  REPLACE_TEXTUALLY ~new_War~ ~%war_string%~
  REPLACE_TEXTUALLY ~new_Exploration~ ~%exploration_string%~
  REPLACE_TEXTUALLY ~new_Knowledge~ ~%knowledge_string%~
  REPLACE_TEXTUALLY ~new_Deception~ ~%deception_string%~
  REPLACE_TEXTUALLY ~new_Thought~ ~%thought_string%~
  REPLACE_TEXTUALLY ~new_Dread~ ~%dread_string%~
  REPLACE_TEXTUALLY ~new_Vigor~ ~%vigor_string%~
  REPLACE_TEXTUALLY ~new_Affliction~ ~%affliction_string%~
  REPLACE_TEXTUALLY ~new_Animal~ ~%animal_string%~
  REPLACE_TEXTUALLY ~new_Plant~ ~%plant_string%~
  REPLACE_TEXTUALLY ~new_Earth~ ~%earth_string%~
  REPLACE_TEXTUALLY ~new_Air~ ~%air_string%~
  REPLACE_TEXTUALLY ~new_Water~ ~%water_string%~
  REPLACE_TEXTUALLY ~new_Fire~ ~%fire_string%~
  REPLACE_TEXTUALLY ~new_Light~ ~%light_string%~
  REPLACE_TEXTUALLY ~new_Shadow~ ~%shadow_string%~
  REPLACE_TEXTUALLY ~new_Magic~ ~%magic_string%~
  REPLACE_TEXTUALLY ~new_Astral~ ~%astral_string%~

WITH_TRA ~faiths_and_powers/language/english/setup.tra~ BEGIN

LAM which_sphere_strings

COPY_EXISTING ~d5altsph.2da~ ~override~
  REPLACE_TEXTUALLY ~eng_Universal~ ~%universal_string%~
  REPLACE_TEXTUALLY ~eng_Life~ ~%life_string%~
  REPLACE_TEXTUALLY ~eng_Death~ ~%death_string%~
  REPLACE_TEXTUALLY ~eng_Benediction~ ~%benediction_string%~
  REPLACE_TEXTUALLY ~eng_Destruction~ ~%destruction_string%~
  REPLACE_TEXTUALLY ~eng_Protection~ ~%protection_string%~
  REPLACE_TEXTUALLY ~eng_War~ ~%war_string%~
  REPLACE_TEXTUALLY ~eng_Exploration~ ~%exploration_string%~
  REPLACE_TEXTUALLY ~eng_Knowledge~ ~%knowledge_string%~
  REPLACE_TEXTUALLY ~eng_Deception~ ~%deception_string%~
  REPLACE_TEXTUALLY ~eng_Thought~ ~%thought_string%~
  REPLACE_TEXTUALLY ~eng_Dread~ ~%dread_string%~
  REPLACE_TEXTUALLY ~eng_Vigor~ ~%vigor_string%~
  REPLACE_TEXTUALLY ~eng_Affliction~ ~%affliction_string%~
  REPLACE_TEXTUALLY ~eng_Animal~ ~%animal_string%~
  REPLACE_TEXTUALLY ~eng_Plant~ ~%plant_string%~
  REPLACE_TEXTUALLY ~eng_Earth~ ~%earth_string%~
  REPLACE_TEXTUALLY ~eng_Air~ ~%air_string%~
  REPLACE_TEXTUALLY ~eng_Water~ ~%water_string%~
  REPLACE_TEXTUALLY ~eng_Fire~ ~%fire_string%~
  REPLACE_TEXTUALLY ~eng_Light~ ~%light_string%~
  REPLACE_TEXTUALLY ~eng_Shadow~ ~%shadow_string%~
  REPLACE_TEXTUALLY ~eng_Magic~ ~%magic_string%~
  REPLACE_TEXTUALLY ~eng_Astral~ ~%astral_string%~

END // end with_tra

END // end if not already exist

END	//	end sphere names macro
//__________________________________________________________________________________


//___________________________________________________________________________________
//___________________________________________________________________________________


DEFINE_ACTION_FUNCTION create_spheres BEGIN

//copy marker file___________________________________________________________________
//
//COPY ~faiths_and_powers/lib/markers/d5_marker.d5~ ~override/d5__spheres.d5~ 

// already did this in the .tp2
//___________________________________________________________________________________


//game check_________________________________________________________________________
//
ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END
//___________________________________________________________________________________

/* not needed with 4b17+
//handle SR spells___________________________________________________________________
//
ACTION_IF ((!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_OBSCURING_MIST~)) AND (FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~)) BEGIN
   INCLUDE ~faiths_and_powers/lib/add_ids.tpa~
END
//___________________________________________________________________________________
*/

//create sphere spells______________________________________________________________
//
//all/universal
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spuni.spl~
//life
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5splif.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5splif~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5splifx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sflif.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5splif~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sflifx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smlif.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smlifx~ END
//death
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spdea.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdea~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spdeax~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfdea.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdea~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfdeax~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smdea.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smdeax~ END
//benediction
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spben.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spben~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spbenx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfben.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spben~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfbenx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smben.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smbenx~ END
//Destruction
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spdes.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdes~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spdesx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfdes.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdes~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfdesx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smdes.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smdesx~ END
//Protection
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sppro.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5sppro~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spprox~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfpro.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5sppro~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfprox~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smpro.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smprox~ END
//war
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spwar.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spwar~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spwarx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfwar.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spwar~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfwarx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smwar.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smwarx~ END
//exploration
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spexp.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spexp~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spexpx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfexp.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spexp~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfexpx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smexp.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smexpx~ END
//knowledge
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spkno.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spkno~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spknox~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfkno.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spkno~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfknox~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smkno.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smknox~ END
//deception
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spdec.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdec~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spdecx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfdec.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdec~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfdecx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smdec.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smdecx~ END
//thought
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sptho.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5sptho~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spthox~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sftho.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5sptho~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfthox~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smtho.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smthox~ END
//dread
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spdre.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdre~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spdrex~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfdre.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spdre~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfdrex~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smdre.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smdrex~ END
//Vigor
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spvig.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spvig~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spvigx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfvig.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spvig~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfvigx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smvig.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smvigx~ END
//affliction
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spaff.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spaff~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spaffx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfaff.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spaff~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfaffx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smaff.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smaffx~ END
//animal
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spani.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spani~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spanix~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfani.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spani~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfanix~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smani.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smanix~ END
//plant
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sppla.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5sppla~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spplax~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfpla.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5sppla~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfplax~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smpla.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smplax~ END
//earth
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spear.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spear~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spearx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfear.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spear~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfearx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smear.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smearx~ END
//air
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spair.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spair~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spairx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfair.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spair~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfairx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smair.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smairx~ END
//water
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spwat.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spwat~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spwatx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfwat.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spwat~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfwatx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smwat.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smwatx~ END
//fire
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spfir.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spfir~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spfirx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sffir.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spfir~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sffirx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smfir.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smfirx~ END
//light
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5splig.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5splig~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spligx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sflig.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5splig~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfligx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smlig.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smligx~ END

//shadow
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spsha.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spsha~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spshax~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfsha.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spsha~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfshax~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smsha.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smshax~ END
//magic
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spmag.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spmag~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spmagx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfmag.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spmag~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfmagx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smmag.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smmagx~ END
//astral
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5spast.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spast~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5spastx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5sfast.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = ~d5spast~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sfastx~ END
COPY ~faiths_and_powers/data/misc/d5sxyz.spl~ ~override/d5smast.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5smastx~ END
//__________________________________________________________________________________

//create sphere effs if necessary____________________________________________________
//
<<<<<<<< .../inlined/d5_blank.file
>>>>>>>>
ACTION_IF !(FILE_EXISTS ~.../inlined/QD_MC_AP.EFF~) BEGIN
  COPY - ~.../inlined/d5_blank.file~ ~.../inlined/QD_MC_AP.EFF~
    INSERT_BYTES 0 0x110
    WRITE_ASCII  0x00 "EFF V2.0EFF V2.0" (16)
    PATCH_FOR_EACH ofs IN ~0x80~ ~0x84~ ~0x88~ ~0x8c~ BEGIN
      WRITE_LONG ofs "-1"
    END
    WRITE_LONG   0x10 146 // cast spell
    WRITE_LONG   0x14 2   // preset target
    WRITE_LONG   0x20 1   // cast instantly (ignore level)
    WRITE_SHORT  0x24 1   // permament until death
    WRITE_SHORT  0x2c 100 // probability 100%
END

COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5splif#.eff~
  WRITE_ASCII 0x30 ~d5splif~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sflif#.eff~
  WRITE_ASCII 0x30 ~d5sflif~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smlif#.eff~
  WRITE_ASCII 0x30 ~d5smlif~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spdea#.eff~
  WRITE_ASCII 0x30 ~d5spdea~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfdea#.eff~
  WRITE_ASCII 0x30 ~d5sfdea~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smdea#.eff~
  WRITE_ASCII 0x30 ~d5smdea~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spben#.eff~
  WRITE_ASCII 0x30 ~d5spben~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfben#.eff~
  WRITE_ASCII 0x30 ~d5sfben~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smben#.eff~
  WRITE_ASCII 0x30 ~d5smben~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spdes#.eff~
  WRITE_ASCII 0x30 ~d5spdes~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfdes#.eff~
  WRITE_ASCII 0x30 ~d5sfdes~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smdes#.eff~
  WRITE_ASCII 0x30 ~d5smdes~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sppro#.eff~
  WRITE_ASCII 0x30 ~d5sppro~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfpro#.eff~
  WRITE_ASCII 0x30 ~d5sfpro~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smpro#.eff~
  WRITE_ASCII 0x30 ~d5smpro~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spwar#.eff~
  WRITE_ASCII 0x30 ~d5spwar~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfwar#.eff~
  WRITE_ASCII 0x30 ~d5sfwar~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smwar#.eff~
  WRITE_ASCII 0x30 ~d5smwar~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spexp#.eff~
  WRITE_ASCII 0x30 ~d5spexp~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfexp#.eff~
  WRITE_ASCII 0x30 ~d5sfexp~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smexp#.eff~
  WRITE_ASCII 0x30 ~d5smexp~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spkno#.eff~
  WRITE_ASCII 0x30 ~d5spkno~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfkno#.eff~
  WRITE_ASCII 0x30 ~d5sfkno~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smkno#.eff~
  WRITE_ASCII 0x30 ~d5smkno~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spdec#.eff~
  WRITE_ASCII 0x30 ~d5spdec~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfdec#.eff~
  WRITE_ASCII 0x30 ~d5sfdec~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smdec#.eff~
  WRITE_ASCII 0x30 ~d5smdec~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sptho#.eff~
  WRITE_ASCII 0x30 ~d5sptho~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sftho#.eff~
  WRITE_ASCII 0x30 ~d5sftho~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smtho#.eff~
  WRITE_ASCII 0x30 ~d5smtho~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spdre#.eff~
  WRITE_ASCII 0x30 ~d5spdre~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfdre#.eff~
  WRITE_ASCII 0x30 ~d5sfdre~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smdre#.eff~
  WRITE_ASCII 0x30 ~d5smdre~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spvig#.eff~
  WRITE_ASCII 0x30 ~d5spvig~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfvig#.eff~
  WRITE_ASCII 0x30 ~d5sfvig~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smvig#.eff~
  WRITE_ASCII 0x30 ~d5smvig~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spaff#.eff~
  WRITE_ASCII 0x30 ~d5spaff~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfaff#.eff~
  WRITE_ASCII 0x30 ~d5sfaff~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smaff#.eff~
  WRITE_ASCII 0x30 ~d5smaff~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spani#.eff~
  WRITE_ASCII 0x30 ~d5spani~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfani#.eff~
  WRITE_ASCII 0x30 ~d5sfani~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smani#.eff~
  WRITE_ASCII 0x30 ~d5smani~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sppla#.eff~
  WRITE_ASCII 0x30 ~d5sppla~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfpla#.eff~
  WRITE_ASCII 0x30 ~d5sfpla~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smpla#.eff~
  WRITE_ASCII 0x30 ~d5smpla~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spear#.eff~
  WRITE_ASCII 0x30 ~d5spear~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfear#.eff~
  WRITE_ASCII 0x30 ~d5sfear~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smear#.eff~
  WRITE_ASCII 0x30 ~d5smear~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spair#.eff~
  WRITE_ASCII 0x30 ~d5spair~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfair#.eff~
  WRITE_ASCII 0x30 ~d5sfair~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smair#.eff~
  WRITE_ASCII 0x30 ~d5smair~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spwat#.eff~
  WRITE_ASCII 0x30 ~d5spwat~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfwat#.eff~
  WRITE_ASCII 0x30 ~d5sfwat~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smwat#.eff~
  WRITE_ASCII 0x30 ~d5smwat~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spfir#.eff~
  WRITE_ASCII 0x30 ~d5spfir~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sffir#.eff~
  WRITE_ASCII 0x30 ~d5sffir~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smfir#.eff~
  WRITE_ASCII 0x30 ~d5smfir~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5splig#.eff~
  WRITE_ASCII 0x30 ~d5splig~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sflig#.eff~
  WRITE_ASCII 0x30 ~d5sflig~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smlig#.eff~
  WRITE_ASCII 0x30 ~d5smlig~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spsha#.eff~
  WRITE_ASCII 0x30 ~d5spsha~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfsha#.eff~
  WRITE_ASCII 0x30 ~d5sfsha~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smsha#.eff~
  WRITE_ASCII 0x30 ~d5smsha~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spmag#.eff~
  WRITE_ASCII 0x30 ~d5spmag~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfmag#.eff~
  WRITE_ASCII 0x30 ~d5sfmag~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smmag#.eff~
  WRITE_ASCII 0x30 ~d5smmag~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5spast#.eff~
  WRITE_ASCII 0x30 ~d5spast~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5sfast#.eff~
  WRITE_ASCII 0x30 ~d5sfast~ (8)
COPY ~.../inlined/QD_MC_AP.EFF~ ~override/d5smast#.eff~
  WRITE_ASCII 0x30 ~d5smast~ (8)

/*
//add duplication prevention________________________________________________________
//
COPY_EXISTING 
			 ~d5splif.spl~ ~override/d5splifx.spl~
			 ~d5sflif.spl~ ~override/d5sflifx.spl~
			 ~d5smlif.spl~ ~override/d5smlifx.spl~
			 ~d5spdea.spl~ ~override/d5spdeax.spl~
			 ~d5sfdea.spl~ ~override/d5sfdeax.spl~
			 ~d5smdea.spl~ ~override/d5smdeax.spl~
			 ~d5spben.spl~ ~override/d5spbenx.spl~
			 ~d5sfben.spl~ ~override/d5sfbenx.spl~
			 ~d5smben.spl~ ~override/d5smbenx.spl~
			 ~d5spdes.spl~ ~override/d5spdesx.spl~
			 ~d5sfdes.spl~ ~override/d5sfdesx.spl~
			 ~d5smdes.spl~ ~override/d5smdesx.spl~
			 ~d5sppro.spl~ ~override/d5spprox.spl~
			 ~d5sfpro.spl~ ~override/d5sfprox.spl~
			 ~d5smpro.spl~ ~override/d5smprox.spl~
			 ~d5spwar.spl~ ~override/d5spwarx.spl~
			 ~d5sfwar.spl~ ~override/d5sfwarx.spl~
			 ~d5smwar.spl~ ~override/d5smwarx.spl~
			 ~d5spexp.spl~ ~override/d5spexpx.spl~
			 ~d5sfexp.spl~ ~override/d5sfexpx.spl~
			 ~d5smexp.spl~ ~override/d5smexpx.spl~
			 ~d5spkno.spl~ ~override/d5spknox.spl~
			 ~d5sfkno.spl~ ~override/d5sfknox.spl~
			 ~d5smkno.spl~ ~override/d5smknox.spl~
			 ~d5spdec.spl~ ~override/d5spdecx.spl~
			 ~d5sfdec.spl~ ~override/d5sfdecx.spl~
			 ~d5smdec.spl~ ~override/d5smdecx.spl~
			 ~d5sptho.spl~ ~override/d5spthox.spl~
			 ~d5sftho.spl~ ~override/d5sfthox.spl~
			 ~d5smtho.spl~ ~override/d5smthox.spl~
			 ~d5spdre.spl~ ~override/d5spdrex.spl~
			 ~d5sfdre.spl~ ~override/d5sfdrex.spl~
			 ~d5smdre.spl~ ~override/d5smdrex.spl~
			 ~d5spvig.spl~ ~override/d5spvigx.spl~
			 ~d5sfvig.spl~ ~override/d5sfvigx.spl~
			 ~d5smvig.spl~ ~override/d5smvigx.spl~
			 ~d5spaff.spl~ ~override/d5spaffx.spl~
			 ~d5sfaff.spl~ ~override/d5sfaffx.spl~
			 ~d5smaff.spl~ ~override/d5smaffx.spl~
			 ~d5spani.spl~ ~override/d5spanix.spl~
			 ~d5sfani.spl~ ~override/d5sfanix.spl~
			 ~d5smani.spl~ ~override/d5smanix.spl~
			 ~d5sppla.spl~ ~override/d5spplax.spl~
			 ~d5sfpla.spl~ ~override/d5sfplax.spl~
			 ~d5smpla.spl~ ~override/d5smplax.spl~
			 ~d5spear.spl~ ~override/d5spearx.spl~
			 ~d5sfear.spl~ ~override/d5sfearx.spl~
			 ~d5smear.spl~ ~override/d5smearx.spl~
			 ~d5spair.spl~ ~override/d5spairx.spl~
			 ~d5sfair.spl~ ~override/d5sfairx.spl~
			 ~d5smair.spl~ ~override/d5smairx.spl~
			 ~d5spwat.spl~ ~override/d5spwatx.spl~
			 ~d5sfwat.spl~ ~override/d5sfwatx.spl~
			 ~d5smwat.spl~ ~override/d5smwatx.spl~
			 ~d5spfir.spl~ ~override/d5spfirx.spl~
			 ~d5sffir.spl~ ~override/d5sffirx.spl~
			 ~d5smfir.spl~ ~override/d5smfirx.spl~
			 ~d5splig.spl~ ~override/d5spligx.spl~
			 ~d5sflig.spl~ ~override/d5sfligx.spl~
			 ~d5smlig.spl~ ~override/d5smligx.spl~
			 ~d5spsha.spl~ ~override/d5spshax.spl~
			 ~d5sfsha.spl~ ~override/d5sfshax.spl~
			 ~d5smsha.spl~ ~override/d5smshax.spl~
			 ~d5spmag.spl~ ~override/d5spmagx.spl~
			 ~d5sfmag.spl~ ~override/d5sfmagx.spl~
			 ~d5smmag.spl~ ~override/d5smmagx.spl~
			 ~d5spast.spl~ ~override/d5spastx.spl~
			 ~d5sfast.spl~ ~override/d5sfastx.spl~
			 ~d5smast.spl~ ~override/d5smastx.spl~
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
//__________________________________________________________________________________
*/


//prepare spell conversions_________________________________________________________
//
/*
ACTION_IF FILE_EXISTS_IN_GAME ~smcudge.itm~ BEGIN
COPY_EXISTING ~smcudge.itm~ ~override~
	WRITE_BYTE 0x8a 2
END                         
*/

/*
COPY_EXISTING ~sppr737.spl~ ~override/d5_1stal.spl~
	LPF DELETE_EFFECT INT_VAR header=1 END

COPY_EXISTING ~sppr108.spl~ ~override~
	SAY NAME1 ~Courage~
	SAY UNIDENTIFIED_DESC ~Courage: the artist formerly known as remove fear~
COPY_EXISTING ~sppr313.spl~ ~override~
	SAY NAME1 ~Divine Wrath~
	SAY UNIDENTIFIED_DESC ~Divine Wrath: the artist formerly known as holy smite~
COPY_EXISTING ~sppr314.spl~ ~override~
	SAY NAME1 ~Infernal Wrath~
	SAY UNIDENTIFIED_DESC ~Infernal Wrath: the artist formerly known as unholy blight~
COPY_EXISTING ~sppr201.spl~ ~override~
	SAY NAME1 ~Invigorate~
	SAY UNIDENTIFIED_DESC ~Invigorate: the artist formerly known as aid~
COPY_EXISTING ~sppr208.spl~ ~override~
	SAY NAME1 ~Paralyze~
	SAY UNIDENTIFIED_DESC ~Paralyze: the artist formerly known as hold person~
*/
//__________________________________________________________________________________


/*
//add new SR spells_________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN

  INCLUDE ~faiths_and_powers/lib/spell_revisions/sr_%game%.tpa~

END
//__________________________________________________________________________________
*/

//remove priest spells from joinable NPCs____________________________________________
//
OUTER_FOR (level = 1; level <= 7; level += 1) BEGIN
  OUTER_SET $spell(~all~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~cleric~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~druid~ ~%level%~ ~length~) = 0
  OUTER_SET $spell(~bogus~ ~%level%~ ~length~) = 0
END

COPY_EXISTING_REGEXP GLOB ~^SPPR[1-7]\(0[1-9]\|[1-4][0-9]\|50\)\.spl$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_SHORT 0x1c spell_type
    PATCH_IF (spell_type == 2) BEGIN // divine, just to be sure
      READ_SHORT 0x20 priest_type
      READ_SHORT 0x1e exclusion_flags
      READ_LONG  0x34 level
      TO_UPPER SOURCE_RES
      PATCH_IF (priest_type == 0x0000) BEGIN // all priests
        SPRINT type ~all~
      END
      ELSE PATCH_IF (priest_type == 0x4000) BEGIN // druid/ranger
        SPRINT type ~druid~
      END
      ELSE PATCH_IF (priest_type == 0x8000) BEGIN // cleric/paladin
        SPRINT type ~cleric~
      END
      ELSE BEGIN // no priests
        SPRINT type ~bogus~
      END
      PATCH_IF (level > 0 && level <= 7) BEGIN
        SET index = $spell(~%type%~ ~%level%~ ~length~)
        SPRINT $spell(~%type%~ ~%level%~ ~%index%~) ~%SOURCE_RES%~
        SET $spell(~%type%~ ~%level%~ ~length~) += 1
        SET $spell(~%type%~ ~%SOURCE_RES%~) = 1
        SET $spell(~%SOURCE_RES%~ ~excl~) = (exclusion_flags BAND 0b111111) // store just the alignment bits
        SET $spell(~%SOURCE_RES%~ ~level~) = level
      END
    END
  END
  BUT_ONLY

DEFINE_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~ BEGIN
  FOR (level = 1; level <= 7; level += 1) BEGIN
    SET length = $spell(~%type%~ ~%level%~ ~length~)
    FOR (i = 0; i < length; i += 1) BEGIN
      SPRINT spell $spell(~%type%~ ~%level%~ ~%i%~)
      REMOVE_KNOWN_SPELL ~%spell%~
    END
  END
END

DEFINE_PATCH_FUNCTION ~REMOVE_BAD_KNOWN_SPELLS~
 // INT_VAR spell_type = 0 // 1 = cleric, 2 = druid, 3 = both
BEGIN
  PATCH_IF (spell_type == 1) BEGIN // remove druid spells from clerics
    SPRINT type ~druid~
    LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
  END
  ELSE PATCH_IF (spell_type = 2) BEGIN // remove cleric spells from druids
    SPRINT type ~cleric~
    LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
  END

  // remove bogus spells from all classes
  SPRINT type ~bogus~
  LAUNCH_PATCH_MACRO ~REMOVE_SPELLS_OF_TYPE~
END

LAM JOINABLE_NPC_ARRAYS

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
//  PRINT ~%cre% => %dv%~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  READ_BYTE 0x273 class
      PATCH_IF (class == 3 || class == 6 || class == 8 || class == 11 || class == 12 || class == 14 || class == 15 || class == 16 || class == 17 || class == 18) BEGIN // divine casters
        LAUNCH_PATCH_FUNCTION ~REMOVE_BAD_KNOWN_SPELLS~ END
//        REMOVE_MEMORIZED_SPELLS
      END
    END
  BUT_ONLY
END
//__________________________________________________________________________________


//some vanilla spell modifications__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518a.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518a.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr518b.spl~ THEN BEGIN
  COPY_EXISTING ~sppr518b.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 93 END
  BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr150.spl~ THEN BEGIN
  COPY_EXISTING ~sppr150.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 219 parameter1 = 121 END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 219 opcode = 100 parameter1 = 9 parameter2 = 7 END
	SAY UNIDENTIFIED_DESC @59999
  BUT_ONLY
END

COPY_EXISTING - ~spell.ids~ ~faiths_and_powers/backup~
  COUNT_REGEXP_INSTANCES ~CLERIC_ALICORN_LANCE~ spell_exists
ACTION_IF (spell_exists) BEGIN
  LAF RES_NUM_OF_SPELL_NAME
	STR_VAR spell_name = ~CLERIC_ALICORN_LANCE~ RET spell_res 
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~%spell_res%.spl~ BEGIN
	COPY_EXISTING ~%spell_res%.spl~ ~override~
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 12 parameter2 = (0 + 64 << 16) savingthrow = 0 END
	BUT_ONLY
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~sppr314.spl~ THEN BEGIN
  COPY_EXISTING ~sppr314.spl~ ~override~
	WRITE_ASCII 0x3a ~sppr313c~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~sppr313b~ END
  BUT_ONLY
END
//__________________________________________________________________________________


//apply spells to sphere system_____________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5spsph.2da~) BEGIN
  COPY ~d5/d5spsph.2da~ ~override~
END

COPY_EXISTING ~d5spsph.2da~ ~override~
  REPLACE_TEXTUALLY ~//.*$~ ~~
  PATCH_IF !(FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
	REPLACE_TEXTUALLY ~NOSR_~ ~~
  END
  PATCH_IF (FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
	REPLACE_TEXTUALLY ~SR_~ ~~
  END
  PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) BEGIN
	REPLACE_TEXTUALLY ~CLERIC_MISCAST_MAGIC~ ~WIZARD_SPELL_THRUST~
  END
BUT_ONLY

COPY_EXISTING ~d5altsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 2
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~fnp_sphere~
	READ_2DA_ENTRY_FORMER rows row 1 ~alt_sphere~
	READ_2DA_ENTRY_FORMER rows row 2 ~eng_sphere~
	SPRINT $altspheres(~%eng_sphere%~ ~%alt_sphere%~) ~%fnp_sphere%~
  END
BUT_ONLY

COPY_EXISTING ~d5spsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 4
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 3 nu_sph
	PATCH_IF (~%nu_sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
	  SET_2DA_ENTRY row 2 4 ~Universal~
	END
	PHP_EACH altspheres AS eng_sph => fnp_sph BEGIN
	  PATCH_IF (~%eng_sph%~ STRING_EQUAL_CASE ~%nu_sph%~) BEGIN
		SET_2DA_ENTRY row 2 4 ~%fnp_sph%~
	  END
	END
  END
BUT_ONLY

<<<<<<<< d5/d5fnplst.2da
2DA V1.0 
SPLRES
		MAJOR	MINOR	FOCUS	SPHERE	SYSTEM	SPONT_IND	SPONT_PROC
>>>>>>>> 
COPY ~d5/d5fnplst.2da~ ~override/d5fnplst.2da~ 

<<<<<<<<  d5/d5spontsphere.2da
 >>>>>>>>
 COPY ~d5/d5spontsphere.2da~ ~override/d5tpuni.2da~


OUTER_SET spl_ind = 101

COPY_EXISTING ~d5spsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 4
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 spl
	READ_2DA_ENTRY_FORMER rows row 1 lvl
//	READ_2DA_ENTRY_FORMER rows row 2 sph
	READ_2DA_ENTRY_FORMER rows row 3 desc_sph
	PHP_EACH altspheres AS eng_sph => fnp_sph BEGIN
	  PATCH_IF (~%eng_sph%~ STRING_EQUAL_CASE ~%desc_sph%~) BEGIN
		SPRINT sph ~%fnp_sph%~
	  END
	END
	INNER_ACTION BEGIN
/*
	  ACTION_IF (~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
 	 	OUTER_INNER_PATCH ~%sph%~ BEGIN
		  SNPRINT 3 ~shortsphere~ ~%sph%~ 
		  SPRINT sphere ~d5sp%shortsphere%~
		  SPRINT fsphere ~d5sf%shortsphere%~
		  SPRINT msphere ~d5sm%shortsphere%~
		END
	  END
	  ACTION_IF !(~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
*/
 	 	OUTER_INNER_PATCH ~%sph%~ BEGIN
		  SNPRINT 3 ~shortsphere~ ~%sph%~ 
		  SPRINT sphere ~d5sp%shortsphere%~
		  SPRINT fsphere ~d5sf%shortsphere%~
		  SPRINT msphere ~d5sm%shortsphere%~
		END
		ACTION_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~[ %TAB%]%spl%[ %TAB%%LNL%%MNL%%WNL%]~)) || (FILE_EXISTS_IN_GAME ~%spl%.spl~) BEGIN
		  ACTION_FOR_EACH type IN ~p~ ~m~ /*~f~*/ BEGIN
			ACTION_IF !(FILE_EXISTS_IN_GAME ~d5t%type%%shortsphere%.2da~) BEGIN
			  COPY ~d5/d5spontsphere.2da~ ~override/d5t%type%%shortsphere%.2da~
//			  COPY ~faiths_and_powers/data/misc/d5_base.spl~ ~override/d5t%type%%shortsphere%.spl~
			END
		  END
		  ACTION_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~[ %TAB%]%spl%[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN
			LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spl%~ RET spell_res spell_num END
			OUTER_TEXT_SPRINT the_spell ~%spell_res%~
			OUTER_TEXT_SPRINT priest_res ~d5p%spell_num%~
			OUTER_TEXT_SPRINT minor_res ~d5m%spell_num%~
			OUTER_TEXT_SPRINT focus_res ~d5f%spell_num%~
			OUTER_TEXT_SPRINT spont_ind ~%spl_ind%~
		  END
	   	  ELSE BEGIN
			OUTER_TEXT_SPRINT the_spell ~%spl%~
			OUTER_TEXT_SPRINT priest_res ~d5pp%spl_ind%~
			OUTER_TEXT_SPRINT minor_res ~d5mm%spl_ind%~
			OUTER_TEXT_SPRINT focus_res ~d5ff%spl_ind%~
			OUTER_TEXT_SPRINT spont_ind ~%spl_ind%~
		  END 
		  ACTION_IF FILE_EXISTS_IN_GAME ~%the_spell%.spl~ BEGIN 
			COPY_EXISTING ~%the_spell%.spl~ ~override~ 
			  READ_SHORT 0x1c spell_type
			  READ_LONG 0x34 spell_lvl
			BUT_ONLY
			ACTION_IF (%lvl% = 0) BEGIN
			  OUTER_SET plvl = %spell_lvl%
			  OUTER_SET flvl = (%spell_lvl% - 1)
			END ELSE BEGIN
			  OUTER_SET plvl = %lvl%
			  OUTER_SET flvl = (%lvl% - 1)
			END
			ACTION_IF (%spell_type% = 2) BEGIN 							 // priest spells: add to spheres
			  ACTION_IF (%plvl% = %spell_lvl%) BEGIN
				OUTER_SPRINT major_spl ~%the_spell%~
				COPY_EXISTING ~%the_spell%.spl~ ~override~ 
				  READ_LONG 0x50 "valid"
				  PATCH_IF (%valid% >= 0) BEGIN 
					READ_STRREF 0x50 ~desc~
					INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
					  REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
					  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
					  REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					END
					SAY_EVALUATED 0x50 ~%new_desc%~
				  END
				BUT_ONLY
				COPY_EXISTING ~%sphere%.spl~ ~override~ 
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%the_spell%	3~
				ACTION_IF (%plvl% < 4) BEGIN
				  OUTER_SPRINT minor_spl ~%the_spell%~
				  COPY_EXISTING ~%msphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tm%shortsphere%.2da~ ~%sph%	%the_spell%	3~
				END
				ACTION_IF (%plvl% = 1) OR (%plvl% = 7) BEGIN
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%the_spell%	3~
				END
			  END	//	end if level unchanged
			  ACTION_IF !(%plvl% = %spell_lvl%) BEGIN
				OUTER_SPRINT major_spl ~%priest_res%~
				ACTION_IF (FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				  COPY_EXISTING ~%priest_res%.spl~ ~override~ 
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN 
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%sphere%.spl~ ~override~ 
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
				ACTION_IF !(FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				  COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
				  	WRITE_LONG 0x34 %plvl%
					READ_LONG 0x64 abil_offset
					READ_SHORT 0x68 abil_number
					READ_BYTE (%abil_offset% + 0x0c) abil_target					
					READ_SHORT (%abil_offset% + 0x0e) abil_range
					READ_LONG 0x6a eff_offset
					WHILE (%abil_number% > 0) BEGIN
					  SET abil_number = (%abil_number% - 1)
					  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
					END
					LPF DELETE_EFFECT END
					PATCH_IF (%abil_target% = 4) BEGIN
					  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %plvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
					  PATCH_IF (%abil_range% < 35) BEGIN
						PATCH_IF (%abil_range% > 4) BEGIN
							LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
						END
						PATCH_IF (%abil_range% < 5) BEGIN
						  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	
						END
					  END
					END
					ELSE BEGIN
					  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %plvl% parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%the_spell%~ END
					END
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN 
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
						REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%sphere%.spl~ ~override~ 
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
				ACTION_IF (%plvl% = 1) OR (%plvl% = 7) BEGIN
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
				ACTION_IF (%plvl% < 4) BEGIN
				  OUTER_SPRINT minor_spl ~%priest_res%~
				  COPY_EXISTING ~%msphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
				  APPEND ~d5tm%shortsphere%.2da~ ~%sph%	%priest_res%	3~
				END
			  END	//	end level differs from vanilla
			  ACTION_IF (%plvl% > 1) BEGIN
				  ACTION_IF (FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
					COPY_EXISTING ~%focus_res%.spl~ ~override~
					  READ_LONG 0x50 "valid"
					  PATCH_IF (%valid% >= 0) BEGIN 
						READ_STRREF 0x50 ~desc~
						INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
						END
						SAY_EVALUATED 0x50 ~%new_desc%~
					  END
					BUT_ONLY
					COPY_EXISTING ~%fsphere%.spl~ ~override~
					  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
					IF_EXISTS BUT_ONLY
//				 	APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				  END
				  ACTION_IF !(FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
					COPY_EXISTING ~%the_spell%.spl~ ~override/%focus_res%.spl~ 	
					  WRITE_LONG 0x34 %flvl%
					  READ_LONG 0x64 abil_offset
					  READ_SHORT 0x68 abil_number
					  READ_BYTE (%abil_offset% + 0x0c) abil_target
					  READ_SHORT (%abil_offset% + 0x0e) abil_range
					  READ_LONG 0x6a eff_offset
					  WHILE (%abil_number% > 0) BEGIN
						SET abil_number = (%abil_number% - 1)
						WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
					  END
					  LPF DELETE_EFFECT END
					  PATCH_IF (%abil_target% = 4) BEGIN
						LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %plvl% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%the_spell%~ END
						PATCH_IF (%abil_range% < 35) BEGIN
						  PATCH_IF (%abil_range% > 4) BEGIN
							LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
						  END
						  PATCH_IF (%abil_range% < 5) BEGIN
							LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	
						  END
						END
					  END
					  ELSE BEGIN
						LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %plvl% parameter1 = 0 parameter2 = 1 timing = 2 STR_VAR resource = EVAL ~%the_spell%~ END
					  END
					  READ_LONG 0x50 "valid"
					  PATCH_IF (%valid% >= 0) BEGIN 
						READ_STRREF 0x50 ~desc~
						INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						  REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
						  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
						  REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
						END
						SAY_EVALUATED 0x50 ~%new_desc%~
					  END
					BUT_ONLY
					COPY_EXISTING ~%fsphere%.spl~ ~override~
					  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
					IF_EXISTS BUT_ONLY
//				 	APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				  END
			  END 	//	end focus spells
			  ACTION_IF (%plvl% > 3) BEGIN
				OUTER_SPRINT minor_spl ~****~
			  END
			END // end type = priest spells
//
			ELSE BEGIN // non-priest spells: make clones
//	 NOTE: STRIP OUT 216 EFFECTS FROM TNB LEVEL 1 CANTRIPS
			  OUTER_SPRINT major_spl ~%priest_res%~
			  ACTION_IF (FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
				  READ_LONG 0x50 "valid"
				  PATCH_IF (%valid% >= 0) BEGIN 
					READ_STRREF 0x50 ~desc~
					INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
					  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
					END
					SAY_EVALUATED 0x50 ~%new_desc%~
				  END
				BUT_ONLY
				COPY_EXISTING ~%sphere%.spl~ ~override~
//				  LPF CLONE_EFFECT INT_VAR silent=1 match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = EVAL ~%priest_res%~ END
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF !(FILE_EXISTS_IN_GAME ~%priest_res%.spl~) BEGIN
				COPY_EXISTING ~%the_spell%.spl~ ~override/%priest_res%.spl~ 
				  WRITE_SHORT 0x1c 2
				  LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
				  WRITE_LONG 0x34 %plvl%
				  READ_LONG 0x50 "valid"
				  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
					READ_STRREF 0x50 ~desc~
					INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
					  REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
					  REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
					  REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					END
					SAY_EVALUATED 0x50 ~%new_desc%~
				  END
				BUT_ONLY
				COPY_EXISTING ~%sphere%.spl~ ~override~
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tp%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF (%plvl% = 1) OR (%plvl% = 7) BEGIN
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF (%plvl% < 4) BEGIN
				OUTER_SPRINT minor_spl ~%priest_res%~
				COPY_EXISTING ~%msphere%.spl~ ~override~
				  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%priest_res%~ END
				IF_EXISTS BUT_ONLY
				APPEND ~d5tm%shortsphere%.2da~ ~%sph%	%priest_res%	3~
			  END
			  ACTION_IF (%plvl% > 1) BEGIN
				ACTION_IF (FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
				  COPY_EXISTING ~%focus_res%.spl~ ~override~ 
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN 
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere: ~ ~%WNL%Sphere: %desc_sph%, ~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				END
				ACTION_IF !(FILE_EXISTS_IN_GAME ~%focus_res%.spl~) BEGIN
				  COPY_EXISTING ~%the_spell%.spl~ ~override/%focus_res%.spl~ 	
					WRITE_SHORT 0x1c 2
					LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
					WRITE_LONG 0x34 %flvl%
					READ_LONG 0x50 "valid"
					PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
					  READ_STRREF 0x50 ~desc~
					  INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~^Level:.*$~ ~Level: %plvl%~
						REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]Sphere:.*$~ ~~
						REPLACE_TEXTUALLY ~^Range:~ ~Sphere: %desc_sph% %WNL%Range:~
					  END
					  SAY_EVALUATED 0x50 ~%new_desc%~
					END
				  BUT_ONLY
				  COPY_EXISTING ~%fsphere%.spl~ ~override~
					LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%focus_res%~ END
				  IF_EXISTS BUT_ONLY
//				  APPEND ~d5tf%shortsphere%.2da~ ~%sph%	%focus_res%	3~
				END
			  END
			  ACTION_IF (%plvl% > 3) BEGIN
				OUTER_SPRINT minor_spl ~****~
			  END
			END
			ACTION_IF !(FILE_CONTAINS_EVALUATED (~d5fnplst.2da~ ~%the_spell%[ %TAB%]~)) BEGIN
			  APPEND ~d5fnplst.2da~ ~%the_spell%	%major_spl%	%minor_spl%	%focus_res%	%desc_sph%	%sph%	%spont_ind% 	no ~
			END
		  END
		END
//	  END
	END
	SET spl_ind = (spl_ind + 1)
  END
BUT_ONLY
//__________________________________________________________________________________


//UI work for contingency___________________________________________________________
//
/*
// read d5fnplst.2da
// find row with spwi617 in 1st col
// find value in 2nd/3rd/4th cols
// perform UI stuff on them
// OR... just do it manually:

// this isn't working anymore...
ACTION_FOR_EACH cont_spl IN ~d5p2617~ ~d5m2617~ ~d5f2617~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%cont_spl%.spl~) BEGIN
	APPEND	~BGEE.LUA~	~mageBookStrings['%cont_spl%'] = mageBookStrings['SPWI617']~
  END
END

COPY_EXISTING ~UI.menu~ ~override~
	REPLACE_TEXTUALLY	~mageBookEnabled[ %TAB%]+==[ %TAB%]+true~	~((mageBookEnabled == true) or (bookMode == 1))~
	REPLACE_TEXTUALLY	~mageBookEnabled[ %TAB%]+==[ %TAB%]+false~	~mageBookEnabled == false and bookMode == 0~
BUT_ONLY
*/

// try this instead
COPY_EXISTING ~ui.menu~ ~override~
	REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~contingencyDescription = mageBookStrings[contingencyResRef].tip~ ~			if not pcall(me_problem) then
				contingencyDescription = 0
			end~
	REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~--reload language~ ~function me_problem()
	contingencyDescription = mageBookStrings[contingencyResRef].tip
end
--reload language~
//__________________________________________________________________________________


/*
//add new spells to 206/318/321/324 effects_________________________________________
//
PRINT ~*Please be patient, this should take 1-2 minutes...*~
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~fsphere~ END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=206 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=318 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=321 STR_VAR resource=~fsphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~sphere~ END
	LPF SPELL_CLONE_EFFECTS INT_VAR match_opcode=324 STR_VAR resource=~fsphere~ END
BUT_ONLY
//__________________________________________________________________________________
*/

/*
//set spell alignment restrictions__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~sppr601.spl~ BEGIN  //  aerial servant = good
	COPY_EXISTING ~sppr601.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f1601.spl~ BEGIN  //  aerial servant = good
	COPY_EXISTING ~d5f1601.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5s2707.spl~ BEGIN  //  cacofiend = evil
	COPY_EXISTING ~d5s2707.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f2707.spl~ BEGIN  //  cacofiend = evil
	COPY_EXISTING ~d5f2707.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr710.spl~ BEGIN  //  holy word = good
	COPY_EXISTING ~sppr710.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f1710.spl~ BEGIN  //  holy word = good
	COPY_EXISTING ~d5f1710.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000010)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr715.spl~ BEGIN  //  unholy word = evil
	COPY_EXISTING ~sppr715.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5f1715.spl~ BEGIN  //  unholy word = evil
	COPY_EXISTING ~d5f1715.spl~ ~override~
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BOR 0b00000100)
	BUT_ONLY
END
//__________________________________________________________________________________
*/

/*
//clean up sphere-spell .2da_________________________________________________________
//
COPY_EXISTING ~d5spsph.2da~ ~override~
  PRETTY_PRINT_2DA
//__________________________________________________________________________________
*/

//set up HLA tables_________________________________________________________________
//
COPY_EXISTING ~faiths_and_powers/data/hlas/luclxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/data/hlas/ludrxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/data/hlas/lufcxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/data/hlas/lucrxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/data/hlas/luctxyz.2da~ ~override~
COPY_EXISTING ~faiths_and_powers/data/hlas/lucmxyz.2da~ ~override~
//__________________________________________________________________________________


LAM ~BACKFILL_FNP_KIT_INFO~


END // end create spheres function
//__________________________________________________________________________________


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION prep_vanilla_spells BEGIN

//no spells for anyone!______________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
	READ_SHORT 0x1c ~spelltype~
	PATCH_IF (~spelltype~ = 2) BEGIN
		WRITE_BYTE 0x21 (THIS | 0b11000000)
	END
  END
BUT_ONLY

//erase spell alignment restrictions_________________________________________________

COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
		READ_BYTE 0x1e align
		WRITE_BYTE 0x1e (align BAND 0b11111001)
	END
BUT_ONLY

END // end prep vanilla spells function
//___________________________________________________________________________________


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION apply_spheres BEGIN

COPY ~faiths_and_powers/data/misc/d5spmem.spl~ ~override~
	SAY NAME1 @1100
	SAY UNIDENTIFIED_DESC @1101
	WRITE_ASCII 0x3a ~d5spm3mb~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5spm3mb~ END
COPY ~faiths_and_powers/data/misc/d5spm3m.spl~ ~override~
	SAY NAME1 @1100
	SAY UNIDENTIFIED_DESC @1101
	WRITE_ASCII 0x3a ~d5spm3mb~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 0 target = 7 STR_VAR icon = ~d5spm3mb~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5spm3m~ END
COPY ~faiths_and_powers/data/misc/d5spm3mb.bam~ ~override~

OUTER_SPRINT sphere_access @1002
OUTER_SPRINT focus_access @1003
OUTER_SPRINT major_access @1004
OUTER_SPRINT minor_access @1005
OUTER_SPRINT advantages @1006
OUTER_SPRINT abilities @1007
OUTER_SPRINT disadvantages @1008
OUTER_SPRINT restrictions @1009
OUTER_TEXT_SPRINT focus_sphere_list ~~
OUTER_TEXT_SPRINT major_sphere_list ~~
OUTER_TEXT_SPRINT minor_sphere_list ~~
OUTER_TEXT_SPRINT paladin_sphere_list ~~
OUTER_TEXT_SPRINT ranger_sphere_list ~~
OUTER_TEXT_SPRINT total_sphere_list ~~

LAM ~READ_FNP_KIT_INFO~

COPY_EXISTING ~d5_class.2da~ ~override~
  READ_2DA_ENTRIES_NOW ~r2en_d5_class~ 2
  FOR (row = 1; row < r2en_d5_class; row += 1) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_d5_class~ row 0 kit
	READ_2DA_ENTRY_FORMER ~r2en_d5_class~ row 1 type
	TEXT_SPRINT $d5_fnp_kit_caster_type(~%kit%~) ~%type%~
  END
BUT_ONLY

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_kitlist~ 10
  FOR (row = 3; row < r2en_kitlist; row += 1) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 5 kit_clab
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 0 kit_index
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kit_label
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 kit_desc
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 9 kit_code
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 8 kit_class
	PATCH_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~%kit_clab%~)) BEGIN
	  SPRINT $d5_kitlist_spheres (~%kit_clab%~ ~%kit_index%~ ~%kit_label%~ ~%kit_desc%~ ~%kit_code%~) ~%kit_class%~
	END
  END
BUT_ONLY
ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~CLERIC~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~cleric_desc~
	  END
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~DRUID~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~druid_desc~
	  END
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~PALADIN~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~paladin_desc~
	  END
	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
	    READ_2DA_ENTRY_FORMER rows row 4 ~ranger_desc~
	  END
//	  PATCH_IF (~%text%~ STRING_EQUAL_CASE ~SHAMAN~) BEGIN
//	    READ_2DA_ENTRY_FORMER rows row 4 ~shaman_desc~
//	  END
	END
  BUT_ONLY
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABPR01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABPR01~ ~pr~ ~CLERIC~ ~%cleric_desc%~ ~0x00004000~) ~3~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABDR01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABDR01~ ~dr~ ~DRUID~ ~%druid_desc%~ ~0x00004000~) ~11~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABPA01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABPA01~ ~pa~ ~PALADIN~ ~%paladin_desc%~ ~0x00004000~) ~6~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABRN01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABRN01~ ~rn~ ~RANGER~ ~%ranger_desc%~ ~0x00004000~) ~12~
  END
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABSH01~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABSH01~ ~sh1~ ~SHAMAN~ ~%shaman_desc%~ ~0x00004000~) ~21~
  END
/*
  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5_class.2da~ ~CLABSHGS~)) BEGIN
	OUTER_SPRINT $d5_kitlist_spheres (~CLABSHGS~ ~sh2~ ~SHAMAN~ ~%shaman_desc%~ ~0x00004000~) ~21~
  END
*/
END
ACTION_FOR_EACH base_kit IN ~clabpr01~ ~clabdr01~ BEGIN
  APPEND ~%base_kit%.2da~ ~SPHERES     AP_D5SPMEM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
	UNLESS ~AP_D5SPMEM~
END
ACTION_PHP_EACH d5_kitlist_spheres AS goo => roo BEGIN
//OUTER_TEXT_SPRINT focus_sphere_list ~~
//OUTER_TEXT_SPRINT major_sphere_list ~~
//OUTER_TEXT_SPRINT minor_sphere_list ~~
	ACTION_IF (%roo% = 3) OR  
 			(%roo% = 11) OR  
 			(%roo% = 8) OR  
 			(%roo% = 14) OR  
 			(%roo% = 15) OR  
 			(%roo% = 18) OR
 			(%roo% = 21) BEGIN
	  COPY_EXISTING ~luabbr.2da~ ~override~
		REPLACE_TEXTUALLY ~^\(%goo_2%[ %TAB%]+\).+$~ ~\1b_%goo_1%~
	  BUT_ONLY
	END
	COPY_EXISTING ~luclxyz.2da~ ~override/lub_%goo_1%.2da~
	ACTION_IF (%roo% = 11) BEGIN 	// druid
	  COPY_EXISTING ~ludrxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 8) BEGIN 	// f/c
	  COPY_EXISTING ~lufcxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 18) BEGIN 	// c/r
	  COPY_EXISTING ~lucrxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 15) BEGIN 	// c/t
	  COPY_EXISTING ~luctxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	ACTION_IF (%roo% = 14) BEGIN 	// c/m
	  COPY_EXISTING ~lucmxyz.2da~ ~override/lub_%goo_1%.2da~
	END
	APPEND ~%goo%.2da~ ~SPHERES     AP_D5SPUNI  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
	ACTION_PHP_EACH d5_fnp_spheres AS sphere => val BEGIN
	  COPY_EXISTING ~d5altsph.2da~ ~override~
		READ_2DA_ENTRIES_NOW rows 2
		FOR (row = 0; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 0 ~fnp_sphere~
		  READ_2DA_ENTRY_FORMER rows row 1 ~alt_sphere~
		  READ_2DA_ENTRY_FORMER rows row 2 ~eng_sphere~
		  PATCH_IF (~%sphere%~ STRING_EQUAL_CASE ~%fnp_sphere%~) BEGIN
			SPRINT ~text_sphere~ ~%alt_sphere%~
			SPRINT ~engl_sphere~ ~%eng_sphere%~
		  END
		END
	  BUT_ONLY
	  ACTION_IF (VARIABLE_IS_SET $d5_fnp_kit_sphere_access(~%sphere%~ ~%goo%~)) BEGIN
		OUTER_TEXT_SPRINT access $d5_fnp_kit_sphere_access(~%sphere%~ ~%goo%~)
		OUTER_INNER_PATCH ~%sphere%~ BEGIN
		  SNPRINT 3 ~shortsphere~ ~%sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~FOCUS~) BEGIN
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
		    COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			  PATCH_IF (FILE_EXISTS ~weidu_external/faiths_and_powers/hlas/hlas_%engl_sphere%.txt~) BEGIN
			    LPM remove_blank_lines
			    APPEND_FILE ~weidu_external/faiths_and_powers/hlas/hlas_%engl_sphere%.txt~
			  END
		    BUT_ONLY
		  END
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]zzz~ ~~
		  BUT_ONLY
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__5E_casting_divine.d5~) AND !(FILE_EXISTS_IN_GAME ~d5__fnp_spont_casting.d5~) BEGIN
			    APPEND ~%goo%.2da~ ~SPHERES     AP_D5SF%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			  END
			  ACTION_IF (FILE_EXISTS_IN_GAME ~d5__5E_casting_divine.d5~) AND !(FILE_CONTAINS_EVALUATED (~%goo%.2da~ ~AP_D5ZZ000~)) BEGIN
			    APPEND ~%goo%.2da~ ~SPHERES     AP_D5SF%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			  END
			  ACTION_IF (FILE_EXISTS_IN_GAME ~d5__5E_casting_divine.d5~) AND (FILE_CONTAINS_EVALUATED (~%goo%.2da~ ~AP_D5ZZ000~)) BEGIN
			    APPEND ~%goo%.2da~ ~SPHERES     AP_D5ZF%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			  END
			  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__5E_casting_divine.d5~) AND (FILE_EXISTS_IN_GAME ~d5__fnp_spont_casting.d5~) BEGIN
			    APPEND ~%goo%.2da~ ~SPHERES     AP_D5ZF%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			  END
			END
		  END
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && (~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT focus_sphere_list ~%focus_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~MAJOR~) BEGIN
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__v_plus_spheres.d5~) BEGIN
		    COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			  PATCH_IF (FILE_EXISTS ~weidu_external/faiths_and_powers/hlas/hlas_%engl_sphere%.txt~) BEGIN
			    LPM remove_blank_lines
			    APPEND_FILE ~weidu_external/faiths_and_powers/hlas/hlas_%engl_sphere%.txt~
			  END
		    BUT_ONLY
		  END
		  COPY_EXISTING ~lub_%goo_1%.2da~ ~override~
			REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]zzz~ ~~
		  BUT_ONLY
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT major_sphere_list ~%major_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~MINOR~) BEGIN
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SM%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~PALADIN~) BEGIN
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list%, %text_sphere%~
		END
		ACTION_IF (VARIABLE_IS_SET $d5_fnp_sphere_access(~%access%~)) && (~%access%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
		  ACTION_PHP_EACH d5_fnp_kit_caster_type AS this_kit => caster_type BEGIN
			ACTION_IF (~%this_kit%~ STRING_EQUAL_CASE ~%goo%~) && !(~%caster_type%~ STRING_EQUAL_CASE ~mystic~) BEGIN
			  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SP%shortsphere%  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
			END
		  END
		  OUTER_TEXT_SPRINT minor_sphere_list ~%minor_sphere_list%, %text_sphere%~
		END
	  END
	END
	ACTION_IF !(~%focus_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT focus_sphere_list ~%WNL%%focus_access%%focus_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%focus_sphere_list%~
	ACTION_IF !(~%major_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT major_sphere_list ~%WNL%%major_access%%major_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%major_sphere_list%~
	ACTION_IF !(~%minor_sphere_list%~ STRING_EQUAL_CASE ~~) BEGIN
		OUTER_TEXT_SPRINT minor_sphere_list ~%WNL%%minor_access%%minor_sphere_list%~
	END
	OUTER_TEXT_SPRINT total_sphere_list ~%total_sphere_list%%minor_sphere_list%~
    OUTER_INNER_PATCH_SAVE total_sphere_list ~%total_sphere_list%~ BEGIN
	  REPLACE_TEXTUALLY ~:,~ ~:~
    END
	OUTER_TEXT_SPRINT kit_sphere_list ~Abilities: %total_sphere_list%~
	ACTION_IF IS_AN_INT ~%goo_3%~ BEGIN
		ACTION_GET_STRREF %goo_3% kit_description 
		OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
			REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
//			REPLACE_TEXTUALLY ~%abilities%~ ~%kit_sphere_list%~
			REPLACE_TEXTUALLY ~%advantages%~ ~%kit_sphere_list%~
		END
		STRING_SET_EVALUATE %goo_3% ~%kit_description%~
	END
	OUTER_TEXT_SPRINT focus_sphere_list ~~
	OUTER_TEXT_SPRINT major_sphere_list ~~
	OUTER_TEXT_SPRINT minor_sphere_list ~~
	OUTER_TEXT_SPRINT total_sphere_list ~~
	ACTION_IF (%roo% = 3) OR  
 			(%roo% = 11) OR  
 			(%roo% = 6) OR  
 			(%roo% = 12) BEGIN
	  APPEND ~%goo%.2da~ ~SPHERES     AP_D5SPMEM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	    UNLESS ~AP_D5SPMEM~
 	END
	ACTION_IF (%roo% = 8) OR  
 			(%roo% = 14) OR  
 			(%roo% = 15) OR  
 			(%roo% = 18) OR
 			(%roo% = 16) BEGIN
	  ACTION_IF (%roo% = 8) OR  
 				(%roo% = 14) OR  
 				(%roo% = 15) OR  
 				(%roo% = 18) BEGIN
 	 	OUTER_TEXT_SPRINT class_letter ~P~
 	  END
	  ACTION_IF (%roo% = 16) BEGIN
 	 	OUTER_TEXT_SPRINT class_letter ~D~
 	  END
	  ACTION_IF IS_AN_INT ~%goo_4%~ BEGIN
		COPY_EXISTING ~%goo%.2da~ ~override~ 
		  COUNT_2DA_COLS cols 
		  READ_2DA_ENTRIES_NOW rows cols  
		  FOR (row = 1; row < rows; ++row) BEGIN 
			READ_2DA_ENTRY_FORMER rows row 0 sphere
			PATCH_IF (~%sphere%~ STRING_EQUAL_CASE ~SPHERES~) BEGIN	
			  FOR (col = 1; col < cols; ++col) BEGIN 
				READ_2DA_ENTRY_FORMER rows row col ability
				PATCH_IF (NOT ~%ability%~ STRING_EQUAL ~****~) BEGIN 
				  SET string_length = (STRING_LENGTH ~%ability%~) - 3
				  LPF SUBSTRING INT_VAR start = 3 length = EVAL %string_length% STR_VAR string = EVAL ~%ability%~ RET abil_new = substring END
				  INNER_ACTION BEGIN 
					ACTION_IF !(FILE_EXISTS_IN_GAME ~QD_MC_AP.eff~) BEGIN
					  CREATE EFF ~QD_MC_AP~ 
						WRITE_LONG   0x10 146 //cast spell
						WRITE_LONG   0x14 2   //preset target 
						WRITE_LONG   0x20 1   //cast instantly (ignore level) 
						WRITE_SHORT  0x24 1   //permament until death
						WRITE_SHORT  0x2c 100 //probability 100% 
					END
					COPY_EXISTING ~QD_MC_AP.eff~ ~override/%abil_new%#.eff~
					  WRITE_EVALUATED_ASCII 0x30 ~%abil_new%~
					  SET col_length = STRING_LENGTH ~%col%~
					LAF QD_ENSURE_QDMC_SPL STR_VAR base_class = EVAL ~%class_letter%~ END
					ACTION_IF (%col_length% = 1) BEGIN 
					  COPY_EXISTING ~override/QD_MC%class_letter%0%col%.spl~ ~override~ 
						LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 timing = 9 resist_dispel = 0 power = 0 parameter1 = %goo_4% parameter2 = 9 STR_VAR resource = EVAL ~%abil_new%#~ END  
					END 
					ACTION_IF (%col_length% = 2) BEGIN
					  COPY_EXISTING ~override/QD_MC%class_letter%%col%.spl~ ~override~ 
						LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 timing = 9 resist_dispel = 0 power = 0 parameter1 = %goo_4% parameter2 = 9 STR_VAR resource = EVAL ~%abil_new%#~ END  
					END 
				  END 
				END
			  END 
			END 
		  END
		BUT_ONLY
	  END
	END
END
ACTION_FOR_EACH base_kit IN ~clabpr01~ ~clabdr01~ BEGIN
  APPEND ~%base_kit%.2da~ ~SPHERES     AP_D5SPMEM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
	UNLESS ~AP_D5SPMEM~
END
COPY_EXISTING ~QD_MCP01.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~QD#MCP01~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~QD#MCP01~ END
IF_EXISTS BUT_ONLY
COPY_EXISTING ~QD_MCD01.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~QD#MCD01~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~QD#MCD01~ END
IF_EXISTS BUT_ONLY

CLEAR_ARRAYS

//copy HLAs and related files________________________________________________________
//
ACTION_IF GAME_IS ~tob bg2ee eet~ BEGIN
	INCLUDE ~faiths_and_powers/lib/spells_hlas.tpa~
END

//fix contingency spells_____________________________________________________________
//
ACTION_FOR_EACH contingency IN ~d5pw617~ ~d5fw617~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%contingency%.spl~ BEGIN
	COPY_EXISTING ~%contingency%.spl~ ~override~
	  LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
	  LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 146 target = 1 power = 6 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~spwi617~ END
	BUT_ONLY
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5hkno1.spl~ BEGIN
  COPY_EXISTING ~d5hkno1.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
	LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 146 target = 1 power = 6 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~spwi908~ END
  BUT_ONLY
END

END // end apply spheres function
//__________________________________________________________________________________


//___________________________________________________________________________________
//___________________________________________________________________________________


DEFINE_ACTION_FUNCTION universal_spells BEGIN

//finally, make sure universal spells are universal_________________________________
//
COPY_EXISTING ~d5spsph.2da~ ~override~
  READ_2DA_ENTRIES_NOW rows 4
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 spl
	READ_2DA_ENTRY_FORMER rows row 2 sph
	PATCH_IF (~%sph%~ STRING_EQUAL_CASE ~universal~) BEGIN
	  PATCH_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~%spl%[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN
		LPF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spl%~ RET spell_res spell_num END
		TEXT_SPRINT the_spell ~%spell_res%~
	  END
	  ELSE BEGIN
		TEXT_SPRINT the_spell ~%spl%~
	  END  
	  PATCH_IF FILE_EXISTS_IN_GAME ~%the_spell%.spl~ BEGIN
		INNER_ACTION BEGIN
		  COPY_EXISTING ~%the_spell%.spl~ ~override~
			WRITE_BYTE 0x21 (THIS BAND 0b00111111)
		  BUT_ONLY
		END
	 END
	END
  END
BUT_ONLY

END // end universal spells function
//__________________________________________________________________________________


//___________________________________________________________________________________
//___________________________________________________________________________________


DEFINE_ACTION_FUNCTION sphere_choice BEGIN

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__sphere_choice.d5~) BEGIN

// sphere feat files_________________________________________________________________
//
COPY ~faiths_and_powers/data/misc/d5_base.spl~ ~override/d5sphc1.spl~
  SAY NAME1 @151
  SAY UNIDENTIFIED_DESC @151
  WRITE_ASCII 0x3a ~d5_featp~ #8
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5_featp~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 0 duration = 12 STR_VAR resource = ~d5sphch~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5sphc1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5sphc1~ END

OUTER_FOR (ind = 2; ind < 10; ++ind) BEGIN
  COPY_EXISTING ~d5sphc1.spl~ ~override/d5sphc%ind%.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR resource = EVAL ~d5sphc%ind%~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~d5sphc%ind%~ END  
END

COPY ~faiths_and_powers/data/misc/d5_featp.bam~ ~override~
COPY ~faiths_and_powers/data/sphere_systems/dlg/d5sphch.eff~ ~override~
COPY ~faiths_and_powers/data/sphere_systems/dlg/d5sphch.cre~ ~override~

LAM which_sphere_strings 

COPY ~faiths_and_powers/data/sphere_systems/dlg/d5sphch.d~ ~weidu_external/faiths_and_powers/compile/d5sphch.d~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_life~ ~#%dlg_life%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_death~ ~#%dlg_death%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_benediction~ ~#%dlg_benediction%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_destruction~ ~#%dlg_destruction%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_protection~ ~#%dlg_protection%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_war~ ~#%dlg_war%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_exploration~ ~#%dlg_exploration%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_knowledge~ ~#%dlg_knowledge%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_deception~ ~#%dlg_deception%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_thought~ ~#%dlg_thought%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_dread~ ~#%dlg_dread%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_vigor~ ~#%dlg_vigor%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_affliction~ ~#%dlg_affliction%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_animal~ ~#%dlg_animal%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_plant~ ~#%dlg_plant%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_earth~ ~#%dlg_earth%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_air~ ~#%dlg_air%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_water~ ~#%dlg_water%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_fire~ ~#%dlg_fire%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_light~ ~#%dlg_light%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_shadow~ ~#%dlg_shadow%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_magic~ ~#%dlg_magic%~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~dlg_astral~ ~#%dlg_astral%~
COPY ~faiths_and_powers/data/sphere_systems/dlg/d5sphch.baf~ ~weidu_external/faiths_and_powers/compile/d5sphch.baf~

COMPILE ~weidu_external/faiths_and_powers/compile/d5sphch.d~ 
COMPILE ~weidu_external/faiths_and_powers/compile/d5sphch.baf~ 

COPY ~faiths_and_powers/lib/markers/d5_marker.d5~ ~override/d5__sphere_choice.d5~

END // end if not file exists

END // end function
//__________________________________________________________________________________


//__________________________________________________________________________________
//__________________________________________________________________________________

