
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC KITS
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________CYRIC___________________________________________________

ADD_KIT ~B_CLERIC_CYRIC~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_CYRIC       1 1 1 1 1 1 1 1~
~B_CLERIC_CYRIC       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                       STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_CLERIC_CYRIC           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                        LG LN LE NG TN NE CG CN CE
~B_CLERIC_CYRIC           0  0  1  0  0  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                        FT CL MA TH DR RA
~B_CLERIC_CYRIC           1  0  1  1  0  1~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/225_cyric/b_ccyr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22501
SAY @22502
SAY @22503
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22503)
		STR_VAR
			kit_name = B_CLERIC_CYRIC
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

//TALOS ABILITY FILES________________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/225_cyric/b_ccyr.2da~ ~override~
//+1 vs. illusions
COPY ~faiths_and_powers/kits/clerics/225_cyric/B_CYR02.spl~ ~override~
COPY_EXISTING ~SPWI401.spl~ ~override/B_CYR03.spl~ // Confusion
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

COPY_EXISTING ~SPWI509.spl~ ~override/B_CYR04.spl~ // feeblemind
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

//protection from fear  (using the tempus spl.  It's basically the same...)
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~25818~ END     //text block
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~17427~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~14007~ END     //text block
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //other text
  COPY ~faiths_and_powers/kits/champions/803_tempus/B_TEM10.spl~ ~override/B_CYR01.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~20568~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 STR_VAR resource = EVAL ~35484~ END     //text block
END//____________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric 		= 1
  STR_VAR
    clab_name 		= ~b_ccyr~
	race 			= ~all~
	s_Life 			= ~minor~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~major~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Knowledge 	= ~x~
	s_Deception 	= ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~x~
	s_Affliction 	= ~major~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~major~
	s_Magic 		= ~minor~
END
//__________________________________________________________________________________


//___________________________CLERIC THEIF___________________________________________________

ADD_KIT ~B_CT_CYRIC~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                          T   S           F   Q             S S
//10                  L S                     W   C           L   U             W I
//9                   A M             B L S   O   I   W       A   A             O N
//8                   R A             A O H   H   M   A       I   R C   S       R G
//7                   G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6                   E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5                   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4                   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3                   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2                   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1                   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CT_CYRIC           1 1 1 1 1 1 1 1~
~B_CT_CYRIC           1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                    STR DEX CON INT WIS CHR
~B_CT_CYRIC           0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                     LG LN LE NG TN NE CG CN CE
~B_CT_CYRIC            0  0  0  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                     FT CL MA TH DR RA
~B_CT_CYRIC            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/225_cyric/b_ctcyr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FC_E  K_FC_H  K_FC_HE  K_FC_G  K_FC_D  K_FC_HL  K_FC_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @22501
SAY @22502
SAY @22503
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@22503)
		STR_VAR
			kit_name = B_CT_CYRIC
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

COPY ~faiths_and_powers/kits/clerics/225_cyric/b_ctcyr.2da~ ~override~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2tal.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CT_CYRIC~
		kit_clab = ~b_ctcyr~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 
//____________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_thief = 1
  STR_VAR
    clab_name 		= ~b_ctcyr~
	race 			= ~all~
	s_Life 			= ~minor~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~major~
	s_Protection 	= ~x~
	s_War 			= ~x~
	s_Knowledge 	= ~x~
	s_Deception 	= ~major~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~x~
	s_Affliction 	= ~major~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~major~
	s_Magic 		= ~minor~
END
//__________________________________________________________________________________
