
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						CLERIC/MAGE - MONITOR OF MYSTRA
//__________________________________________________________________________________
//__________________________________________________________________________________


//ADD MONITOR_________________________________________________________________________
//

ADD_KIT ~D5_CM_AZUTH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                      T   S           F   Q             S S
//10              L S                     W   C           L   U             W I
//9               A M             B L S   O   I   W       A   A             O N
//8               R A             A O H   H   M   A       I   R C   S       R G
//7               G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6               E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_CM_AZUTH      1 1 1 1 1 1 1 1~
~D5_CM_AZUTH      1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                   STR DEX CON INT WIS CHR
~D5_CM_AZUTH         0   0   0   13  12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                   STR DEX CON INT WIS CHR
~D5_CM_AZUTH         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                   STR DEX CON INT WIS CHR
~D5_CM_AZUTH         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                   STR DEX CON INT WIS CHR
~D5_CM_AZUTH         0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                   LG LN LE NG TN NE CG CN CE
~D5_CM_AZUTH         1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                   FT CL MA TH DR RA
~D5_CM_AZUTH         0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cmazu.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CM_D  K_CM_E  K_CM_G  K_CM_H  K_CM_HE  K_CM_HL  K_CM_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004400 14~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @46501
SAY @46502
SAY @46503
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@46504)
		STR_VAR
			kit_name = D5_CM_AZUTH
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________


//MONITOR ABILITY FILES_______________________________________________________________
//
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cmazu.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cstbo.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cllv1.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cllv2.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cllv3.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cllv4.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5cllv5.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5mglv1.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5mglv2.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5mglv3.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5mglv4.spl~ ~override~
COPY ~faiths_and_powers/kits/multiclass/465_cm_azuth/d5mglv5.spl~ ~override~
//____________________________________________________________________________________


//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5cmazu.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_CM_AZUTH~ 
		kit_clab = ~d5cmazu~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 
//____________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_mage	= 1
  STR_VAR
    clab_name 		= ~d5cmazu~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~x~
	s_Knowledge 	= ~major~
	s_Deception 	= ~minor~
	s_Thought 		= ~minor~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~minor~
	s_Light 		= ~major~
	s_Shadow 		= ~minor~
	s_Magic 		= ~major~
END
//__________________________________________________________________________________

