//Informal prefix seperating different spelltypes

//xx = consecutive, but otherwise random, numbers
//n = spell level

//zero level cantrips: b_wc_1xx (wizard cantrips)
//zero level cantrips: b_pc_1xx (priest cantrips)

//1st level cantrips: b_1w1xx (wizard cantrips)
//1st level cantrips: b_2c1xx (priest cantrips)

//Regular added spells b_wnxx(wizard spells)
//Regular added spells b_pnxx(priest spells)

/*opcode = 177
target = 2
power = 0
timing = 4
parameter1 = 5
parameter2 = 160
power = 0
resist_dispel = 2
duration = 1
probability1 = 100
probability2 = 0
dicenumber = 0
dicesize = 0
savingthrow = 0
savebonus = 0
header =
insert_point = 7

FYI   */


// SD: eliminate #bonecir.spl from IWDEE
ACTION_IF GAME_IS ~iwdee~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME "#bonecir.spl" BEGIN
	DISABLE_FROM_KEY "#bonecir.spl"
  END
  ACTION_IF FILE_EXISTS "override\#bonecir.spl" BEGIN
	DELETE "override\#bonecir.spl"
  END
END

//SPell REVISIONS COMPATIBLITY:  Check for it in original tp2. Install all 'extra' spells using addspell so there is no issue.  (I think this applies to v4 only)


//IMPLEMENT SPHERE CODE (0URS). PROBABLY MUST BE INSTALLED BEFORE SPHERE.TPA.  THAT COMPONENT COULD CHECK TO SEE IF THIS, IWDEE OR IWDIFICATION IS NOT INSTALLED AND INSTALL THIS FIRST IF SO
//DECIDE WHAT TO DO IF IWDIFICATION DIVINE SPELLS ARE INSTALLED (PROBABLY NOT INSTALL SPECIFIC SPELLS, THOUGH KEEP SOME COMPATIBILITY CODE)

//2017-03-14 come back to sunscorch, cause light wounds, Resist Fire and Cold, Cure Moderate Wounds, Cause Moderate wounds, Cause Medium Wounds
// .  Complicated especially in light of SR, but also other components of this mod
 //COntinue from 1546

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             WIZARD SPELLS               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//
//To detect this subcomponent for immunities
 COPY ~%mod_folder%/data/iwd_spells/b_wizo.itm~ ~override/b_wizd.itm~   //To detect this sub component

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 1   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Expeditious Retreat_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Spell Revisions Has a version of Ex retreat, so no need to install this spell if SR present
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN   //any version of sr

//THIS MAY BE A GOOD CANTRIP...COMPARE WITH SR VERSION

//Revised or Cantrip verion of this spell will not work (and be despelled by) if character under haste or slow effects (using haste_list and slow_list tpas)
//Will NOT give immunity to these (higher level) spells...

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_1/EFF_M08.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_1/EFF_E01.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_1/b_w101.spl~ 2 1 ~WIZARD_EXPEDITIOUS_RETREAT~ //
        SAY NAME1 @1260000
        SAY NAME2 @1260000
        SAY UNIDENTIFIED_DESC @1260001
	SAY DESC @1260001

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EXPEDITIOUS_RETREAT~
  RET spell_res
END
//protect from 'slowed', 'slow' and 'haste'
 COPY_EXISTING ~%spell_res%.spl~ ~override~
     LPF cd_apply_batch STR_VAR array_name = b_removal_haste_arrays END
     LPF cd_apply_batch STR_VAR array_name = b_removal_slow_arrays END
     LPF cd_apply_batch STR_VAR array_name = cd_immunity_haste_arrays END
     LPF cd_apply_batch STR_VAR array_name = cd_immunity_slow_arrays END

 COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_1/SPWI126a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_1/SPWI126b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_1/SPWI126c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Sh. of Entropy immunity list  REVISED OR CANTRIP: USE
INCLUDE ~%mod_folder%/lib/spell_lists/haste_list.tpa~
INCLUDE ~%mod_folder%/lib/spell_lists/slow_list.tpa~

//No scroll if Cantrips installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN   //Not if cantrips installed (NOTE: CANTRIPS WILL HAVE TO REMOVE ITEM IF THIS INSTALLED FIRST...)
//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI126X.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @1260000
	SAY DESC @1260001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~

 COPY_EXISTING ~SPWI126X.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI126X~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI126X~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI126X~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI126X~ #1 #0 #0 ~IDENTIFIED~ #4
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI126X~ #1 #0 #0 ~IDENTIFIED~ #2
 END
 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI126X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END
END//END if not cantrip installed
END//End if SR not installed

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 2   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Cat's Grace_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//bam
//animations
//3d animation
//sounds   Copy sound #EFF_M08
//COPY ~%mod_folder%/data/iwd_spells/wizard_2/TRA_18.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_2/b_w225.spl~ 2 2 ~WIZARD_CATS_GRACE~ //
        SAY NAME1 @2250000
        SAY NAME2 @2250000
        SAY UNIDENTIFIED_DESC @2250001
	SAY DESC @2250001

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_CATS_GRACE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//Text Dexterity Modification
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SET strref = RESOLVE_STR_REF(@2250002)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 match_parameter1 = 14024 parameter1 = %strref%   END      //

//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI225a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI225b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI225c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_2/B_CAT.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@2250000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_CAT~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END

//Sh. of Entropy immunity list   No immunities nec I think
//INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI223A.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @2250000
	SAY DESC @2250001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SPWI223A.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Decastave_________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//ADD PORTRAIT ICON

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_2/DECASTA.bam~ ~override~
//animations
COPY ~%mod_folder%/data/iwd_spells/wizard_2/INVOCH.bam~ ~override~   //
//3d animation
//sounds   Copy sound #EFF_M08
COPY ~%mod_folder%/data/iwd_spells/wizard_2/#EFF_M06.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_2/#EFF_E02.WAV~ ~override~   //
//effs
//itm
COPY ~%mod_folder%/data/iwd_spells/wizard_2/DECASTA.itm~ ~override~
        SAY NAME1 @2160000
        SAY NAME2 @2160000
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_2/b_w216.spl~ 2 2 ~WIZARD_DECASTAVE~ //
        SAY NAME1 @2160000
        SAY NAME2 @2160000
        SAY UNIDENTIFIED_DESC @2160001
	SAY DESC @2160001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_DECASTAVE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
     LPF cd_apply_batch STR_VAR array_name = b_magic_item_arrays END   //removes previous items first

//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI216a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI216b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI216c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Portrait Icons    (maybe I'll make one for this
//Icon itself
//COPY ~%mod_folder%/data/iwd_spells/wizard_2/B_CAT.bam~ ~override~
// SET strref = RESOLVE_STR_REF(@2250000)
/*    Not needed at this time
//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_CAT~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END
*/
//Sh. of Entropy immunity list   No immunities nec I think
//INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SCDECA.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @2160000
	SAY DESC @2160001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SCDECA.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SCDECA~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SCDECA~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCDECA~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SCDECA~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SCDECA~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCDECA~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SCDECA~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Snilloc's Snowball Swarm_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_2/IDPRO217.pro~   //projectile
//VVC
COPY ~%mod_folder%/data/iwd_spells/wizard_2/#SSSWARM.vvc~ ~override~   //animation
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SSSWART.BAM~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SSSWARR.BAM~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SSSWARX.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_2/TRA_18.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_2/RNG_M02.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_2/b_w204.spl~ 2 2 ~WIZARD_SNILLOCS_SNOWBALL_SWARM~ //
        SAY NAME1 @2040000
        SAY NAME2 @2040000
        SAY UNIDENTIFIED_DESC @2040001
	SAY DESC @2040001

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SNILLOCS_SNOWBALL_SWARM~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO217% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI204a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI204b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI204c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SCSNILL.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @2040000
	SAY DESC @2040001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SCSNILL.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 148 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SCSNILL~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SCSNILL~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCSNILL~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SCSNILL~ #1 #0 #0 ~IDENTIFIED~ #4
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCSNILL~ #1 #0 #0 ~IDENTIFIED~ #2
 END
 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SCSNILL~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END
//Sh. of Entropy immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~
//lev 2
INCLUDE ~%mod_folder%/lib/spell_lists/2nd_list.tpa~

//SR NWN spell deflection
OUTER_SET $aoe_spell(~WIZARD_SNILLOCS_SNOWBALL_SWARM~)=1

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 3   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Icelance_____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_3/IDPRO251.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_3/ICELANT.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_3/#TRA_19.wav~ ~override~   //animation
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_3/b_w327.spl~ 2 3 ~WIZARD_ICELANCE~ //
        SAY NAME1 @3270000
        SAY NAME2 @3270000
        SAY UNIDENTIFIED_DESC @3270001
	SAY DESC @3270001
    LPF cd_apply_batch STR_VAR array_name = cd_full_stun_arrays END

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_ICELANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SET strref = RESOLVE_STR_REF(@3270002)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 match_parameter1 = 14024 parameter1 = %strref%   END      //
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO251% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SPWI327a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SPWI327b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SPWI327c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~


//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SCICE.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @3270000
	SAY DESC @3270001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SCICE.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries   //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SCICE~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SCICE~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCICE~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SCICE~ #1 #0 #0 ~IDENTIFIED~ #4
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCICE~ #1 #0 #0 ~IDENTIFIED~ #2
 END
 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SCICE~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END
//Sh. of Entropy immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________Lance of Disruption_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_3/IDPRO313.pro~   //projectile
//Regular Items ?
//Projectile
//VVC
//bam
//animations
COPY ~%mod_folder%/data/iwd_spells/wizard_3/LODISRT.bam~ ~override~   //
//3d animation
//sounds   Copy sound #EFF_M08
COPY ~%mod_folder%/data/iwd_spells/wizard_3/#TRA_59.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_3/#EFF_M06.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_3/b_w328.spl~ 2 3 ~WIZARD_LANCE_OF_DISRUPTION~ //
        SAY NAME1 @3280000
        SAY NAME2 @3280000
        SAY UNIDENTIFIED_DESC @3280001
	SAY DESC @3280001

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_LANCE_OF_DISRUPTION~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
/*     Not needed
//Text Dexterity Modification
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SET strref = RESOLVE_STR_REF(@2250002)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 match_parameter1 = 14024 parameter1 = %strref%   END      //
*/
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO313% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SPWI328a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SPWI328b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SPWI328c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
/* Not needeed
//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_2/B_CAT.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@2250000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_CAT~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END
*/

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_3/SPWI319X.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @3280000
	SAY DESC @3280001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SPWI319X.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 148 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI319X~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI319X~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI319X~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI319X~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI319X~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI319X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI319X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 4   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________Beltyn's Burning Blood______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//ADD PORTRAIT ICON

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//bam
//sec spell
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#BELTYN.spl~ ~override~   //
 SET strref = RESOLVE_STR_REF(@4220002)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 match_parameter1 = 37605 parameter1 = %strref%   END      //Berserk
//animations
//3d animation
COPY ~%mod_folder%/data/iwd_spells/wizard_4/NECROH.bam~ ~override~   //
//sounds   Copy sound
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#EFF_M07.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w422.spl~ 2 4 ~WIZARD_BELTYNS_BURNING_BLOOD~ //
        SAY NAME1 @4220000
        SAY NAME2 @4220000
        SAY UNIDENTIFIED_DESC @4220001
	SAY DESC @4220001

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_BELTYNS_BURNING_BLOOD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
/*     Sec spell done above
//Text Dexterity Modification
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SET strref = RESOLVE_STR_REF(@2250002)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 match_parameter1 = 14024 parameter1 = %strref%   END      //
*/
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI422a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI422b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI422c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
/* Not needeed
//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_2/B_CAT.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@2250000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_CAT~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END
*/
//Sh. of Entropy immunity list  nope
// INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SCBLOO.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @4220000
	SAY DESC @4220001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SCBLOO.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SCBLOO~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SCBLOO~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCBLOO~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SCBLOO~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SCBLOO~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCBLOO~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SCBLOO~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Dimension Door_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/*
//Projectile
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_4/DDOORH.bam~ ~override~   //
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#EFF_M09.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/B_W433.spl~ 2 4 ~WIZARD_DIMENSION_DOOR~ //
        SAY NAME1 @4290000
        SAY NAME2 @4290000
        SAY UNIDENTIFIED_DESC @4290001
	SAY DESC @4290001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_DIMENSION_DOOR~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
//CONTINUE
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI429a.bam~ ~override/b_w429a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI429b.bam~ ~override/b_w429b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI429c.bam~ ~override/b_w429c.bam~
//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_4/B_HOPE.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@4290000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_HOPE~
PRETTY_PRINT_2DA
COPY_EXISTING ~b_w429.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END

//add bams to spl
COPY_EXISTING ~b_w429.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro407% STR_VAR icon = EVAL  ~b_w429B~ END
  WRITE_EVALUATED_ASCII 0x003a ~b_w429C~

//bloodrage immunity list
//INCLUDE ~%mod_folder%/lib/spell_lists/blood_list.tpa~
//emotion
//INCLUDE ~%mod_folder%/lib/spell_lists/emotion_list.tpa~
*/

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Emotion: Courage_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/idpro407.pro~   //projectile
//VVC
//bam
//bam
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#EFF_M05.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w427.spl~ 2 4 ~WIZARD_EMOTION_COURAGE~ //
        SAY NAME1 @4270000
        SAY NAME2 @4270000
        SAY UNIDENTIFIED_DESC @4270001
	SAY DESC @4270001
//    LPF cd_apply_batch STR_VAR array_name = cd_fear_removal_arrays END
//    LPF cd_apply_batch STR_VAR array_name = cd_immunity_fear_arrays END

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EMOTION_COURAGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321 STR_VAR match_resource = ~SPWI427~ resource = EVAL ~%spell_res%~ END      // SPWI427
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI427a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI427b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI427c.bam~ ~override/%spell_res%c.bam~
//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_4/B_COUR.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@4270000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_COUR~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END

//add pro/bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro407% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//bloodrage immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/blood_list.tpa~
//emotion
INCLUDE ~%mod_folder%/lib/spell_lists/emotion_list.tpa~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SCCOUR.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @4270000
	SAY DESC @4270001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SCCOUR.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 148 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries   //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SCCOUR~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SCCOUR~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDNAZRAM.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDNAZRAM.STO~ ~override~
   ADD_STORE_ITEM ~SCCOUR~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SCCOUR~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
//COPY_EXISTING ~UDDROW25.STO~ ~override~
// ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCCOUR~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SCCOUR~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Emotion: Fear________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/idpro255.pro~   //projectile
//VVC
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#GENENCH.VVC~ ~override~   //
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_4/ENCHANX.BAM~ ~override~   //
//bam
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_4/ARE_M21.WAV~ ~override~   //#EFF_E05.WAV
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#EFF_E05.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#EFF_M05.WAV~ ~override~   //#EFF_E05.WAV
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w428.spl~ 2 4 ~WIZARD_EMOTION_FEAR~ //
        SAY NAME1 @4280000
        SAY NAME2 @4280000
        SAY UNIDENTIFIED_DESC @4280001
	SAY DESC @4280001
//    LPF cd_apply_batch STR_VAR array_name = b_fear_arrays END

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EMOTION_FEAR~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SET strref = RESOLVE_STR_REF(@4280002)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 parameter1 = %strref%   END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI428a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI428b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI428c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro255% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//bloodrage immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/blood_list.tpa~
//fear
INCLUDE ~%mod_folder%/lib/spell_lists/fear_list.tpa~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SCFEAR.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @4280000
	SAY DESC @4280001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SCFEAR.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 148 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries   //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SCFEAR~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SCFEAR~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDNAZRAM.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDNAZRAM.STO~ ~override~
   ADD_STORE_ITEM ~SCFEAR~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SCFEAR~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SCFEAR~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCFEAR~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SCFEAR~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END

//CONTINUE FROM HERE
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Emotion: Hope________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/idpro407.pro~   //projectile
//VVC
//bam
//bam
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#EFF_M05.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#EFF_E03.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w429.spl~ 2 4 ~WIZARD_EMOTION_HOPE~ //
        SAY NAME1 @4290000
        SAY NAME2 @4290000
        SAY UNIDENTIFIED_DESC @4290001
	SAY DESC @4290001
//    LPF cd_apply_batch STR_VAR array_name = cd_fear_removal_arrays END
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EMOTION_HOPE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI429a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI429b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI429c.bam~ ~override/%spell_res%c.bam~
//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_4/B_HOPE.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@4290000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_HOPE~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END

//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro407% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//bloodrage immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/blood_list.tpa~
//emotion
INCLUDE ~%mod_folder%/lib/spell_lists/emotion_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________Mordenkainen's Force Missiles__________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/MFMISS.pro~   //projectile  primary spell
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/SMLLAREA.pro~   //Sec Pro
//Probam
COPY ~%mod_folder%/data/iwd_spells/wizard_4/MFMISST.bam~ ~override~   //
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_4/MFMISSX.bam~ ~override~   //
//sec spell
//animations
//3d animation
//sounds   Copy sound
COPY ~%mod_folder%/data/iwd_spells/wizard_4/TRA_55.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#FF_M103.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w430.spl~ 2 4 ~WIZARD_MORDENKAINENS_FORCE_MISSILES~ //
        SAY NAME1 @4300000
        SAY NAME2 @4300000
        SAY UNIDENTIFIED_DESC @4300001
	SAY DESC @4300001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_MORDENKAINENS_FORCE_MISSILES~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 333            //  Static Charge opcode
      STR_VAR resource = EVAL ~%spell_res%B~
  END      //
//Sec Spell
COPY ~%mod_folder%/data/iwd_spells/wizard_4/b_w430b.spl~ ~override/%spell_res%B.spl~   //
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %SMLLAREA% END

/*     Sec spell done above
//Text Dexterity Modification
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SET strref = RESOLVE_STR_REF(@2250002)    //Does this work???
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 match_parameter1 = 14024 parameter1 = %strref%   END      //
*/
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %MFMISS% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI430a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI430b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI430c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
/* Not needeed
//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_2/B_CAT.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@2250000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_CAT~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END
*/
//Sh. of Entropy immunity list  nope
 INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI422X.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @4300000
	SAY DESC @4300001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SPWI422X.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI422X~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI422X~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI422X~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI422X~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI422X~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI422X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI422X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________vitriolic sphere_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/idpro316.pro~   //projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/SMLLARNC.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_4/VSPHERT.BAM~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_4/VSPHERX.BAM~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_4/ACIDH.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#TRA_60.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/TRA_06.WAV~ ~override~   //
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w432.spl~ 2 4 ~WIZARD_VITRIOLIC_SPHERE~ //
        SAY NAME1 @4320000
        SAY NAME2 @4320000
        SAY UNIDENTIFIED_DESC @4320001
	SAY DESC @4320001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_VITRIOLIC_SPHERE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro316% STR_VAR icon = EVAL  ~%spell_res%B~ END

COPY ~%mod_folder%/data/iwd_spells/wizard_4/b_w432y.spl~ ~override/%spell_res%y.spl~   //sec spell
//pro (and, sure, spell icon) to spell
	LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro316% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_4/b_w432z.spl~ ~override/%spell_res%z.spl~   //sec spell
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 146            //
      STR_VAR resource = EVAL ~%spell_res%y~
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 146 STR_VAR resource = EVAL ~%spell_res%z~ END     //
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI432a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI432b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI432c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI424X.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @4320000
	SAY DESC @4320001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SPWI424X.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries   //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDNAZRAM.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDNAZRAM.STO~ ~override~
   ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Shadow Monsters_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//2da
COPY ~%mod_folder%/data/iwd_spells/wizard_4/b_sh01.2da~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_4/b_sh02.2da~ ~override~   //animation
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_4/MSumm1X.bam~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_4/MSumm1H.bam~ ~override~   //animation
//animations
//3d animation
//itm
COPY ~%mod_folder%/data/iwd_spells/wizard_4/TRANS20.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SUMRING.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/P1-6.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/S1-12.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_4/M1D7SLSH.itm~ ~override~   //
//sounds
//effs
//cre
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1gob1.cre~ ~override~   //
        SAY NAME1 ~goblin~
        SAY NAME2 ~goblin~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1GOB2.cre~ ~override~   //
        SAY NAME1 ~goblin~
        SAY NAME2 ~goblin~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1GOB3.cre~ ~override~   //
        SAY NAME1 ~goblin~
        SAY NAME2 ~goblin~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1liz3.cre~ ~override~   //
        SAY NAME1 ~Lizard Man~
        SAY NAME2 ~Lizard Man~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1liz4.cre~ ~override~   //
        SAY NAME1 ~Lizard Man~
        SAY NAME2 ~Lizard Man~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1TRL6.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1TRL7.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SS1TRL8.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w426.spl~ 2 4 ~WIZARD_SHADOW_MONSTERS~ //
        SAY NAME1 @4260000
        SAY NAME2 @4260000
        SAY UNIDENTIFIED_DESC @4260001
	SAY DESC @4260001
LPF ALTER_EFFECT
      INT_VAR match_opcode = 331 STR_VAR resource = EVAL ~b_sh02~ END
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHADOW_MONSTERS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 331  parameter2 = 0   END      //
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 82 END   //82% 2 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 65 END   //66% 3 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 49 END   //50% 4 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 32 END   //33% 5 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 16 END   //~17% 6 cre
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI426a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI426b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI426c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//put a scroll on Kalah
//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SCSHAD.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @4260000
	SAY DESC @4260001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SCSHAD.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 148 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries   //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SCSHAD~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCSHAD~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SCSHAD~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI424X~ #1 #0 #0 ~IDENTIFIED~ #4
END

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SCSHAD~ #1 #0 #0 ~IDENTIFIED~ #2
 END
 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SCSHAD~ #1 #0 #0 ~IDENTIFIED~ #2
 END
 ACTION_IF FILE_EXISTS_IN_GAME ~KALAH2.CRE~ BEGIN  //
   COPY_EXISTING ~KALAH2.CRE~ ~override~   //Kalah...should prob just be added to Kalah2...
  ADD_CRE_ITEM ~SCSHAD~ #1 #0 #0 ~IDENTIFIED~ ~INV7 INV8 INV9 INV10 INV11 INV12 INV13 INV14 INV15 INV16~
 END
ACTION_IF FILE_EXISTS_IN_GAME ~KALAH.CRE~ BEGIN  //
  COPY_EXISTING ~KALAH.CRE~ ~override~   //shouldn't hurt?
  ADD_CRE_ITEM ~SCSHAD~ #1 #0 #0 ~IDENTIFIED~ ~INV7 INV8 INV9 INV10 INV11 INV12 INV13 INV14 INV15 INV16~
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________________Shout__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_4/idpro315.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SHOUTT.BAM~ ~override~   //
//bam
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#TRA_08.WAV~ ~override~   //#FF_M100.WAV
COPY ~%mod_folder%/data/iwd_spells/wizard_4/#FF_M100.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_4/b_w431.spl~ 2 4 ~WIZARD_SHOUT~ //
        SAY NAME1 @4310000
        SAY NAME2 @4310000
        SAY UNIDENTIFIED_DESC @4310001
	SAY DESC @4310001
//    LPF cd_apply_batch STR_VAR array_name = b_deafness_arrays END
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHOUT~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI431a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI431b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_4/SPWI431c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro315% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//bloodrage immunity list
//INCLUDE ~%mod_folder%/lib/spell_lists/blood_list.tpa~
//SR NWN spell deflection
 OUTER_SET $aoe_spell(~WIZARD_SHOUT~)=1

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 6   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Darts of Bone_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//ADD PORTRAIT ICON

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_6/MFMISS.pro~   //projectile  primary spell
//ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_6/SMLLAREA.pro~   //Sec Pro
//Probam
//COPY ~%mod_folder%/data/iwd_spells/wizard_6/MFMISST.bam~ ~override~   //
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_6/IDOBONE.bam~ ~override~   //
//COPY ~%mod_folder%/data/iwd_spells/wizard_6/MFMISSX.bam~ ~override~   //
//sec spell
//Itm
COPY ~%mod_folder%/data/iwd_spells/wizard_6/DOBONE.itm~ ~override~   //actual bone darts
        SAY NAME1 @6300002
        SAY NAME2 @6300002
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~IDOBONE~ END
        WRITE_ASCIIE 0x3a ~IDOBONE~
//animations
//3d animation
//sounds   Copy sound
//COPY ~%mod_folder%/data/iwd_spells/wizard_6/TRA_55.WAV~ ~override~   //
//COPY ~%mod_folder%/data/iwd_spells/wizard_6/#FF_M103.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_6/b_w630.spl~ 2 6 ~WIZARD_DARTS_OF_BONE~ //
        SAY NAME1 @6300000
        SAY NAME2 @6300000
        SAY UNIDENTIFIED_DESC @6300001
	SAY DESC @6300001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_DARTS_OF_BONE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
     LPF cd_apply_batch STR_VAR array_name = b_magic_item_arrays END   //removes previous items first rEALLY NEEDED?

/*     Sec spell done above
//Text Dexterity Modification
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SET strref = RESOLVE_STR_REF(@2250002)    //Does this work???
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 match_parameter1 = 14024 parameter1 = %strref%   END      //
*/
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI630a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI630b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI630c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
/* Not needeed
//Portrait Icons
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/wizard_2/B_CAT.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@2250000)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_CAT~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END
*/
//Sh. of Entropy immunity list  nope
// INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

//Add scroll, and add scroll to stores
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI618X.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @6300000
	SAY DESC @6300001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SPWI618X.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
//  COPY_EXISTING ~STO0703.sto~ ~override~
//    ADD_STORE_ITEM ~SPWI618X~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI618X~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI618X~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI618X~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI618X~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI618X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI618X~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Shades_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
//VVC
//2da
COPY ~%mod_folder%/data/iwd_spells/wizard_6/b_sh03.2da~ ~override~   //animation
//bam
//animations
//3d animation
//itm
COPY ~%mod_folder%/data/iwd_spells/wizard_6/TRANS40.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_6/S1-8.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_6/B1-12.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_6/REG1HP2.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_6/TRANS60.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SUMAMU.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_6/UMBERHLK.itm~ ~override~   //
//sounds
//effs
//cre
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS2gob2.cre~ ~override~   //
        SAY NAME1 ~Goblin Elite~
        SAY NAME2 ~Goblin Elite~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS2gob3.cre~ ~override~   //
        SAY NAME1 ~Goblin Elite~
        SAY NAME2 ~Goblin Elite~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS2liz5.cre~ ~override~   //
        SAY NAME1 ~Tough Lizard Man~
        SAY NAME2 ~Tough Lizard Man~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS2liz6.cre~ ~override~   //
        SAY NAME1 ~Tough Lizard Man~
        SAY NAME2 ~Tough Lizard Man~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS2liz7.cre~ ~override~   //
        SAY NAME1 ~Tough Lizard Man~
        SAY NAME2 ~Tough Lizard Man~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS3trl7.cre~ ~override~   //
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS3trl8.cre~ ~override~   // Check animations...actually check all animations
        SAY NAME1 ~Troll~
        SAY NAME2 ~Troll~
/*    Uhulk anims not in all
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS3umb8.cre~ ~override~   //
        SAY NAME1 ~Umber Hulk~
        SAY NAME2 ~Umber Hulk~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SS3umb9.cre~ ~override~   //
        SAY NAME1 ~Umber Hulk~
        SAY NAME2 ~Umber Hulk~
*/
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_6/B_W629.spl~ 2 6 ~WIZARD_SHADES~ //
        SAY NAME1 @6290000
        SAY NAME2 @6290000
        SAY UNIDENTIFIED_DESC @6290001
	SAY DESC @6290001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHADES~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 331  parameter2 = 0      STR_VAR resource = EVAL ~B_SH03~ END      //
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 82 END   //82% 2 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 65 END   //66% 3 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 49 END   //50% 4 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 32 END   //33% 5 cre
  LPF CLONE_EFFECT INT_VAR multi_match = 1     match_opcode = 331  probability1 = 16 END   //~17% 6 cre

//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI629a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI629b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI629c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Soul Eater__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_6/idpro299.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SEATERA.bam~ ~override~   //animation
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_6/B_W631.spl~ 2 6 ~WIZARD_SOUL_EATER~ //
        SAY NAME1 @6310000
        SAY NAME2 @6310000
        SAY UNIDENTIFIED_DESC @6310001
	SAY DESC @6310001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SOUL_EATER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 326            //
      STR_VAR resource = EVAL ~%spell_res%b~
  END      //
//secondary spells
COPY ~%mod_folder%/data/iwd_spells/wizard_6/B_W631b.spl~ ~override/%spell_res%b.spl~   //sec spell
//creature for secspell
COPY ~%mod_folder%/data/iwd_spells/wizard_6/AD3SKLM.cre~ ~override~   //sec spell cre
        SAY NAME1 ~Skeleton~
        SAY NAME2 ~Skeleton~
//cre items
COPY ~%mod_folder%/data/iwd_spells/wizard_6/RNDTRE40.itm~ ~override~   //sec spell cre itm
COPY ~%mod_folder%/data/iwd_spells/wizard_6/RING95.itm~ ~override~   //sec spell cre itm
//cre script
  COMPILE ~%mod_folder%/data/iwd_spells/wizard_6/GNSUMMM.baf~
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI631a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI631b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_6/SPWI631c.bam~ ~override/%spell_res%c.bam~
//add pro/bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro299% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//SR NWN spell deflection
 OUTER_SET $aoe_spell(~WIZARD_SOUL_EATER~)=1
 
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 7   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Acid Storm___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_7/idpro211.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_7/ASTORMA.bam~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_7/ARE_M04.WAV~ ~override~   //
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_7/b_w724.spl~ 2 7 ~WIZARD_ACID_STORM~ //
        SAY NAME1 @7240000
        SAY NAME2 @7240000
        SAY UNIDENTIFIED_DESC @7240001
	SAY DESC @7240001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_ACID_STORM~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/wizard_7/SPWI724a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_7/SPWI724b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_7/SPWI724c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro211% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//SR NWN spell deflection
OUTER_SET $aoe_spell(~WIZARD_ACID_STORM~)=1

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  Special   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//entropy pros
INCLUDE ~%mod_folder%/lib/spell_lists/pro_wiz_list1.tpa~
