//Priest Orisons b_po###  (010, 020,...990) 010 = @@101000000; 020 = @@102000000...990 = @199000000


//At least two options regarding relatively 'useless' spells.  
//Infravision, Hold ANimal, Magic Stone, Goodberry Converted to cantrips, or only converted to cantrips if B_REVISE Is installed (sometimes if SR installed)...

////////////////////////////////////////////////////////////////
/////////////////   Cantrips and Orisons    ////////////////////
////////////////////////////////////////////////////////////////

//NOTE: Add compatibility with sphere system
//compatibility: Entropy shield, if present, should protect vs all, or almost all, cantrip projectiles.  
////CHECK Malediction et alIWDEE   (WILL NEED TO COME BACK TO THIS ONCE SR CAN BE INSTALLED ON IWDEE...

// SD: eliminate #bonecir.spl from IWDEE
ACTION_IF GAME_IS ~iwdee~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME "#bonecir.spl" BEGIN
	DISABLE_FROM_KEY "#bonecir.spl"
  END
  ACTION_IF FILE_EXISTS "override\#bonecir.spl" BEGIN
	DELETE "override\#bonecir.spl"
  END
END
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////               Priest             /////////////////////////////
/////////////////////////////              Orisons             /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Template__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE: no
//                                          IWDification: no
//                                          My IWD spells: no
//                                          my revised spells: no
//                                          spheres: no
//                                          SR: no
//                                          Other: no

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________________Calm___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Calm              Added                   Fnp:                    Double Checked: no
//                                          IWDEE:
//                                          IWDIFICATION: )
//                                          my IWD Spells:
//                                          SR:
COPY ~%mod_folder%/data/cantrips/divine/b_po080.spl~ ~override~
        SAY NAME1 @108000001
        SAY NAME2 @108000002
        SAY UNIDENTIFIED_DESC @107000003
	SAY DESC @107000003
    LPF cd_apply_batch STR_VAR array_name = cd_fear_removal_arrays END
//FnP compatibility
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po080.spl~ ~override~
 SPRINT old @103000002//old text healing sphere from cure minor wounds
 SPRINT new @104000004//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (charm to thought sphere)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________________Canticle________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Canticle              Added               Acolyte of Tempus: yes                                 Double Checked: no
//                                          IWDEE: yes         (prayer)  
//                                          IWDIFICATION: yes  (prayer)
//                                          my IWD Spells: Yes (prayer) Both ways
//                                          SR: Needed?

//CHECK SPELL REVISIONS!
COPY ~%mod_folder%/data/cantrips/divine/b_po020.spl~ ~override~
        SAY NAME1 @102000000
        SAY NAME2 @102000000
        SAY UNIDENTIFIED_DESC @102000001
	SAY DESC @102000001
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@102000004) END  //Notification: Chanting

COPY ~%mod_folder%/data/cantrips/divine/b_po021.spl~ ~override~      //to remove
        SAY NAME1 @102000002
        SAY NAME2 @102000002
        SAY UNIDENTIFIED_DESC @102000002
	SAY DESC @102000002


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cause Minor Wounds_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Cause Minor Wounds   Added                Compatiblity                                          Double Checked: no
//                                          My Revised: yes
//                                          Spheres: looks like it
//                                          others?
//ADD SPHERE SYSTEM COMPATIBILITY: SPHERE: Death: Done.   d5_spheres.d5
//Change spell name
//Animation
COPY ~%mod_folder%/data/cantrips/divine/CLDAMAH.bam~ ~override~
//Sound
COPY ~%mod_folder%/data/cantrips/divine/#FF_P103.WAV~ ~override~
//icons (placeholders)
COPY ~%mod_folder%/data/cantrips/divine/SPPR114A.BAM~ ~override~
COPY ~%mod_folder%/data/cantrips/divine/SPPR114B.BAM~ ~override~
COPY ~%mod_folder%/data/cantrips/divine/SPPR114C.BAM~ ~override~
//spell itself
COPY ~%mod_folder%/data/cantrips/divine/b_po050.spl~ ~override~
        SAY NAME1 @105000000
        SAY NAME2 @105000000
        SAY UNIDENTIFIED_DESC @105000001
	SAY DESC @105000001
 LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~b_po050~
  END 

//Compatibility: sphere system Description: death sphere
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
 SPRINT old @101000002//old text healing sphere from cure minor wounds
 SPRINT new @105000002//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (charm to thought sphere)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

//Compatibility: Altered spells
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
 SPRINT old @105000003//old text
 SPRINT new @105000004//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (set damage to % of target's hp)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
  LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 match_savingthrow = 0 parameter1 = 5 parameter2 = 4194307 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 match_savingthrow = 1 parameter1 = 5 parameter2 = 4194307 savingthrow = 4 END
END

//sr change to sr nomenclature
ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN   //any version of sr
COPY_EXISTING ~b_po050.spl~ ~override~
        SAY NAME1 @105000005
        SAY NAME2 @105000005
 SPRINT old @105000000//old text
 SPRINT new @105000005//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (cause to inflict)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

//ATTENTION: IF SR IS INSTALLED, CHANGE INFLICT MINOR WOUNDS TO WORK AS OTHER INFLICT SPELLS

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//________________________________________________________________Cure Minor Wounds_________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//cure minor wounds     added               Revised Spells: yes (both ways?)                       Double Checked: no
//                                          (Our) Spheres: NO DO  From 'healing' to 'life'
//                                          Others?

//ADD SPHERE SYSTEM COMPATIBILITY: SPHERE: LIFE  d5_spheres.d5
//STANDARD VERSION
COPY ~%mod_folder%/data/cantrips/divine/b_po010.spl~ ~override~
        SAY NAME1 @101000000
        SAY NAME2 @101000000
        SAY UNIDENTIFIED_DESC @101000001
	SAY DESC @101000001

ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN   //If FnP is installed (change sphere from healing to life)

  COPY_EXISTING ~b_po010.spl~ ~override~
    SPRINT old @101000002//old sphere (healing)
    SPRINT new @101000003//new sphere (life)
   READ_LONG 0x50 "valid"
     PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
     READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~
        END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END
END

 ///ATTENTION:  SEE HOW TO ADD TO LIFE SPHERE
 //Add to life sphere level 1 (i.e. by setting the variable)
 
 /* Verify how to do this these days!!!
COPY_EXISTING ~d5plif1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode=171 opcode = 309 timing = 9 parameter1 = 1 parameter2 = 0 STR_VAR resource = EVAL ~b_life~ END // add to life sphere
COPY_EXISTING ~d5flif1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode=171 opcode = 309 timing = 9 parameter1 = 1 parameter2 = 0 STR_VAR resource = EVAL ~b_life~ END // add to life sphere
END //end copatibility w/fnp
*/

//Compatibility with Revised Spells
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~b_po010.spl~ ~override~      //description
 SPRINT old @101000004//old text
 SPRINT new @101000005//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //Change to 10% +1 HP
  LPF ALTER_EFFECT INT_VAR match_opcode = 17  parameter1 = 2 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 10 parameter2 = 2 END
END



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Detect Evil/Alignment__________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Cause Minor Wounds   Added                Compatiblity                                          Double Checked: no
//                                          My Revised: yes
//                                          Spheres: looks like it
//                                          others?
//Will be Detect Alignment in Spell Revisions

COPY_EXISTING ~SPPR104.spl~ ~override/b_po090.spl~      //Copy spell as innate
    WRITE_BYTE 0x1c ~4~ // change spell type to innate
      LPF ALTER_SPELL_HEADER INT_VAR location = 4 END   //Change of location
 SPRINT old @200004001//old text
 SPRINT new @200004002//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //Level: Orison
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
//Cantrip infinite use
COPY_EXISTING_REGEXP GLOB ~b_po090.spl~ ~override~
 PATCH_IF  (%spell_type% = 4) BEGIN
        READ_LONG 	0x64	ab_off			// Abilities Offset
	READ_SHORT	0x68	ab_num			// Number of Abilities
	READ_SHORT	0x6a	fx_off			// Effects Offset
	READ_SHORT	0x70	glob_fx			// Number of Global Effects
	SET	glob_add = 0

	INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 171			// Give innate
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~b_po090~	// resource
	++glob_add

        INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 172			// Remove spell
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~b_po090~	// resource
	++glob_add

//	INSERT_BYTES (fx_off) 0x30			//Second effect
//	  WRITE_etc...
//	++glob_add

	glob_fx += glob_add
	WRITE_SHORT 0x70 glob_fx			// Increment Number of Global Effects
	FOR (i = 0; i < ab_num; ++i) BEGIN		// Offset Effect Index for all Abilities
	  READ_SHORT (ab_off + i * 0x28 + 0x20) fx_idx
	  WRITE_SHORT (ab_off + i * 0x28 + 0x20) (fx_idx + glob_add)
	END
 END
 //No failure
 COPY_EXISTING ~b_po090.spl~ ~override~
   WRITE_LONG 0x0018 ~16384~            //No failure

 COPY_EXISTING ~SPPR104.spl~ ~override~   //Copy over the original spell
    WRITE_BYTE 0x21 (THIS | 0b11000000) //exlcude priests n druids from original spell

//Detect evil/alignment scroll?
//global


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Hold animal____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE: no need
//                                          IWDification: no need
//                                          My IWD spells: no need
//                                          my revised spells: yes
//                                          spheres: no
//                                          SR: Double check v3 improves hold animal (almost certainly does, but...)
//                                          SR: any unique spells dispell hold besides Remove Paralysis?
//                                          Other: no need as far as I can tell
//Adding the cantrip either way
COPY ~%mod_folder%/data/cantrips/divine/b_po070.spl~ ~override~
        SAY NAME1 @107000000
        SAY NAME2 @107000000
        SAY UNIDENTIFIED_DESC @107000001
	SAY DESC @107000001
//disable original spell if neither SR nor Revise installed

//If Neither SR nor Revise is installed, Cont animals needs to be removed
ACTION_IF (NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~) AND (NOT FILE_EXISTS_IN_GAME ~B_REVISE.ITM~) BEGIN   //not installed, disable spell
 COPY_EXISTING ~SPPR305.spl~ ~override~   //Copy over the original spell
    WRITE_BYTE 0x21 (THIS | 0b11000000) //exlcude all priest classes
END
//END SR OR B_REVISE ONLY

 ///ATTENTION:  SEE HOW TO ADD TO ANIMAL SPHERE
//Hold animal scrolls?

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Infravision_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Infravision            Added:Yes          Compatiblity:                                         Double Checked: no
//                                          IWDEE: Not needed
//                                          IWDification: Not needed
//                                          My IWD spells: Not needed
//                                          my revised spells: No (may have a 'heat vision' version...)
//                                          spheres: Not needed
//                                          SR: (wiz version will need it) SR may use icons...
//                                          Other: Not needed
//
COPY ~%mod_folder%/data/cantrips/divine/b_po060.spl~ ~override~
        SAY NAME1 @106000000
        SAY NAME2 @106000000
        SAY UNIDENTIFIED_DESC @106000001
	SAY DESC @106000001
//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po060.spl~ ~override~
 SPRINT old @106000002//old text
 SPRINT new @106000003//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (charm to thought sphere)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END
//If Neither SR nor Revise is installed, Infa needs to be removed
ACTION_IF (NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~) AND (NOT FILE_EXISTS_IN_GAME ~B_REVISE.ITM~) BEGIN   //not installed, disable spell
 COPY_EXISTING ~SPWI111.spl~ ~override~   //Copy over the original spell
    WRITE_LONG 0x1e ~0x7fc0~ //  wildmage spell but...
    WRITE_BYTE 0x21 (THIS | 0b10000000) //exlcude wildmage
END
//END SR OR B_REVISE ONLY
 ///ATTENTION:  SEE HOW TO ADD TO KNOWLEDGE SPHERE
//Take care of wiz infravision scrolls...

/* Change per this description:
Duration: 10 minutes
Casting Time: 1
Area of Effect: All allies within 30' 
Saving Throw: None
The recipients of this spell gains the ability to see with infravision, just as an elf or dwarf can.
*/

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Malediction_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Malediction           Added               Acolyte of Tempus: yes                                 Double Checked: no
//                                          IWDEE: yes
//                                          IWDIFICATION: yes
//                                          my IWD spells: yes
//                                          spheres:  I believe so
//                                          SR: Yes (I believe so)

COPY ~%mod_folder%/data/cantrips/divine/b_po030.spl~ ~override~
        SAY NAME1 @103000000
        SAY NAME2 @103000000
        SAY UNIDENTIFIED_DESC @103000001
	SAY DESC @103000001
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@103000000) END  //Notification: Malediction
//bless, aid, chant doom
//bless
//Compatibility
//fnp
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po030.spl~ ~override~    //change sphere from charm to dread
 SPRINT old @103000002//old text
 SPRINT new @103000003//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (sphere from charm to dread)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END
//SR
//Spell Revisions (Break Enchantment removes Malediction)
ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN   //any version of sr
COPY_EXISTING ~sppr307.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 221 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
COPY_EXISTING ~spwi410.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 221 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Meditation________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Meditation            Added               Acolyte of Tempus: yes                                 Double Checked: no
//                                          IWDEE: yes
//                                          IWDIFICATION: yes
//                                          my IWD spells: yes
//                                          spheres:  I believe so
//                                          SR: I don't think so
//CHECK SPELL REVISIONS!
//From Charm to Thought for FnP
COPY ~%mod_folder%/data/cantrips/divine/b_po040.spl~ ~override~
        SAY NAME1 @104000000
        SAY NAME2 @104000000
        SAY UNIDENTIFIED_DESC @104000001
	SAY DESC @104000001
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@104000002) END  //Notification: meditating
//compatibility
//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po040.spl~ ~override~
 SPRINT old @104000003//old text
 SPRINT new @104000004//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (charm to thought sphere)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________________Benediction________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Canticle              Added               Acolyte of Tempus: yes                                 Double Checked: no
//                                          IWDEE: yes         (prayer)  
//                                          IWDIFICATION: yes  (prayer)
//                                          my IWD Spells: Yes (prayer) Both ways
//                                          SR: Needed?

//CHECK SPELL REVISIONS!
COPY ~%mod_folder%/data/cantrips/divine/b_po090.spl~ ~override~
        SAY NAME1 @109000000
        SAY NAME2 @109000000
        SAY UNIDENTIFIED_DESC @109000001
	SAY DESC @109000001
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@102000004) END  //Notification: Chanting

//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po090.spl~ ~override~
 SPRINT old @109000002//old text
 SPRINT new @109000003//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (all to benediction sphere)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////               Mage               /////////////////////////////
/////////////////////////////              Cantrips            /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Drench_________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//
//                                          Other:
//Adding the cantrip either way

//Animation
COPY ~%mod_folder%/data/cantrips/arcane/b_wet.bam~ ~override~
//spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc003.spl~ ~override~   //Drench
        SAY NAME1 @200005001
        SAY NAME2 @200005001
        SAY UNIDENTIFIED_DESC @200005002
	SAY DESC @200005002
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324             //
      STR_VAR resource = EVAL ~b_wc003~
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318             //
      STR_VAR resource = EVAL ~b_wc003~
  END
 SET strref = RESOLVE_STR_REF(@200005003)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 parameter1 = %strref%   END      //


/* 
//When Shround of flame is added to non-IWDEE games...
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHROUD_OF_FLAME~
  RET spell_res
END
COPY_EXISTING ~b_wc003.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR match_resource = ~SPWI524~ resource = EVAL ~%spell_res%~
  END
*/
//Create Dispel fire effect batch macro

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Drowse_________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//                                          Other:
//
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc004.spl~  ~override~
        SAY NAME1 @200003001
        SAY NAME2 @200003001
        SAY UNIDENTIFIED_DESC @200003002
	SAY DESC @200003002
//to add: Opponent becomes immune for 1 day.


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Frost Ray______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//                                          Other: no need as far as I can tell
//
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc001.spl~  ~override~
        SAY NAME1 @200001001
        SAY NAME2 @200001001
        SAY UNIDENTIFIED_DESC @200001002
	SAY DESC @200001002
LPF ALTER_SPELL_HEADER INT_VAR projectile = %b_1c101% END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________________Jolt_____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//this cantrip virtually assumes SR shocking grasp.
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc002.spl~  ~override~
        SAY NAME1 @200002001
        SAY NAME2 @200002001
        SAY UNIDENTIFIED_DESC @200002002
	SAY DESC @200002002

//Need an electricty batch protection.  Immunity to electricity should prot vs. the speed penalty as well (so, prot vs. the cantrip).

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Chill Touch____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//                                          Other: no need as far as I can tell
//

//All versions of Chill Touch are converted to a cantrip, even if SR is installed
 COPY_EXISTING ~SPWI117.spl~ ~override/b_wc005.spl~      //Copy spell as innate
    WRITE_BYTE 0x1c ~4~ // change spell type to innate
      LPF ALTER_SPELL_HEADER INT_VAR location = 4 END   //Change of location
 SPRINT old @200002003//old text
 SPRINT new @200002004//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //Level: Cantrip
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //

 COPY_EXISTING ~SPWI117.spl~ ~override~   //Copy over the original spell
    WRITE_LONG 0x1e ~0x7fc0~ //  wildmage spell but...
    WRITE_BYTE 0x21 (THIS | 0b10000000) //exlcude wildmage

//Cantrip infinite use
COPY_EXISTING_REGEXP GLOB ~b_wc005.spl~ ~override~
	PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
        READ_LONG 	0x64	ab_off			// Abilities Offset
	READ_SHORT	0x68	ab_num			// Number of Abilities
	READ_SHORT	0x6a	fx_off			// Effects Offset
	READ_SHORT	0x70	glob_fx			// Number of Global Effects
	SET	glob_add = 0

	INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 171			// Give innate
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~b_wc005~	// resource
	++glob_add

        INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 172			// Remove spell
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~b_wc005~	// resource
	++glob_add

//	INSERT_BYTES (fx_off) 0x30			//Second effect
//	  WRITE_etc...
//	++glob_add

	glob_fx += glob_add
	WRITE_SHORT 0x70 glob_fx			// Increment Number of Global Effects
	FOR (i = 0; i < ab_num; ++i) BEGIN		// Offset Effect Index for all Abilities
	  READ_SHORT (ab_off + i * 0x28 + 0x20) fx_idx
	  WRITE_SHORT (ab_off + i * 0x28 + 0x20) (fx_idx + glob_add)
	END
END
//No failure
 COPY_EXISTING ~b_wc005.spl~ ~override~
   WRITE_LONG 0x0018 ~16384~            //No failure

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Acid Splash_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//this cantrip virtually assumes SR shocking grasp.
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc102.spl~  ~override~
        SAY NAME1 @200006001
        SAY NAME2 @200006001
        SAY UNIDENTIFIED_DESC @200006002
	SAY DESC @200006002

COPY_EXISTING_REGEXP GLOB ~b_wc102.spl~ ~override~
	PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
        READ_LONG 	0x64	ab_off			// Abilities Offset
	READ_SHORT	0x68	ab_num			// Number of Abilities
	READ_SHORT	0x6a	fx_off			// Effects Offset
	READ_SHORT	0x70	glob_fx			// Number of Global Effects
	SET	glob_add = 0

	INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 171			// Give innate
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~b_wc102~	// resource
	++glob_add

        INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 172			// Remove spell
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~b_wc102~	// resource
	++glob_add

//	INSERT_BYTES (fx_off) 0x30			//Second effect
//	  WRITE_etc...
//	++glob_add

	glob_fx += glob_add
	WRITE_SHORT 0x70 glob_fx			// Increment Number of Global Effects
	FOR (i = 0; i < ab_num; ++i) BEGIN		// Offset Effect Index for all Abilities
	  READ_SHORT (ab_off + i * 0x28 + 0x20) fx_idx
	  WRITE_SHORT (ab_off + i * 0x28 + 0x20) (fx_idx + glob_add)
	END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Fire Bolt_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Credit for this spell goes to SubtleDoctor. Used and modified with permission.

//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/D5_MSORN.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/cantrips/arcane/SPMAGM04.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/d5_wfir.spl~  ~override~
        SAY NAME1 @200007001
        SAY NAME2 @200007001
        SAY UNIDENTIFIED_DESC @200007002
	SAY DESC @200007002
//add projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %D5_MSORN% STR_VAR END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________Magic Bolt_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Credit for this spell goes to SubtleDoctor. Used and modified with permission.

//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/D5_MSBLU.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/cantrips/arcane/SPMAGM07.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/D5_WIIN.spl~  ~override~
        SAY NAME1 @200008001
        SAY NAME2 @200008001
        SAY UNIDENTIFIED_DESC @200008002
	SAY DESC @200008002
//add projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %D5_MSBLU% STR_VAR END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Audible Glamer_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//this cantrip virtually assumes SR shocking grasp.
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp1.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp2.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp3.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp4.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp5.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp6.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp7.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/B_WC103.spl~  ~override~
        SAY NAME1 @200009001
        SAY NAME2 @200009001
        SAY UNIDENTIFIED_DESC @200009002
	SAY DESC @200009002
	

//CONTINUE FROM HERE
/*
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msred.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msblu.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msgrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msbrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msorn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_mswhi.pro~
COPY ~TomeAndBlood/data/cantrips/spmagm02.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm03.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm04.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm05.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm06.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm07.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cant.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp420.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp710.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp809.bam~ ~override~

COPY ~TomeAndBlood/data/cantrips/d5_wiin.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~


Cantrips/Orisons: In progress
Minor spells used 'at will'.  Divine cantrips are called Orisons.  
The first number denotes generalist and wild mages (and clerics/druids/mystics), while the second denotes Specialists (and, perhaps, acolytes in FnP):
Level		Cantrips Known	Prepared Cantrips
1		     4/2+1		   2/2+1
2-3		     4/2+1		   3/3+1
4		     6/3+1		   4/4+1
5-12		     7/4+1		   5/5+1
13-20		     9/5+1		   6/6+1
20+		     10/6+1		   7/7+1
Sorcerers/Shaman:
Level			Cantrips Known	
1			       1
2-3			       2
4			       3
5-12			       4
13-20			       5
20+			       6
*/
//Light?  Possible?  Useful?

//Audible Glamer: Target saves or is distracted (deaf immune)

//Catapult: throws dagger

//Air Bubble +4 save vs. gas

//Ceremony:  A dialog cantrip that allows the priest to do a number of things.  All cost gold, or something...
//Ceremony: Bless Water          To add    Implementation: Dialog: costs gold, creates a vial of water that damages undead
//
//Ceremony: Consecrate ground    To add    All enemies in area recieve a -1 penalty to saves.  Cannot be used while enemies present (good for sleeping)
//
//Ceremony: communion            To add    Gives allies a blessing of some sort
//
//Alternatively: Rituals: Cast spells with a gold cost that is more powerful/long lasting than normal (or both?)


//Acid Splash (Conjuration): Casting time 3, sv. Breath +2 or 1d3 points of acid, +1d3 points of acid 1 round later)

//Anticipation (Divination): +2 to AC/breath saves for 1 min

//Bedazzle (Illusion): - 1 to THAC0/AC 2 rounds.  Save or -3 and opponent is blind for 3 seconds.  Opponent becomes immune for 1 day.

//Conjure Critter (Conjuration): Summon minor rodent for 1 turn or so

//Elemental Protection (Abjuration): 5% resist acid/elect/fire/cold for 1 min.

//Earthen Grasp (Transmutation): Earth 'grabs' one opponent.  Save or can't move.  (Need bam!)

//Find Familiar (Conjuration): As the (modified) spell

//Fire Bolt (Evocation): Casting time 3, 1d8 fire damage.  Save vs. breath to avoid.

//Frost Ray (Evocation): Casting time 3, 1d6 cold damage (ray).  Save vs. breath to avoid.

//Magic Bolt (Evocation): Casting time 5, 1d4 magic damage.

//Stiffen Bones (Necromancy): Casting time 1, -1 to THAC0/AC for 2 rounds.  Save vs. death or slowed for that time.


//Sense Magic                    To add    just the reveal magic opcode

//Expedious retreat              To add    1st lev iwdee spell

//Animal Companion (druid)      To add     animal versions of familiar like spell

//Detect Creature               To add     As track

//Disorient                     To add     Creature hesitates for a moment


/*    COde for adding to priest clabs.  Adds 'cure minor wounds' to all priest spells.
Will need to set up an array for cleric vs paladin vs. ranger vs. druid cantrips, and then a different one for fnp spheres dependin on sphere membership
These will need to be added to compatibility code.  
*/

/*
COPY_EXISTING ~CLABPR01.2da~ ~override~ //Base cleric
              ~CLABPA01.2da~ ~override~ //Base paladin
              ~CLABDR01.2da~ ~override~ //Base Druid
              ~CLABRN01.2da~ ~override~ //Base Ranger
              APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~

//add to clab
//thanks subtledoctor!
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_base_spell_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY


ACTION_PHP_EACH d5_base_spell_array AS bo => zo BEGIN
	ACTION_IF (%zo% = 2) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 3) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 6) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 11) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 12) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 21) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
END
*/

//CONTINUE FROM HERE Create arrays based on fnp, tnb, and vanilla (for both addition and immunities)

//cleric innates
COPY ~%mod_folder%/data/cantrips/divine/b_prc01.spl~ ~override/b_pr01.spl~ //will need to add all cantrips to this and





/* TO BE ADDED


*/

//CONTINUE FROM HERE
/*





COPY ~clchng/Arcane/Cantrip/Spells/b_wc101.spl~ ~override~
  SAY NAME1 @105000 // Fire Bolt
  SAY UNIDENTIFIED_DESC @105001

COPY ~clchng/Arcane/Cantrip/Spells/b_wc102.spl~ ~override~
  SAY NAME1 @105002 //Acid Splash (Cantrip)
  SAY UNIDENTIFIED_DESC @105003
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc103.spl~ ~override~
  SAY NAME1 @105004 //Cold Ray (Cantrip)
  SAY UNIDENTIFIED_DESC @105005
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc104.spl~ ~override~
  SAY NAME1 @105006 //Shocking Grasp (Cantrip)
  SAY UNIDENTIFIED_DESC @105007

COPY ~clchng/Arcane/Cantrip/Itm/sgrasp.itm~ ~override~

COPY ~clchng/Arcane/Cantrip/Spells/b_wc105.spl~ ~override~
  SAY NAME1 @105008//Infravision (Cantrip)
  SAY UNIDENTIFIED_DESC @105009
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc106.spl~ ~override~
  SAY NAME1 @105010//Friends (Cantrip)
  SAY UNIDENTIFIED_DESC @105011

COPY ~clchng/Arcane/Cantrip/Spells/b_wc107.spl~ ~override~
  SAY NAME1 @105012//Chill Touch (Cantrip)
  SAY UNIDENTIFIED_DESC @105013

@105000 = ~Fire Bolt (Cantrip)~
@105001 = ~Fire Bolt (Cantrip)
Level: Cantrip
School: Evocation
Range: Long
Duration: Instant
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster shoots a bolt of fire from his hand at the target of his choosing causing 1d6 points of fire damage on a sucessful hit.  A creature may make a save vs breath +2 to avoid being damaged by this spell~

@105002 = ~Acid Splash (Cantrip)~
@105003 = ~Acid Splash (Cantrip)
Level: Cantrip
School: Conjuration
Range: Long
Duration: 1 round
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster conjurs a ball of acid and hurls it towards his target causing 1d3 acid damage on a successful hit on the first round, and an additional 1d3 points of damage one round later.  A creature may make a save vs breath +2 to avoid being damaged by this spell~

@105004 = ~Frost Ray (Cantrip)~
@105005 = ~Frost Ray (Cantrip)
Level: Cantrip
School: Evocation
Range: Long
Duration: Instant
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster shoots a fay of frost from his hand at the target of his choosing causing 1d6 points of cold damage on a sucessful hit.  A creature may make a save vs breath +2 to avoid being damaged by this spell~


@105006 = ~Shocking Grasp (Cantrip)~
@105007 = ~Shocking Grasp (Cantrip)
Level: Cantrip
School: Alteration
Range: Touch
Duration: 1 round (special)
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

When the wizard touches a creature while this cantrip is in effect, an electrical charge will deal 1d8 points of damage to the creature touched. In addition, the grasp itself does 1d2 fist damage (Strength bonuses apply). The wizard only has one charge, and once an opponent has been touched, the spell's energies have been used. If the wizard misses, the spell is wasted.~

@105008 = ~Infravision (Cantrip)~
@105009 = ~Infravision (Cantrip)
Level: Cantrip
School: General
Range: 30 ft.
Duration: 2 hours
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

Upon the casting of this spell the recipient gains the ability to see with infravision, just as an elf or a dwarf would. This effect lasts for the duration of the spell or until dispelled.~

@105010 = ~Friends (Cantrip)~
@105011 = ~Friends (Cantrip)
Level: Cantrip
School: Enchantment
Range: 0
Duration: 10 rounds
Casting Time: 1
Area of Effect: The caster
Saving Throw: None

A Friends spell causes the wizard to temporarily gain 6 points of Charisma. Those who view the caster tend to be very impressed with <PRO_HIMHER> and make an effort to be <PRO_HISHER> friends and help <PRO_HIMHER>, as appropriate to the situation. Officious bureaucrats might decide to become helpful; surly gate guards might wax informative; attacking orcs might spare the caster's life, taking <PRO_HIMHER> captive instead.~

@105012 = ~Chill Touch (Cantrip)~
@105013 = ~Chill Touch (Cantrip)
Level: Cantrip
School: Necromancy
Range: 0
Duration: 1 round
Casting Time: 1
Area of Effect: The creature
Saving Throw: Neg.

When the caster completes this spell, a blue glow encompasses <PRO_HISHER> hand. This energy attacks the life force of any living creature upon which the wizard makes a successful melee attack. (Nonliving creatures such as golems and undead are unaffected by this spell.) The creature is punched for 1d2 fist damage (Strength bonuses apply) and must make a Saving Throw vs. Spell or suffer 1d8 points of damage and receive a -2 THAC0 penalty for 5 rounds.~


//////////////////////////////////////
////////// SPl, cre,baf,dlg //////////
//////////////////////////////////////

COPY ~clchng/Arcane/Cantrip/Spl/b_csel1.spl~ ~override~
  SAY NAME1 @115259//Prep Cantrip
@115259 = ~Select your cantrips~
//Clearly not all of this is needed...

COPY ~clchng/Arcane/Cantrip/Spl/b_can00.2da~ ~override~

COMPILE ~clchng/Arcane/Cantrip/Baf/b_csel1.baf~ 
COMPILE ~clchng/Arcane/Cantrip/dlg/b_csel1.d~ 

COPY ~clchng/Arcane/Cantrip/cre/b_csel1.cre~ ~override~
//end to be added
COPY ~TomeAndBlood/data/cantrips/d5_wfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
	WRITE_SHORT 0x098 ~%d5_msorn%~

ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msred.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msblu.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msgrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msbrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msorn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_mswhi.pro~
COPY ~TomeAndBlood/data/cantrips/spmagm02.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm03.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm04.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm05.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm06.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm07.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cant.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp420.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp710.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp809.bam~ ~override~
//COPY ~TomeAndBlood/data/cantrips/d5_wildm.2da~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstbo.spl~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstpn.spl~ ~override~
//Choose a cantrip
COPY ~TomeAndBlood/data/cantrips/d5_cantr.spl~ ~override~
	SAY NAME1 @6012
COPY ~TomeAndBlood/data/cantrips/d5_cant.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant1.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant2.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant3.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cantr.2da~ ~override~

//abjurer cantrip: protective shell
COPY ~TomeAndBlood/data/cantrips/d5_maab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
COPY ~TomeAndBlood/data/cantrips/d5_wiab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
//conjurer cantrip: summon rabbit	
COPY ~TomeAndBlood/data/cantrips/d5_maco.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_wico.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_rabb.cre~ ~override~
	SAY NAME1 @6018
//diviner cantrip: anticipation
COPY ~TomeAndBlood/data/cantrips/d5_madi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
COPY ~TomeAndBlood/data/cantrips/d5_widi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
//enchanter cantrip: drowse
COPY ~TomeAndBlood/data/cantrips/d5_maen.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
COPY ~TomeAndBlood/data/cantrips/d5_wien.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
//illusionist cantrip: bedazzle
COPY ~TomeAndBlood/data/cantrips/d5_mail.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
COPY ~TomeAndBlood/data/cantrips/d5_wiil.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
//invoker cantrip: magic bolt
COPY ~TomeAndBlood/data/cantrips/d5_main.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
COPY ~TomeAndBlood/data/cantrips/d5_wiin.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
//necromancer cantrip: stiffen bones
COPY ~TomeAndBlood/data/cantrips/d5_mane.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
COPY ~TomeAndBlood/data/cantrips/d5_wine.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
//transmuter cantrip: earthen grasp
COPY ~TomeAndBlood/data/cantrips/d5_matr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
COPY ~TomeAndBlood/data/cantrips/d5_witr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
//fire bolt
COPY ~TomeAndBlood/data/cantrips/d5_mfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
COPY ~TomeAndBlood/data/cantrips/d5_wfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
	WRITE_SHORT 0x098 ~%d5_msorn%~
//ice bolt
COPY ~TomeAndBlood/data/cantrips/d5_mcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
COPY ~TomeAndBlood/data/cantrips/d5_wcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
	WRITE_SHORT 0x098 ~%d5_mswhi%~
//acid bolt
COPY ~TomeAndBlood/data/cantrips/d5_macd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
COPY ~TomeAndBlood/data/cantrips/d5_wacd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
	WRITE_SHORT 0x098 ~%d5_msgrn%~
//electric bolt
COPY ~TomeAndBlood/data/cantrips/d5_melc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
COPY ~TomeAndBlood/data/cantrips/d5_welc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
	WRITE_SHORT 0x098 ~%d5_msblu%~
//earth bolt
COPY ~TomeAndBlood/data/cantrips/d5_wert.spl~ ~override~
	SAY NAME1 @6039
	SAY UNIDENTIFIED_DESC @6040
	WRITE_SHORT 0x098 ~%d5_msbrn%~
//shield spell now protects against cantrips
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maen~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wien~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_main~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiin~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mail~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiil~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mane~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wine~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_madi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_widi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_matr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_witr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maco~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wico~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wfir~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_welc~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wcld~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wacd~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wert~ END
	BUT_ONLY 
	
//adding cantrips to appropriate mages
APPEND ~CLABMA01.2da~ ~CANTRIPS GA_D5_CANT1 ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA02.2da~ ~CANTRIPS GA_D5_WIAB ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA03.2da~ ~CANTRIPS GA_D5_WINE ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA04.2da~ ~CANTRIPS GA_D5_WITR ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA05.2da~ ~CANTRIPS GA_D5_WIDI ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA06.2da~ ~CANTRIPS GA_D5_WICO ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA07.2da~ ~CANTRIPS GA_D5_WIIN ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA08.2da~ ~CANTRIPS GA_D5_WIIL ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA09.2da~ ~CANTRIPS GA_D5_WIEN ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		
APPEND ~CLABSO01.2da~ ~CANTRIPS GA_D5_WFIR ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~		

//updating descriptions
//9563
	ACTION_GET_STRREF 9563 mage
	OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
	  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
	END
	STRING_SET_EVALUATE 9563 ~%mage%~
	//17245
	ACTION_GET_STRREF 17245 mage
	OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
	  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
	END
	STRING_SET_EVALUATE 17245 ~%mage%~
	//9564: abjurer
		ACTION_GET_STRREF 9564 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 9564 ~%mage%~
		//9565: conjurer
		ACTION_GET_STRREF 9565 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 9565 ~%mage%~
		//9566: diviner
		ACTION_GET_STRREF 9566 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 9566 ~%mage%~
		//9567: enchanter
		ACTION_GET_STRREF 9567 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 9567 ~%mage%~
		//9568: illusionist
		ACTION_GET_STRREF 9568 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 9568 ~%mage%~
		//9569: invoker
		ACTION_GET_STRREF 9569 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 9569 ~%mage%~
		//9570: necromancer
		ACTION_GET_STRREF 9570 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 9570 ~%mage%~
		//9571: transmuter
		ACTION_GET_STRREF 9571 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 9571 ~%mage%~
//bgee	
	ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
		//24233
		ACTION_GET_STRREF 24233 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 24233 ~%sorcerer%~
	END
//bg2ee
	ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN 
		//45866
		ACTION_GET_STRREF 45866 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
			REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 45866 ~%sorcerer%~
	END 
//bgee and bg2ee
ACTION_IF GAME_IS ~bgee bg2ee~ THEN BEGIN 
		//24290: abjurer
		ACTION_GET_STRREF 24290 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 24290 ~%mage%~
		//24291: conjurer
		ACTION_GET_STRREF 24291 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 24291 ~%mage%~
		//24292: diviner
		ACTION_GET_STRREF 24292 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 24292 ~%mage%~
		//24293: enchanter
		ACTION_GET_STRREF 24293 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 24293 ~%mage%~
		//24294: illusionist
		ACTION_GET_STRREF 24294 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 24294 ~%mage%~
		//24295: invoker
		ACTION_GET_STRREF 24295 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 24295 ~%mage%~
		//24296: necromancer
		ACTION_GET_STRREF 24296 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 24296 ~%mage%~
		//24297: transmuter
		ACTION_GET_STRREF 24297 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 24297 ~%mage%~
END 
//iwdee
	ACTION_IF GAME_IS ~iwdee~ THEN BEGIN 
		//37189
		ACTION_GET_STRREF 37189 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 37189 ~%mage%~
		//34605
		ACTION_GET_STRREF 34605 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip at 1st level. ~
		END
		STRING_SET_EVALUATE 34605 ~%sorcerer%~
		//37249
		ACTION_GET_STRREF 37249 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 37249 ~%sorcerer%~
//37193: abjurer
		ACTION_GET_STRREF 37193 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 37193 ~%mage%~
		//37196: conjurer
		ACTION_GET_STRREF 37196 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 37196 ~%mage%~
		//37199: diviner
		ACTION_GET_STRREF 37199 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 37199 ~%mage%~
		//37202: enchanter
		ACTION_GET_STRREF 37202 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 37202 ~%mage%~
		//37205: illusionist
		ACTION_GET_STRREF 37205 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 37205 ~%mage%~
		//37208: invoker
		ACTION_GET_STRREF 37208 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 37208 ~%mage%~
		//37211: necromancer
		ACTION_GET_STRREF 37211 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 37211 ~%mage%~
		//37214: transmuter
		ACTION_GET_STRREF 37214 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 37214 ~%mage%~
END 

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
		READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
		FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
			PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~DRAGON_DISCIPLE~) BEGIN
			  READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
			END
		  END
		ACTION_IF (strref >= 0) BEGIN
		  ACTION_GET_STRREF strref dd
		  OUTER_PATCH_SAVE dd ~%dd%~ BEGIN
			REPLACE_TEXTUALLY CASE_SENSITIVE ~Advantages:~ ~Advantages:
– May use the Fire Bolt cantrip.~
		END
		STRING_SET_EVALUATE strref ~%dd%~
		END 		
				  
*/				  
				  
				  
				  
				  
