//Informal prefix seperating different spelltypes

//xx = consecutive, but otherwise random, numbers
//n = spell level

//zero level cantrips: b_wc_1xx (wizard cantrips)
//zero level cantrips: b_pc_1xx (priest cantrips)

//1st level cantrips: b_1w1xx (wizard cantrips)
//1st level cantrips: b_2c1xx (priest cantrips)

//Regular added spells b_wnxx(wizard spells)
//Regular added spells b_pnxx(priest spells)

/*opcode = 177
target = 2
power = 0
timing = 4
parameter1 = 5
parameter2 = 160
power = 0
resist_dispel = 2
duration = 1
probability1 = 100
probability2 = 0
dicenumber = 0
dicesize = 0
savingthrow = 0
savebonus = 0
header =
insert_point = 7

FYI   


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________     EXAMPLE SPELL       ________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/wizard_2/IDPRO217.pro~   //projectile
//VVC
COPY ~%mod_folder%/data/iwd_spells/wizard_2/#SSSWARM.vvc~ ~override~   //animation
//bam
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SSSWART.BAM~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SSSWARR.BAM~ ~override~   //animation
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SSSWARX.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/wizard_2/TRA_18.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/wizard_2/RNG_M02.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/wizard_2/b_w204.spl~ 2 2 ~WIZARD_SNILLOCS_SNOWBALL_SWARM~ //
        SAY NAME1 @2040000
        SAY NAME2 @2040000
        SAY UNIDENTIFIED_DESC @2040001
	SAY DESC @2040001

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SNILLOCS_SNOWBALL_SWARM~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO217% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI204a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI204b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI204c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Sh. of Entropy immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

//The Scroll
/*
//Copy over the scroll:
COPY ~%mod_folder%/data/iwd_spells/wizard_2/SPWI223A.itm~ ~override~
        SAY NAME1 @10
        SAY NAME2 @2250000
	SAY DESC @2250001
//Change icon
        WRITE_ASCIIE 0x3a ~%spell_res%A~
 COPY_EXISTING ~SPWI223A.itm~ ~override~     //these work
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 147 STR_VAR resource = EVAL  ~%spell_res%~ END
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END */

*/

//SPell REVISIONS COMPATIBLITY:  Check for it in original tp2. Install all 'extra' spells using addspell so there is no issue.  (I think this applies to v4 only)


//IMPLEMENT SPHERE CODE (0URS). PROBABLY MUST BE INSTALLED BEFORE SPHERE.TPA.  THAT COMPONENT COULD CHECK TO SEE IF THIS, IWDEE OR IWDIFICATION IS NOT INSTALLED AND INSTALL THIS FIRST IF SO
//DECIDE WHAT TO DO IF IWDIFICATION DIVINE SPELLS ARE INSTALLED (PROBABLY NOT INSTALL SPECIFIC SPELLS, THOUGH KEEP SOME COMPATIBILITY CODE)

//2017-03-14 come back to sunscorch, cause light wounds, Resist Fire and Cold, Cure Moderate Wounds, Cause Moderate wounds, Cause Medium Wounds
// .  Complicated especially in light of SR, but also other components of this mod
 //COntinue from 1546

// SD: eliminate #bonecir.spl from IWDEE
ACTION_IF GAME_IS ~iwdee~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME "#bonecir.spl" BEGIN
	DISABLE_FROM_KEY "#bonecir.spl"
  END
  ACTION_IF FILE_EXISTS "override\#bonecir.spl" BEGIN
	DELETE "override\#bonecir.spl"
  END
END
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             DIVINE SPELLS               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//detect this sub component
 COPY ~%mod_folder%/data/iwd_spells/b_wizo.itm~ ~override/b_prez.itm~   //To detect this sub component

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 1   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________________Curse___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Item revisions: Spell protections ?
//Regular Items ?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_1/idpro237.pro~   //projectile
//VVC
COPY ~%mod_folder%/data/iwd_spells/priest_1/#BLESS.vvc~ ~override~   //
//bam
COPY ~%mod_folder%/data/iwd_spells/priest_1/AREA1X.bam~ ~override~   //animation
//animations
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_1/CURSEH.bam~ ~override~   //animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_1/#EFF_P99.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/iwd_spells/priest_1/#EFF_P32.wav~ ~override~   //sound
COPY ~%mod_folder%/data/iwd_spells/priest_1/#EFF_E04.WAV~ ~override~   //sound
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_1/b_p112.spl~ 1 1 ~CLERIC_CURSE~ //Curse Spell
        SAY NAME1 @11200000
        SAY NAME2 @11200000
        SAY UNIDENTIFIED_DESC @11200001
	SAY DESC @11200001
//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURSE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321  multi_match = 1          //
      STR_VAR resource = EVAL ~%spell_res%~
  END
//     LPF cd_apply_batch STR_VAR array_name = b_curse_arrays END
//     LPF cd_apply_batch STR_VAR array_name = b_bless_cantrip_arrays END
      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr112a.bam~ ~override/%spell_res%a.bam~
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr112b.bam~ ~override/%spell_res%b.bam~
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr112c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro237% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove Curse
INCLUDE ~%mod_folder%/lib/spell_lists/curse_list.tpa~

//The Scroll Not in IWDEE.  Will have to create it

//Copy over the scroll:
COPY ~%mod_folder%/data/scrolls/priest_1/generic/B_ge148.itm~ ~override/%spell_res%.itm~
        SAY NAME1 @10
        SAY NAME2 @11200000
	SAY DESC @11200001
//Change icons and spells
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 148 STR_VAR resource = EVAL  ~%spell_res%~ END
  WRITE_ASCIIE 0x3a ~%spell_res%A~
/*
//Add to temples, where approapriate 
//BGEE
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END */

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cause Light Wounds_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//TRIPLE CHECK THIS ONE... (AND COME BACK TO IT)

//not installed if SRv4 is installed (though, see revisions to alter that version)

ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
//Projectile
//animations
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_1/cldamah.bam~ ~override~   //animation
//sounds
//effs
//%b_pfire%
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_1/b_p114.spl~ 1 1 ~CLERIC_CAUSE_LIGHT_WOUNDS~ //CLW Spell
        SAY NAME1 @11400000
        SAY NAME2 @11400000
        SAY UNIDENTIFIED_DESC @11400001
	SAY DESC @11400001

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_LIGHT_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//compatibity revised spells
//20% damage + 6 damage (save vs death for half) and name changed to 'inflict'
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode= 12 END//
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 3 parameter2 = 4194304 savingthrow = 0 STR_VAR resource = EVAL ~~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 savingthrow = 4 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 parameter2 = 4194307 END

COPY_EXISTING ~%spell_res%.spl~ ~override~
 SPRINT old @11400004//old text
 SPRINT new @11400005//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old w new
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr114a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr114b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr114c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//The Scroll Not in IWDEE.  Will have to create it

//Copy over the scroll:
COPY ~%mod_folder%/data/scrolls/priest_1/generic/B_ge146.itm~ ~override/%spell_res%.itm~
        SAY NAME1 @10
        SAY NAME2 @11400000
	SAY DESC @11400001
//Change icons and spells
  LPF ALTER_ITEM_HEADER STR_VAR icon = EVAL  ~%spell_res%A~ END
  LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 STR_VAR resource = EVAL  ~%spell_res%~ END
  WRITE_ASCIIE 0x3a ~%spell_res%A~

/*
//BGEE - Sorcerous Sundries
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
  COPY_EXISTING ~STO0703.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
//High Hedge
  COPY_EXISTING ~HIGHHEDG.sto~ ~override~
    ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  A
//Lady Yuth
COPY_EXISTING ~SCROLLS.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4
//Underdark
COPY_EXISTING ~UDDROW25.STO~ ~override~
 ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #4

 ACTION_IF FILE_EXISTS_IN_GAME ~BDSORCSC.STO~ BEGIN  //SoD
  COPY_EXISTING ~BDSORCSC.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~STO0703.STO~ BEGIN  //SoD
  COPY_EXISTING ~STO0703.STO~ ~override~
   ADD_STORE_ITEM ~SPWI223A~ #1 #0 #0 ~IDENTIFIED~ #2
 END

END */


END //END SR NOT INSTALLED

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Sunscorch_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//TRIPLE CHECK THIS ONE... (AND COME BACK TO IT)

//Not installed if any version of SR is installed:
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN

COPY ~%mod_folder%/data/iwd_spells/priest_1/SUNSCOH.bam~ ~override~   //pro bam
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_1/SUNSCOH.pro~   //projectile
//animations
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr115a.bam~ ~override~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr115b.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr115c.bam~ ~override~   //bam
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_1/#EFF_P39.wav~ ~override~   //sound
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_1/b_p115.spl~ 1 1 ~CLERIC_SUNSCORCH~ //CLW Spell
        SAY NAME1 @11500000
        SAY NAME2 @11500000
        SAY UNIDENTIFIED_DESC @11500001
	SAY DESC @11500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SUNSCORCH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF cd_apply_batch STR_VAR array_name = cd_full_blindness_opcode_arrays END //Blindness notification
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 326            //
      STR_VAR resource = EVAL ~%spell_res%D~
  END      //

//secondary spells
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr115D.spl~ ~override/%spell_res%D.spl~   //sec spell
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr115a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr115b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_1/sppr115c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams and projectiles to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %SUNSCOH% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Sh. of Entropy immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~

END  //end not SR

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 2   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Resist Fire and Cold___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////
//Not installed if any version of SR is installed (but, see revised spells)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN    //SR installs resist elements (sppr210)
//Projectile
//animations
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_2/ALTERH.bam~ ~override~   //animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_2/#EFF_P07.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/iwd_spells/priest_2/#EFF_E03.WAV~ ~override~   //sound
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_2/b_p216.spl~ 1 2 ~CLERIC_RESIST_FIRE_AND_COLD~ //CMW Spell
        SAY NAME1 @21600000
        SAY NAME2 @21600000
        SAY UNIDENTIFIED_DESC @21600001
	SAY DESC @21600001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_RESIST_FIRE_AND_COLD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr210a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr210b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr210c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams and projectiles to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~


END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cure Moderate Wounds___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////
//Not installed if any version of SR is installed (but, see revised spells)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN

//Projectile
//animations
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_2/cmwounh.bam~ ~override~   //animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_2/#EFF_P26.WAV~ ~override~   //sound
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_2/b_p217.spl~ 1 2 ~CLERIC_CURE_MODERATE_WOUNDS~ //CMW Spell
        SAY NAME1 @21700000
        SAY NAME2 @21700000
        SAY UNIDENTIFIED_DESC @21700001
	SAY DESC @21700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURE_MODERATE_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//COMPATIBILITY: REVISED CURE SPELLS
//cure moderate wound 30%

ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
 COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 6
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 30 parameter2 = 2 END
  SPRINT old @10100012//old text
  SPRINT new @10100013//new text
   READ_LONG 0x50 "valid"
   PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
   READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old w new
	END
   SAY_EVALUATED 0x50 ~%new_desc%~
   END  //
END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr217a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr217b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr217c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams and projectiles to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Alicorn Lance______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//DOES ENTROPY SPHERE PROTECT VS   SAY 0x1c

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_2/IDPRO298.pro~   //projectile
//animations
COPY ~%mod_folder%/data/iwd_spells/priest_2/ALANCET.BAM~ ~override~   //Pro bam

//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_2/#EFF_E08.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/iwd_spells/priest_2/#TRA_57.WAV~ ~override~   //Pro sound
//effs
COPY ~%mod_folder%/data/iwd_spells/priest_2/b_p218.eff~ ~override~   //for notification
  SAY 0x1c @21800003    //Notification
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_2/b_p218.spl~ 1 2 ~CLERIC_ALICORN_LANCE~ // Spell
        SAY NAME1 @21800000
        SAY NAME2 @21800000
        SAY UNIDENTIFIED_DESC @21800001
	SAY DESC @21800001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ALICORN_LANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr218a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr218b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr218c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO298% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Sh. of Entropy immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/entropy_list.tpa~



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________________Beast claw_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_2/ALTERH.BAM~ ~override~   //sound
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_2/#EFF_P07.WAV~ ~override~   //sound
//itm
COPY ~%mod_folder%/data/iwd_spells/priest_2/BCLAW.itm~ ~override~   //item
        SAY NAME1 @21900000
        SAY NAME2 @21900000
//itm icons
COPY ~%mod_folder%/data/iwd_spells/priest_2/IBCLAW.BAM~ ~override~   //item
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_2/b_p219.spl~ 1 2 ~CLERIC_BEAST_CLAW~ // Spell
        SAY NAME1 @21900000
        SAY NAME2 @21900000
        SAY UNIDENTIFIED_DESC @21900001
	SAY DESC @21900001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_BEAST_CLAW~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr219a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr219b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr219c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//________________________________________________________________Cause Moderate Wounds_________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//not installed if SRv4 is installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
//Projectile
//animations
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_2/CMDAMAH.BAM~ ~override~   //animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_2/#FF_P103.WAV~ ~override~   //sound
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_2/b_p220.spl~ 1 2 ~CLERIC_CAUSE_MODERATE_WOUNDS~ //CMW Spell
        SAY NAME1 @22000000
        SAY NAME2 @22000000
        SAY UNIDENTIFIED_DESC @22000001
	SAY DESC @22000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_MODERATE_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//compatibity revised spells
//30% damage + 8 damage (save vs death for half) and name changed to 'inflict'
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY NAME1 @11400005
        SAY NAME2 @11400005
        SAY UNIDENTIFIED_DESC @11400003
	SAY DESC @11400003
  LPF DELETE_EFFECT INT_VAR match_opcode= 12 END//
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 3 parameter2 = 4194304 savingthrow = 0 STR_VAR resource = EVAL ~ ~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 savingthrow = 4 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 parameter2 = 4194307 END
//spheres installed, change sphere to 'life'
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr220a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr220b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_2/sppr220c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams and projectiles to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

END


//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 3   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________________Prayer_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//AI: Make a version that badguys can use

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_3/OHVRNP.pro~   //projectile    vs badguys
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_3/OHVRPO.pro~   //projectile    goodies
//probam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/PRAYERH.BAM~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/PRAYERG.BAM~ ~override~   //
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#EFF_P31.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/EFF_E03.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
COPY ~%mod_folder%/data/iwd_spells/priest_3/#PRAYERB.SPL~ ~override~   //spl
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@31600002) END  //Notification: Combat Pentalties
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 215            //
      STR_VAR resource = EVAL ~PRAYERG~           //dreadred
  END      //
LPF ALTER_SPELL_HEADER INT_VAR projectile = %OHVRNP% END
//  LPF cd_apply_batch STR_VAR array_name = b_bless_cantrip_arrays END //bless related cantrip removal/protection


COPY ~%mod_folder%/data/iwd_spells/priest_3/#PRAYERG.SPL~ ~override~   //spl
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@31600004) END  //Notification: Combat Bounouses
  LPF ALTER_EFFECT  INT_VAR match_opcode = 139 opcode = 177 parameter1 = 0  parameter2 = 2  STR_VAR resource = EVAL ~PRAYG~ END
  LPF ALTER_EFFECT  INT_VAR match_opcode = 215    STR_VAR resource = EVAL ~PRAYERH~    END      // aaaahhh
  LPF ALTER_EFFECT  INT_VAR match_opcode = 142   parameter2 = 32  END      //goodluck
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %OHVRPO% END
//  LPF cd_apply_batch STR_VAR array_name = b_bless_cantrip_arrays END //bless related cantrip removal/protection
//text eff
COPY ~%mod_folder%/data/iwd_spells/priest_2/b_p218.eff~ ~override/PRAYG.eff~   //for notification
  SAY 0x1c @31600004   //Combat Boni


//Portrait Icon
//Icon itself
COPY ~%mod_folder%/data/iwd_spells/priest_3/B_PRAYG.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@31600002)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_PRAYG~
PRETTY_PRINT_2DA
COPY_EXISTING ~#PRAYERG.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END

//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p316.spl~ 1 3 ~CLERIC_PRAYER~ // Spell
        SAY NAME1 @31600000
        SAY NAME2 @31600000
        SAY UNIDENTIFIED_DESC @31600001
	SAY DESC @31600001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~

//Compatibility
ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN
//non-sphere description
COPY_EXISTING ~b_po020.spl~ ~override~    //canticle
 SPRINT old @102000005//old text
 SPRINT new @102000006//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (adds prayer immunity)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
COPY_EXISTING ~b_po030.spl~ ~override~      //Malediction
 SPRINT old @102000005//old text
 SPRINT new @102000006//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (adds prayer immunity)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
COPY_EXISTING ~b_po040.spl~ ~override~  //Meditation
 SPRINT old @102000005//old text
 SPRINT new @102000006//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (adds prayer immunity)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr316a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr316b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr316c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Cause Disease_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//icons
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/CDISEAH.BAM~ ~override~   //
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#FF_P108.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/EFF_E03.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p320.spl~ 1 3 ~CLERIC_CAUSE_DISEASE~ // Spell
        SAY NAME1 @32000000
        SAY NAME2 @32000000
        SAY UNIDENTIFIED_DESC @32000001
	SAY DESC @32000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_DISEASE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//  LPF cd_apply_batch STR_VAR array_name = b_disease_arrays END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr320a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr320b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr320c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove Disease
INCLUDE ~%mod_folder%/lib/spell_lists/disease_list.tpa~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Exaltation________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/EXALTAH.BAM~ ~override~   //
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#FF_P106.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
//Need to remove blood rage (prob animal rage, too?)
//Copied over for protections
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p321.spl~ 1 3 ~CLERIC_EXALTATION~ // Spell
        SAY NAME1 @32100000
        SAY NAME2 @32100000
        SAY UNIDENTIFIED_DESC @32100001
	SAY DESC @32100001
/*
  LPF cd_apply_batch STR_VAR array_name = cd_fear_removal_arrays END
  LPF cd_apply_batch STR_VAR array_name = cd_immunity_fear_arrays END
  LPF cd_apply_batch STR_VAR array_name = cd_immunity_sleep_arrays END
  LPF cd_apply_batch STR_VAR array_name = cd_immunity_feeblemind_arrays END
  LPF cd_apply_batch STR_VAR array_name = b_removal_rage_arrays END
  LPF cd_apply_batch STR_VAR array_name = b_immunity_berserk_arrays END
  LPF cd_apply_batch STR_VAR array_name = b_immunity_rage_arrays END
  LPF cd_apply_batch STR_VAR array_name = cd_immunity_confusion_arrays END
*/
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_EXALTATION~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr321a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr321b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr321c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove bless
INCLUDE ~%mod_folder%/lib/spell_lists/bless_list.tpa~
//3rd lev
INCLUDE ~%mod_folder%/lib/spell_lists/3rd_list.tpa~

//CONTINUE FROM HERE

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Moonblade_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#EFF_M06.WAV~ ~override~   //itm sound
//itm
COPY ~%mod_folder%/data/iwd_spells/priest_3/MOONBLA.itm~ ~override~   //itm
        SAY NAME1 @32200000
        SAY NAME2 @32200000
//itm icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/MOONBLA.BAM~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/GSW1H01.BAM~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/INVOCH.BAM~ ~override~   //itm 3d
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p322.spl~ 1 3 ~CLERIC_MOONBLADE~ // Spell
        SAY NAME1 @32200000
        SAY NAME2 @32200000
        SAY UNIDENTIFIED_DESC @32200001
	SAY DESC @32200001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MOONBLADE~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr322a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr322b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr322c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Circle of Bones______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/COBONH1.BAM~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/COBONH2.BAM~ ~override~   //
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#ARE_P21.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/#AFT_P22.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
COPY ~%mod_folder%/data/iwd_spells/priest_3/SPPR323D.spl~ ~override~   //
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p323.spl~ 1 3 ~CLERIC_CIRCLE_OF_BONES~ // Spell
        SAY NAME1 @32300000
        SAY NAME2 @32300000
        SAY UNIDENTIFIED_DESC @32300001
	SAY DESC @32300001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CIRCLE_OF_BONES~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr323a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr323b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr323c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Spike Growth_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//not installed if SRv4 is installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_3/idpro300.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sgrowta.BAM~ ~override~   //pro bam
//3d animation
//sounds
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p324.spl~ 1 3 ~CLERIC_SPIKE_GROWTH~ // Spell
        SAY NAME1 @32400000
        SAY NAME2 @32400000
        SAY UNIDENTIFIED_DESC @32400001
	SAY DESC @32400001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SPIKE_GROWTH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr324a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr324b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr324c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro300% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//3rd lev
INCLUDE ~%mod_folder%/lib/spell_lists/3rd_list.tpa~

END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Cloudburst___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//REMOVE Shroud of Flame (wizard spell) once added
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_3/idpro301.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sgrowta.BAM~ ~override~   //pro bam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/CLOUDBA.bam~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/CLOUDBH.BAM~ ~override~   // bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/ARE_P24.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p325.spl~ 1 3 ~CLERIC_CLOUDBURST~ // Spell
        SAY NAME1 @32500000
        SAY NAME2 @32500000
        SAY UNIDENTIFIED_DESC @32500001
	SAY DESC @32500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CLOUDBURST~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr325a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr325b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr325c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro301% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//3rd lev
INCLUDE ~%mod_folder%/lib/spell_lists/3rd_list.tpa~

/* When Shround of flame is added... From drench cantrip.  Changes are needed...Need to do this with fire macro???
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHROUD_OF_FLAME~
  RET spell_res
END
COPY_EXISTING ~b_wc003.spl~ ~override~    //This needs to be cloudburst...
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321 duration = 6            //
      STR_VAR match_resource = ~SPWI524~ resource = EVAL ~%spell_res%~
  END
*/


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Mold Touch___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_3/idmold.pro~   //projectile
//probam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/MTOUCHH.BAM~ ~override~   // bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#FF_P107.WAV~ ~override~   //
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p326.spl~ 1 3 ~CLERIC_MOLD_TOUCH~ // Spell
        SAY NAME1 @32600000
        SAY NAME2 @32600000
        SAY UNIDENTIFIED_DESC @32600001
	SAY DESC @32600001

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MOLD_TOUCH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//secondary spells
COPY ~%mod_folder%/data/iwd_spells/priest_3/SPPR326B.spl~ ~override/%spell_res%B.spl~   // bam  NEEDED?
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idmold% STR_VAR icon = EVAL  ~%spell_res%B~ END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr326a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr326b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr326c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove Disease
INCLUDE ~%mod_folder%/lib/spell_lists/disease_list.tpa~
//3rd lev
INCLUDE ~%mod_folder%/lib/spell_lists/3rd_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Storm Shell__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr327a.bam~ ~override~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr327b.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr327c.bam~ ~override~   //bam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/ISTORMA.BAM~ ~override~   // bam
//sounds
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p327.spl~ 1 3 ~CLERIC_STORM_SHELL~ // Spell
        SAY NAME1 @32700000
        SAY NAME2 @32700000
        SAY UNIDENTIFIED_DESC @32700001
	SAY DESC @32700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STORM_SHELL~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr327a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr327b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr327c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Cause Medium Wounds_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//not installed if SRv4 is installed
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
//Projectile
//probam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/CMDAMAH.BAM~ ~override~   // bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#FF_P103.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p330.spl~ 1 3 ~CLERIC_CAUSE_MEDIUM_WOUNDS~ // Spell
        SAY NAME1 @33000000
        SAY NAME2 @33000000
        SAY UNIDENTIFIED_DESC @33000001
	SAY DESC @33000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_MEDIUM_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr330a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr330b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr330c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Favor of Ilmater________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//unfamilliar opcode.  Hope it's good
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_3/sparklpu.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_3/TRAVEL.bam~ ~override~   //pro bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/STTRAVL5.BMP~ ~override~   //bmp
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_3/CMWOUNH.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/CMDAMAH.BAM~ ~override~   // bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_3/#EFF_P26.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_3/#FF_P103.WAV~ ~override~   //
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_3/b_p327.spl~ 1 3 ~CLERIC_FAVOR_OF_ILMATER~ // Spell
        SAY NAME1 @33100000
        SAY NAME2 @33100000
        SAY UNIDENTIFIED_DESC @33100001
	SAY DESC @33100001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_FAVOR_OF_ILMATER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr331a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr331b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_3/sppr331c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %sparklpu% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 4   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Giant Insect____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_4/cldamah.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/CURSEH.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbma1.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbma1e.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbma4.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbma4e.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmca.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmcae.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmde.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmdee.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmgh.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmghe.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmgu.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmgue.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmsc.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmsce.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmsd.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmsde.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmsl.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmsle.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmsp.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmspe.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmtw.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmtwe.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmwk.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbmwke.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbeta1.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbeta1e.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetca.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetcae.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetde.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetdee.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetgh.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetghe.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetgu.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetgue.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetsc.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetsce.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetsd.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetsde.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetsl.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetsle.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetsp.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetspe.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbettw.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbettwe.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetwk.BAM~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbetwke.BAM~ ~override~   // bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/#EFF_E04.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/#EFF_P32.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/#EFF_P39.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba01.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba02.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba03a.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba03b.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba03c.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba07.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba08.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba09a.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba09b.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/bomba11.WAV~ ~override~   //
//cre
COPY ~%mod_folder%/data/iwd_spells/priest_4/b_bebom.cre~ ~override~   //  bomba beetle
        SAY NAME1 @41800003
        SAY NAME2 @41800003
COPY ~%mod_folder%/data/iwd_spells/priest_4/b_bebor.cre~ ~override~   // boring beetle
        SAY NAME1 @41800004
        SAY NAME2 @41800004
//2da
COPY ~%mod_folder%/data/iwd_spells/priest_4/b_ginsc.2da~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbbm.2da~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/mbet.2da~ ~override~   //
//itm
COPY ~%mod_folder%/data/iwd_spells/priest_4/fartrng.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/s1-12.itm~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/s5-20.itm~ ~override~   //
//itm icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/pincers.BAM~ ~override~   // bam
//effs
COPY ~%mod_folder%/data/iwd_spells/priest_4/b_ginsc.eff~ ~override~   // actual summon eff
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p418.spl~ 1 4 ~CLERIC_GIANT_INSECT~ // Spell
        SAY NAME1 @41800000
        SAY NAME2 @41800000
        SAY UNIDENTIFIED_DESC @41800001
	SAY DESC @41800001

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_GIANT_INSECT~
  RET spell_res
END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr418a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr418b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr418c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Produce Fire_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//_______________________________________________________
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/idpro215.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_4/PFIREA.bam~ ~override~   // bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/PFIREX.bam~ ~override~   // bam
//vvc
COPY ~%mod_folder%/data/iwd_spells/priest_4/#PRFIRE.vvc~ ~override~   // bam
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/#EFF_P45.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/#ARE_P03.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spells
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p419.spl~ 1 4 ~CLERIC_PRODUCE_FIRE~ // Spell
        SAY NAME1 @41900000
        SAY NAME2 @41900000
        SAY UNIDENTIFIED_DESC @41900001
	SAY DESC @41900001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRODUCE_FIRE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr419a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr419b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr419c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro215% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove/prevent fire
INCLUDE ~%mod_folder%/lib/spell_lists/fire_list.tpa~
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//________________________________________________________________Static Charge_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//secondary projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/idstatic.pro~   //projectile
//probam
//vvc
//icons
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_4/SCHARGH.BAM~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/EFF_P42.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs

//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p420.spl~ 1 4 ~CLERIC_STATIC_CHARGE~ // Spell
        SAY NAME1 @42000000
        SAY NAME2 @42000000
        SAY UNIDENTIFIED_DESC @42000001
	SAY DESC @42000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STATIC_CHARGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 333            //
      STR_VAR resource = EVAL ~%spell_res%B~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142            //
      parameter2 = 94 //magnitized portrait icon for now
  END      //

//secondary spell
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr420b.spl~ ~override/%spell_res%B.spl~   //sec spell
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 13107
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%b~
  END      //
COPY ~%mod_folder%/data/iwd_spells/priest_4/b_p420a.eff~ ~override~   //text notification
  SAY 0x1c @42000004    //Notification
//must add projectile
COPY_EXISTING ~%spell_res%B.spl~ ~override~
	WRITE_SHORT 0x098 ~%idstatic%~  //Projectile
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr420a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr420b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr420c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove/prevent electricty(?)
INCLUDE ~%mod_folder%/lib/spell_lists/elect_list.tpa~
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Recitation__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/b_p421a.pro~   //projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/b_p421b.pro~   //projectile
//probam
//vvc
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_4/RECITAH.BAM~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/B_RECR.bam~ ~override~   //bam (missing, so created)
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/#EFF_P44.WAV~ ~override~   //Wav
COPY ~%mod_folder%/data/iwd_spells/priest_4/EFF_E03.WAV~ ~override~   //Wav
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
COPY ~%mod_folder%/data/iwd_spells/priest_4/#RECITEG.spl~ ~override~   //
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %OHVRPO% END
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@31600004) END  //Notification: combat bonuses
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142            //
      parameter2 = 17     //blessed
  END      //
COPY ~%mod_folder%/data/iwd_spells/priest_4/#RECITEB.spl~ ~override~   //
LPF ALTER_SPELL_HEADER INT_VAR projectile = %OHVRNP% END
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (@31600002) END  //Notification: Combat Penalties
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 215            //
      STR_VAR resource = EVAL ~B_RECR~ //missing bam
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 142            //
      parameter2 = 35     //cursed
  END      //

//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p421.spl~ 1 4 ~CLERIC_RECITATION~ // Spell
        SAY NAME1 @42100000
        SAY NAME2 @42100000
        SAY UNIDENTIFIED_DESC @42100001
	SAY DESC @42100001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_RECITATION~
  RET spell_res
END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr421a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr421b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr421c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove bless
INCLUDE ~%mod_folder%/lib/spell_lists/bless_list.tpa~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Blood Rage________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



//Projectile
//probam
//vvc
//icons
//3d animation
//sounds
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p422.spl~ 1 4 ~CLERIC_BLOOD_RAGE~
        SAY NAME1 @42200000
        SAY NAME2 @42200000
        SAY UNIDENTIFIED_DESC @42200001
	SAY DESC @42200001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_BLOOD_RAGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 324  STR_VAR match_resource = ~SPPR422~ resource = EVAL ~%spell_res%~   END      //
  LPF ALTER_EFFECT INT_VAR match_opcode = 321  STR_VAR match_resource = ~SPPR422~ resource = EVAL ~%spell_res%~   END      //
  LPF ALTER_EFFECT INT_VAR match_opcode = 318  STR_VAR match_resource = ~SPPR422~ resource = EVAL ~%spell_res%~   END      //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  BGEE text notifications
 COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35473 parameter1 = 25810 STR_VAR  END      // heal
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14022 parameter1 = 25810 STR_VAR  END      // heal
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35544 parameter1 = 26206 STR_VAR  END      // domination
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 26206 parameter1 = 14780 STR_VAR  END      // dire charm  (BG2EE/BGEE)
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 17392 parameter1 = 31787 STR_VAR  END      // dire charm
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37801 parameter1 = 31787 STR_VAR  END      // charm
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = 31787 STR_VAR  END      // Morale Failure: Panic
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35484 parameter1 = 25818 STR_VAR  END      // Panic
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37613 parameter1 = 26371 STR_VAR  END      // Sleep
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37340 parameter1 = 26371 STR_VAR  END      // Unconscious    DON'T KNOW THIS VALUE FOR BGEE
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14043 parameter1 = 26371 STR_VAR  END      // Stun
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 1280 parameter1 = 26050 STR_VAR  END      // Stunned
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 26050 parameter1 = 25862 STR_VAR  END      // Stun
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14102 parameter1 = 26050 STR_VAR  END      // Held
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35542 parameter1 = 14650 STR_VAR  END      // Paralyzed
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35606 parameter1 = 31799 STR_VAR  END      // Held
  LPF CLONE_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 31799 parameter1 = 25866 STR_VAR  END      // Held
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37603 parameter1 = 26184 STR_VAR  END      // Rigid Thinking
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37604 parameter1 = 25807 STR_VAR  END      // Confused
END    //END BGEE
//BG2EE and EET
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //  BGEE text notifications
 COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35473 STR_VAR  END      // heal, but only in iwdee (maybe also bgee)
 //   LPF DELETE_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35544 STR_VAR  END      // heal, but only in iwdee (maybe also bgee)  CHECK!
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35473 parameter1 = 25810 STR_VAR  END      // heal
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14022 parameter1 = 25810 STR_VAR  END      // is in BG2ee
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35544 parameter1 = 8364 STR_VAR  END      // domination
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 17392 parameter1 = 14780 STR_VAR  END      // dire charm
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37801 parameter1 = 14672 STR_VAR  END      // charm
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = 31787 STR_VAR  END      // Morale Failure: Panic
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35484 parameter1 = 14007 STR_VAR  END      // Morale Failure: Panic
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = 17427 STR_VAR  END      // Morale Failure: Panic
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37613 parameter1 = 14001 STR_VAR  END      // Sleep
  LPF DELETE_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37340 STR_VAR  END      // Unconscious    DON'T KNOW THIS VALUE FOR this notification, but its not this
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14043 parameter1 = 26371 STR_VAR  END      // Stun
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 1280 parameter1 = 26050 STR_VAR  END      // Stunned
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14102 parameter1 = 26050 STR_VAR  END      // Held
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35542 parameter1 = 14650 STR_VAR  END      //  paralyzed
//  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35606 parameter1 = 31799 STR_VAR  END      // Held
//  LPF CLONE_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 31799 parameter1 = 25866 STR_VAR  END      // Held
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37603 parameter1 = 14791 STR_VAR  END      // Rigid Thinking
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37604 parameter1 = 14782 STR_VAR  END      // Confused
END   //END bg2ee/eet

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr422a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr422b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr422c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

  //RIGHT NOW DOES NOT DISPLAY THE BLOOD RAGE SPECIAL EFFECT.  USED BESERK INSTEAD
//NOT SURE ABOUT "STATE 35"...Not sure if AI CAN OR CANNOT HANDLE THIS SPELL.  DLTCEP SAYS THAT IT SHOULD BE 4 SO, COnfused
//MAKE PROTECT FROM WIZARD EMOTION SPELLS ONCE ADDED

//sanctity immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/sanctity_list.tpa~

//exaltation immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/exaltation_list.tpa~

//rage immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/rage_list.tpa~

//Emotion dispelling
INCLUDE ~%mod_folder%/lib/spell_lists/emo_disp_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cloud of Pestilence____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//will anything remove or prevent this spell?
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/idpro309.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_4/copesta.BAM~ ~override~   //
//vvc
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/ARE_P25.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself                                                //WHY DIFFERENT VERSIONS OF SPELL????
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //  ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN 
 ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/bgee/b_p423.spl~ 1 4 ~CLERIC_CLOUD_OF_PESTILENCE~ // Spell
        SAY NAME1 @42300000
        SAY NAME2 @42300000
        SAY UNIDENTIFIED_DESC @42300001
	SAY DESC @42300001
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
 ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/bg2ee/b_p423.spl~ 1 4 ~CLERIC_CLOUD_OF_PESTILENCE~ // Spell
        SAY NAME1 @42300000
        SAY NAME2 @42300000
        SAY UNIDENTIFIED_DESC @42300001
	SAY DESC @42300001
END

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CLOUD_OF_PESTILENCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr423a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr423b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr423c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro309% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//Remove CoP (zone of clear air??)
INCLUDE ~%mod_folder%/lib/spell_lists/cloud_list.tpa~ // //
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Unfailing Endurance____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_4/NECROH.BAM~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/#FF_P112.WAV~ ~override~   //Wav
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p424.spl~ 1 4 ~CLERIC_UNFAILING_ENDURANCE~ // Spell
        SAY NAME1 @42400000
        SAY NAME2 @42400000
        SAY UNIDENTIFIED_DESC @42400001
	SAY DESC @42400001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNFAILING_ENDURANCE~
  RET spell_res
END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr424a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr424b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr424c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER  STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//IMPROVEMENTS:
//Removes fatigue effects?
//IMPROVED 'MY' VERSION

ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
//should be able to use exact same code for iwdee and iwdification
//spec ability
COPY ~%mod_folder%/data/revised_spells/unfailing_endurance/b_fatig.spl~ ~override~
        SAY NAME1 @10100000
        SAY NAME2 @10100000
        SAY UNIDENTIFIED_DESC @10100004
	SAY DESC @10100004
//heal notification
COPY ~%mod_folder%/data/revised_spells/unfailing_endurance/B_HEALN.eff~ ~override~
  SAY 0x1c ~Healed~ //healed (already in dialog.tlk so...)

//animation
COPY ~%mod_folder%/data/revised_spells/unfailing_endurance/ENCHAH.bam~ ~override~

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNFAILING_ENDURANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY NAME1 @10100002
        SAY NAME2 @10100002
        SAY UNIDENTIFIED_DESC @10100003
	SAY DESC @10100003
	WRITE_BYTE 0x072 ~2~  //Projectile
	WRITE_BYTE 0x07E ~5~  //Self
	WRITE_SHORT 0x098 ~158~  //DH Projectile
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 324 parameter1 = 0 parameter2 = 1 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 17 parameter1 = 10 parameter2 = 2 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 171 timing = 0 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 172 timing = 4 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 177 parameter1 = 0 parameter2 = 2 STR_VAR resource = EVAL ~b_healn~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 STR_VAR resource = EVAL ~ENCHAH~  END
END  //End 'my version'


//Maybe a duration where immune to fatigue effects (e.g. from haste and RWOTF)
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Star Metal Cudgel______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_4/ISMCUDGE.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/CONJUH.bam~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/#EFF_P02.WAV~ ~override~   //
//cre
//2da
//itm
COPY ~%mod_folder%/data/iwd_spells/priest_4/SMCUDGE.itm~ ~override~   //
        SAY NAME1 @42500000
        SAY NAME2 @42500000
//itm icons
//effs
COPY ~%mod_folder%/data/iwd_spells/priest_4/SMCUDGE.eff~ ~override~   //eff
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p425.spl~ 1 4 ~CLERIC_STAR_METAL_CUDGEL~ // Spell
        SAY NAME1 @42500000
        SAY NAME2 @42500000
        SAY UNIDENTIFIED_DESC @42500001
	SAY DESC @42500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STAR_METAL_CUDGEL~
  RET spell_res
END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr425a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr425b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr425c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Smashing Wave______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//ADD CD_STUN/UNCONSCIOUS STUFF (OR MAKE A NEW ONE IF NEEDED) TEST IT!!

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/swave.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_4/SWAVEX.bam~ ~override~   //
//vvc
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_4/SWAVEX.bam~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/SWAVEH.BAM~ ~override~   //
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/#FF_P110.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs  missing stun display (check for immunities...)
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p426.spl~ 1 4 ~CLERIC_SMASHING_WAVE~ // Spell
        SAY NAME1 @42600000
        SAY NAME2 @42600000
        SAY UNIDENTIFIED_DESC @42600001
	SAY DESC @42600001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SMASHING_WAVE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 149            //
      opcode = 139 //
  END      //
END      //

ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
 COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 149            //
      opcode = 139 //
      parameter1 = 26050
  END      //
END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr426a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr426b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr426c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %swave% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Thorn Spray________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/idpro303.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_4/TSPRAYT.bam~ ~override~   //
//vvc
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/#TRA_61.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/b_p427.spl~ 1 4 ~CLERIC_THORN_SPRAY~ // Spell
        SAY NAME1 @42700000
        SAY NAME2 @42700000
        SAY UNIDENTIFIED_DESC @42700001
	SAY DESC @42700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_THORN_SPRAY~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr427a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr427b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr427c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro303% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Wall of Moonlight___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//DID I REMOVE THE ALIGNMENT STUFF?  ADD IT AGAIN

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_4/womoon.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_4/WOMOONX.bam~ ~override~   //
//vvc
COPY ~%mod_folder%/data/iwd_spells/priest_4/WOMOONX.vvc~ ~override~   //
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_4/ARE_P22.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/AFT_P21.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_4/B_P428.spl~ 1 4 ~CLERIC_WALL_OF_MOONLIGHT~ // Spell
        SAY NAME1 @42800000
        SAY NAME2 @42800000
        SAY UNIDENTIFIED_DESC @42800001
	SAY DESC @42800001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_WALL_OF_MOONLIGHT~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 326            //
      STR_VAR resource = EVAL ~%spell_res%A~
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 326 parameter2 = 1 STR_VAR resource = EVAL ~%spell_res%B~ END
//Secondary Spells
COPY ~%mod_folder%/data/iwd_spells/priest_4/SPPR428A.spl~ ~override/%spell_res%A.spl~   //
COPY ~%mod_folder%/data/iwd_spells/priest_4/SPPR428B.spl~ ~override/%spell_res%B.spl~   //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr428a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr428b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_4/sppr428c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %womoon% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//4th lev
INCLUDE ~%mod_folder%/lib/spell_lists/4th_list.tpa~

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 5   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________Righteous Wrath of the Faithful______________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//display icon not yet available (ADD THEM!)  Using 'Heroism' for now...
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_5/idpro266.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_5/ABJURAX.bam~ ~override~   //
//vvc
COPY ~%mod_folder%/data/iwd_spells/priest_5/#GENABJU.vvc~ ~override~   //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr518a.bam~ ~override~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr518b.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr518c.bam~ ~override~   //bam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_5/RWOTFAH.BAM~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_5/#EFF_P36.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_5/#EFF_E01.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_5/B_P518.spl~ 1 5 ~CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL~ // Spell
        SAY NAME1 @51800000
        SAY NAME2 @51800000
        SAY UNIDENTIFIED_DESC @51800001
	SAY DESC @51800001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 318 parameter2 = 50 STR_VAR resource = EVAL ~%spell_res%B~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 146 STR_VAR resource = EVAL ~%spell_res%B~ END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 0            //
      opcode = 318
      parameter2 = 50
      STR_VAR resource = EVAL ~%spell_res%A~
  END      //
//secondary spells
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //
 COPY ~%mod_folder%/data/iwd_spells/priest_5/bgee/SPPR518A.spl~ ~override/%spell_res%A.spl~   //
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //
 COPY ~%mod_folder%/data/iwd_spells/priest_5/bg2ee/SPPR518A.spl~ ~override/%spell_res%A.spl~   //
END
COPY ~%mod_folder%/data/iwd_spells/priest_5/SPPR518B.spl~ ~override/%spell_res%B.spl~   // CHECK STRINGS, SOUND EFFECTS AND ANIMATIONS
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%B~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr518a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr518b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr518c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro266% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//NOT A BLESS SPELL.  REMOVED BY ANYTHIGN ELSE???? EG HOPELESSNESS?

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Spike Stones_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_5/idpro213.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_5/SSTONEA.BAM~ ~override~   //
//vvc
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_5/ARE_P04.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_5/EFF_P48.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_5/#CRE_P03.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_5/B_P519.spl~ 1 5 ~CLERIC_SPIKE_STONES~ // Spell
        SAY NAME1 @51900000
        SAY NAME2 @51900000
        SAY UNIDENTIFIED_DESC @51900001
	SAY DESC @51900001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SPIKE_STONES~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr519a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr519b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr519c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro213% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Shield of Lathander____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//ADD IN ALIGNMENT RESTRICTION 
//'IMPROVED VERSION' CHANGE NAME AND...
//Projectile
//probam
//vvc
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_5/SPSTRENH.bam~ ~override~   //bams  missing! using 'boon of lath' instead (already included)
//sounds
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_5/B_P520.spl~ 1 5 ~CLERIC_SHIELD_OF_LATHANDER~ // Spell
        SAY NAME1 @52000000
        SAY NAME2 @52000000
        SAY UNIDENTIFIED_DESC @52000001
	SAY DESC @52000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SHIELD_OF_LATHANDER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr520a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr520b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr520c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Undead Ward_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//WHAT IS THE POINT OF THIS SPELL?  SO A PRIEST CAN USE WHILE DOING OTHER THINGS? LET"S SEE ABOUT IMPROVING IT
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_5/uward.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_5/UWARDX.BAM~ ~override~   //
//vvc
COPY ~%mod_folder%/data/iwd_spells/priest_5/UWARDX.vvc~ ~override~   //
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_5/#ARE_P28.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_5/#AFT_P27.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_5/B_P521.spl~ 1 5 ~CLERIC_UNDEAD_WARD~ // Spell
        SAY NAME1 @52100000
        SAY NAME2 @52100000
        SAY UNIDENTIFIED_DESC @52100001
	SAY DESC @52100001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNDEAD_WARD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr521a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr521b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr521c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %uward% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Animal Rage_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_5/#ARE_P28.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_5/#AFT_P27.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_5/b_p522.spl~ 1 5 ~CLERIC_ANIMAL_RAGE~ // Spell
        SAY NAME1 @52200000
        SAY NAME2 @52200000
        SAY UNIDENTIFIED_DESC @52200001
	SAY DESC @52200001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ANIMAL_RAGE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//secondary spell
COPY ~%mod_folder%/data/iwd_spells/priest_5/SPPR522B.spl~ ~override/%spell_res%b.spl~   //

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr522a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr522b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr522c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//sanctity immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/sanctity_list.tpa~

//exaltation immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/exaltation_list.tpa~

//rage immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/rage_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Mass Cause Light Wounds________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_5/sparrenp.pro~   //projectile
//probam
//vvc
//bmp
COPY ~%mod_folder%/data/iwd_spells/priest_5/STTRAVL6.BMP~ ~override~   //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr523a.bam~ ~override~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr523b.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr523c.bam~ ~override~   //bam
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_5/TRAVEL.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/CLDAMAH.bam~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_5/#FF_P103.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_5/b_p523.spl~ 1 5 ~CLERIC_MASS_CAUSE_LIGHT_WOUNDS~ // Spell
        SAY NAME1 @52300000
        SAY NAME2 @52300000
        SAY UNIDENTIFIED_DESC @52300001
	SAY DESC @52300001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MASS_CAUSE_LIGHT_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr523a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr523b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_5/sppr523c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %sparrenp% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 6   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//Double CHECK from here
//FIND ACTUAL UPDATED VERSION (on comp at work?)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Entropy Shield_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//PROTECT FROM ICELANCE when added!  Right now, the description says that it's immune to icelance, though the spell doesn't exist in
//protect from all cantrips/orison missile spells (if implemented)
//added sol's searing orb (seemed approapriate)
//make sure to update description such that all protected spells are listed in description

//Projectile
//probam
//vvc
//bmp
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_6/ABJURH.bam~ ~override~   //bam
//COPY ~%mod_folder%/data/iwd_spells/priest_6/#ENTROPY.bam~ ~override~   //bam  Missing #ENTROPY.bam
//sounds
//cre
//2da
//itm
//itm icons
//effs
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_6/b_p615.spl~ 1 6 ~CLERIC_ENTROPY_SHIELD~ // Spell
        SAY NAME1 @61500000
        SAY NAME2 @61500000
        SAY UNIDENTIFIED_DESC @61500001
	SAY DESC @61500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ENTROPY_SHIELD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321           //
      STR_VAR resource = EVAL ~%spell_res%~
  END
// now sol's searing orb projectile immunity
  LPF CLONE_EFFECT INT_VAR match_opcode = 0 opcode = 83 parameter1 = 0 parameter2 = 257 END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr615a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr615b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr615c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//How would this be dispelled?


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Whirlwind__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_6/whirlw.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_6/WHIRLWX.bam~ ~override~   //bam
//vvc
//bmp
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_6/EFF_P105.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_6/b_p617.spl~ 1 6 ~CLERIC_WHIRLWIND~ // Spell
        SAY NAME1 @61700000
        SAY NAME2 @61700000
        SAY UNIDENTIFIED_DESC @61700001
	SAY DESC @61700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_WHIRLWIND~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 206           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN   //change stun notification
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139           //
      parameter1 = 1280
  END      //
END
ACTION_IF GAME_IS ~bgee~ THEN BEGIN   //change stun notification ACTION_IF GAME_IS ~bgee sod~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139           //
      parameter1 = 26050
  END      //
END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr617a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr617b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr617c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %whirlw% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//REMOVE CLOUD SPELLS?  

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Spiritual Wrath____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_6/idpro312.pro~   //projectile
//sec pro
//ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_6/IDPRO207.pro~   //projectile
//don't know how to add this...use an existing one that is similar enough (a non-bouncing lightning bolt...) seems to automatically use the bg2ee equiv
//probam
//vvc
//bmp
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_6/INVOCH.bam~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_6/TRA_08.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_6/TRA_09.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_6/#EFF_P05.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_6/b_p618.spl~ 1 6 ~CLERIC_SPIRITUAL_WRATH~ // Spell
        SAY NAME1 @61800000
        SAY NAME2 @61800000
        SAY UNIDENTIFIED_DESC @61800001
	SAY DESC @61800001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SPIRITUAL_WRATH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr616a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr616b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_6/sppr616c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro312% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~


//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  LEVEL 7   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Symbol, Pain_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Portrait icon: Nauseated. Update portrait icons and change to pain
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_7/iceglyp.pro~   //projectile
//probam
//vvc
COPY ~%mod_folder%/data/iwd_spells/priest_7/ICSPAIN.vvc~ ~override~   //bam
//bmp
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_7/SPGLYPTI.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/SHGLYPH.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/SPSPAINI.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/CONJUH.bam~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_7/#EFF_P02.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_7/#EFF_E04.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_7/EFF_P22A.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
COPY ~%mod_folder%/data/iwd_spells/priest_7/B_P714a.eff~ ~override~   //
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p714.spl~ 1 7 ~CLERIC_SYMBOL_OF_PAIN~ // Spell
        SAY NAME1 @71400000
        SAY NAME2 @71400000
        SAY UNIDENTIFIED_DESC @71400001
	SAY DESC @71400001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SYMBOL_OF_PAIN~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321           //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr714a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr714b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr714c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %iceglyp% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//bloodrage immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/blood_list.tpa~

//spells that remove pain effects
INCLUDE ~%mod_folder%/lib/spell_lists/pain_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Symbol, Hopelessness___________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_7/idpro277.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_7/SOHOPEX.bam~ ~override~   //bam
//vvc
COPY ~%mod_folder%/data/iwd_spells/priest_7/SOHOPEX.vvc~ ~override~   //bam
//bmp
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_7/PARALH.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/SPGLYPTI.bam~ ~override~   //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/SHGLYPH.bam~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_7/#EFF_P02.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_7/#EFF_E04.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p716.spl~ 1 7 ~CLERIC_SYMBOL_OF_HOPELESSNESS~ // Spell
        SAY NAME1 @71600000
        SAY NAME2 @71600000
        SAY UNIDENTIFIED_DESC @71600001
	SAY DESC @71600001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SYMBOL_OF_HOPELESSNESS~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr716a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr716b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr716c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro277% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//bloodrage immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/blood_list.tpa~

//sanctity immunity list
INCLUDE ~%mod_folder%/lib/spell_lists/sanctity_list.tpa~

//REmove hopelessness
INCLUDE ~%mod_folder%/lib/spell_lists/hopeless_list.tpa~

//emotion
INCLUDE ~%mod_folder%/lib/spell_lists/emotion_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Impervious Sanctity of Mind_______________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//bmp
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_7/ABJURH.BAM~ ~override~   //
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_7/#EFF_E03.WAV~ ~override~   //
COPY ~%mod_folder%/data/iwd_spells/priest_7/#EFF_P01.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p733.spl~ 1 7 ~CLERIC_IMPERVIOUS_SANCTITY_OF_MIND~ // Spell
        SAY NAME1 @73300000
        SAY NAME2 @73300000
        SAY UNIDENTIFIED_DESC @73300001
	SAY DESC @73300001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_IMPERVIOUS_SANCTITY_OF_MIND~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr733a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr733b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr733c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~





//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________________Destruction_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//bmp
//3d animation
COPY ~%mod_folder%/data/iwd_spells/priest_7/DESTRUH.BAM~ ~override~   //bam
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_7/#FF_P113.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p734.spl~ 1 7 ~CLERIC_DESTRUCTION~ // Spell
        SAY NAME1 @73400000
        SAY NAME2 @73400000
        SAY UNIDENTIFIED_DESC @73400001
	SAY DESC @73400001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_DESTRUCTION~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr734a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr734b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr734c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//protect vs. death
INCLUDE ~%mod_folder%/lib/spell_lists/death_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Greater Shield of Lathander__________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 //Note: portrait display icon uses 'shielded'
 //ALIGNMENT!!!! PUT BACK IN (WITH OPTION TO CHANGE VIA 'REVISED')
//Projectile
//probam
//vvc
//bmp
//3d animation
//missing! Using shield (ie first lev wiz spell) in its place
//sounds
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p735.spl~ 1 7 ~CLERIC_GREATER_SHIELD_OF_LATHANDER~ // Spell
        SAY NAME1 @73500000
        SAY NAME2 @73500000
        SAY UNIDENTIFIED_DESC @73500001
	SAY DESC @73500001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_GREATER_SHIELD_OF_LATHANDER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr735a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr735b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr735c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

  
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Mist of Eldath_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~%mod_folder%/data/iwd_spells/priest_7/idpro307.pro~   //projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_7/MOELDAA.BAM~ ~override~   //bam
//vvc
//bmp
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_7/EFF_P104.WAV~ ~override~   //
//cre
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p736.spl~ 1 7 ~CLERIC_MIST_OF_ELDATH~ // Spell
        SAY NAME1 @73600000
        SAY NAME2 @73600000
        SAY UNIDENTIFIED_DESC @73600001
	SAY DESC @73600001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_MIST_OF_ELDATH~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr736a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr736b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr736c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %idpro307% STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//REMOVE FIRE EFFECTS???  Probably not...Supposed to be an aid

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Stalker____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//REVISE IN LIGHT OF THE NATURE'S WRATH SPELL...
//Projectile
//probam
COPY ~%mod_folder%/data/iwd_spells/priest_7/MOELDAA.BAM~ ~override~   //bam
//vvc
//bmp
//3d animation
//sounds
//cre
COPY ~%mod_folder%/data/iwd_spells/priest_7/SMOUNDSU.cre~ ~override~   //
//script
//COMPILE if Needed
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p737.spl~ 1 7 ~CLERIC_STALKER~ // Spell
        SAY NAME1 @73700000
        SAY NAME2 @73700000
        SAY UNIDENTIFIED_DESC @73700001
	SAY DESC @73700001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STALKER~
  RET spell_res
END

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr737a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr737b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr737c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Energy Drain_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//probam
//vvc
//bmp
//3d animation
//sounds
COPY ~%mod_folder%/data/iwd_spells/priest_7/EFF_M07.WAV~ ~override~   //
//cre
//script
//2da
//itm
//itm icons
//effs
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p739.spl~ 1 7 ~CLERIC_ENERGY_DRAIN~ // Spell
        SAY NAME1 @73900000
        SAY NAME2 @73900000
        SAY UNIDENTIFIED_DESC @73900001
	SAY DESC @73900001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ENERGY_DRAIN~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 25803 //text display
  END      //
END
//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/SPWI914a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/SPWI914b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/SPWI914c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//protect vs. drain
INCLUDE ~%mod_folder%/lib/spell_lists/drain_list.tpa~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________________Wither_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Projectile
//probam
//vvc
//bmp
//3d animation
//missing! Using Dust?  Why not
COPY ~%mod_folder%/data/iwd_spells/priest_7/DUST.BAM~ ~override~   //
//sounds
//cre
//2da
//itm
//itm icons
//secondary spell
//Spell itself
ADD_SPELL ~%mod_folder%/data/iwd_spells/priest_7/b_p740.spl~ 1 7 ~CLERIC_WITHER~ // Spell
        SAY NAME1 @74000000
        SAY NAME2 @74000000
        SAY UNIDENTIFIED_DESC @74000001
	SAY DESC @74000001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_WITHER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 54337 //text display  'diseased'
  END      //
END
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139            //
      parameter1 = 31238 //text display  'diseased'
  END      //
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
LPF ALTER_EFFECT
      INT_VAR match_opcode = 272
      STR_VAR resource = EVAL ~%spell_res%~
  END      //

//eff
COPY ~%mod_folder%/data/iwd_spells/priest_7/SPPR740.eff~ ~override/%spell_res%.eff~   //

//icons
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr740a.bam~ ~override/%spell_res%a.bam~   //scroll bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr740b.bam~ ~override/%spell_res%b.bam~    //bam
COPY ~%mod_folder%/data/iwd_spells/priest_7/sppr740c.bam~ ~override/%spell_res%c.bam~    //bam
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
//remove disease?
INCLUDE ~%mod_folder%/lib/spell_lists/disease_list.tpa~


//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////  Special   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//entropy pros
//pros if no sr
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN
  INCLUDE ~%mod_folder%/lib/spell_lists/entropy_sun.tpa~
END

INCLUDE ~%mod_folder%/lib/spell_lists/entropy_pro_pri.tpa~

