
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ACOLYTE OF DENEIR
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________

ADD_KIT ~B_PRIEST_DENEIR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_PRIEST_DENEIR  	0 0 0 0 1 1 0 1~
~B_PRIEST_DENEIR       1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_PRIEST_DENEIR  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_PRIEST_DENEIR  1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_PRIEST_DENEIR  0  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/315_deneir/b_aden.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @31501
SAY @31502
SAY @31503
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@31503)
		STR_VAR
			kit_name = B_PRIEST_DENEIR
			clswpbon = ~0 0 3~
			hpclass = ~HPPRS~
	END
END
//____________________________________________________________________________________

// ABILITY FILES_______________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/315_deneir/b_aden.2da~ ~override~
COPY ~faiths_and_powers/kits/acolytes/315_deneir/b_den01.spl~ ~override~  //immunities


COPY_EXISTING ~SPPR205.spl~ ~override/b_den02.spl~ // detect traps
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
  WRITE_BYTE 0x84 1//Casting time
  WRITE_BYTE 0x74 4//Location

COPY_EXISTING ~SPPR304.spl~ ~override/b_den03.spl~ // glyph of warding
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
 LPF ALTER_SPELL_HEADER INT_VAR location = 4 END

COPY_EXISTING ~SPPR303.spl~ ~override/b_den04.spl~ // dispel magic
  WRITE_LONG 0x34 1 //level
  WRITE_BYTE 0x1c 4//Innate
 LPF ALTER_SPELL_HEADER INT_VAR location = 4 END



//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~b_aden~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~x~
	s_Protection 	= ~major~
	s_War 			= ~minor~
	s_Knowledge 	= ~focus~
	s_Deception 	= ~minor~
	s_Thought 		= ~major~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~minor~
	s_Plant 		= ~minor~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~major~
	s_Shadow 		= ~x~
	s_Magic 		= ~major~
END
//__________________________________________________________________________________
