
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							CLERIC OF LOVIATAR
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________

ADD_KIT ~B_CLERIC_LOVIATAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CLERIC_LOVIATAR      0 0 0 0 1 1 0 1~
~B_CLERIC_LOVIATAR      1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   11  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CLERIC_LOVIATAR  0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CLERIC_LOVIATAR  0  1  1  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CLERIC_LOVIATAR  1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21901 //lower
SAY @21902 //Mixed
SAY @21903 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21903)
		STR_VAR
			kit_name = B_CLERIC_LOVIATAR
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________


//LOVIATAR ABILITY FILES______________________________________________________________
//
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~ ~override~
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.spl~     ~override~  // Pain Touch
	SAY NAME1 @21911
	SAY NAME2 @21911
	SAY UNIDENTIFIED_DESC @21912  //
	SAY IDENTIFIED_DESC @21912  //
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.itm~     ~override~  // Pain Touch
  SAY NAME1 @21911
  SAY NAME2 @21911
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov01.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov02.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov03.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov04.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov05.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov06.eff~     ~override~  // Pain Touch
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov02.spl~     ~override~  // Pain Touch
  SAY NAME1 @6
  SAY NAME2 @6
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov03.spl~     ~override~  // Loviatar's Caress
	SAY NAME1 @21914
	SAY NAME2 @21914
	SAY UNIDENTIFIED_DESC @21915  //
	SAY IDENTIFIED_DESC @21915  //
COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_lov04.spl~     ~override~  // Suppress Pain Touch
  SAY NAME1 @21916
  SAY NAME2 @21916
//____________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric 		= 1
  STR_VAR
    clab_name 		= ~b_clov~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~minor~
	s_Protection 	= ~x~
	s_War 			= ~minor~
	s_Knowledge 	= ~major~
	s_Deception 	= ~minor~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~major~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~minor~
	s_Magic 		= ~x~
END
//__________________________________________________________________________________



//CLERIC/THIEF________________________________________________________________________

ADD_KIT ~B_CT_LOVIATAR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   		T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_CT_LOVIATAR      0 0 0 0 1 1 0 1~
~B_CT_LOVIATAR      1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   11  0~

//KIT STAT MODIFIERS________________________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                  STR DEX CON INT WIS CHR
~B_CT_LOVIATAR      0   0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                  LG LN LE NG TN NE CG CN CE
~B_CT_LOVIATAR      0  1  1  0  1  1  0  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                  FT CL MA TH DR RA
~B_CT_LOVIATAR      1  0  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/clerics/219_loviatar/b_2lov.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CT_E  K_CT_H  K_CT_HE  K_CT_G  K_CT_D  K_CT_HL  K_CT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 15~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Cl0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21901 //lower
SAY @21902 //Mixed
SAY @21903 //Help
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21903)
		STR_VAR
			kit_name = B_CT_LOVIATAR
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

COPY ~faiths_and_powers/kits/clerics/219_loviatar/b_clov.2da~ ~override/b_2lov.2da~

//MULTICLASS KIT______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b_2lov.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~B_CT_LOVIATAR~ 
		kit_clab = ~b_2lov~
		base_class = ~P~
		mc_dir = ~faiths_and_powers/lib/qd_mc~
  END
END 
//____________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric_thief 	= 1
  STR_VAR
    clab_name 		= ~b_2lov~
	race 			= ~all~
	s_Life 			= ~major~
	s_Death 		= ~major~
	s_Benediction 	= ~minor~
	s_Destruction 	= ~minor~
	s_Protection 	= ~x~
	s_War 			= ~minor~
	s_Knowledge 	= ~major~
	s_Deception 	= ~minor~
	s_Thought 		= ~major~
	s_Dread 		= ~major~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~major~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~minor~
	s_Magic 		= ~x~
END
//__________________________________________________________________________________
