
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						ACOLYTE OF MYSTRA
//__________________________________________________________________________________
//__________________________________________________________________________________


//add acolyte of mystra____________________________________________________________
//
ADD_KIT ~D5_AC_MYS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_AC_MYS     0 1 0 0 1 0 0 1~
~D5_AC_MYS     0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   13  13  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_AC_MYS          0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_AC_MYS          1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_AC_MYS          0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~faiths_and_powers/kits/acolytes/325_mystra/d5acmys.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_D_E  K_C_E  K_C_G  K_C_H  K_C_HE  K_C_HL  K_C_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x02000000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @32501
SAY @32502
SAY @32503
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@32503)
		STR_VAR
			kit_name = D5_AC_MYS
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________


//MYSTRA ABILITY FILES___________________________________________________________
//
COPY ~faiths_and_powers/kits/acolytes/325_mystra/d5acmys.2da~ ~override~
COPY ~faiths_and_powers/kits/misc/d5_cllv1.spl~ ~override~
//	SAY NAME1 @6
//	SAY UNIDENTIFIED_DESC @6
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm1.spl~ ~override~
	SAY NAME1 @46605
	SAY UNIDENTIFIED_DESC @46606
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm1.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc1b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc1c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm2.spl~ ~override~
	SAY NAME1 @46607
	SAY UNIDENTIFIED_DESC @46608
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm2.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc2b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc2c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm3.spl~ ~override~
	SAY NAME1 @46609
	SAY UNIDENTIFIED_DESC @46610
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm3.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc3b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc3c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm4.spl~ ~override~
	SAY NAME1 @46611
	SAY UNIDENTIFIED_DESC @46612
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm4.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc4b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc4c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm5.spl~ ~override~
	SAY NAME1 @46613
	SAY UNIDENTIFIED_DESC @46614
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm5.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc5b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc5c.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5arcm6.spl~ ~override~
	SAY NAME1 @46615
	SAY UNIDENTIFIED_DESC @46616
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arcm6.2da~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc6b.bam~ ~override~
COPY ~faiths_and_powers/kits/multiclass/466_cm_mystra/d5_arc6c.bam~ ~override~
//Huge thanks to DreamSlaveOne at forums.gibberlings3.net for providing the .BAMs for these abilities!
/*
ACTION_IF FILE_EXISTS_IN_GAME ~d5_wiz.d5~ THEN BEGIN
	COPY_EXISTING ~d5_inmys.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~faiths_and_powers/kits/acolytes/325_mystra/mystracant.txt~
END
*/
//___________________________________________________________________________________


//DEFINE SPHERE ACCESS______________________________________________________________
//
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_acolyte 		= 1
  STR_VAR
    clab_name 		= ~d5acmys~
	race 			= ~human~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~x~
	s_Knowledge 	= ~major~
	s_Deception 	= ~minor~
	s_Thought 		= ~minor~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~minor~
	s_Light 		= ~major~
	s_Shadow 		= ~minor~
	s_Magic 		= ~major~
END
//__________________________________________________________________________________

